import { Question } from "../types.js";

export const billingPricingAndSupportQuestions: Question[] = [
  {
    id: "bill1",
    domain: "billing-pricing-and-support",
    text: "Which AWS pricing model requires no upfront payment and lets you pay for compute capacity by the second or hour with no long-term commitment?",
    options: [
      { id: "a", text: "Reserved Instances" },
      { id: "b", text: "On-Demand Instances" },
      { id: "c", text: "Spot Instances" },
      { id: "d", text: "Savings Plans" },
    ],
    correctOptionIds: ["b"],
    explanation: "On-Demand Instances let you pay for compute capacity with no upfront payment or long-term commitment.",
    optionRationale: {
      a: "Reserved Instances require a 1- or 3-year commitment in exchange for a discount, so they don't fit 'no commitment'.",
      b: "On-Demand Instances are billed by the second or hour with no upfront payment and no long-term contract.",
      c: "Spot Instances also carry no commitment, but they draw on spare capacity at a discount and can be interrupted by AWS, which isn't what's described here.",
      d: "Savings Plans trade a 1- or 3-year usage commitment for a lower rate — the opposite of what's being asked about.",
    },
    referenceUrl: "https://aws.amazon.com/ec2/pricing/on-demand/",
    referenceLabel: "Amazon EC2 On-Demand Pricing",
    diagram: "flowchart TD\n  Need{Workload Commitment?} --> None[No Commitment] --> OnDemand[On-Demand Pricing]\n  Need --> Term[1 or 3 Year Term] --> Reserved[Reserved Instances or Savings Plans]\n  Need --> Flex[Interruptible and Flexible] --> Spot[Spot Instances]",
    cliExample: {
      description: "List running EC2 instances using standard (on-demand) lifecycle",
      command: "aws ec2 describe-instances --filters Name=instance-lifecycle,Values=normal",
    },
  },
  {
    id: "bill2",
    domain: "billing-pricing-and-support",
    text: "Which EC2 purchasing option lets you use spare AWS compute capacity at steep discounts, with the risk that the instance can be interrupted by AWS with short notice?",
    options: [
      { id: "a", text: "On-Demand Instances" },
      { id: "b", text: "Reserved Instances" },
      { id: "c", text: "Spot Instances" },
      { id: "d", text: "Dedicated Hosts" },
    ],
    correctOptionIds: ["c"],
    explanation: "Spot Instances use spare EC2 capacity at a discount but can be reclaimed by AWS with short notice.",
    optionRationale: {
      a: "On-Demand Instances aren't discounted spare capacity, and AWS never reclaims them for pricing reasons.",
      b: "Reserved Instances require a commitment and are guaranteed for their term — the opposite of interruptible spare capacity.",
      c: "Spot Instances let you tap spare EC2 capacity at up to 90% off, with the trade-off that AWS can reclaim them with a two-minute interruption notice.",
      d: "Dedicated Hosts are physical servers billed for compliance or licensing needs, not discounted spare capacity.",
    },
    referenceUrl: "https://aws.amazon.com/ec2/spot/",
    referenceLabel: "Amazon EC2 Spot Instances",
    diagram: "flowchart LR\n  Spare[AWS Spare Capacity] --> Spot[Spot Instance at a Discount]\n  Spot --> Notice[2-Minute Interruption Notice]\n  Notice --> Reclaim[AWS Reclaims Capacity]",
    cliExample: {
      description: "View recent Spot price history for an instance type",
      command: "aws ec2 describe-spot-price-history --instance-types t3.micro --product-descriptions Linux/UNIX --max-results 5",
    },
  },
  {
    id: "bill3",
    domain: "billing-pricing-and-support",
    text: "A company plans to run a steady, predictable workload for the next three years and wants the lowest possible price for that commitment. Which pricing option best fits this need?",
    options: [
      { id: "a", text: "On-Demand Instances" },
      { id: "b", text: "Spot Instances" },
      { id: "c", text: "Reserved Instances or Savings Plans" },
      { id: "d", text: "Free Tier" },
    ],
    correctOptionIds: ["c"],
    explanation: "Reserved Instances and Savings Plans offer significant discounts in exchange for a committed usage term.",
    optionRationale: {
      a: "On-Demand carries no discount for a long-term commitment, so it isn't the cheapest choice for a known 3-year workload.",
      b: "Spot Instances suit flexible, interruptible workloads, not a workload that needs a guaranteed steady 3-year presence.",
      c: "Reserved Instances and Savings Plans both let you commit to 1 or 3 years of usage in exchange for the deepest discounts — ideal for predictable, steady workloads.",
      d: "Free Tier only covers limited usage for new accounts and doesn't apply to a sustained production workload.",
    },
    referenceUrl: "https://aws.amazon.com/savingsplans/",
    referenceLabel: "AWS Savings Plans",
    diagram: "flowchart LR\n  Steady[Steady Predictable Workload] --> Commit[1 or 3 Year Commitment] --> Discount[Reserved Instances or Savings Plans Discount]",
    cliExample: {
      description: "List available Reserved Instance offerings for an instance type",
      command: "aws ec2 describe-reserved-instances-offerings --instance-type t3.micro --product-description Linux/UNIX --max-results 5",
    },
  },
  {
    id: "bill4",
    domain: "billing-pricing-and-support",
    text: "Which AWS service allows you to set custom cost and usage budgets and receive alerts when actual or forecasted costs exceed your thresholds?",
    options: [
      { id: "a", text: "AWS Cost Explorer" },
      { id: "b", text: "AWS Budgets" },
      { id: "c", text: "AWS Trusted Advisor" },
      { id: "d", text: "AWS Cost and Usage Report" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Budgets lets you set custom cost and usage thresholds and alerts when they are exceeded or forecast to be exceeded.",
    optionRationale: {
      a: "Cost Explorer visualizes historical and forecasted costs but doesn't let you define alert thresholds.",
      b: "AWS Budgets lets you define custom cost, usage, RI, or Savings Plans budgets and sends alerts when actual or forecasted spend crosses your threshold.",
      c: "Trusted Advisor offers best-practice checks, including some cost checks, but it isn't a budgeting or alerting service.",
      d: "The Cost and Usage Report is a detailed data export, not an interactive budgeting or alerting tool.",
    },
    referenceUrl: "https://aws.amazon.com/aws-cost-management/aws-budgets/",
    referenceLabel: "AWS Budgets",
    diagram: "flowchart LR\n  Usage[AWS Usage and Billing Data] --> Explorer[AWS Cost Explorer]\n  Usage --> Budgets[AWS Budgets]\n  Budgets --> Alert[Budget Alert Notification]\n  Explorer --> Forecast[Cost Forecast]",
    cliExample: {
      description: "Retrieve the budgets configured for your account",
      command: "aws budgets describe-budgets --account-id $(aws sts get-caller-identity --query Account --output text)",
    },
  },
  {
    id: "bill5",
    domain: "billing-pricing-and-support",
    text: "Which AWS service provides visualization and analysis of your historical AWS spending and usage patterns?",
    options: [
      { id: "a", text: "AWS Budgets" },
      { id: "b", text: "AWS Cost Explorer" },
      { id: "c", text: "Amazon CloudWatch" },
      { id: "d", text: "AWS Organizations" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Cost Explorer visualizes and analyzes historical AWS costs and usage patterns.",
    optionRationale: {
      a: "AWS Budgets sets thresholds and sends alerts; it isn't the visualization and analysis tool itself.",
      b: "AWS Cost Explorer gives you a visual, filterable view of historical costs and usage trends, plus basic forecasting.",
      c: "CloudWatch monitors operational metrics and logs, not billing and cost data.",
      d: "AWS Organizations manages multiple accounts and consolidated billing, but Cost Explorer is the dedicated spend-visualization tool.",
    },
    referenceUrl: "https://aws.amazon.com/aws-cost-management/aws-cost-explorer/",
    referenceLabel: "AWS Cost Explorer",
    diagram: "flowchart LR\n  Data[Historical Billing Data] --> CE[AWS Cost Explorer] --> Viz[Interactive Cost and Usage Charts]",
    cliExample: {
      description: "Retrieve unblended cost and usage totals for a monthly period",
      command: "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics UnblendedCost",
    },
  },
  {
    id: "bill6",
    domain: "billing-pricing-and-support",
    text: "What is a key benefit of using AWS Organizations' consolidated billing feature?",
    options: [
      { id: "a", text: "It combines usage across multiple accounts to potentially achieve volume pricing discounts, with a single bill" },
      { id: "b", text: "It grants every account root-level access to all resources" },
      { id: "c", text: "It automatically encrypts all account data" },
      { id: "d", text: "It eliminates the need for a payment method" },
    ],
    correctOptionIds: ["a"],
    explanation: "Consolidated billing combines usage from multiple accounts into a single bill and can unlock volume discounts.",
    optionRationale: {
      a: "Consolidated billing rolls usage from every linked account into one bill, combining volume to reach pricing tier and Savings Plans/RI discounts sooner.",
      b: "Consolidated billing doesn't grant cross-account root access; each account's access is still controlled independently through IAM and SCPs.",
      c: "Consolidated billing has nothing to do with encryption; encryption is configured per resource and service.",
      d: "The management account still needs a valid payment method — consolidated billing doesn't remove that requirement.",
    },
    referenceUrl: "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html",
    referenceLabel: "AWS Organizations",
    diagram: "flowchart TD\n  Mgmt[Management Account] --> A1[Member Account A]\n  Mgmt --> A2[Member Account B]\n  Mgmt --> A3[Member Account C]\n  A1 --> Bill[Single Consolidated Bill]\n  A2 --> Bill\n  A3 --> Bill",
    cliExample: {
      description: "List the member accounts included in an AWS Organization",
      command: "aws organizations list-accounts",
    },
  },
  {
    id: "bill7",
    domain: "billing-pricing-and-support",
    text: "Which AWS Support plan is the only paid plan that includes access to a designated Technical Account Manager (TAM)?",
    options: [
      { id: "a", text: "Basic" },
      { id: "b", text: "Developer" },
      { id: "c", text: "Business" },
      { id: "d", text: "Enterprise" },
    ],
    correctOptionIds: ["d"],
    explanation: "Only the Enterprise Support plan includes a designated Technical Account Manager.",
    optionRationale: {
      a: "Basic Support is free and doesn't include a TAM or proactive guidance.",
      b: "Developer Support adds business-hours technical support but still has no TAM.",
      c: "Business Support adds 24/7 technical support and full Trusted Advisor checks, but a TAM is exclusive to Enterprise.",
      d: "Enterprise Support is the only tier that includes a designated Technical Account Manager for proactive, ongoing guidance.",
    },
    referenceUrl: "https://aws.amazon.com/premiumsupport/plans/",
    referenceLabel: "AWS Support Plans",
    diagram: "flowchart BT\n  Basic[Basic Support Free] --> Developer[Developer Support]\n  Developer --> Business[Business Support]\n  Business --> Enterprise[Enterprise Support with TAM]",
    cliExample: {
      description: "List the case severity levels available under your support plan",
      command: "aws support describe-severity-levels",
    },
  },
  {
    id: "bill8",
    domain: "billing-pricing-and-support",
    text: "A startup wants free access to basic account and billing support, along with access to AWS Trusted Advisor's core checks, without paying for a support plan. Which support plan provides this?",
    options: [
      { id: "a", text: "Basic Support" },
      { id: "b", text: "Developer Support" },
      { id: "c", text: "Business Support" },
      { id: "d", text: "Enterprise Support" },
    ],
    correctOptionIds: ["a"],
    explanation: "Basic Support is free for all AWS customers and includes core Trusted Advisor checks and account/billing support.",
    optionRationale: {
      a: "Basic Support is included free with every AWS account and provides account/billing support plus the core Trusted Advisor checks.",
      b: "Developer Support is a paid plan aimed at testing and early-stage production use, not a free tier.",
      c: "Business Support is a paid, 24/7 plan for production workloads, well beyond a free basic offering.",
      d: "Enterprise Support is the highest, paid tier with a TAM — not a free option.",
    },
    referenceUrl: "https://aws.amazon.com/premiumsupport/plans/",
    referenceLabel: "AWS Support Plans",
    diagram: "flowchart LR\n  Basic[Basic Support: Free] --> AccountBilling[Account and Billing Support]\n  Basic --> CoreTA[Core Trusted Advisor Checks]",
    cliExample: {
      description: "List Trusted Advisor checks available to your account (requires a Business or Enterprise support plan)",
      command: "aws support describe-trusted-advisor-checks --language en",
    },
  },
  {
    id: "bill9",
    domain: "billing-pricing-and-support",
    text: "Which tool helps prospective and current AWS customers estimate the monthly cost of AWS services before deploying them?",
    options: [
      { id: "a", text: "AWS Cost Explorer" },
      { id: "b", text: "AWS Pricing Calculator" },
      { id: "c", text: "AWS Budgets" },
      { id: "d", text: "AWS Trusted Advisor" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Pricing Calculator estimates the cost of AWS services before you deploy them.",
    optionRationale: {
      a: "Cost Explorer analyzes costs you've already incurred, not a pre-deployment cost estimate.",
      b: "AWS Pricing Calculator lets you model the cost of a planned architecture before you deploy any of it.",
      c: "AWS Budgets tracks and alerts on spend after usage starts, not a pre-deployment estimator.",
      d: "Trusted Advisor reviews your existing account for best practices; it doesn't estimate costs for services you haven't deployed.",
    },
    referenceUrl: "https://calculator.aws/",
    referenceLabel: "AWS Pricing Calculator",
    diagram: "flowchart LR\n  Plan[Planned Architecture] --> Calc[AWS Pricing Calculator] --> Estimate[Monthly Cost Estimate]",
  },
  {
    id: "bill10",
    domain: "billing-pricing-and-support",
    text: "Which TWO of the following can help reduce AWS costs?",
    options: [
      { id: "a", text: "Using Reserved Instances or Savings Plans for steady-state workloads" },
      { id: "b", text: "Using Spot Instances for fault-tolerant, flexible workloads" },
      { id: "c", text: "Always choosing On-Demand pricing regardless of workload" },
      { id: "d", text: "Ignoring AWS Budgets alerts" },
      { id: "e", text: "Provisioning maximum capacity at all times 'just in case'" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Matching commitment-based pricing to steady workloads and Spot to flexible ones are common cost-reduction strategies.",
    optionRationale: {
      a: "Matching Reserved Instances or Savings Plans to steady-state workloads locks in a lower rate in exchange for commitment, cutting cost for predictable usage.",
      b: "Spot Instances can cut compute costs by up to 90% for workloads that tolerate interruption, such as batch jobs or fault-tolerant distributed processing.",
      c: "Always using On-Demand regardless of workload shape means paying the highest rate even for steady usage, which increases cost rather than reducing it.",
      d: "Ignoring Budgets alerts removes your early warning for overspend, which tends to increase costs, not reduce them.",
      e: "Provisioning maximum capacity 'just in case' wastes money on unused resources instead of scaling to actual demand.",
    },
    referenceUrl: "https://aws.amazon.com/aws-cost-management/",
    referenceLabel: "AWS Cost Management",
    diagram: "flowchart TD\n  Reduce[Reduce AWS Costs] --> Steady[Steady Workloads] --> RI[Reserved Instances or Savings Plans]\n  Reduce --> Flexible[Flexible, Fault-Tolerant Workloads] --> Spot[Spot Instances]",
    cliExample: {
      description: "Get EC2 right-sizing recommendations to help cut costs",
      command: "aws compute-optimizer get-ec2-instance-recommendations",
    },
  },
  {
    id: "bill11",
    domain: "billing-pricing-and-support",
    text: "Which TWO of the following are ways to organize and track AWS costs across teams or projects?",
    options: [
      { id: "a", text: "Cost allocation tags" },
      { id: "b", text: "AWS Organizations with consolidated billing" },
      { id: "c", text: "Deleting the AWS Cost and Usage Report" },
      { id: "d", text: "Disabling AWS Budgets" },
      { id: "e", text: "Sharing root account credentials" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Cost allocation tags and consolidated billing under AWS Organizations both help attribute and track spend across teams.",
    optionRationale: {
      a: "Cost allocation tags label resources by team, project, or environment so spend can be broken down in Cost Explorer and the Cost and Usage Report.",
      b: "AWS Organizations with consolidated billing groups accounts — for example by team or project — under one management account, making it easy to track spend per account.",
      c: "Deleting the Cost and Usage Report removes a key source of detailed billing data, which hurts cost tracking rather than helping it.",
      d: "Disabling Budgets removes cost alerting, making it harder, not easier, to track and control spend.",
      e: "Sharing root account credentials is a security anti-pattern and has nothing to do with organizing or tracking costs.",
    },
    referenceUrl: "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html",
    referenceLabel: "Cost Allocation Tags",
    diagram: "flowchart TD\n  Track[Track Cost by Team or Project] --> Tags[Cost Allocation Tags]\n  Track --> Orgs[AWS Organizations Consolidated Billing]",
    cliExample: {
      description: "Retrieve cost and usage grouped by a cost allocation tag",
      command:
        "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics UnblendedCost --group-by Type=TAG,Key=Project",
    },
  },
  {
    id: "bill12",
    domain: "billing-pricing-and-support",
    text: "A company runs a steady compute workload but expects to move some of it from EC2 to AWS Fargate and AWS Lambda over the next year, and may also change instance families and Regions. It wants a 1-year commitment discount that keeps applying as the workload shifts. Which purchasing option best meets these requirements?",
    options: [
      { id: "a", text: "Compute Savings Plan" },
      { id: "b", text: "EC2 Instance Savings Plan" },
      { id: "c", text: "Standard Reserved Instances" },
      { id: "d", text: "Spot Instances" },
    ],
    correctOptionIds: ["a"],
    explanation: "Compute Savings Plans commit to an hourly dollar spend and apply automatically across EC2 instance families, sizes, Regions, operating systems, and tenancy, as well as Fargate and Lambda usage.",
    optionRationale: {
      a: "A Compute Savings Plan is the most flexible commitment option: the discount follows usage across any EC2 instance family, size, Region, OS, and tenancy, and also covers AWS Fargate and AWS Lambda, so it keeps applying as the workload migrates.",
      b: "An EC2 Instance Savings Plan offers a deeper discount but is locked to a specific instance family within a single Region and does not cover Fargate or Lambda, so it wouldn't follow the migration.",
      c: "Standard Reserved Instances are tied to a specific instance type, Region, and platform, and cannot be applied to Fargate or Lambda usage.",
      d: "Spot Instances are interruptible spare capacity with no commitment; they don't provide a commitment-based discount for a steady workload and don't apply to Fargate or Lambda.",
    },
    referenceUrl: "https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html",
    referenceLabel: "What are Savings Plans?",
    diagram: "flowchart LR\n  Commit[1 or 3 Year Hourly Spend Commitment] --> CSP[Compute Savings Plan]\n  CSP --> EC2[Any EC2 Family, Size, Region, OS]\n  CSP --> Fargate[AWS Fargate]\n  CSP --> Lambda[AWS Lambda]\n  Commit --> ESP[EC2 Instance Savings Plan]\n  ESP --> Family[One Instance Family in One Region]",
    cliExample: {
      description: "Retrieve Savings Plans purchase recommendations for a 1-year, no-upfront Compute Savings Plan",
      command: "aws ce get-savings-plans-purchase-recommendation --savings-plans-type COMPUTE_SP --term-in-years ONE_YEAR --payment-option NO_UPFRONT --lookback-period-in-days THIRTY_DAYS",
    },
  },
  {
    id: "bill13",
    domain: "billing-pricing-and-support",
    text: "A company is preparing to launch a production workload on AWS. It needs 24/7 phone, chat, and email access to Cloud Support Engineers and a response time of one hour or less for production system down cases, but it does not need a Technical Account Manager. Which AWS Support plan is the lowest-cost option that meets these requirements?",
    options: [
      { id: "a", text: "Basic Support" },
      { id: "b", text: "Developer Support" },
      { id: "c", text: "Business Support" },
      { id: "d", text: "Enterprise Support" },
    ],
    correctOptionIds: ["c"],
    explanation: "Business Support is the lowest-cost plan that provides 24/7 phone, chat, and email access to Cloud Support Engineers, with a response time of less than one hour for production system down cases and full Trusted Advisor checks.",
    optionRationale: {
      a: "Basic Support is free but only covers account and billing questions plus core Trusted Advisor checks; it provides no technical support cases at all.",
      b: "Developer Support offers business-hours email access to Cloud Support Associates with a 12-hour response for system impaired cases; it has no 24/7 phone or chat access and no production-down SLA.",
      c: "Business Support provides 24/7 phone, chat, and email access to Cloud Support Engineers, with a response time of less than 1 hour for production system down cases and less than 4 hours for production system impaired cases — the lowest-cost plan that meets the requirements.",
      d: "Enterprise Support (and Enterprise On-Ramp) would also meet the response-time requirement, adding a 15-minute business-critical response and a TAM, but at a much higher cost than needed.",
    },
    referenceUrl: "https://aws.amazon.com/premiumsupport/plans/",
    referenceLabel: "Compare AWS Support Plans",
    diagram: "flowchart TD\n  Dev[Developer: Business Hours Email] --> DevSLA[System Impaired < 12 hrs]\n  Biz[Business: 24/7 Phone, Chat, Email] --> BizSLA[Production Down < 1 hr]\n  Ramp[Enterprise On-Ramp: 24/7 + Pool of TAMs] --> RampSLA[Business-Critical Down < 30 min]\n  Ent[Enterprise: 24/7 + Designated TAM] --> EntSLA[Business-Critical Down < 15 min]",
    cliExample: {
      description: "Open a high-severity support case (requires a Business, Enterprise On-Ramp, or Enterprise support plan)",
      command: "aws support create-case --subject \"Production API unavailable\" --service-code amazon-elastic-compute-cloud-linux --severity-code urgent --category-code other --communication-body \"Production instances are unreachable since 09:00 UTC.\"",
    },
  },
  {
    id: "bill14",
    domain: "billing-pricing-and-support",
    text: "A startup is reviewing its first AWS bill and wants to understand which data transfer charges to expect. Which TWO statements about AWS data transfer pricing are correct?",
    options: [
      { id: "a", text: "Data transferred into AWS from the internet is generally free of charge" },
      { id: "b", text: "Data transferred out from AWS to the internet is charged per GB" },
      { id: "c", text: "Data transferred between AWS Regions is always free" },
      { id: "d", text: "Data transferred out to the internet is free for the first 10 TB every month regardless of service" },
      { id: "e", text: "Uploading objects to Amazon S3 from on-premises incurs a per-GB inbound transfer charge" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Inbound data transfer from the internet to AWS is free, while outbound data transfer from AWS to the internet and transfer between Regions is charged per GB.",
    optionRationale: {
      a: "Inbound data transfer from the internet into AWS services such as EC2 and S3 is free; AWS charges primarily for data leaving its network.",
      b: "Outbound data transfer from AWS to the internet is billed per GB on a tiered schedule, which is why architectures often use CloudFront or keep traffic inside a Region to lower costs.",
      c: "Cross-Region data transfer (for example, S3 Cross-Region Replication or inter-Region VPC peering) is charged per GB; it is not free.",
      d: "The AWS Free Tier includes 100 GB of free outbound data transfer per month across services (and 1 TB from CloudFront), not 10 TB regardless of service.",
      e: "Uploading (inbound transfer) to S3 is free; you pay for storage and requests, not for the inbound bytes.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/aws/aws-free-tier-data-transfer-expansion-100-gb-from-regions-and-1-tb-from-amazon-cloudfront-per-month/",
    referenceLabel: "AWS Free Tier Data Transfer Expansion",
    diagram: "flowchart LR\n  Internet[Internet] -->|Inbound: Free| AWS[AWS Region]\n  AWS -->|Outbound: Charged per GB| Internet\n  AWS -->|Cross-Region: Charged per GB| Region2[Another AWS Region]",
    cliExample: {
      description: "Retrieve monthly cost filtered to data transfer usage types",
      command: "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics UnblendedCost --filter '{\"Dimensions\":{\"Key\":\"USAGE_TYPE_GROUP\",\"Values\":[\"EC2: Data Transfer - Internet (Out)\"]}}'",
    },
  },
];
