import { Question } from "../types.js";

export const billingPricingAndSupportQuestions: Question[] = [
  {
    id: "bill1",
    domain: "billing-pricing-and-support",
    text: "Which AWS pricing model requires no upfront payment and lets you pay for compute capacity by the second or hour with no long-term commitment?",
    options: [
      { id: "a", text: "Reserved Instances" },
      { id: "b", text: "On-Demand Instances" },
      { id: "c", text: "Spot Instances" },
      { id: "d", text: "Savings Plans" },
    ],
    correctOptionIds: ["b"],
    explanation: "On-Demand Instances let you pay for compute capacity with no upfront payment or long-term commitment.",
  },
  {
    id: "bill2",
    domain: "billing-pricing-and-support",
    text: "Which EC2 purchasing option lets you use spare AWS compute capacity at steep discounts, with the risk that the instance can be interrupted by AWS with short notice?",
    options: [
      { id: "a", text: "On-Demand Instances" },
      { id: "b", text: "Reserved Instances" },
      { id: "c", text: "Spot Instances" },
      { id: "d", text: "Dedicated Hosts" },
    ],
    correctOptionIds: ["c"],
    explanation: "Spot Instances use spare EC2 capacity at a discount but can be reclaimed by AWS with short notice.",
  },
  {
    id: "bill3",
    domain: "billing-pricing-and-support",
    text: "A company plans to run a steady, predictable workload for the next three years and wants the lowest possible price for that commitment. Which pricing option best fits this need?",
    options: [
      { id: "a", text: "On-Demand Instances" },
      { id: "b", text: "Spot Instances" },
      { id: "c", text: "Reserved Instances or Savings Plans" },
      { id: "d", text: "Free Tier" },
    ],
    correctOptionIds: ["c"],
    explanation: "Reserved Instances and Savings Plans offer significant discounts in exchange for a committed usage term.",
  },
  {
    id: "bill4",
    domain: "billing-pricing-and-support",
    text: "Which AWS service allows you to set custom cost and usage budgets and receive alerts when actual or forecasted costs exceed your thresholds?",
    options: [
      { id: "a", text: "AWS Cost Explorer" },
      { id: "b", text: "AWS Budgets" },
      { id: "c", text: "AWS Trusted Advisor" },
      { id: "d", text: "AWS Cost and Usage Report" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Budgets lets you set custom cost and usage thresholds and alerts when they are exceeded or forecast to be exceeded.",
  },
  {
    id: "bill5",
    domain: "billing-pricing-and-support",
    text: "Which AWS service provides visualization and analysis of your historical AWS spending and usage patterns?",
    options: [
      { id: "a", text: "AWS Budgets" },
      { id: "b", text: "AWS Cost Explorer" },
      { id: "c", text: "Amazon CloudWatch" },
      { id: "d", text: "AWS Organizations" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Cost Explorer visualizes and analyzes historical AWS costs and usage patterns.",
  },
  {
    id: "bill6",
    domain: "billing-pricing-and-support",
    text: "What is a key benefit of using AWS Organizations' consolidated billing feature?",
    options: [
      { id: "a", text: "It combines usage across multiple accounts to potentially achieve volume pricing discounts, with a single bill" },
      { id: "b", text: "It grants every account root-level access to all resources" },
      { id: "c", text: "It automatically encrypts all account data" },
      { id: "d", text: "It eliminates the need for a payment method" },
    ],
    correctOptionIds: ["a"],
    explanation: "Consolidated billing combines usage from multiple accounts into a single bill and can unlock volume discounts.",
  },
  {
    id: "bill7",
    domain: "billing-pricing-and-support",
    text: "Which AWS Support plan is the only paid plan that includes access to a designated Technical Account Manager (TAM)?",
    options: [
      { id: "a", text: "Basic" },
      { id: "b", text: "Developer" },
      { id: "c", text: "Business" },
      { id: "d", text: "Enterprise" },
    ],
    correctOptionIds: ["d"],
    explanation: "Only the Enterprise Support plan includes a designated Technical Account Manager.",
  },
  {
    id: "bill8",
    domain: "billing-pricing-and-support",
    text: "A startup wants free access to basic account and billing support, along with access to AWS Trusted Advisor's core checks, without paying for a support plan. Which support plan provides this?",
    options: [
      { id: "a", text: "Basic Support" },
      { id: "b", text: "Developer Support" },
      { id: "c", text: "Business Support" },
      { id: "d", text: "Enterprise Support" },
    ],
    correctOptionIds: ["a"],
    explanation: "Basic Support is free for all AWS customers and includes core Trusted Advisor checks and account/billing support.",
  },
  {
    id: "bill9",
    domain: "billing-pricing-and-support",
    text: "Which tool helps prospective and current AWS customers estimate the monthly cost of AWS services before deploying them?",
    options: [
      { id: "a", text: "AWS Cost Explorer" },
      { id: "b", text: "AWS Pricing Calculator" },
      { id: "c", text: "AWS Budgets" },
      { id: "d", text: "AWS Trusted Advisor" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Pricing Calculator estimates the cost of AWS services before you deploy them.",
  },
  {
    id: "bill10",
    domain: "billing-pricing-and-support",
    text: "Which TWO of the following can help reduce AWS costs?",
    options: [
      { id: "a", text: "Using Reserved Instances or Savings Plans for steady-state workloads" },
      { id: "b", text: "Using Spot Instances for fault-tolerant, flexible workloads" },
      { id: "c", text: "Always choosing On-Demand pricing regardless of workload" },
      { id: "d", text: "Ignoring AWS Budgets alerts" },
      { id: "e", text: "Provisioning maximum capacity at all times 'just in case'" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Matching commitment-based pricing to steady workloads and Spot to flexible ones are common cost-reduction strategies.",
  },
  {
    id: "bill11",
    domain: "billing-pricing-and-support",
    text: "Which TWO of the following are ways to organize and track AWS costs across teams or projects?",
    options: [
      { id: "a", text: "Cost allocation tags" },
      { id: "b", text: "AWS Organizations with consolidated billing" },
      { id: "c", text: "Deleting the AWS Cost and Usage Report" },
      { id: "d", text: "Disabling AWS Budgets" },
      { id: "e", text: "Sharing root account credentials" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Cost allocation tags and consolidated billing under AWS Organizations both help attribute and track spend across teams.",
  },
];
