import { Question } from "../types.js";

export const cloudConceptsQuestions: Question[] = [
  {
    id: "cc1",
    domain: "cloud-concepts",
    text: "Which AWS pricing benefit allows customers to pay only for the compute capacity they actually use, with no upfront commitment?",
    options: [
      { id: "a", text: "Economies of scale" },
      { id: "b", text: "Pay-as-you-go pricing" },
      { id: "c", text: "Reserved capacity guarantee" },
      { id: "d", text: "Fixed monthly billing" },
    ],
    correctOptionIds: ["b"],
    explanation: "Pay-as-you-go pricing means you pay only for what you consume, with no long-term contracts required.",
  },
  {
    id: "cc2",
    domain: "cloud-concepts",
    text: "What does 'elasticity' mean in the context of cloud computing?",
    options: [
      { id: "a", text: "The ability to automatically scale resources up or down to match demand" },
      { id: "b", text: "The physical durability of AWS data centers" },
      { id: "c", text: "The ability to run workloads across multiple regions simultaneously" },
      { id: "d", text: "The encryption of data at rest" },
    ],
    correctOptionIds: ["a"],
    explanation: "Elasticity is the ability to grow or shrink infrastructure resources dynamically to meet changing demand.",
  },
  {
    id: "cc3",
    domain: "cloud-concepts",
    text: "A company wants to convert its large upfront hardware purchases into ongoing, usage-based expenses. Which cloud economic benefit does this describe?",
    options: [
      { id: "a", text: "Economies of scale" },
      { id: "b", text: "Trading capital expense for variable expense" },
      { id: "c", text: "Increased speed and agility" },
      { id: "d", text: "Going global in minutes" },
    ],
    correctOptionIds: ["b"],
    explanation: "Cloud computing replaces large upfront capital expenditure with variable operational expense based on actual usage.",
  },
  {
    id: "cc4",
    domain: "cloud-concepts",
    text: "Which AWS Cloud Adoption Framework (AWS CAF) perspective focuses on aligning IT strategy with business goals?",
    options: [
      { id: "a", text: "Technology" },
      { id: "b", text: "Operations" },
      { id: "c", text: "Business" },
      { id: "d", text: "Security" },
    ],
    correctOptionIds: ["c"],
    explanation: "The Business perspective of AWS CAF focuses on ensuring IT aligns with and enables business strategy and outcomes.",
  },
  {
    id: "cc5",
    domain: "cloud-concepts",
    text: "What is the primary advantage of AWS's global infrastructure for a company launching an application to customers on multiple continents?",
    options: [
      { id: "a", text: "It eliminates the need for a content delivery network" },
      { id: "b", text: "It allows the company to deploy in new geographic regions in minutes instead of months" },
      { id: "c", text: "It guarantees zero latency worldwide" },
      { id: "d", text: "It removes the need for an internet connection" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS's global footprint of Regions lets companies deploy infrastructure close to customers worldwide in minutes.",
  },
  {
    id: "cc6",
    domain: "cloud-concepts",
    text: "An Availability Zone (AZ) consists of one or more discrete data centers with redundant power, networking, and connectivity. What is the main purpose of having multiple AZs within a Region?",
    options: [
      { id: "a", text: "To reduce data transfer costs" },
      { id: "b", text: "To provide high availability and fault tolerance within a Region" },
      { id: "c", text: "To enable multi-factor authentication" },
      { id: "d", text: "To provide a global content delivery network" },
    ],
    correctOptionIds: ["b"],
    explanation: "Spreading resources across multiple, isolated Availability Zones protects applications from a single data center failure.",
  },
  {
    id: "cc7",
    domain: "cloud-concepts",
    text: "Which TWO of the following are pillars of the AWS Well-Architected Framework?",
    options: [
      { id: "a", text: "Operational Excellence" },
      { id: "b", text: "Cost Optimization" },
      { id: "c", text: "Marketing Efficiency" },
      { id: "d", text: "Vendor Lock-in Avoidance" },
      { id: "e", text: "Customer Obsession" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "The six pillars are Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, and Sustainability.",
  },
  {
    id: "cc8",
    domain: "cloud-concepts",
    text: "A company is deciding between building its own data center and using AWS. Which factor is a common advantage of AWS over on-premises infrastructure?",
    options: [
      { id: "a", text: "No need to ever patch software" },
      { id: "b", text: "Ability to stop guessing capacity and scale based on actual demand" },
      { id: "c", text: "Guaranteed lower cost regardless of usage" },
      { id: "d", text: "Unlimited free data transfer" },
    ],
    correctOptionIds: ["b"],
    explanation: "Cloud computing removes the need to guess infrastructure capacity in advance; you can scale up or down as actual demand changes.",
  },
  {
    id: "cc9",
    domain: "cloud-concepts",
    text: "Which migration strategy (one of the '6 R's') involves moving an application to the cloud with no code changes?",
    options: [
      { id: "a", text: "Refactor" },
      { id: "b", text: "Rehost ('lift and shift')" },
      { id: "c", text: "Replatform" },
      { id: "d", text: "Retire" },
    ],
    correctOptionIds: ["b"],
    explanation: "Rehosting, or 'lift and shift', moves an application to the cloud as-is, without changing its code or architecture.",
  },
  {
    id: "cc10",
    domain: "cloud-concepts",
    text: "Which migration strategy involves making minor optimizations to take advantage of cloud capabilities without changing the application's core architecture?",
    options: [
      { id: "a", text: "Rehost" },
      { id: "b", text: "Replatform ('lift and reshape')" },
      { id: "c", text: "Repurchase" },
      { id: "d", text: "Retain" },
    ],
    correctOptionIds: ["b"],
    explanation: "Replatforming makes a few targeted cloud optimizations, such as swapping a self-managed database for a managed one, without a full rearchitecture.",
  },
  {
    id: "cc11",
    domain: "cloud-concepts",
    text: "A business decides to stop using a legacy on-premises application and instead subscribe to a SaaS alternative. Which migration strategy does this represent?",
    options: [
      { id: "a", text: "Retire" },
      { id: "b", text: "Repurchase" },
      { id: "c", text: "Rehost" },
      { id: "d", text: "Refactor" },
    ],
    correctOptionIds: ["b"],
    explanation: "Repurchasing means replacing an existing application with a different product, typically a SaaS offering.",
  },
  {
    id: "cc12",
    domain: "cloud-concepts",
    text: "Which cloud computing benefit refers to the increased speed and ease with which IT resources can be provisioned, enabling faster experimentation?",
    options: [
      { id: "a", text: "Agility" },
      { id: "b", text: "Elasticity" },
      { id: "c", text: "Durability" },
      { id: "d", text: "Compliance" },
    ],
    correctOptionIds: ["a"],
    explanation: "Agility describes how quickly teams can provision resources, experiment, and iterate compared to traditional infrastructure.",
  },
  {
    id: "cc13",
    domain: "cloud-concepts",
    text: "What is a key characteristic that differentiates fault tolerance from high availability?",
    options: [
      { id: "a", text: "Fault-tolerant systems continue operating with zero downtime even if a component fails, while highly available systems minimize but may not eliminate downtime" },
      { id: "b", text: "Fault tolerance only applies to storage services" },
      { id: "c", text: "High availability requires multiple AWS accounts" },
      { id: "d", text: "Fault tolerance is only achieved through manual intervention" },
    ],
    correctOptionIds: ["a"],
    explanation: "Fault tolerance masks failures entirely with no downtime, while high availability aims to minimize downtime but may involve a brief interruption.",
  },
  {
    id: "cc14",
    domain: "cloud-concepts",
    text: "Which TWO of the following are perspectives in the AWS Cloud Adoption Framework (AWS CAF)?",
    options: [
      { id: "a", text: "Governance" },
      { id: "b", text: "Platform" },
      { id: "c", text: "Advertising" },
      { id: "d", text: "Sales Enablement" },
      { id: "e", text: "Human Resources" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "The six CAF perspectives are Business, People, Governance, Platform, Security, and Operations.",
  },
  {
    id: "cc15",
    domain: "cloud-concepts",
    text: "A startup wants to test a new idea with minimal upfront investment. Which cloud benefit best supports this goal?",
    options: [
      { id: "a", text: "Stop spending money running and maintaining data centers" },
      { id: "b", text: "Guaranteed 100% uptime" },
      { id: "c", text: "Mandatory long-term contracts" },
      { id: "d", text: "Fixed hardware refresh cycles" },
    ],
    correctOptionIds: ["a"],
    explanation: "By not owning data centers, a startup avoids large upfront investments and can redirect resources toward its product.",
  },
  {
    id: "cc16",
    domain: "cloud-concepts",
    text: "What is the relationship between a Region and Availability Zones in AWS?",
    options: [
      { id: "a", text: "A Region contains multiple, isolated Availability Zones" },
      { id: "b", text: "An Availability Zone contains multiple Regions" },
      { id: "c", text: "Regions and Availability Zones are the same thing" },
      { id: "d", text: "Availability Zones exist outside of Regions" },
    ],
    correctOptionIds: ["a"],
    explanation: "Each AWS Region is a separate geographic area made up of multiple isolated Availability Zones.",
  },
  {
    id: "cc17",
    domain: "cloud-concepts",
    text: "Which of the following best describes an AWS edge location?",
    options: [
      { id: "a", text: "A primary data center used exclusively for compute workloads" },
      { id: "b", text: "A site used by Amazon CloudFront and other services to cache content closer to end users" },
      { id: "c", text: "A backup Region used only for disaster recovery" },
      { id: "d", text: "A physical office where AWS support staff work" },
    ],
    correctOptionIds: ["b"],
    explanation: "Edge locations cache content near end users to reduce latency for services like Amazon CloudFront.",
  },
  {
    id: "cc18",
    domain: "cloud-concepts",
    text: "A company currently runs all its workloads on-premises but occasionally bursts to the cloud during peak demand. Which deployment model does this describe?",
    options: [
      { id: "a", text: "All-in cloud" },
      { id: "b", text: "On-premises only" },
      { id: "c", text: "Hybrid" },
      { id: "d", text: "Multi-cloud" },
    ],
    correctOptionIds: ["c"],
    explanation: "A hybrid deployment combines on-premises infrastructure with cloud resources, often used for cloud bursting.",
  },
  {
    id: "cc19",
    domain: "cloud-concepts",
    text: "Which TWO of the following are benefits commonly associated with cloud computing over traditional on-premises IT?",
    options: [
      { id: "a", text: "Trade capital expense for variable expense" },
      { id: "b", text: "Benefit from massive economies of scale" },
      { id: "c", text: "Guaranteed zero cost" },
      { id: "d", text: "Elimination of the shared responsibility model" },
      { id: "e", text: "No need for any security controls" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Cloud computing's core benefits include trading capex for variable opex and benefiting from AWS's economies of scale.",
  },
  {
    id: "cc20",
    domain: "cloud-concepts",
    text: "Which statement best describes 'economies of scale' as an AWS Cloud benefit?",
    options: [
      { id: "a", text: "As AWS grows, higher volumes lead to lower costs, which AWS can pass on as lower pricing to customers" },
      { id: "b", text: "Each customer negotiates a unique lower price directly" },
      { id: "c", text: "Costs decrease only for customers using a single AWS service" },
      { id: "d", text: "Economies of scale apply only to compute services" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS's massive scale of operation drives down per-unit costs, savings that are passed on to customers through lower prices.",
  },
  {
    id: "cc21",
    domain: "cloud-concepts",
    text: "What is the main purpose of the AWS Well-Architected Framework?",
    options: [
      { id: "a", text: "To provide a consistent approach for evaluating and improving cloud architectures against best practices" },
      { id: "b", text: "To replace the AWS Shared Responsibility Model" },
      { id: "c", text: "To calculate exact monthly billing" },
      { id: "d", text: "To manage IAM permissions automatically" },
    ],
    correctOptionIds: ["a"],
    explanation: "The Well-Architected Framework gives a consistent set of questions and best practices for reviewing cloud architectures.",
  },
];
