import { Question } from "../types.js";

export const cloudConceptsQuestions: Question[] = [
  {
    id: "cc1",
    domain: "cloud-concepts",
    text: "Which AWS pricing benefit allows customers to pay only for the compute capacity they actually use, with no upfront commitment?",
    options: [
      { id: "a", text: "Economies of scale" },
      { id: "b", text: "Pay-as-you-go pricing" },
      { id: "c", text: "Reserved capacity guarantee" },
      { id: "d", text: "Fixed monthly billing" },
    ],
    correctOptionIds: ["b"],
    explanation: "Pay-as-you-go pricing means you pay only for what you consume, with no long-term contracts required.",
    optionRationale: {
      a: "Economies of scale explains why AWS's costs (and prices) fall as it grows — it's not the customer's payment model.",
      b: "Pay-as-you-go pricing charges you only for the compute capacity you actually consume, with no upfront commitment.",
      c: "Reserved capacity requires a commitment in exchange for a discount, the opposite of pay-as-you-go.",
      d: "Fixed monthly billing doesn't track actual usage, so it isn't pay-as-you-go pricing.",
    },
    referenceUrl: "https://aws.amazon.com/pricing/",
    referenceLabel: "AWS Pricing Overview",
    diagram:
      "flowchart LR\n    Usage[Track Actual Usage] --> Bill[Pay-as-you-go Bill]\n    NoCommit[No Upfront Commitment] --> Bill\n    Bill --> Stop[Stop Anytime]",
    cliExample: {
      description: "Look up on-demand (pay-as-you-go) pricing for an EC2 instance type",
      command: "aws pricing get-products --service-code AmazonEC2 --region us-east-1 --filters Type=TERM_MATCH,Field=instanceType,Value=t3.micro",
      sampleOutput: "{\n  \"FormatVersion\": \"aws_v1\",\n  \"PriceList\": [\n    \"{\\\"product\\\":{\\\"productFamily\\\":\\\"Compute Instance\\\",\\\"attributes\\\":{\\\"instanceType\\\":\\\"t3.micro\\\",\\\"vcpu\\\":\\\"2\\\",\\\"memory\\\":\\\"1 GiB\\\",\\\"location\\\":\\\"US East (N. Virginia)\\\"}},\\\"terms\\\":{\\\"OnDemand\\\":{\\\"...\\\":{\\\"priceDimensions\\\":{\\\"...\\\":{\\\"unit\\\":\\\"Hrs\\\",\\\"pricePerUnit\\\":{\\\"USD\\\":\\\"0.0104000000\\\"}}}}}}}\"\n  ],\n  \"NextToken\": \"AYABeF0z...\"\n}",
    },
  },
  {
    id: "cc2",
    domain: "cloud-concepts",
    text: "What does 'elasticity' mean in the context of cloud computing?",
    options: [
      { id: "a", text: "The ability to automatically scale resources up or down to match demand" },
      { id: "b", text: "The physical durability of AWS data centers" },
      { id: "c", text: "The ability to run workloads across multiple regions simultaneously" },
      { id: "d", text: "The encryption of data at rest" },
    ],
    correctOptionIds: ["a"],
    explanation: "Elasticity is the ability to grow or shrink infrastructure resources dynamically to meet changing demand.",
    optionRationale: {
      a: "This is the definition of elasticity: resources scale automatically to match demand.",
      b: "Physical durability of data centers is a facilities/resilience concept, not elasticity.",
      c: "Running across multiple regions is about geographic reach, not scaling capacity up or down.",
      d: "Encryption at rest is a data-protection concept, unrelated to scaling.",
    },
    referenceUrl: "https://aws.amazon.com/what-is-cloud-computing/",
    referenceLabel: "What Is Cloud Computing?",
    diagram:
      "flowchart LR\n    Low[Low Demand] --> Scale[Elastic Resources]\n    High[High Demand] --> Scale\n    Scale --> Out[Scale Out Automatically]\n    Scale --> In[Scale In Automatically]",
    cliExample: {
      description: "List Auto Scaling groups, which implement elasticity for EC2 capacity",
      command: "aws autoscaling describe-auto-scaling-groups",
      sampleOutput: "{\n  \"AutoScalingGroups\": [\n    {\n      \"AutoScalingGroupName\": \"web-asg\",\n      \"AutoScalingGroupARN\": \"arn:aws:autoscaling:us-east-1:123456789012:autoScalingGroup:6f9a1b2c-3d4e-5f60-7a8b-9c0d1e2f3a4b:autoScalingGroupName/web-asg\",\n      \"LaunchTemplate\": {\n        \"LaunchTemplateId\": \"lt-0123456789abcdef0\",\n        \"Version\": \"$Latest\"\n      },\n      \"MinSize\": 2,\n      \"MaxSize\": 10,\n      \"DesiredCapacity\": 4,\n      \"AvailabilityZones\": [\n        \"us-east-1a\",\n        \"us-east-1b\"\n      ],\n      \"Instances\": [\n        {\n          \"InstanceId\": \"i-0abc123def456789a\",\n          \"AvailabilityZone\": \"us-east-1a\",\n          \"LifecycleState\": \"InService\",\n          \"HealthStatus\": \"Healthy\"\n        }\n      ],\n      \"CreatedTime\": \"2026-03-02T09:15:30.000Z\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc3",
    domain: "cloud-concepts",
    text: "A company wants to convert its large upfront hardware purchases into ongoing, usage-based expenses. Which cloud economic benefit does this describe?",
    options: [
      { id: "a", text: "Economies of scale" },
      { id: "b", text: "Trading capital expense for variable expense" },
      { id: "c", text: "Increased speed and agility" },
      { id: "d", text: "Going global in minutes" },
    ],
    correctOptionIds: ["b"],
    explanation: "Cloud computing replaces large upfront capital expenditure with variable operational expense based on actual usage.",
    optionRationale: {
      a: "Economies of scale is about AWS's costs falling as it grows, not about how a customer's spending is structured.",
      b: "This directly describes trading capex for variable opex: large upfront purchases become ongoing usage-based spending.",
      c: "Speed and agility is about how fast resources can be provisioned, not the expense model.",
      d: "Going global in minutes describes geographic reach, not the shift from capex to opex.",
    },
    referenceUrl: "https://aws.amazon.com/economics/",
    referenceLabel: "AWS Cloud Economics",
    diagram:
      "flowchart LR\n    CapEx[Upfront Capital Expense] --> Cloud[Move to AWS Cloud]\n    Cloud --> OpEx[Ongoing Variable Operating Expense]",
    cliExample: {
      description: "View AWS costs by month, reflecting usage-based variable operating expense",
      command: "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics UnblendedCost",
      sampleOutput: "{\n  \"ResultsByTime\": [\n    {\n      \"TimePeriod\": {\n        \"Start\": \"2024-01-01\",\n        \"End\": \"2024-02-01\"\n      },\n      \"Total\": {\n        \"UnblendedCost\": {\n          \"Amount\": \"1284.7312\",\n          \"Unit\": \"USD\"\n        }\n      },\n      \"Groups\": [],\n      \"Estimated\": false\n    }\n  ],\n  \"DimensionValueAttributes\": []\n}",
    },
  },
  {
    id: "cc4",
    domain: "cloud-concepts",
    text: "Which AWS Cloud Adoption Framework (AWS CAF) perspective focuses on aligning IT strategy with business goals?",
    options: [
      { id: "a", text: "Technology" },
      { id: "b", text: "Operations" },
      { id: "c", text: "Business" },
      { id: "d", text: "Security" },
    ],
    correctOptionIds: ["c"],
    explanation: "The Business perspective of AWS CAF focuses on ensuring IT aligns with and enables business strategy and outcomes.",
    optionRationale: {
      a: "The Technology perspective covers architecture and technical delivery, not business-IT alignment.",
      b: "The Operations perspective covers running, monitoring, and managing workloads day to day.",
      c: "The Business perspective ensures IT investments and strategy align with and enable business outcomes.",
      d: "The Security perspective covers risk management and compliance, not business alignment.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/overview-aws-cloud-adoption-framework/welcome.html",
    referenceLabel: "AWS Cloud Adoption Framework",
    diagram:
      "flowchart LR\n    Business[Business Perspective] --> Strategy[IT Strategy]\n    Strategy --> Goals[Aligned Business Outcomes]",
  },
  {
    id: "cc5",
    domain: "cloud-concepts",
    text: "What is the primary advantage of AWS's global infrastructure for a company launching an application to customers on multiple continents?",
    options: [
      { id: "a", text: "It eliminates the need for a content delivery network" },
      { id: "b", text: "It allows the company to deploy in new geographic regions in minutes instead of months" },
      { id: "c", text: "It guarantees zero latency worldwide" },
      { id: "d", text: "It removes the need for an internet connection" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS's global footprint of Regions lets companies deploy infrastructure close to customers worldwide in minutes.",
    optionRationale: {
      a: "Global infrastructure complements a CDN like Amazon CloudFront; it doesn't remove the need for one.",
      b: "AWS's global footprint of Regions lets a company stand up infrastructure near customers worldwide in minutes.",
      c: "No infrastructure can guarantee zero latency; AWS reduces latency but doesn't eliminate it entirely.",
      d: "Cloud applications still require network connectivity; global infrastructure doesn't remove that need.",
    },
    referenceUrl: "https://aws.amazon.com/about-aws/global-infrastructure/",
    referenceLabel: "AWS Global Infrastructure",
    consoleUrl: "https://console.aws.amazon.com/ec2globalview/home",
    consoleLabel: "EC2 Global View",
    diagram:
      "flowchart LR\n    Company[Company] --> Launch[Launch Infrastructure]\n    Launch --> Region[New AWS Region]\n    Region --> Minutes[Live in Minutes]",
    cliExample: {
      description: "List AWS Regions available to deploy infrastructure into",
      command: "aws ec2 describe-regions",
      sampleOutput: "{\n  \"Regions\": [\n    {\n      \"Endpoint\": \"ec2.us-east-1.amazonaws.com\",\n      \"RegionName\": \"us-east-1\",\n      \"OptInStatus\": \"opt-in-not-required\"\n    },\n    {\n      \"Endpoint\": \"ec2.ap-southeast-1.amazonaws.com\",\n      \"RegionName\": \"ap-southeast-1\",\n      \"OptInStatus\": \"opt-in-not-required\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc6",
    domain: "cloud-concepts",
    text: "An Availability Zone (AZ) consists of one or more discrete data centers with redundant power, networking, and connectivity. What is the main purpose of having multiple AZs within a Region?",
    options: [
      { id: "a", text: "To reduce data transfer costs" },
      { id: "b", text: "To provide high availability and fault tolerance within a Region" },
      { id: "c", text: "To enable multi-factor authentication" },
      { id: "d", text: "To provide a global content delivery network" },
    ],
    correctOptionIds: ["b"],
    explanation: "Spreading resources across multiple, isolated Availability Zones protects applications from a single data center failure.",
    optionRationale: {
      a: "Multiple AZs exist for resilience, not primarily to lower data transfer costs.",
      b: "Spreading resources across isolated AZs protects an application from a single data center or facility failure.",
      c: "Multi-factor authentication is an identity security feature, unrelated to AZ design.",
      d: "A global CDN is provided by edge locations and CloudFront, not by AZs within a Region.",
    },
    referenceUrl: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
    referenceLabel: "AWS Regions and Availability Zones",
    diagram:
      "flowchart TD\n    R[AWS Region] --> AZ1[Availability Zone 1]\n    R --> AZ2[Availability Zone 2]\n    R --> AZ3[Availability Zone 3]\n    AZ1 --> DC1[Data Center]\n    AZ2 --> DC2[Data Center]\n    AZ3 --> DC3[Data Center]",
    cliExample: {
      description: "List the Availability Zones available in a Region",
      command: "aws ec2 describe-availability-zones --region us-east-1",
      sampleOutput: "{\n  \"AvailabilityZones\": [\n    {\n      \"State\": \"available\",\n      \"OptInStatus\": \"opt-in-not-required\",\n      \"RegionName\": \"us-east-1\",\n      \"ZoneName\": \"us-east-1a\",\n      \"ZoneId\": \"use1-az6\",\n      \"ZoneType\": \"availability-zone\",\n      \"NetworkBorderGroup\": \"us-east-1\"\n    },\n    {\n      \"State\": \"available\",\n      \"OptInStatus\": \"opt-in-not-required\",\n      \"RegionName\": \"us-east-1\",\n      \"ZoneName\": \"us-east-1b\",\n      \"ZoneId\": \"use1-az1\",\n      \"ZoneType\": \"availability-zone\",\n      \"NetworkBorderGroup\": \"us-east-1\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc7",
    domain: "cloud-concepts",
    text: "Which TWO of the following are pillars of the AWS Well-Architected Framework?",
    options: [
      { id: "a", text: "Operational Excellence" },
      { id: "b", text: "Cost Optimization" },
      { id: "c", text: "Marketing Efficiency" },
      { id: "d", text: "Vendor Lock-in Avoidance" },
      { id: "e", text: "Customer Obsession" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "The six pillars are Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, and Sustainability.",
    optionRationale: {
      a: "Operational Excellence is one of the six official Well-Architected Framework pillars.",
      b: "Cost Optimization is one of the six official Well-Architected Framework pillars.",
      c: "Marketing Efficiency is not a real Well-Architected pillar.",
      d: "Vendor Lock-in Avoidance is not a named Well-Architected pillar.",
      e: "Customer Obsession is an Amazon leadership principle, not a Well-Architected Framework pillar.",
    },
    referenceUrl: "https://aws.amazon.com/well-architected/",
    referenceLabel: "AWS Well-Architected Framework",
    diagram:
      "flowchart TD\n    WAF[AWS Well-Architected Framework] --> P1[Operational Excellence]\n    WAF --> P2[Security]\n    WAF --> P3[Reliability]\n    WAF --> P4[Performance Efficiency]\n    WAF --> P5[Cost Optimization]\n    WAF --> P6[Sustainability]",
  },
  {
    id: "cc8",
    domain: "cloud-concepts",
    text: "A company is deciding between building its own data center and using AWS. Which factor is a common advantage of AWS over on-premises infrastructure?",
    options: [
      { id: "a", text: "No need to ever patch software" },
      { id: "b", text: "Ability to stop guessing capacity and scale based on actual demand" },
      { id: "c", text: "Guaranteed lower cost regardless of usage" },
      { id: "d", text: "Unlimited free data transfer" },
    ],
    correctOptionIds: ["b"],
    explanation: "Cloud computing removes the need to guess infrastructure capacity in advance; you can scale up or down as actual demand changes.",
    optionRationale: {
      a: "Patching responsibilities still exist under the shared responsibility model; AWS doesn't eliminate all patching.",
      b: "Cloud removes the need to guess capacity ahead of time — you scale to match actual, observed demand.",
      c: "Cost isn't guaranteed to be lower regardless of usage; it depends heavily on how resources are used and managed.",
      d: "Data transfer is a billed dimension in AWS pricing, not unlimited and free.",
    },
    referenceUrl: "https://aws.amazon.com/economics/",
    referenceLabel: "AWS Cloud Economics",
    diagram:
      "flowchart LR\n    Guess[Guess Capacity Upfront] --> Waste[Over- or Under-provisioned]\n    Cloud[AWS Cloud] --> Match[Scale to Match Actual Demand]",
    cliExample: {
      description: "View recent Auto Scaling activity that matches capacity to actual demand",
      command: "aws autoscaling describe-scaling-activities",
      sampleOutput: "{\n  \"Activities\": [\n    {\n      \"ActivityId\": \"9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d\",\n      \"AutoScalingGroupName\": \"web-asg\",\n      \"Description\": \"Launching a new EC2 instance: i-0abc123def456789a\",\n      \"Cause\": \"At 2026-04-11T14:02:10Z a monitor alarm cpu-high in state ALARM triggered policy scale-out changing the desired capacity from 2 to 3.\",\n      \"StartTime\": \"2026-04-11T14:02:12.000Z\",\n      \"EndTime\": \"2026-04-11T14:02:55.000Z\",\n      \"StatusCode\": \"Successful\",\n      \"Progress\": 100\n    }\n  ]\n}",
    },
  },
  {
    id: "cc9",
    domain: "cloud-concepts",
    text: "Which migration strategy (one of the '6 R's') involves moving an application to the cloud with no code changes?",
    options: [
      { id: "a", text: "Refactor" },
      { id: "b", text: "Rehost ('lift and shift')" },
      { id: "c", text: "Replatform" },
      { id: "d", text: "Retire" },
    ],
    correctOptionIds: ["b"],
    explanation: "Rehosting, or 'lift and shift', moves an application to the cloud as-is, without changing its code or architecture.",
    optionRationale: {
      a: "Refactor re-architects the application to take advantage of cloud-native features, the opposite of no changes.",
      b: "Rehost, or 'lift and shift', moves the application to the cloud as-is with no code changes.",
      c: "Replatform makes some targeted optimizations during the move, so it isn't strictly zero changes.",
      d: "Retire means decommissioning an application, not migrating it.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/enterprise-strategy/6-strategies-for-migrating-applications-to-the-cloud/",
    referenceLabel: "6 Strategies for Migrating Applications to the Cloud",
    diagram:
      "flowchart LR\n    Retire --> Retain --> Repurchase --> Rehost --> Replatform --> Refactor",
  },
  {
    id: "cc10",
    domain: "cloud-concepts",
    text: "Which migration strategy involves making minor optimizations to take advantage of cloud capabilities without changing the application's core architecture?",
    options: [
      { id: "a", text: "Rehost" },
      { id: "b", text: "Replatform ('lift and reshape')" },
      { id: "c", text: "Repurchase" },
      { id: "d", text: "Retain" },
    ],
    correctOptionIds: ["b"],
    explanation: "Replatforming makes a few targeted cloud optimizations, such as swapping a self-managed database for a managed one, without a full rearchitecture.",
    optionRationale: {
      a: "Rehost makes no changes at all, so it doesn't involve any cloud optimizations.",
      b: "Replatform, or 'lift and reshape', makes small targeted optimizations without changing the core architecture.",
      c: "Repurchase means switching to a different product entirely, not tuning the existing application.",
      d: "Retain means keeping the application where it currently runs, not migrating and optimizing it.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/enterprise-strategy/6-strategies-for-migrating-applications-to-the-cloud/",
    referenceLabel: "6 Strategies for Migrating Applications to the Cloud",
    diagram:
      "flowchart LR\n    Rehost[Rehost: No Changes] --> Replatform[Replatform: Minor Optimizations]\n    Replatform --> Refactor[Refactor: Re-architect]",
  },
  {
    id: "cc11",
    domain: "cloud-concepts",
    text: "A business decides to stop using a legacy on-premises application and instead subscribe to a SaaS alternative. Which migration strategy does this represent?",
    options: [
      { id: "a", text: "Retire" },
      { id: "b", text: "Repurchase" },
      { id: "c", text: "Rehost" },
      { id: "d", text: "Refactor" },
    ],
    correctOptionIds: ["b"],
    explanation: "Repurchasing means replacing an existing application with a different product, typically a SaaS offering.",
    optionRationale: {
      a: "Retire means shutting the application down without a direct replacement.",
      b: "Repurchase means replacing the existing application with a different product, commonly a SaaS offering.",
      c: "Rehost keeps the same application and simply moves it to the cloud unchanged.",
      d: "Refactor re-architects the existing application rather than replacing it with a different product.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/enterprise-strategy/6-strategies-for-migrating-applications-to-the-cloud/",
    referenceLabel: "6 Strategies for Migrating Applications to the Cloud",
    diagram:
      "flowchart LR\n    Legacy[Legacy On-premises App] --> SaaS[SaaS Alternative]",
  },
  {
    id: "cc12",
    domain: "cloud-concepts",
    text: "Which cloud computing benefit refers to the increased speed and ease with which IT resources can be provisioned, enabling faster experimentation?",
    options: [
      { id: "a", text: "Agility" },
      { id: "b", text: "Elasticity" },
      { id: "c", text: "Durability" },
      { id: "d", text: "Compliance" },
    ],
    correctOptionIds: ["a"],
    explanation: "Agility describes how quickly teams can provision resources, experiment, and iterate compared to traditional infrastructure.",
    optionRationale: {
      a: "Agility is exactly this: the speed and ease of provisioning resources to experiment and iterate quickly.",
      b: "Elasticity is about scaling capacity up or down with demand, not the speed of initial provisioning.",
      c: "Durability describes long-term data resilience, unrelated to provisioning speed.",
      d: "Compliance describes meeting regulatory requirements, unrelated to provisioning speed.",
    },
    referenceUrl: "https://aws.amazon.com/what-is-cloud-computing/",
    referenceLabel: "What Is Cloud Computing?",
    diagram:
      "flowchart LR\n    Idea[New Idea] --> Provision[Provision Resources in Minutes]\n    Provision --> Experiment[Experiment and Iterate Fast]",
  },
  {
    id: "cc13",
    domain: "cloud-concepts",
    text: "What is a key characteristic that differentiates fault tolerance from high availability?",
    options: [
      {
        id: "a",
        text: "Fault-tolerant systems continue operating with zero downtime even if a component fails, while highly available systems minimize but may not eliminate downtime",
      },
      { id: "b", text: "Fault tolerance only applies to storage services" },
      { id: "c", text: "High availability requires multiple AWS accounts" },
      { id: "d", text: "Fault tolerance is only achieved through manual intervention" },
    ],
    correctOptionIds: ["a"],
    explanation: "Fault tolerance masks failures entirely with no downtime, while high availability aims to minimize downtime but may involve a brief interruption.",
    optionRationale: {
      a: "This is the key distinction: fault tolerance masks a failure with zero downtime, while high availability minimizes but doesn't guarantee zero downtime.",
      b: "Fault tolerance is a design principle that applies broadly across services, not only storage.",
      c: "High availability doesn't require multiple AWS accounts; it's typically achieved with redundancy across AZs.",
      d: "Fault tolerance is normally achieved through automatic failover, not manual intervention.",
    },
    referenceUrl: "https://aws.amazon.com/well-architected/",
    referenceLabel: "Reliability Pillar — AWS Well-Architected Framework",
    diagram:
      "flowchart TD\n    Goal[Minimize Downtime] --> HA[High Availability]\n    Goal --> FT[Fault Tolerance]\n    HA --> HA1[Brief interruption possible]\n    FT --> FT1[Zero downtime on component failure]",
    cliExample: {
      description: "List load balancer target groups, used to monitor health and support high availability",
      command: "aws elbv2 describe-target-groups",
      sampleOutput: "{\n  \"TargetGroups\": [\n    {\n      \"TargetGroupArn\": \"arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/web-tg/73e2d6bc24d8a067\",\n      \"TargetGroupName\": \"web-tg\",\n      \"Protocol\": \"HTTP\",\n      \"Port\": 80,\n      \"VpcId\": \"vpc-0123456789abcdef0\",\n      \"HealthCheckProtocol\": \"HTTP\",\n      \"HealthCheckPath\": \"/health\",\n      \"HealthCheckIntervalSeconds\": 30,\n      \"HealthyThresholdCount\": 5,\n      \"UnhealthyThresholdCount\": 2,\n      \"LoadBalancerArns\": [\n        \"arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/web-alb/50dc6c495c0c9188\"\n      ],\n      \"TargetType\": \"instance\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc14",
    domain: "cloud-concepts",
    text: "Which TWO of the following are perspectives in the AWS Cloud Adoption Framework (AWS CAF)?",
    options: [
      { id: "a", text: "Governance" },
      { id: "b", text: "Platform" },
      { id: "c", text: "Advertising" },
      { id: "d", text: "Sales Enablement" },
      { id: "e", text: "Human Resources" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "The six CAF perspectives are Business, People, Governance, Platform, Security, and Operations.",
    optionRationale: {
      a: "Governance is one of the six official AWS CAF perspectives.",
      b: "Platform is one of the six official AWS CAF perspectives.",
      c: "Advertising is not one of the AWS CAF perspectives.",
      d: "Sales Enablement is not one of the AWS CAF perspectives.",
      e: "Human Resources is not a CAF perspective; the closest official perspective is People.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/overview-aws-cloud-adoption-framework/welcome.html",
    referenceLabel: "AWS Cloud Adoption Framework",
    diagram:
      "flowchart TD\n    CAF[AWS Cloud Adoption Framework] --> Business\n    CAF --> People\n    CAF --> Governance\n    CAF --> Platform\n    CAF --> Security\n    CAF --> Operations",
  },
  {
    id: "cc15",
    domain: "cloud-concepts",
    text: "A startup wants to test a new idea with minimal upfront investment. Which cloud benefit best supports this goal?",
    options: [
      { id: "a", text: "Stop spending money running and maintaining data centers" },
      { id: "b", text: "Guaranteed 100% uptime" },
      { id: "c", text: "Mandatory long-term contracts" },
      { id: "d", text: "Fixed hardware refresh cycles" },
    ],
    correctOptionIds: ["a"],
    explanation: "By not owning data centers, a startup avoids large upfront investments and can redirect resources toward its product.",
    optionRationale: {
      a: "Not owning or maintaining data centers avoids large upfront investment, letting a startup redirect funds to its product.",
      b: "AWS does not guarantee 100% uptime, and this isn't related to minimizing upfront investment.",
      c: "Mandatory long-term contracts would work against a startup's need for low upfront commitment.",
      d: "Fixed hardware refresh cycles describe an on-premises constraint, not a cloud benefit.",
    },
    referenceUrl: "https://aws.amazon.com/economics/",
    referenceLabel: "AWS Cloud Economics",
    diagram:
      "flowchart LR\n    Startup[Startup] --> Avoid[Avoid Data Center Capex]\n    Avoid --> Invest[Redirect Funds to Product]",
  },
  {
    id: "cc16",
    domain: "cloud-concepts",
    text: "What is the relationship between a Region and Availability Zones in AWS?",
    options: [
      { id: "a", text: "A Region contains multiple, isolated Availability Zones" },
      { id: "b", text: "An Availability Zone contains multiple Regions" },
      { id: "c", text: "Regions and Availability Zones are the same thing" },
      { id: "d", text: "Availability Zones exist outside of Regions" },
    ],
    correctOptionIds: ["a"],
    explanation: "Each AWS Region is a separate geographic area made up of multiple isolated Availability Zones.",
    optionRationale: {
      a: "Correct: an AWS Region is a geographic area made up of multiple, isolated Availability Zones.",
      b: "This reverses the actual relationship — a Region contains AZs, not the other way around.",
      c: "Regions and AZs are distinct concepts: a Region is the geographic area, AZs are the isolated locations within it.",
      d: "Every Availability Zone belongs to a specific Region; none exist outside one.",
    },
    referenceUrl: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
    referenceLabel: "AWS Regions and Availability Zones",
    diagram:
      "flowchart TD\n    Region[AWS Region] --> AZ1[Availability Zone A]\n    Region --> AZ2[Availability Zone B]\n    Region --> AZ3[Availability Zone C]",
    cliExample: {
      description: "List the Availability Zones that make up a Region",
      command: "aws ec2 describe-availability-zones --region us-east-1",
      sampleOutput: "{\n  \"AvailabilityZones\": [\n    {\n      \"State\": \"available\",\n      \"OptInStatus\": \"opt-in-not-required\",\n      \"RegionName\": \"us-east-1\",\n      \"ZoneName\": \"us-east-1a\",\n      \"ZoneId\": \"use1-az6\",\n      \"ZoneType\": \"availability-zone\",\n      \"NetworkBorderGroup\": \"us-east-1\"\n    },\n    {\n      \"State\": \"available\",\n      \"OptInStatus\": \"opt-in-not-required\",\n      \"RegionName\": \"us-east-1\",\n      \"ZoneName\": \"us-east-1b\",\n      \"ZoneId\": \"use1-az1\",\n      \"ZoneType\": \"availability-zone\",\n      \"NetworkBorderGroup\": \"us-east-1\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc17",
    domain: "cloud-concepts",
    text: "Which of the following best describes an AWS edge location?",
    options: [
      { id: "a", text: "A primary data center used exclusively for compute workloads" },
      { id: "b", text: "A site used by Amazon CloudFront and other services to cache content closer to end users" },
      { id: "c", text: "A backup Region used only for disaster recovery" },
      { id: "d", text: "A physical office where AWS support staff work" },
    ],
    correctOptionIds: ["b"],
    explanation: "Edge locations cache content near end users to reduce latency for services like Amazon CloudFront.",
    optionRationale: {
      a: "Edge locations aren't primary compute data centers; they're smaller sites focused on caching content.",
      b: "Edge locations are used by services like Amazon CloudFront to cache content closer to end users, reducing latency.",
      c: "Disaster recovery uses full AWS Regions, not edge locations.",
      d: "Edge locations are technical infrastructure sites, not support offices.",
    },
    referenceUrl: "https://aws.amazon.com/cloudfront/",
    referenceLabel: "Amazon CloudFront",
    consoleUrl: "https://console.aws.amazon.com/cloudfront/v4/home#/distributions",
    consoleLabel: "CloudFront > Distributions",
    diagram:
      "flowchart LR\n    User[End User Request] --> Edge[Edge Location Cache]\n    Edge -->|Cache Hit| User\n    Edge -->|Cache Miss| Origin[Origin Server]",
    cliExample: {
      description: "List CloudFront distributions that use edge locations to cache content",
      command: "aws cloudfront list-distributions",
      sampleOutput: "{\n  \"DistributionList\": {\n    \"Marker\": \"\",\n    \"MaxItems\": 100,\n    \"IsTruncated\": false,\n    \"Quantity\": 1,\n    \"Items\": [\n      {\n        \"Id\": \"E1A2B3C4D5E6F7\",\n        \"ARN\": \"arn:aws:cloudfront::123456789012:distribution/E1A2B3C4D5E6F7\",\n        \"Status\": \"Deployed\",\n        \"LastModifiedTime\": \"2026-02-18T08:41:12.345Z\",\n        \"DomainName\": \"d111111abcdef8.cloudfront.net\",\n        \"Enabled\": true,\n        \"PriceClass\": \"PriceClass_All\",\n        \"HttpVersion\": \"http2and3\"\n      }\n    ]\n  }\n}",
    },
  },
  {
    id: "cc18",
    domain: "cloud-concepts",
    text: "A company currently runs all its workloads on-premises but occasionally bursts to the cloud during peak demand. Which deployment model does this describe?",
    options: [
      { id: "a", text: "All-in cloud" },
      { id: "b", text: "On-premises only" },
      { id: "c", text: "Hybrid" },
      { id: "d", text: "Multi-cloud" },
    ],
    correctOptionIds: ["c"],
    explanation: "A hybrid deployment combines on-premises infrastructure with cloud resources, often used for cloud bursting.",
    optionRationale: {
      a: "All-in cloud means running entirely in the cloud, which contradicts the on-premises baseline described here.",
      b: "On-premises only would mean never using the cloud, which contradicts the described cloud bursting.",
      c: "Combining an on-premises baseline with cloud bursting for peak demand is the definition of a hybrid deployment.",
      d: "Multi-cloud means using multiple cloud providers, not combining on-premises with a single cloud provider.",
    },
    referenceUrl: "https://aws.amazon.com/hybrid/",
    referenceLabel: "Hybrid Cloud with AWS",
    diagram:
      "flowchart LR\n    OnPrem[On-premises Data Center] <--> Link[Network Connection]\n    Link <--> Cloud[AWS Cloud]",
    cliExample: {
      description: "List VPN connections linking on-premises infrastructure to AWS for a hybrid deployment",
      command: "aws ec2 describe-vpn-connections",
      sampleOutput: "{\n  \"VpnConnections\": [\n    {\n      \"VpnConnectionId\": \"vpn-0123456789abcdef0\",\n      \"State\": \"available\",\n      \"Type\": \"ipsec.1\",\n      \"CustomerGatewayId\": \"cgw-0123456789abcdef0\",\n      \"VpnGatewayId\": \"vgw-0123456789abcdef0\",\n      \"Category\": \"VPN\",\n      \"VgwTelemetry\": [\n        {\n          \"OutsideIpAddress\": \"203.0.113.10\",\n          \"Status\": \"UP\",\n          \"LastStatusChange\": \"2026-05-03T02:17:44.000Z\",\n          \"AcceptedRouteCount\": 3\n        },\n        {\n          \"OutsideIpAddress\": \"203.0.113.11\",\n          \"Status\": \"UP\",\n          \"LastStatusChange\": \"2026-05-03T02:17:49.000Z\",\n          \"AcceptedRouteCount\": 3\n        }\n      ]\n    }\n  ]\n}",
    },
  },
  {
    id: "cc19",
    domain: "cloud-concepts",
    text: "Which TWO of the following are benefits commonly associated with cloud computing over traditional on-premises IT?",
    options: [
      { id: "a", text: "Trade capital expense for variable expense" },
      { id: "b", text: "Benefit from massive economies of scale" },
      { id: "c", text: "Guaranteed zero cost" },
      { id: "d", text: "Elimination of the shared responsibility model" },
      { id: "e", text: "No need for any security controls" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Cloud computing's core benefits include trading capex for variable opex and benefiting from AWS's economies of scale.",
    optionRationale: {
      a: "Trading capital expense for variable expense is one of the core cloud computing benefits.",
      b: "Benefiting from AWS's massive economies of scale is one of the core cloud computing benefits.",
      c: "Cloud computing is not free; usage is billed based on consumption.",
      d: "The shared responsibility model still applies in the cloud — it isn't eliminated.",
      e: "Security controls are still required; the customer retains responsibility for security 'in' the cloud.",
    },
    referenceUrl: "https://aws.amazon.com/economics/",
    referenceLabel: "AWS Cloud Economics",
    diagram:
      "flowchart LR\n    Cloud[Cloud Computing Benefits] --> CapexOpex[Capex to Variable Opex]\n    Cloud --> Scale[Economies of Scale]",
  },
  {
    id: "cc20",
    domain: "cloud-concepts",
    text: "Which statement best describes 'economies of scale' as an AWS Cloud benefit?",
    options: [
      { id: "a", text: "As AWS grows, higher volumes lead to lower costs, which AWS can pass on as lower pricing to customers" },
      { id: "b", text: "Each customer negotiates a unique lower price directly" },
      { id: "c", text: "Costs decrease only for customers using a single AWS service" },
      { id: "d", text: "Economies of scale apply only to compute services" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS's massive scale of operation drives down per-unit costs, savings that are passed on to customers through lower prices.",
    optionRationale: {
      a: "This is the definition: AWS's growing scale lowers its costs, and those savings are passed on as lower prices for everyone.",
      b: "Economies of scale come from AWS's aggregate volume, not individual customer negotiations.",
      c: "The benefit isn't limited to single-service customers; it comes from AWS's overall infrastructure scale.",
      d: "Economies of scale apply broadly across AWS services, not only compute.",
    },
    referenceUrl: "https://aws.amazon.com/economics/",
    referenceLabel: "AWS Cloud Economics",
    diagram:
      "flowchart LR\n    Scale[AWS Growing Scale] --> LowerCosts[Lower AWS Costs]\n    LowerCosts --> LowerPrices[Lower Prices for Customers]",
  },
  {
    id: "cc21",
    domain: "cloud-concepts",
    text: "What is the main purpose of the AWS Well-Architected Framework?",
    options: [
      { id: "a", text: "To provide a consistent approach for evaluating and improving cloud architectures against best practices" },
      { id: "b", text: "To replace the AWS Shared Responsibility Model" },
      { id: "c", text: "To calculate exact monthly billing" },
      { id: "d", text: "To manage IAM permissions automatically" },
    ],
    correctOptionIds: ["a"],
    explanation: "The Well-Architected Framework gives a consistent set of questions and best practices for reviewing cloud architectures.",
    optionRationale: {
      a: "The framework provides a consistent set of questions and best practices for reviewing and improving architectures.",
      b: "The Well-Architected Framework complements, not replaces, the Shared Responsibility Model.",
      c: "Exact billing calculations come from tools like the Pricing Calculator and Cost Explorer, not Well-Architected.",
      d: "Well-Architected is a review framework, not an IAM automation tool.",
    },
    referenceUrl: "https://aws.amazon.com/well-architected/",
    referenceLabel: "AWS Well-Architected Framework",
    consoleUrl: "https://console.aws.amazon.com/wellarchitected/home",
    consoleLabel: "AWS Well-Architected Tool",
    diagram:
      "flowchart LR\n    Review[Well-Architected Review] --> BestPractices[Best Practices Checklist]\n    BestPractices --> Improve[Improve Architecture]",
    cliExample: {
      description: "List workloads registered in the AWS Well-Architected Tool",
      command: "aws wellarchitected list-workloads",
      sampleOutput: "{\n  \"WorkloadSummaries\": [\n    {\n      \"WorkloadId\": \"5f2c1a9b8e7d6c5b4a3f2e1d0c9b8a7f\",\n      \"WorkloadArn\": \"arn:aws:wellarchitected:us-east-1:123456789012:workload/5f2c1a9b8e7d6c5b4a3f2e1d0c9b8a7f\",\n      \"WorkloadName\": \"retail-web-platform\",\n      \"Owner\": \"platform-team@example.com\",\n      \"UpdatedAt\": \"2026-06-09T11:30:00.000Z\",\n      \"Lenses\": [\n        \"wellarchitected\"\n      ],\n      \"RiskCounts\": {\n        \"UNANSWERED\": 12,\n        \"HIGH\": 3,\n        \"MEDIUM\": 5,\n        \"NONE\": 26,\n        \"NOT_APPLICABLE\": 0\n      },\n      \"ImprovementStatus\": \"IN_PROGRESS\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc22",
    domain: "cloud-concepts",
    text: "A company's web application runs on a single EC2 instance in one Availability Zone. During a recent AZ disruption the site was offline for several hours. Which Well-Architected Framework pillar most directly addresses designing the workload to recover from this type of failure?",
    options: [
      { id: "a", text: "Reliability" },
      { id: "b", text: "Performance Efficiency" },
      { id: "c", text: "Cost Optimization" },
      { id: "d", text: "Operational Excellence" },
    ],
    correctOptionIds: ["a"],
    explanation: "The Reliability pillar covers the ability of a workload to perform its intended function correctly and consistently, including recovering from infrastructure or service disruptions by using multiple Availability Zones and automated recovery.",
    optionRationale: {
      a: "Reliability focuses on recovering from failures, scaling to meet demand, and mitigating disruptions such as an AZ outage through redundancy and automatic recovery.",
      b: "Performance Efficiency is about using computing resources efficiently to meet requirements as demand and technology change, not surviving failures.",
      c: "Cost Optimization is about avoiding unnecessary spending, which does not address availability during an outage.",
      d: "Operational Excellence covers running and monitoring systems and improving processes and procedures, not the redundancy design itself.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html",
    referenceLabel: "Reliability Pillar — AWS Well-Architected Framework",
    diagram:
      "flowchart LR\n    Single[Single AZ Instance] -->|AZ outage| Down[Site Offline]\n    Multi[Instances in Multiple AZs] -->|AZ outage| Up[Traffic Shifts to Healthy AZ]\n    Multi --> Pillar[Reliability Pillar]",
    cliExample: {
      description: "List lens reviews for a workload in the AWS Well-Architected Tool, which include the Reliability pillar",
      command: "aws wellarchitected list-lens-reviews --workload-id 0123456789abcdef0123456789abcdef",
      sampleOutput: "{\n  \"WorkloadId\": \"5f2c1a9b8e7d6c5b4a3f2e1d0c9b8a7f\",\n  \"LensReviewSummaries\": [\n    {\n      \"LensAlias\": \"wellarchitected\",\n      \"LensArn\": \"arn:aws:wellarchitected::aws:lens/wellarchitected\",\n      \"LensVersion\": \"2024-06-27\",\n      \"LensName\": \"AWS Well-Architected Framework\",\n      \"LensStatus\": \"CURRENT\",\n      \"UpdatedAt\": \"2026-06-09T11:30:00.000Z\",\n      \"RiskCounts\": {\n        \"UNANSWERED\": 12,\n        \"HIGH\": 3,\n        \"MEDIUM\": 5,\n        \"NONE\": 26,\n        \"NOT_APPLICABLE\": 0\n      }\n    }\n  ]\n}",
    },
  },
  {
    id: "cc23",
    domain: "cloud-concepts",
    text: "An organization wants to reduce the environmental impact of its cloud workloads by right-sizing resources and choosing Regions with lower carbon intensity. Which Well-Architected Framework pillar addresses this goal?",
    options: [
      { id: "a", text: "Security" },
      { id: "b", text: "Sustainability" },
      { id: "c", text: "Operational Excellence" },
      { id: "d", text: "Performance Efficiency" },
    ],
    correctOptionIds: ["b"],
    explanation: "The Sustainability pillar, added in 2021, focuses on minimizing the environmental impact of running cloud workloads through efficient resource usage, Region selection, and reducing waste.",
    optionRationale: {
      a: "Security covers protecting data, systems, and assets through identity management, detection, and encryption.",
      b: "Sustainability addresses environmental impact, including right-sizing, maximizing utilization, and selecting Regions near renewable energy sources.",
      c: "Operational Excellence is about running workloads effectively and continually improving procedures, not environmental impact.",
      d: "Performance Efficiency focuses on selecting the right resource types to meet performance requirements; while related, it is not the pillar dedicated to environmental impact.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/sustainability-pillar.html",
    referenceLabel: "Sustainability Pillar — AWS Well-Architected Framework",
    diagram:
      "flowchart LR\n    Goal[Reduce Environmental Impact] --> RightSize[Right-size Resources]\n    Goal --> Region[Choose Low-carbon Regions]\n    Goal --> Utilize[Maximize Utilization]\n    RightSize --> Pillar[Sustainability Pillar]\n    Region --> Pillar\n    Utilize --> Pillar",
    cliExample: {
      description: "Retrieve EC2 right-sizing recommendations from AWS Compute Optimizer to reduce over-provisioned resources",
      command: "aws compute-optimizer get-ec2-instance-recommendations",
      sampleOutput: "{\n  \"instanceRecommendations\": [\n    {\n      \"instanceArn\": \"arn:aws:ec2:us-east-1:123456789012:instance/i-0abc123def456789a\",\n      \"accountId\": \"123456789012\",\n      \"instanceName\": \"batch-worker-1\",\n      \"currentInstanceType\": \"m5.2xlarge\",\n      \"finding\": \"OVER_PROVISIONED\",\n      \"findingReasonCodes\": [\n        \"CPUOverprovisioned\",\n        \"MemoryOverprovisioned\"\n      ],\n      \"recommendationOptions\": [\n        {\n          \"instanceType\": \"m5.large\",\n          \"projectedUtilizationMetrics\": [\n            {\n              \"name\": \"CPU\",\n              \"statistic\": \"MAXIMUM\",\n              \"value\": 38.5\n            }\n          ],\n          \"performanceRisk\": 1.0,\n          \"rank\": 1,\n          \"savingsOpportunity\": {\n            \"savingsOpportunityPercentage\": 75.0,\n            \"estimatedMonthlySavings\": {\n              \"currency\": \"USD\",\n              \"value\": 210.24\n            }\n          }\n        }\n      ],\n      \"lastRefreshTimestamp\": \"2026-07-01T00:12:44.000Z\",\n      \"currentPerformanceRisk\": \"VeryLow\"\n    }\n  ],\n  \"errors\": []\n}",
    },
  },
  {
    id: "cc24",
    domain: "cloud-concepts",
    text: "During migration discovery, a company finds that 15% of its on-premises applications are no longer used by anyone. Which migration strategy should be applied to these applications?",
    options: [
      { id: "a", text: "Retain" },
      { id: "b", text: "Rehost" },
      { id: "c", text: "Retire" },
      { id: "d", text: "Refactor" },
    ],
    correctOptionIds: ["c"],
    explanation: "Retire means decommissioning applications that are no longer needed, which reduces the migration scope and eliminates their ongoing cost.",
    optionRationale: {
      a: "Retain means keeping an application on-premises for now, typically because it is not ready to migrate or has dependencies; unused apps should not be kept.",
      b: "Rehost would move the unused applications to the cloud as-is, wasting effort and money on something nobody uses.",
      c: "Retire is the correct choice: applications that are no longer useful are decommissioned rather than migrated.",
      d: "Refactor re-architects an application for cloud-native benefits, which makes no sense for an application with no users.",
    },
    referenceUrl: "https://docs.aws.amazon.com/prescriptive-guidance/latest/migration-retiring-applications/",
    referenceLabel: "AWS Prescriptive Guidance — Retiring Applications",
    diagram:
      "flowchart TD\n    Discover[Discovery: App Inventory] --> Used{Still in use?}\n    Used -->|Yes| Migrate[Choose Migration Strategy]\n    Used -->|No| Retire[Retire: Decommission]\n    Retire --> Savings[Reduced Scope and Cost]",
    cliExample: {
      description: "List servers discovered by AWS Application Discovery Service to help identify unused applications",
      command: "aws discovery list-configurations --configuration-type SERVER",
      sampleOutput: "{\n  \"configurations\": [\n    {\n      \"server.configurationId\": \"d-server-0123456789abcdef0\",\n      \"server.hostName\": \"legacy-app-01.corp.example.com\",\n      \"server.osName\": \"Windows Server 2012 R2\",\n      \"server.type\": \"VMWARE\",\n      \"server.agentId\": \"o-0123456789abcdef0\",\n      \"server.timeOfCreation\": \"2026-01-20 03:14:07.0\"\n    },\n    {\n      \"server.configurationId\": \"d-server-0fedcba9876543210\",\n      \"server.hostName\": \"legacy-app-02.corp.example.com\",\n      \"server.osName\": \"Linux - Red Hat Enterprise Linux 7.9\",\n      \"server.type\": \"VMWARE\",\n      \"server.agentId\": \"o-0fedcba9876543210\",\n      \"server.timeOfCreation\": \"2026-01-20 03:14:09.0\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc25",
    domain: "cloud-concepts",
    text: "A financial company must keep certain workloads on-premises for data residency reasons but wants to use native AWS services and APIs on that hardware. Which AWS offering meets this requirement?",
    options: [
      { id: "a", text: "AWS Local Zones" },
      { id: "b", text: "AWS Wavelength" },
      { id: "c", text: "AWS Outposts" },
      { id: "d", text: "Amazon CloudFront" },
    ],
    correctOptionIds: ["c"],
    explanation: "AWS Outposts is a fully managed rack or server that AWS installs in the customer's own data center, extending AWS infrastructure, services, and APIs to on-premises locations.",
    optionRationale: {
      a: "AWS Local Zones are AWS-owned facilities placed in metropolitan areas to bring low-latency compute closer to users; they are not installed in the customer's data center.",
      b: "AWS Wavelength embeds AWS compute and storage inside telecommunications providers' 5G networks for ultra-low-latency mobile applications.",
      c: "AWS Outposts delivers AWS hardware and services into the customer's own facility, satisfying data residency while using the same AWS APIs and tools.",
      d: "Amazon CloudFront is a content delivery network that caches content at edge locations; it does not host workloads on-premises.",
    },
    referenceUrl: "https://aws.amazon.com/outposts/",
    referenceLabel: "AWS Outposts",
    consoleUrl: "https://console.aws.amazon.com/outposts/home",
    consoleLabel: "AWS Outposts",
    diagram:
      "flowchart LR\n    Region[AWS Region] --> Outposts[AWS Outposts in Customer Data Center]\n    Region --> LZ[Local Zone in Metro Area]\n    Region --> WL[Wavelength Zone in 5G Network]\n    Outposts --> Residency[Data Stays On-premises]",
    cliExample: {
      description: "List AWS Outposts installed for the account",
      command: "aws outposts list-outposts",
      sampleOutput: "{\n  \"Outposts\": [\n    {\n      \"OutpostId\": \"op-0123456789abcdef0\",\n      \"OwnerId\": \"123456789012\",\n      \"OutpostArn\": \"arn:aws:outposts:us-east-1:123456789012:outpost/op-0123456789abcdef0\",\n      \"SiteId\": \"os-0123456789abcdef0\",\n      \"Name\": \"nyc-dc1-rack\",\n      \"LifeCycleStatus\": \"ACTIVE\",\n      \"AvailabilityZone\": \"us-east-1a\",\n      \"AvailabilityZoneId\": \"use1-az6\",\n      \"SiteArn\": \"arn:aws:outposts:us-east-1:123456789012:site/os-0123456789abcdef0\",\n      \"SupportedHardwareType\": \"RACK\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc26",
    domain: "cloud-concepts",
    text: "A new administrator notices that some AWS services in the Management Console do not require selecting a Region. Which of the following is a global service that operates across all Regions?",
    options: [
      { id: "a", text: "Amazon EC2" },
      { id: "b", text: "AWS Identity and Access Management (IAM)" },
      { id: "c", text: "Amazon RDS" },
      { id: "d", text: "AWS Lambda" },
    ],
    correctOptionIds: ["b"],
    explanation: "IAM is a global service: users, groups, roles, and policies are defined once and apply across every Region in the account. Other global services include Route 53, CloudFront, and AWS Organizations.",
    optionRationale: {
      a: "Amazon EC2 is Regional; instances are launched into a specific Region and AZ.",
      b: "IAM is global — identities and policies are not tied to any Region and are visible everywhere in the account.",
      c: "Amazon RDS is Regional; database instances live in a chosen Region's subnets.",
      d: "AWS Lambda is Regional; functions are deployed to and invoked in a specific Region.",
    },
    referenceUrl: "https://docs.aws.amazon.com/global-infrastructure/latest/regions/aws-regions.html",
    referenceLabel: "AWS Regions and Global Services",
    consoleUrl: "https://console.aws.amazon.com/iam/home#/users",
    consoleLabel: "IAM > Users",
    diagram:
      "flowchart TD\n    Account[AWS Account] --> Global[Global Services: IAM, Route 53, CloudFront]\n    Account --> R1[us-east-1: EC2, RDS, Lambda]\n    Account --> R2[eu-west-1: EC2, RDS, Lambda]\n    Global -.applies to.-> R1\n    Global -.applies to.-> R2",
    cliExample: {
      description: "List IAM users; no Region flag is needed because IAM is a global service",
      command: "aws iam list-users",
      sampleOutput: "{\n  \"Users\": [\n    {\n      \"Path\": \"/\",\n      \"UserName\": \"alice\",\n      \"UserId\": \"AIDA2EXAMPLE1234567890\",\n      \"Arn\": \"arn:aws:iam::123456789012:user/alice\",\n      \"CreateDate\": \"2026-01-15T08:22:10+00:00\",\n      \"PasswordLastUsed\": \"2026-09-16T07:45:31+00:00\"\n    },\n    {\n      \"Path\": \"/\",\n      \"UserName\": \"ci-deployer\",\n      \"UserId\": \"AIDA2EXAMPLE0987654321\",\n      \"Arn\": \"arn:aws:iam::123456789012:user/ci-deployer\",\n      \"CreateDate\": \"2026-02-03T12:00:00+00:00\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc27",
    domain: "cloud-concepts",
    text: "A company wants a disaster recovery strategy in which a minimal version of its core environment (such as a replicated database) is always running in a second Region, with application servers only started when a disaster occurs. Which DR strategy does this describe?",
    options: [
      { id: "a", text: "Backup and restore" },
      { id: "b", text: "Pilot light" },
      { id: "c", text: "Warm standby" },
      { id: "d", text: "Multi-site active/active" },
    ],
    correctOptionIds: ["b"],
    explanation: "Pilot light keeps core components such as data replication running in the recovery Region while other resources are provisioned only during failover, giving faster recovery than backup and restore at lower cost than warm standby.",
    optionRationale: {
      a: "Backup and restore stores backups in the recovery Region but has nothing running there; everything must be restored, giving the slowest recovery and lowest cost.",
      b: "Pilot light keeps the essential 'core' (typically data) live and scaled-down, and only starts the remaining infrastructure when a disaster occurs.",
      c: "Warm standby runs a scaled-down but fully functional copy of the entire environment that can immediately handle reduced traffic.",
      d: "Multi-site active/active runs full production capacity in multiple Regions simultaneously, giving near-zero recovery time at the highest cost.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html",
    referenceLabel: "Disaster Recovery Options in the Cloud",
    diagram:
      "flowchart LR\n    BR[Backup and Restore] --> PL[Pilot Light]\n    PL --> WS[Warm Standby]\n    WS --> MS[Multi-site Active/Active]\n    BR -.Lower cost, slower recovery.-> MS\n    PL --> Core[Core data replicated, app servers off until failover]",
    cliExample: {
      description: "Create a cross-Region read replica so core data is always replicated for a pilot light strategy",
      command: "aws rds create-db-instance-read-replica --db-instance-identifier dr-replica --source-db-instance-identifier arn:aws:rds:us-east-1:123456789012:db:prod-db --region us-west-2",
      sampleOutput: "{\n  \"DBInstance\": {\n    \"DBInstanceIdentifier\": \"dr-replica\",\n    \"DBInstanceClass\": \"db.r6g.large\",\n    \"Engine\": \"mysql\",\n    \"DBInstanceStatus\": \"creating\",\n    \"DBInstanceArn\": \"arn:aws:rds:us-west-2:123456789012:db:dr-replica\",\n    \"ReadReplicaSourceDBInstanceIdentifier\": \"arn:aws:rds:us-east-1:123456789012:db:prod-db\",\n    \"AvailabilityZone\": \"us-west-2a\",\n    \"MultiAZ\": false,\n    \"EngineVersion\": \"8.0.36\",\n    \"StorageEncrypted\": true,\n    \"KmsKeyId\": \"arn:aws:kms:us-west-2:123456789012:key/1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d\",\n    \"StorageType\": \"gp3\",\n    \"AllocatedStorage\": 100\n  }\n}",
    },
  },
  {
    id: "cc28",
    domain: "cloud-concepts",
    text: "A development team deploys code to AWS Elastic Beanstalk, which automatically handles capacity provisioning, load balancing, and patching of the underlying platform. Which cloud service model does this best represent?",
    options: [
      { id: "a", text: "Infrastructure as a Service (IaaS)" },
      { id: "b", text: "Platform as a Service (PaaS)" },
      { id: "c", text: "Software as a Service (SaaS)" },
      { id: "d", text: "On-premises hosting" },
    ],
    correctOptionIds: ["b"],
    explanation: "PaaS removes the need to manage the underlying infrastructure so teams can focus on deploying and managing applications; Elastic Beanstalk is a classic PaaS example.",
    optionRationale: {
      a: "IaaS provides raw building blocks such as virtual machines, storage, and networking (for example, Amazon EC2) that the customer configures and manages.",
      b: "PaaS manages the hardware, operating system, and runtime platform so developers only deploy code, which is exactly what Elastic Beanstalk provides.",
      c: "SaaS delivers a complete end-user application managed by the provider (for example, a web-based email service); you do not deploy your own code to it.",
      d: "On-premises hosting means the company owns and operates the hardware itself, the opposite of a managed cloud platform.",
    },
    referenceUrl: "https://aws.amazon.com/types-of-cloud-computing/",
    referenceLabel: "Types of Cloud Computing",
    consoleUrl: "https://console.aws.amazon.com/elasticbeanstalk/home#/applications",
    consoleLabel: "Elastic Beanstalk > Applications",
    diagram:
      "flowchart LR\n    IaaS[IaaS: EC2, EBS, VPC] --> PaaS[PaaS: Elastic Beanstalk]\n    PaaS --> SaaS[SaaS: Complete Application]\n    IaaS -.Customer manages more.-> SaaS",
    cliExample: {
      description: "Create an Elastic Beanstalk application, a PaaS offering that manages the underlying platform",
      command: "aws elasticbeanstalk create-application --application-name my-web-app",
      sampleOutput: "{\n  \"Application\": {\n    \"ApplicationArn\": \"arn:aws:elasticbeanstalk:us-east-1:123456789012:application/my-web-app\",\n    \"ApplicationName\": \"my-web-app\",\n    \"DateCreated\": \"2026-08-12T10:05:22.113Z\",\n    \"DateUpdated\": \"2026-08-12T10:05:22.113Z\",\n    \"ConfigurationTemplates\": [],\n    \"ResourceLifecycleConfig\": {\n      \"VersionLifecycleConfig\": {\n        \"MaxCountRule\": {\n          \"Enabled\": false,\n          \"MaxCount\": 200,\n          \"DeleteSourceFromS3\": false\n        },\n        \"MaxAgeRule\": {\n          \"Enabled\": false,\n          \"MaxAgeInDays\": 180,\n          \"DeleteSourceFromS3\": false\n        }\n      }\n    }\n  }\n}",
    },
  },
  {
    id: "cc29",
    domain: "cloud-concepts",
    text: "A company is planning a large data center migration to AWS. It wants to build a business case that estimates projected cloud costs, and then perform automated lift-and-shift of its servers. Which TWO AWS services should it use?",
    options: [
      { id: "a", text: "AWS Migration Evaluator" },
      { id: "b", text: "AWS Application Migration Service" },
      { id: "c", text: "Amazon Inspector" },
      { id: "d", text: "AWS Trusted Advisor" },
      { id: "e", text: "Amazon QuickSight" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Migration Evaluator (formerly TSO Logic) builds a data-driven business case with projected AWS costs, while Application Migration Service (AWS MGN) automates the lift-and-shift rehosting of physical, virtual, and cloud servers.",
    optionRationale: {
      a: "Migration Evaluator collects on-premises usage data and produces a business case and cost projection for moving to AWS.",
      b: "Application Migration Service (AWS MGN) replicates source servers and converts them to run natively on AWS for automated rehosting.",
      c: "Amazon Inspector is a vulnerability management service that scans EC2 instances and container images for software vulnerabilities.",
      d: "AWS Trusted Advisor provides best-practice recommendations for existing AWS resources, not migration planning or execution.",
      e: "Amazon QuickSight is a business intelligence and dashboarding service, not a migration tool.",
    },
    referenceUrl: "https://aws.amazon.com/application-migration-service/",
    referenceLabel: "AWS Application Migration Service",
    consoleUrl: "https://console.aws.amazon.com/mgn/home#/sourceServers",
    consoleLabel: "Application Migration Service > Source servers",
    diagram:
      "flowchart LR\n    Assess[Assess: Migration Evaluator Business Case] --> Mobilize[Mobilize: Plan Migration]\n    Mobilize --> Migrate[Migrate: Application Migration Service Lift-and-Shift]\n    Migrate --> AWS[Servers Running on AWS]",
    cliExample: {
      description: "List source servers registered with AWS Application Migration Service for rehosting",
      command: "aws mgn describe-source-servers",
      sampleOutput: "{\n  \"items\": [\n    {\n      \"sourceServerID\": \"s-0123456789abcdef0\",\n      \"arn\": \"arn:aws:mgn:us-east-1:123456789012:source-server/s-0123456789abcdef0\",\n      \"isArchived\": false,\n      \"dataReplicationInfo\": {\n        \"dataReplicationState\": \"CONTINUOUS\",\n        \"lagDuration\": \"PT0S\",\n        \"replicatedDisks\": [\n          {\n            \"deviceName\": \"/dev/sda1\",\n            \"totalStorageBytes\": 107374182400,\n            \"replicatedStorageBytes\": 107374182400,\n            \"backloggedStorageBytes\": 0\n          }\n        ]\n      },\n      \"lifeCycle\": {\n        \"state\": \"READY_FOR_TEST\",\n        \"addedToServiceDateTime\": \"2026-05-20T09:12:30.000Z\"\n      },\n      \"sourceProperties\": {\n        \"identificationHints\": {\n          \"hostname\": \"erp-app-01\"\n        },\n        \"os\": {\n          \"fullString\": \"Ubuntu 22.04.4 LTS\"\n        },\n        \"cpus\": [\n          {\n            \"cores\": 4,\n            \"modelName\": \"Intel(R) Xeon(R) CPU E5-2686 v4\"\n          }\n        ],\n        \"ramBytes\": 17179869184\n      },\n      \"replicationType\": \"AGENT_BASED\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc30",
    domain: "cloud-concepts",
    text: "A research institute needs to move 400 TB of archived data to Amazon S3 from a remote site with an unreliable, low-bandwidth internet connection. Which AWS service is the MOST appropriate for this one-time migration?",
    options: [
      { id: "a", text: "AWS Direct Connect" },
      { id: "b", text: "AWS Snowball Edge" },
      { id: "c", text: "AWS DataSync over the internet" },
      { id: "d", text: "Amazon S3 Transfer Acceleration" },
    ],
    correctOptionIds: ["b"],
    explanation: "The AWS Snow Family provides physical devices for offline data transfer; Snowball Edge devices are shipped to the customer, loaded locally, and returned to AWS, avoiding the need for network bandwidth entirely.",
    optionRationale: {
      a: "AWS Direct Connect is a dedicated private network link that takes weeks to provision and is meant for ongoing hybrid connectivity, not a one-time transfer from a remote site.",
      b: "Snowball Edge is a rugged physical appliance (tens of TB per device) designed exactly for petabyte-scale offline migrations where the network is a bottleneck.",
      c: "AWS DataSync accelerates online transfers but still depends on the available internet bandwidth, which is unreliable and slow here.",
      d: "S3 Transfer Acceleration speeds up uploads through CloudFront edge locations but still requires a usable internet connection for hundreds of terabytes.",
    },
    referenceUrl: "https://aws.amazon.com/snowball/",
    referenceLabel: "AWS Snowball",
    consoleUrl: "https://console.aws.amazon.com/snowfamily/home#/jobs",
    consoleLabel: "AWS Snow Family > Jobs",
    diagram:
      "flowchart LR\n    AWS[AWS ships Snowball Edge] --> Site[Remote Site loads 400 TB]\n    Site --> Return[Device shipped back to AWS]\n    Return --> S3[Data imported into Amazon S3]",
    cliExample: {
      description: "List Snow Family jobs, such as a Snowball Edge import job",
      command: "aws snowball list-jobs",
      sampleOutput: "{\n  \"JobListEntries\": [\n    {\n      \"JobId\": \"JID123e4567-e89b-12d3-a456-426614174000\",\n      \"JobState\": \"InProgress\",\n      \"IsMaster\": false,\n      \"JobType\": \"IMPORT\",\n      \"SnowballType\": \"EDGE_S\",\n      \"CreationDate\": \"2026-06-22T04:30:15.000Z\",\n      \"Description\": \"Archive migration batch 1\"\n    },\n    {\n      \"JobId\": \"JID987e6543-e21b-45d3-b654-426614174999\",\n      \"JobState\": \"Complete\",\n      \"IsMaster\": false,\n      \"JobType\": \"IMPORT\",\n      \"SnowballType\": \"EDGE_S\",\n      \"CreationDate\": \"2026-05-02T11:03:48.000Z\",\n      \"Description\": \"Archive migration pilot\"\n    }\n  ]\n}",
    },
  },
  {
    id: "cc31",
    domain: "cloud-concepts",
    text: "An e-commerce application's order service calls the inventory service directly. When the inventory service is slow or unavailable, orders fail. Which architectural principle should be applied, and which AWS service helps implement it?",
    options: [
      { id: "a", text: "Tight coupling using direct API calls with retries" },
      { id: "b", text: "Loose coupling using Amazon SQS as a buffer between the services" },
      { id: "c", text: "Vertical scaling by using a larger instance for the inventory service" },
      { id: "d", text: "Data encryption using AWS KMS" },
    ],
    correctOptionIds: ["b"],
    explanation: "Loose coupling means components interact through intermediaries such as queues or topics, so a failure or slowdown in one component does not cascade to others. Amazon SQS decouples producers from consumers.",
    optionRationale: {
      a: "Tight coupling is the current problem: direct dependencies mean one component's failure directly breaks the other.",
      b: "Placing an SQS queue between the services lets the order service enqueue messages and continue even when inventory is slow; inventory processes messages when ready.",
      c: "Vertical scaling may reduce slowness temporarily but does not remove the direct dependency, so an outage still breaks orders.",
      d: "Encryption with AWS KMS protects data confidentiality and has no effect on service dependencies.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html",
    referenceLabel: "Overview of Amazon Web Services",
    consoleUrl: "https://console.aws.amazon.com/sqs/v3/home#/queues",
    consoleLabel: "Amazon SQS > Queues",
    diagram:
      "flowchart LR\n    Order[Order Service] --> Queue[Amazon SQS Queue]\n    Queue --> Inventory[Inventory Service]\n    Inventory -.slow or down.-> Queue\n    Queue --> Buffer[Messages buffered until processed]",
    cliExample: {
      description: "Create an SQS queue to decouple the order and inventory services",
      command: "aws sqs create-queue --queue-name order-events",
      sampleOutput: "{\n  \"QueueUrl\": \"https://sqs.us-east-1.amazonaws.com/123456789012/order-events\"\n}",
    },
  },
  {
    id: "cc32",
    domain: "cloud-concepts",
    text: "A startup is deciding whether to build a new API on AWS Lambda and Amazon API Gateway instead of on a fleet of EC2 instances. Which TWO benefits are characteristic of a serverless architecture?",
    options: [
      { id: "a", text: "No servers to provision, patch, or manage" },
      { id: "b", text: "Automatic scaling with pay-per-use billing when code is not running" },
      { id: "c", text: "Full control over the underlying operating system and kernel" },
      { id: "d", text: "Guaranteed dedicated physical hardware for each function" },
      { id: "e", text: "Requirement to purchase Reserved Instances for cost savings" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Serverless services such as Lambda remove infrastructure management, scale automatically with demand, and charge only for the compute consumed, with no charge when the code is idle.",
    optionRationale: {
      a: "With serverless, AWS manages the servers, operating systems, and patching; developers only supply code.",
      b: "Lambda scales automatically in response to requests and bills per invocation and duration, so idle time costs nothing.",
      c: "Serverless abstracts away the OS entirely; if you need OS or kernel control, you would use EC2 instead.",
      d: "Serverless runs on shared, AWS-managed infrastructure; dedicated hardware is an EC2 Dedicated Host or Dedicated Instance feature.",
      e: "Reserved Instances apply to EC2 and RDS; Lambda has no such requirement and uses pay-per-use pricing.",
    },
    referenceUrl: "https://aws.amazon.com/serverless/",
    referenceLabel: "Serverless on AWS",
    consoleUrl: "https://console.aws.amazon.com/lambda/home#/functions",
    consoleLabel: "Lambda > Functions",
    diagram:
      "flowchart LR\n    Client[Client Request] --> APIGW[Amazon API Gateway]\n    APIGW --> Lambda[AWS Lambda Function]\n    Lambda --> Scale[Scales Automatically]\n    Lambda --> Pay[Pay Only While Running]\n    Lambda --> NoOps[No Servers to Manage]",
    cliExample: {
      description: "List Lambda functions, which run without any servers to manage",
      command: "aws lambda list-functions",
      sampleOutput: "{\n  \"Functions\": [\n    {\n      \"FunctionName\": \"orders-api\",\n      \"FunctionArn\": \"arn:aws:lambda:us-east-1:123456789012:function:orders-api\",\n      \"Runtime\": \"nodejs22.x\",\n      \"Role\": \"arn:aws:iam::123456789012:role/orders-api-role\",\n      \"Handler\": \"index.handler\",\n      \"CodeSize\": 48213,\n      \"Description\": \"Order API backend\",\n      \"Timeout\": 10,\n      \"MemorySize\": 256,\n      \"LastModified\": \"2026-08-30T15:20:11.000+0000\",\n      \"Version\": \"$LATEST\",\n      \"PackageType\": \"Zip\",\n      \"Architectures\": [\n        \"arm64\"\n      ],\n      \"EphemeralStorage\": {\n        \"Size\": 512\n      }\n    }\n  ]\n}",
    },
  },
];
