import { Question } from "../types.js";

export const cloudTechnologyAndServicesQuestions: Question[] = [
  {
    id: "tech1",
    domain: "cloud-technology-and-services",
    text: "Which AWS compute service lets you run code without provisioning or managing servers, charging you only for the compute time consumed?",
    options: [
      { id: "a", text: "Amazon EC2" },
      { id: "b", text: "AWS Lambda" },
      { id: "c", text: "Amazon Lightsail" },
      { id: "d", text: "AWS Elastic Beanstalk" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Lambda runs your code in response to events without you provisioning or managing servers, billed per use.",
    optionRationale: {
      a: "EC2 requires you to provision and manage virtual server instances yourself, not a serverless model.",
      b: "Lambda runs your code without provisioning or managing servers, billed only for compute time used.",
      c: "Lightsail hands you a pre-configured virtual private server that you still manage, not a serverless model.",
      d: "Elastic Beanstalk deploys your app onto managed infrastructure (like EC2) that still exists as servers.",
    },
    referenceUrl: "https://docs.aws.amazon.com/lambda/latest/dg/welcome.html",
    referenceLabel: "What Is AWS Lambda?",
    cliExample: { description: "List your deployed Lambda functions", command: "aws lambda list-functions" },
  },
  {
    id: "tech2",
    domain: "cloud-technology-and-services",
    text: "Which AWS service provides resizable virtual servers in the cloud, giving you full control over the operating system?",
    options: [
      { id: "a", text: "Amazon EC2" },
      { id: "b", text: "AWS Lambda" },
      { id: "c", text: "Amazon S3" },
      { id: "d", text: "Amazon RDS" },
    ],
    correctOptionIds: ["a"],
    explanation: "Amazon EC2 provides resizable virtual servers (instances) with full control over the guest operating system.",
    optionRationale: {
      a: "EC2 gives you resizable virtual server instances with full control over the guest operating system.",
      b: "Lambda is serverless — there's no OS or instance for you to manage.",
      c: "S3 is object storage, not a compute service with an operating system.",
      d: "RDS is a managed database service; you don't get OS-level access to the underlying server.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html",
    referenceLabel: "Amazon EC2 Concepts",
    cliExample: { description: "List your running EC2 instances", command: "aws ec2 describe-instances" },
  },
  {
    id: "tech3",
    domain: "cloud-technology-and-services",
    text: "Which service automatically adjusts the number of EC2 instances in a group based on demand?",
    options: [
      { id: "a", text: "Elastic Load Balancing" },
      { id: "b", text: "Amazon EC2 Auto Scaling" },
      { id: "c", text: "AWS Lambda" },
      { id: "d", text: "Amazon CloudFront" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon EC2 Auto Scaling adds or removes instances automatically to match changing demand.",
    optionRationale: {
      a: "ELB distributes traffic across existing targets; it doesn't add or remove instances itself.",
      b: "EC2 Auto Scaling automatically launches or terminates instances in a group to match demand.",
      c: "Lambda scales its own concurrency automatically, but it doesn't manage an EC2 instance group.",
      d: "CloudFront is a content delivery network and has no role in EC2 instance counts.",
    },
    referenceUrl: "https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html",
    referenceLabel: "What Is Amazon EC2 Auto Scaling?",
    diagram: `flowchart TD
  A[Demand Increases] --> B[Amazon EC2 Auto Scaling]
  B --> C[Launch New Instances]
  D[Demand Decreases] --> B
  B --> E[Terminate Instances]`,
  },
  {
    id: "tech4",
    domain: "cloud-technology-and-services",
    text: "What is the primary function of Elastic Load Balancing (ELB)?",
    options: [
      { id: "a", text: "To store static website files" },
      { id: "b", text: "To automatically distribute incoming application traffic across multiple targets, such as EC2 instances" },
      { id: "c", text: "To encrypt data at rest" },
      { id: "d", text: "To provide a managed relational database" },
    ],
    correctOptionIds: ["b"],
    explanation: "Elastic Load Balancing distributes incoming traffic across multiple targets to improve availability and fault tolerance.",
    optionRationale: {
      a: "Storing static files is Amazon S3's job, not a load balancer's.",
      b: "ELB automatically distributes incoming traffic across multiple targets like EC2 instances.",
      c: "Encryption at rest is handled by storage/database services and KMS, not ELB.",
      d: "A managed relational database is Amazon RDS, unrelated to traffic distribution.",
    },
    referenceUrl: "https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html",
    referenceLabel: "What Is Elastic Load Balancing?",
    diagram: `flowchart TD
  U[Incoming Traffic] --> LB[Elastic Load Balancer]
  LB --> I1[EC2 Instance 1]
  LB --> I2[EC2 Instance 2]
  LB --> I3[EC2 Instance 3]`,
  },
  {
    id: "tech5",
    domain: "cloud-technology-and-services",
    text: "Which AWS service is a fully managed container orchestration option that runs Amazon ECS and Kubernetes-compatible workloads without requiring you to manage the underlying servers?",
    options: [
      { id: "a", text: "AWS Fargate" },
      { id: "b", text: "Amazon EC2" },
      { id: "c", text: "AWS Lambda" },
      { id: "d", text: "Amazon Lightsail" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS Fargate is a serverless compute engine for containers that removes the need to provision or manage servers.",
    optionRationale: {
      a: "Fargate runs ECS and EKS container workloads as a serverless compute engine, with no servers to manage.",
      b: "EC2 requires you to provision and manage the underlying servers yourself.",
      c: "Lambda runs individual functions; it isn't the engine that runs ECS/Kubernetes container workloads.",
      d: "Lightsail offers simplified virtual private servers, not serverless container orchestration.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html",
    referenceLabel: "AWS Fargate",
  },
  {
    id: "tech6",
    domain: "cloud-technology-and-services",
    text: "A developer wants the simplest way to deploy a web application to AWS without manually configuring the underlying infrastructure like load balancers and EC2 instances. Which service should they use?",
    options: [
      { id: "a", text: "AWS Elastic Beanstalk" },
      { id: "b", text: "Amazon VPC" },
      { id: "c", text: "AWS Direct Connect" },
      { id: "d", text: "Amazon Route 53" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS Elastic Beanstalk automatically handles provisioning, load balancing, and scaling for deployed applications.",
    optionRationale: {
      a: "Elastic Beanstalk automatically provisions and configures the load balancer, instances, and scaling for you.",
      b: "VPC defines a virtual network; it doesn't deploy or configure an application for you.",
      c: "Direct Connect is a dedicated network link to AWS, unrelated to application deployment.",
      d: "Route 53 handles DNS routing, not application infrastructure provisioning.",
    },
    referenceUrl: "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/Welcome.html",
    referenceLabel: "What Is AWS Elastic Beanstalk?",
  },
  {
    id: "tech7",
    domain: "cloud-technology-and-services",
    text: "Which Amazon S3 storage class is best suited for data that is accessed infrequently but requires rapid access when needed?",
    options: [
      { id: "a", text: "S3 Standard" },
      { id: "b", text: "S3 Standard-Infrequent Access (S3 Standard-IA)" },
      { id: "c", text: "S3 Glacier Deep Archive" },
      { id: "d", text: "S3 Intelligent-Tiering configured only for frequent access" },
    ],
    correctOptionIds: ["b"],
    explanation: "S3 Standard-IA offers lower storage cost for infrequently accessed data while still allowing millisecond retrieval.",
    optionRationale: {
      a: "S3 Standard costs more and is designed for data accessed frequently, not infrequently.",
      b: "Standard-IA is priced for infrequent access but still offers millisecond retrieval when you need the data.",
      c: "Glacier Deep Archive retrieval takes hours, not the rapid access this scenario requires.",
      d: "Forcing Intelligent-Tiering to frequent access defeats its purpose and costs more than Standard-IA for this pattern.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html",
    referenceLabel: "Amazon S3 Storage Classes",
    diagram: `flowchart LR
  A[S3 Standard] --> B[S3 Standard-IA]
  B --> C[S3 One Zone-IA]
  C --> D[S3 Glacier Instant Retrieval]
  D --> E[S3 Glacier Deep Archive]`,
    cliExample: { description: "List your S3 buckets", command: "aws s3api list-buckets" },
  },
  {
    id: "tech8",
    domain: "cloud-technology-and-services",
    text: "Which S3 storage class is designed for long-term archival data that is rarely accessed and can tolerate retrieval times of many hours?",
    options: [
      { id: "a", text: "S3 Standard" },
      { id: "b", text: "S3 One Zone-IA" },
      { id: "c", text: "S3 Glacier Deep Archive" },
      { id: "d", text: "S3 Standard-IA" },
    ],
    correctOptionIds: ["c"],
    explanation: "S3 Glacier Deep Archive is the lowest-cost S3 storage class, meant for long-term archives rarely accessed.",
    optionRationale: {
      a: "S3 Standard is the most expensive option here and is meant for frequently accessed data.",
      b: "One Zone-IA still offers millisecond retrieval, not the multi-hour retrieval tolerance described.",
      c: "Glacier Deep Archive is the lowest-cost class, built for archives rarely accessed and retrieved over hours.",
      d: "Standard-IA still offers millisecond retrieval, not built for long-term rarely accessed archives.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html",
    referenceLabel: "Amazon S3 Storage Classes",
  },
  {
    id: "tech9",
    domain: "cloud-technology-and-services",
    text: "Which TWO of the following statements about Amazon EBS are true?",
    options: [
      { id: "a", text: "EBS volumes provide block-level storage for use with EC2 instances" },
      { id: "b", text: "EBS volumes can be attached to multiple Availability Zones simultaneously" },
      { id: "c", text: "EBS volumes can persist independently of the life of the instance, when configured to do so" },
      { id: "d", text: "EBS is an object storage service like Amazon S3" },
      { id: "e", text: "EBS volumes cannot be backed up" },
    ],
    correctOptionIds: ["a", "c"],
    explanation: "EBS provides block storage for EC2, and volumes can be configured to persist after an instance is terminated.",
    optionRationale: {
      a: "EBS provides block-level storage volumes that attach to EC2 instances.",
      b: "An EBS volume lives in a single Availability Zone; it can't span multiple AZs at once.",
      c: "You can configure a volume to persist (skip 'delete on termination') so it survives instance termination.",
      d: "EBS is block storage, not object storage — that's what distinguishes it from S3.",
      e: "EBS volumes can be backed up using snapshots stored in S3.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html",
    referenceLabel: "Amazon EBS",
  },
  {
    id: "tech10",
    domain: "cloud-technology-and-services",
    text: "Which AWS storage service provides a scalable, fully managed file system that can be mounted concurrently by multiple EC2 instances?",
    options: [
      { id: "a", text: "Amazon S3" },
      { id: "b", text: "Amazon EFS (Elastic File System)" },
      { id: "c", text: "Amazon EBS" },
      { id: "d", text: "AWS Storage Gateway" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon EFS is a managed, elastic file system that many EC2 instances can mount and share at once.",
    optionRationale: {
      a: "S3 is object storage accessed via API calls, not a POSIX file system you mount on instances.",
      b: "EFS is a managed elastic file system that many EC2 instances can mount and share concurrently.",
      c: "A standard EBS volume attaches to one instance at a time, not shared concurrently across many.",
      d: "Storage Gateway bridges on-premises storage with AWS; it isn't itself a shared EC2-mountable file system.",
    },
    referenceUrl: "https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html",
    referenceLabel: "What Is Amazon EFS?",
    cliExample: { description: "List your EFS file systems", command: "aws efs describe-file-systems" },
  },
  {
    id: "tech11",
    domain: "cloud-technology-and-services",
    text: "Which service helps organizations integrate on-premises storage environments with AWS cloud storage?",
    options: [
      { id: "a", text: "AWS Storage Gateway" },
      { id: "b", text: "Amazon S3 Transfer Acceleration" },
      { id: "c", text: "AWS Snowball" },
      { id: "d", text: "Amazon FSx" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS Storage Gateway is a hybrid cloud storage service connecting on-premises environments with AWS storage.",
    optionRationale: {
      a: "Storage Gateway is purpose-built to connect on-premises environments to AWS storage.",
      b: "Transfer Acceleration speeds up uploads to S3 over the internet; it's not a hybrid storage integration.",
      c: "Snowball is for one-off physical bulk data transfer, not ongoing hybrid storage integration.",
      d: "FSx provides managed file systems that run in AWS, not an on-premises integration layer.",
    },
    referenceUrl: "https://docs.aws.amazon.com/storagegateway/latest/userguide/WhatIsStorageGateway.html",
    referenceLabel: "What Is AWS Storage Gateway?",
  },
  {
    id: "tech12",
    domain: "cloud-technology-and-services",
    text: "Which AWS database service is a fully managed relational database that supports engines such as MySQL, PostgreSQL, and SQL Server?",
    options: [
      { id: "a", text: "Amazon DynamoDB" },
      { id: "b", text: "Amazon RDS" },
      { id: "c", text: "Amazon Redshift" },
      { id: "d", text: "Amazon ElastiCache" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon RDS is a managed relational database service supporting multiple engines including MySQL and PostgreSQL.",
    optionRationale: {
      a: "DynamoDB is a NoSQL key-value/document database, not a relational engine like MySQL or SQL Server.",
      b: "RDS is a managed relational database service supporting engines including MySQL, PostgreSQL, and SQL Server.",
      c: "Redshift is a data warehouse for analytics, not a general-purpose relational database service.",
      d: "ElastiCache is an in-memory caching service, not a relational database.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html",
    referenceLabel: "What Is Amazon RDS?",
    cliExample: { description: "List your RDS database instances", command: "aws rds describe-db-instances" },
  },
  {
    id: "tech13",
    domain: "cloud-technology-and-services",
    text: "Which AWS database service is a key-value and document NoSQL database designed for single-digit millisecond performance at any scale?",
    options: [
      { id: "a", text: "Amazon RDS" },
      { id: "b", text: "Amazon DynamoDB" },
      { id: "c", text: "Amazon Redshift" },
      { id: "d", text: "Amazon Aurora" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon DynamoDB is a fully managed NoSQL key-value and document database built for fast, consistent performance.",
    optionRationale: {
      a: "RDS is a relational database service, not a key-value/document NoSQL store.",
      b: "DynamoDB is a fully managed NoSQL key-value/document database built for single-digit millisecond performance.",
      c: "Redshift is a SQL data warehouse for analytics, not a low-latency NoSQL store.",
      d: "Aurora is a relational (MySQL/PostgreSQL-compatible) database, not NoSQL.",
    },
    referenceUrl: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html",
    referenceLabel: "What Is Amazon DynamoDB?",
    cliExample: { description: "List your DynamoDB tables", command: "aws dynamodb list-tables" },
  },
  {
    id: "tech14",
    domain: "cloud-technology-and-services",
    text: "Which TWO caching engines are supported by Amazon ElastiCache?",
    options: [
      { id: "a", text: "Redis" },
      { id: "b", text: "Memcached" },
      { id: "c", text: "MySQL" },
      { id: "d", text: "PostgreSQL" },
      { id: "e", text: "MongoDB" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Amazon ElastiCache supports the Redis and Memcached in-memory caching engines.",
    optionRationale: {
      a: "Redis is one of the two in-memory engines ElastiCache supports.",
      b: "Memcached is the other in-memory engine ElastiCache supports.",
      c: "MySQL is a relational database engine, not an ElastiCache caching engine.",
      d: "PostgreSQL is a relational database engine, not an ElastiCache caching engine.",
      e: "MongoDB is a document database, not one of ElastiCache's supported caching engines.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html",
    referenceLabel: "What Is Amazon ElastiCache?",
  },
  {
    id: "tech15",
    domain: "cloud-technology-and-services",
    text: "Which AWS service is purpose-built as a fully managed data warehouse for running complex analytic queries against large volumes of data?",
    options: [
      { id: "a", text: "Amazon RDS" },
      { id: "b", text: "Amazon Redshift" },
      { id: "c", text: "Amazon DynamoDB" },
      { id: "d", text: "Amazon Aurora" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon Redshift is a managed data warehouse service optimized for large-scale analytic queries.",
    optionRationale: {
      a: "RDS is optimized for transactional (OLTP) workloads, not large-scale analytic queries.",
      b: "Redshift is a managed data warehouse purpose-built for complex analytic queries at scale.",
      c: "DynamoDB is a NoSQL store optimized for fast lookups, not complex analytic SQL queries.",
      d: "Aurora is a relational database for transactional workloads, not a dedicated data warehouse.",
    },
    referenceUrl: "https://docs.aws.amazon.com/redshift/latest/mgmt/welcome.html",
    referenceLabel: "What Is Amazon Redshift?",
    cliExample: { description: "List your Redshift clusters", command: "aws redshift describe-clusters" },
  },
  {
    id: "tech16",
    domain: "cloud-technology-and-services",
    text: "Which AWS networking service lets you provision a logically isolated section of the AWS Cloud where you can launch resources in a virtual network you define?",
    options: [
      { id: "a", text: "Amazon VPC" },
      { id: "b", text: "Amazon Route 53" },
      { id: "c", text: "AWS Direct Connect" },
      { id: "d", text: "Amazon CloudFront" },
    ],
    correctOptionIds: ["a"],
    explanation: "Amazon VPC lets you define and control a logically isolated virtual network within AWS.",
    optionRationale: {
      a: "VPC lets you provision a logically isolated virtual network and define its IP ranges, subnets, and routing.",
      b: "Route 53 is a DNS service; it doesn't provision an isolated virtual network.",
      c: "Direct Connect is a dedicated physical link into AWS, not the virtual network itself.",
      d: "CloudFront is a content delivery network, unrelated to defining a virtual network.",
    },
    referenceUrl: "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html",
    referenceLabel: "What Is Amazon VPC?",
    diagram: `flowchart TD
  V[Amazon VPC] --> PubSub[Public Subnet]
  V --> PrivSub[Private Subnet]
  PubSub --> IGW[Internet Gateway]
  PrivSub --> NAT[NAT Gateway]
  NAT --> IGW`,
    cliExample: { description: "List your VPCs", command: "aws ec2 describe-vpcs" },
  },
  {
    id: "tech17",
    domain: "cloud-technology-and-services",
    text: "Which AWS service is a scalable Domain Name System (DNS) web service used to route end users to internet applications?",
    options: [
      { id: "a", text: "Amazon CloudFront" },
      { id: "b", text: "Amazon Route 53" },
      { id: "c", text: "AWS Global Accelerator" },
      { id: "d", text: "Amazon API Gateway" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon Route 53 is AWS's scalable DNS and domain registration service.",
    optionRationale: {
      a: "CloudFront is a content delivery network that caches content; it isn't the DNS service itself.",
      b: "Route 53 is AWS's scalable DNS web service, used to route users to internet applications.",
      c: "Global Accelerator improves network performance using the AWS global network, but it isn't primarily a DNS service.",
      d: "API Gateway manages and publishes APIs; it doesn't provide general-purpose DNS routing.",
    },
    referenceUrl: "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/Welcome.html",
    referenceLabel: "What Is Amazon Route 53?",
    cliExample: { description: "List your Route 53 hosted zones", command: "aws route53 list-hosted-zones" },
  },
  {
    id: "tech18",
    domain: "cloud-technology-and-services",
    text: "Which AWS service is a content delivery network (CDN) that securely delivers data, videos, and applications to users with low latency by caching content at edge locations?",
    options: [
      { id: "a", text: "Amazon Route 53" },
      { id: "b", text: "Amazon CloudFront" },
      { id: "c", text: "AWS Direct Connect" },
      { id: "d", text: "Amazon VPC" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon CloudFront is AWS's CDN, caching content at edge locations to reduce latency for end users.",
    optionRationale: {
      a: "Route 53 is a DNS service; it doesn't cache content at edge locations.",
      b: "CloudFront is AWS's CDN, caching content at edge locations for low-latency delivery.",
      c: "Direct Connect provides a private network link to AWS, not edge caching for end users.",
      d: "VPC defines a virtual network; it plays no role in content caching or delivery.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html",
    referenceLabel: "What Is Amazon CloudFront?",
    diagram: `flowchart LR
  Origin[Origin Server] --> CF[CloudFront Distribution]
  CF --> Edge1[Edge Location A]
  CF --> Edge2[Edge Location B]
  Edge1 --> User1[End User]
  Edge2 --> User2[End User]`,
    cliExample: { description: "List your CloudFront distributions", command: "aws cloudfront list-distributions" },
  },
  {
    id: "tech19",
    domain: "cloud-technology-and-services",
    text: "Which service provides a dedicated, private network connection between an on-premises data center and AWS, bypassing the public internet?",
    options: [
      { id: "a", text: "AWS VPN" },
      { id: "b", text: "AWS Direct Connect" },
      { id: "c", text: "Amazon CloudFront" },
      { id: "d", text: "AWS Transit Gateway" },
    ],
    correctOptionIds: ["b"],
    explanation: "AWS Direct Connect establishes a dedicated private network connection between on-premises infrastructure and AWS.",
    optionRationale: {
      a: "AWS VPN creates encrypted tunnels over the public internet, not a dedicated private line.",
      b: "Direct Connect establishes a dedicated private connection between on-premises infrastructure and AWS, bypassing the public internet.",
      c: "CloudFront is a CDN and has no role in private network connectivity.",
      d: "Transit Gateway interconnects VPCs and on-premises networks, but it doesn't itself provide the dedicated physical link.",
    },
    referenceUrl: "https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html",
    referenceLabel: "What Is AWS Direct Connect?",
  },
  {
    id: "tech20",
    domain: "cloud-technology-and-services",
    text: "Which AWS service allows developers to create, publish, and manage APIs at scale, including handling authorization, throttling, and monitoring?",
    options: [
      { id: "a", text: "Amazon API Gateway" },
      { id: "b", text: "AWS AppSync" },
      { id: "c", text: "Amazon Route 53" },
      { id: "d", text: "AWS Lambda" },
    ],
    correctOptionIds: ["a"],
    explanation: "Amazon API Gateway lets you create, publish, and manage APIs, including authorization, throttling, and monitoring.",
    optionRationale: {
      a: "API Gateway lets you create, publish, and manage APIs, including authorization, throttling, and monitoring.",
      b: "AppSync focuses specifically on managed GraphQL APIs, a narrower case than general API management.",
      c: "Route 53 is a DNS service, not an API management platform.",
      d: "Lambda can run the backend code behind an API, but it doesn't provide API publishing or throttling itself.",
    },
    referenceUrl: "https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html",
    referenceLabel: "What Is Amazon API Gateway?",
    diagram: `flowchart LR
  Client[Client App] --> APIGW[Amazon API Gateway]
  APIGW --> Lambda[AWS Lambda Function]
  Lambda --> DB[(Database)]`,
  },
  {
    id: "tech21",
    domain: "cloud-technology-and-services",
    text: "Which AWS service provides detailed monitoring through metrics, logs, and alarms for AWS resources and applications?",
    options: [
      { id: "a", text: "AWS CloudTrail" },
      { id: "b", text: "Amazon CloudWatch" },
      { id: "c", text: "AWS Config" },
      { id: "d", text: "AWS X-Ray" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon CloudWatch collects metrics and logs and lets you set alarms to monitor AWS resources and applications.",
    optionRationale: {
      a: "CloudTrail logs API activity for auditing, rather than general metrics, logs, and alarms.",
      b: "CloudWatch collects metrics and logs and lets you configure alarms across AWS resources and applications.",
      c: "AWS Config tracks resource configuration changes and compliance, not general performance monitoring.",
      d: "X-Ray traces requests through distributed applications for debugging, a narrower focus than CloudWatch.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html",
    referenceLabel: "What Is Amazon CloudWatch?",
    cliExample: { description: "List your CloudWatch alarms", command: "aws cloudwatch describe-alarms" },
  },
  {
    id: "tech22",
    domain: "cloud-technology-and-services",
    text: "Which service lets you model, provision, and manage AWS resources by treating infrastructure as code using declarative templates?",
    options: [
      { id: "a", text: "AWS CloudFormation" },
      { id: "b", text: "AWS Systems Manager" },
      { id: "c", text: "AWS OpsWorks" },
      { id: "d", text: "AWS Config" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS CloudFormation provisions and manages AWS resources using declarative infrastructure-as-code templates.",
    optionRationale: {
      a: "CloudFormation provisions and manages AWS resources from declarative infrastructure-as-code templates.",
      b: "Systems Manager focuses on operational visibility and automation, not declarative resource provisioning.",
      c: "OpsWorks manages infrastructure through Chef/Puppet configuration management, a different IaC approach.",
      d: "AWS Config tracks and audits configuration state; it doesn't provision resources from templates.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html",
    referenceLabel: "What Is AWS CloudFormation?",
    cliExample: { description: "List your CloudFormation stacks", command: "aws cloudformation list-stacks" },
  },
  {
    id: "tech23",
    domain: "cloud-technology-and-services",
    text: "Which AWS service gives you visibility into operational data and allows you to automate operational tasks across your AWS resources, such as patch management?",
    options: [
      { id: "a", text: "AWS Systems Manager" },
      { id: "b", text: "Amazon CloudWatch" },
      { id: "c", text: "AWS Config" },
      { id: "d", text: "AWS Trusted Advisor" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS Systems Manager provides operational visibility and automation, including patch management, across AWS resources.",
    optionRationale: {
      a: "Systems Manager provides operational visibility and automation, including patch management, across resources.",
      b: "CloudWatch focuses on metrics, logs, and alarms, not broad operational automation like patching.",
      c: "AWS Config tracks configuration state and compliance; it doesn't automate operational tasks like patching.",
      d: "Trusted Advisor gives best-practice recommendations but doesn't execute automated operational tasks.",
    },
    referenceUrl: "https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-systems-manager.html",
    referenceLabel: "What Is AWS Systems Manager?",
  },
  {
    id: "tech24",
    domain: "cloud-technology-and-services",
    text: "Which fully managed message queuing service enables you to decouple and scale microservices, distributed systems, and serverless applications?",
    options: [
      { id: "a", text: "Amazon SNS" },
      { id: "b", text: "Amazon SQS" },
      { id: "c", text: "Amazon EventBridge" },
      { id: "d", text: "AWS Step Functions" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon SQS is a fully managed message queuing service used to decouple and scale distributed application components.",
    optionRationale: {
      a: "SNS is a pub/sub service for fanning out notifications, not a point-to-point message queue.",
      b: "SQS is a fully managed message queue that decouples and scales distributed application components.",
      c: "EventBridge routes events between applications based on rules; it's an event bus, not a simple queue.",
      d: "Step Functions orchestrates multi-step workflows; it isn't a message queuing service.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html",
    referenceLabel: "What Is Amazon SQS?",
    cliExample: { description: "List your SQS queues", command: "aws sqs list-queues" },
  },
  {
    id: "tech25",
    domain: "cloud-technology-and-services",
    text: "Which AWS service is a fully managed publish/subscribe messaging service used to fan out notifications to multiple subscribers, such as email, SMS, or Lambda functions?",
    options: [
      { id: "a", text: "Amazon SQS" },
      { id: "b", text: "Amazon SNS" },
      { id: "c", text: "Amazon MQ" },
      { id: "d", text: "AWS Step Functions" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon SNS is a publish/subscribe messaging service that fans out notifications to multiple types of subscribers.",
    optionRationale: {
      a: "SQS is a queue meant for one consumer processing messages, not fanning out to many subscriber types.",
      b: "SNS is a pub/sub service that fans out notifications to subscribers like email, SMS, and Lambda.",
      c: "Amazon MQ is a managed broker for existing protocols like JMS/AMQP, a different messaging model.",
      d: "Step Functions orchestrates workflows; it doesn't fan out notifications to subscribers.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sns/latest/dg/welcome.html",
    referenceLabel: "What Is Amazon SNS?",
    cliExample: { description: "List your SNS topics", command: "aws sns list-topics" },
  },
  {
    id: "tech26",
    domain: "cloud-technology-and-services",
    text: "Which service allows you to coordinate multiple AWS Lambda functions and other AWS services into serverless workflows using visual state machines?",
    options: [
      { id: "a", text: "AWS Step Functions" },
      { id: "b", text: "Amazon EventBridge" },
      { id: "c", text: "Amazon SQS" },
      { id: "d", text: "AWS Batch" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS Step Functions coordinates multiple AWS services into serverless workflows using visual state machines.",
    optionRationale: {
      a: "Step Functions coordinates Lambda functions and other services into serverless workflows using visual state machines.",
      b: "EventBridge routes events between services based on rules; it doesn't provide a visual state-machine builder.",
      c: "SQS is a message queue, not a workflow orchestrator.",
      d: "AWS Batch runs batch computing jobs; it doesn't coordinate multi-step serverless workflows visually.",
    },
    referenceUrl: "https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html",
    referenceLabel: "What Is AWS Step Functions?",
    diagram: `stateDiagram-v2
  [*] --> ValidateInput
  ValidateInput --> ProcessOrder
  ProcessOrder --> SendNotification
  SendNotification --> [*]`,
  },
  {
    id: "tech27",
    domain: "cloud-technology-and-services",
    text: "Which AWS service converts speech to text?",
    options: [
      { id: "a", text: "Amazon Polly" },
      { id: "b", text: "Amazon Transcribe" },
      { id: "c", text: "Amazon Comprehend" },
      { id: "d", text: "Amazon Lex" },
    ],
    correctOptionIds: ["b"],
    explanation: "Amazon Transcribe is an automatic speech recognition service that converts spoken audio into text.",
    optionRationale: {
      a: "Polly converts text to speech — the opposite direction from what's described.",
      b: "Transcribe is AWS's automatic speech recognition service, converting spoken audio into text.",
      c: "Comprehend analyzes existing text for sentiment and entities; it doesn't transcribe audio.",
      d: "Lex builds conversational chatbots and uses speech recognition internally, but it isn't the standalone transcription service.",
    },
    referenceUrl: "https://docs.aws.amazon.com/transcribe/latest/dg/what-is-transcribe.html",
    referenceLabel: "What Is Amazon Transcribe?",
  },
  {
    id: "tech28",
    domain: "cloud-technology-and-services",
    text: "Which AWS service provides a fully managed environment for building, training, and deploying machine learning models?",
    options: [
      { id: "a", text: "Amazon SageMaker" },
      { id: "b", text: "Amazon Rekognition" },
      { id: "c", text: "Amazon Comprehend" },
      { id: "d", text: "AWS DeepLens" },
    ],
    correctOptionIds: ["a"],
    explanation: "Amazon SageMaker provides a fully managed environment covering the full machine learning lifecycle.",
    optionRationale: {
      a: "SageMaker provides a fully managed environment covering the full build-train-deploy ML lifecycle.",
      b: "Rekognition analyzes images and video; it's a pre-built AI service, not a general ML development platform.",
      c: "Comprehend performs natural language processing; it's a pre-built AI service, not a general ML platform.",
      d: "DeepLens is an AI-enabled camera device, not a managed ML development environment.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html",
    referenceLabel: "What Is Amazon SageMaker?",
  },
  {
    id: "tech29",
    domain: "cloud-technology-and-services",
    text: "Which service allows you to run interactive SQL queries directly against data stored in Amazon S3 without needing to load it into a database?",
    options: [
      { id: "a", text: "Amazon Athena" },
      { id: "b", text: "Amazon Redshift" },
      { id: "c", text: "Amazon EMR" },
      { id: "d", text: "Amazon Kinesis" },
    ],
    correctOptionIds: ["a"],
    explanation: "Amazon Athena is a serverless query service that runs SQL directly against data stored in Amazon S3.",
    optionRationale: {
      a: "Athena is a serverless query service that runs SQL directly against data already sitting in S3.",
      b: "Redshift requires loading data into its own warehouse first, unlike Athena's direct S3 querying.",
      c: "EMR runs big data frameworks like Hadoop/Spark on managed clusters, a heavier tool than ad hoc SQL on S3.",
      d: "Kinesis is for ingesting streaming data, not running ad hoc SQL queries against data at rest in S3.",
    },
    referenceUrl: "https://docs.aws.amazon.com/athena/latest/ug/what-is.html",
    referenceLabel: "What Is Amazon Athena?",
  },
  {
    id: "tech30",
    domain: "cloud-technology-and-services",
    text: "Which TWO of the following AWS services are primarily used for real-time or near-real-time streaming data ingestion and processing?",
    options: [
      { id: "a", text: "Amazon Kinesis" },
      { id: "b", text: "Amazon MSK (Managed Streaming for Apache Kafka)" },
      { id: "c", text: "Amazon Redshift" },
      { id: "d", text: "Amazon RDS" },
      { id: "e", text: "AWS CloudFormation" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Amazon Kinesis and Amazon MSK are both built for ingesting and processing streaming data in real time.",
    optionRationale: {
      a: "Kinesis is purpose-built for real-time streaming data ingestion and processing.",
      b: "MSK is a managed Apache Kafka service, also purpose-built for streaming data.",
      c: "Redshift queries data already loaded into a warehouse; it isn't a streaming ingestion service.",
      d: "RDS is a transactional relational database, not built for streaming ingestion.",
      e: "CloudFormation provisions infrastructure and has nothing to do with streaming data.",
    },
    referenceUrl: "https://docs.aws.amazon.com/streams/latest/dev/introduction.html",
    referenceLabel: "What Is Amazon Kinesis Data Streams?",
  },
  {
    id: "tech31",
    domain: "cloud-technology-and-services",
    text: "Which TWO of the following are container-related AWS services?",
    options: [
      { id: "a", text: "Amazon ECS (Elastic Container Service)" },
      { id: "b", text: "Amazon EKS (Elastic Kubernetes Service)" },
      { id: "c", text: "Amazon Route 53" },
      { id: "d", text: "AWS Direct Connect" },
      { id: "e", text: "Amazon SNS" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Amazon ECS and Amazon EKS are AWS's managed container orchestration services.",
    optionRationale: {
      a: "ECS is AWS's native container orchestration service.",
      b: "EKS is AWS's managed Kubernetes service for running containers.",
      c: "Route 53 is a DNS service, unrelated to running containers.",
      d: "Direct Connect is dedicated network connectivity, unrelated to running containers.",
      e: "SNS is a pub/sub messaging service, unrelated to running containers.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonECS/latest/developerguide/Welcome.html",
    referenceLabel: "What Is Amazon ECS?",
    diagram: `flowchart TD
  Dev[Container Image] --> ECR[Amazon ECR]
  ECR --> Orchestrator{ECS or EKS}
  Orchestrator --> Fargate[AWS Fargate]
  Orchestrator --> EC2[EC2 Cluster]`,
    cliExample: { description: "List your ECS clusters", command: "aws ecs list-clusters" },
  },
];
