import { Question } from "../../types.js";

export const aiMlFundamentalsQuestions: Question[] = [
  {
    id: "aif-ml1",
    domain: "ai-ml-fundamentals",
    text: "A retailer wants a model that predicts next month's sales figure for each store from historical sales data. Which type of machine learning problem is this?",
    options: [
      { id: "a", text: "Regression" },
      { id: "b", text: "Binary classification" },
      { id: "c", text: "Clustering" },
      { id: "d", text: "Anomaly detection" },
      { id: "e", text: "Multi-class classification" },
      { id: "f", text: "Dimensionality reduction" },
      { id: "g", text: "Time-series forecasting" },
      { id: "h", text: "Reinforcement learning" },
    ],
    correctOptionIds: ["a", "g"],
    answerType: "single",
    explanation: "Predicting a continuous value such as next month's sales is a regression problem, and because it projects a series of past values forward in time, it is also time-series forecasting.",
    optionRationale: {
      a: "Regression predicts a continuous number, which is exactly a sales figure.",
      b: "Binary classification predicts one of two labels, not a numeric amount.",
      c: "Clustering groups similar records without a target value; it is unsupervised.",
      d: "Anomaly detection flags unusual records rather than forecasting a number.",
      e: "Multi-class classification picks one label from several, not a continuous value.",
      f: "Dimensionality reduction compresses features; it does not produce a prediction.",
      g: "Predicting future values such as next month's sales from a sequence of past values over time is time-series forecasting.",
      h: "Reinforcement learning trains an agent through rewards and penalties, not by predicting a numeric value from historical records.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-training.html",
    referenceLabel: "Amazon SageMaker: How training works",
  },
  {
    id: "aif-ml2",
    domain: "ai-ml-fundamentals",
    text: "Which TWO statements describe supervised learning?",
    options: [
      { id: "a", text: "The training data includes labeled target values." },
      { id: "b", text: "The model learns from rewards and penalties while interacting with an environment." },
      { id: "c", text: "Classification and regression are common supervised tasks." },
      { id: "d", text: "The algorithm discovers hidden groupings without any labels." },
      { id: "e", text: "It requires a foundation model as the starting point." },
      { id: "f", text: "It can only be used with image data." },
      { id: "g", text: "Predicting house prices from past sales records is a typical example." },
      { id: "h", text: "Model accuracy can be measured against known answers in test data." },
      { id: "i", text: "A human reviews every prediction the model makes before it is used." },
      { id: "j", text: "It generates new content, such as text or images, from a prompt." },
    ],
    correctOptionIds: ["a", "c", "g", "h"],
    answerType: "multi",
    explanation: "Supervised learning trains on examples that already carry the correct answer (labels), so its predictions can be scored against known answers, and it covers classification and regression tasks such as house-price prediction.",
    optionRationale: {
      a: "Labels are the defining feature of supervised learning.",
      b: "Learning from rewards describes reinforcement learning.",
      c: "Both classification and regression need labeled examples and are the two main supervised task types.",
      d: "Discovering groupings without labels is unsupervised learning (clustering).",
      e: "Supervised learning predates foundation models and does not require one.",
      f: "Supervised learning works with tabular, text, image, audio, and other data types.",
      g: "Past sales records carry the known price for each house, so learning to predict price from them is a textbook supervised regression task.",
      h: "Because the data is labeled, held-out test examples have known answers to score predictions against.",
      i: "The 'supervision' comes from labeled training data, not from a person checking each prediction, which is a separate human-in-the-loop step such as Amazon A2I.",
      j: "Generating new content from a prompt describes generative AI; supervised learning is defined by training on labeled examples.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/machine-learning/",
    referenceLabel: "What is machine learning? (AWS)",
  },
  {
    id: "aif-ml3",
    domain: "ai-ml-fundamentals",
    text: "An engineering team describes a system that stacks many layers of artificial neurons and learns useful features directly from raw images, with no manual feature extraction step. Which term best describes this approach?",
    options: [
      { id: "a", text: "Deep learning" },
      { id: "b", text: "Rule-based expert system" },
      { id: "c", text: "Generative AI" },
      { id: "d", text: "Reinforcement learning" },
      { id: "e", text: "Robotic process automation" },
      { id: "f", text: "Business intelligence reporting" },
      { id: "g", text: "Extract, transform, and load (ETL)" },
      { id: "h", text: "Convolutional neural networks" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Deep learning, which includes convolutional neural networks for images, is the subset of machine learning that uses multi-layer neural networks to learn feature representations directly from raw data such as images, audio, or text.",
    optionRationale: {
      a: "Deep learning is precisely this: many-layered neural networks that learn their own features from raw data.",
      b: "A rule-based expert system encodes if-then rules written by humans and learns nothing from data.",
      c: "Generative AI describes models that produce new content; it is an application area built on deep learning, not the layered-network technique itself.",
      d: "Reinforcement learning is defined by learning from rewards during interaction with an environment, not by network depth.",
      e: "Robotic process automation scripts repetitive user-interface steps and involves no learning from data.",
      f: "Business intelligence reporting summarizes historical data for humans; it makes no predictions.",
      g: "ETL moves and reshapes data between systems; it is a data pipeline step, not a learning method.",
      h: "Convolutional neural networks are many-layered networks that learn visual features directly from raw pixels, which is exactly the approach described.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/deep-learning/",
    referenceLabel: "What is deep learning? (AWS)",
  },
  {
    id: "aif-ml4",
    domain: "ai-ml-fundamentals",
    text: "A marketing department wants a system that drafts new product descriptions and summarizes inbound customer emails. Which statement best distinguishes generative AI from traditional predictive machine learning?",
    options: [
      { id: "a", text: "Generative AI produces new content such as text, images, or code, while traditional predictive models output a label or a numeric value." },
      { id: "b", text: "Generative AI needs a labeled example for every possible output, while predictive models do not." },
      { id: "c", text: "Generative AI removes the need to evaluate output quality." },
      { id: "d", text: "Generative AI models are always smaller and cheaper to run than predictive models." },
      { id: "e", text: "Generative AI works only with images, never with text." },
      { id: "f", text: "Generative AI guarantees that every response is factually correct." },
      { id: "g", text: "Traditional predictive models cannot be trained on tabular data." },
      { id: "h", text: "Generative AI creates new samples from learned patterns, while predictive models map inputs to a target." },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Generative models create new content in response to a prompt, whereas classic predictive models return a class label or a number for a given input.",
    optionRationale: {
      a: "This is the core difference: generative models synthesize new content, predictive models emit a label or a number.",
      b: "Foundation models are pretrained on large unlabeled corpora, so they do not need a label for every possible output.",
      c: "Generative output still has to be evaluated for relevance, accuracy, toxicity, and bias.",
      d: "Foundation models are typically far larger and more expensive to run than a tabular classifier.",
      e: "Generative models cover text, images, audio, video, and code.",
      f: "Generative models can hallucinate, so factual correctness is never guaranteed.",
      g: "Tabular data is the most common input for traditional predictive models.",
      h: "Generative models learn the patterns of their training data well enough to produce new samples, whereas predictive models learn a mapping from an input to a label or value.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/generative-ai/",
    referenceLabel: "What is generative AI? (AWS)",
  },
  {
    id: "aif-ml5",
    domain: "ai-ml-fundamentals",
    text: "An insurer wants software that reads free-text claim notes and pulls out the sentiment, the key phrases, and the names of people and places mentioned. Which field of AI does this work belong to?",
    options: [
      { id: "a", text: "Natural language processing" },
      { id: "b", text: "Computer vision" },
      { id: "c", text: "Speech synthesis" },
      { id: "d", text: "Reinforcement learning" },
      { id: "e", text: "Time series forecasting" },
      { id: "f", text: "Optical character recognition" },
      { id: "g", text: "Robotics" },
      { id: "h", text: "Natural language understanding" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Natural language processing (NLP), including its natural language understanding (NLU) branch, covers machine understanding of human language such as sentiment analysis, key phrase extraction, and named entity recognition; Amazon Comprehend is the AWS managed service for these tasks.",
    optionRationale: {
      a: "Sentiment, key phrases, and named entities are classic NLP tasks performed on text.",
      b: "Computer vision interprets images and video, not written language.",
      c: "Speech synthesis turns text into spoken audio, which is the opposite direction of this task.",
      d: "Reinforcement learning trains an agent through rewards and has no bearing on reading text.",
      e: "Time series forecasting predicts future numeric values from historical sequences.",
      f: "Optical character recognition converts text in images into machine-readable characters; here the claim notes are already digital text.",
      g: "Robotics concerns controlling physical machines.",
      h: "Natural language understanding is the branch of NLP concerned with extracting meaning, such as sentiment and named entities, from written text.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/nlp/",
    referenceLabel: "What is natural language processing? (AWS)",
  },
  {
    id: "aif-ml6",
    domain: "ai-ml-fundamentals",
    text: "A marketing team holds 4 million customer records with no labels and wants to discover natural groupings of similar customers so campaigns can be targeted. Which technique fits, and which built-in Amazon SageMaker AI algorithm is designed for it?",
    options: [
      { id: "a", text: "Clustering, using the built-in K-Means algorithm" },
      { id: "b", text: "Binary classification, using the built-in XGBoost algorithm" },
      { id: "c", text: "Regression, using the built-in Linear Learner algorithm" },
      { id: "d", text: "Reinforcement learning, using a hand-designed reward function" },
      { id: "e", text: "Time series forecasting, using the built-in DeepAR algorithm" },
      { id: "f", text: "Object detection, using a built-in computer vision algorithm" },
      { id: "g", text: "Text summarization, using a foundation model" },
      { id: "h", text: "Unsupervised learning, using the built-in K-Means algorithm" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "With no labels and a goal of finding natural groups, this is unsupervised clustering, and K-Means is the built-in SageMaker AI algorithm for clustering.",
    optionRationale: {
      a: "Clustering finds groups in unlabeled data, and K-Means is the SageMaker AI built-in algorithm for exactly that.",
      b: "Binary classification needs labeled examples of two classes, which this dataset does not have.",
      c: "Regression predicts a continuous target and also requires labels.",
      d: "Reinforcement learning needs an environment and reward signal, neither of which exists here.",
      e: "DeepAR forecasts future values of time series; the team wants customer groups, not a forecast.",
      f: "Object detection locates items in images, which is unrelated to customer records.",
      g: "Summarization condenses text and does not group records by similarity.",
      h: "The records carry no labels, which makes this unsupervised learning, and K-Means is the SageMaker AI built-in algorithm that groups similar records.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/k-means.html",
    referenceLabel: "Amazon SageMaker AI: K-Means algorithm",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml7",
    domain: "ai-ml-fundamentals",
    text: "A warehouse robotics team trains an agent in simulation. The agent tries an action, receives a positive reward when a package lands in the correct bin and a penalty when it hits a shelf, and gradually improves its policy. Which type of machine learning is this?",
    options: [
      { id: "a", text: "Reinforcement learning" },
      { id: "b", text: "Supervised learning" },
      { id: "c", text: "Unsupervised learning" },
      { id: "d", text: "Semi-supervised learning" },
      { id: "e", text: "Transfer learning" },
      { id: "f", text: "Batch inference" },
      { id: "g", text: "Feature engineering" },
      { id: "h", text: "Trial-and-error learning" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Reinforcement learning, often described as trial-and-error learning, trains an agent that takes actions in an environment and improves its policy from the rewards and penalties it receives.",
    optionRationale: {
      a: "An agent, an environment, actions, and a reward signal are the defining elements of reinforcement learning.",
      b: "Supervised learning needs a dataset of inputs paired with correct answers, not a reward signal.",
      c: "Unsupervised learning finds structure in unlabeled data and involves no actions or rewards.",
      d: "Semi-supervised learning mixes a small labeled set with a large unlabeled set; there are no labels here at all.",
      e: "Transfer learning reuses a pretrained model for a new task and describes how training starts, not how the agent learns from rewards.",
      f: "Batch inference is a way of running predictions on a stored dataset, not a learning type.",
      g: "Feature engineering prepares input variables before training and is not a learning paradigm.",
      h: "Trial-and-error learning guided by rewards and penalties is the standard plain-language description of reinforcement learning, which is what this agent is doing.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/reinforcement-learning/",
    referenceLabel: "What is reinforcement learning? (AWS)",
  },
  {
    id: "aif-ml8",
    domain: "ai-ml-fundamentals",
    text: "A data engineer inventories three sources: rows in an Amazon RDS for PostgreSQL table, JSON clickstream files whose optional fields vary from record to record, and scanned PDF contracts. How are these three best classified?",
    options: [
      { id: "a", text: "Structured, semi-structured, and unstructured, in that order" },
      { id: "b", text: "Structured, structured, and semi-structured, in that order" },
      { id: "c", text: "Semi-structured, structured, and unstructured, in that order" },
      { id: "d", text: "Unstructured, semi-structured, and structured, in that order" },
      { id: "e", text: "All three are structured because each is stored in an AWS service" },
      { id: "f", text: "All three are unstructured because each contains text" },
      { id: "g", text: "Labeled, unlabeled, and semi-labeled, in that order" },
      { id: "h", text: "Tabular, semi-structured, and unstructured, in that order" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Rows in a relational table follow a fixed schema and are structured, tabular data, JSON with varying optional fields is semi-structured, and scanned documents have no predefined schema and are unstructured.",
    optionRationale: {
      a: "Relational rows are structured, flexible-schema JSON is semi-structured, and scanned PDFs are unstructured.",
      b: "JSON with varying fields is semi-structured rather than structured, and a scanned PDF is unstructured rather than semi-structured.",
      c: "Relational table rows are structured, not semi-structured, so the order is wrong.",
      d: "This reverses the classification entirely.",
      e: "Where data is stored does not determine its structure; an S3 object can hold any of the three kinds.",
      f: "Containing text does not make data unstructured; structure is about having a predefined, consistent schema.",
      g: "Labeled and unlabeled describe whether a target value is present for training, which is a different distinction from data structure.",
      h: "Relational rows are tabular, which is structured data, flexible-schema JSON is semi-structured, and scanned PDFs are unstructured.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/structured-data/",
    referenceLabel: "What is structured data? (AWS)",
  },
  {
    id: "aif-ml9",
    domain: "ai-ml-fundamentals",
    text: "Since 2024, a retail company's ML team has used the same AWS capability to draw bounding boxes around products in 200,000 photographs, manage the human workforce doing the work, and produce a training-ready manifest of labels. Which AWS capability is the team using?",
    options: [
      { id: "a", text: "Amazon SageMaker Ground Truth" },
      { id: "b", text: "Amazon SageMaker Model Monitor" },
      { id: "c", text: "Amazon SageMaker Feature Store" },
      { id: "d", text: "Amazon SageMaker Clarify" },
      { id: "e", text: "The Amazon Rekognition DetectLabels API" },
      { id: "f", text: "AWS Glue crawlers" },
      { id: "g", text: "Amazon SageMaker automatic model tuning" },
      { id: "h", text: "The Amazon SageMaker AI CreateLabelingJob API" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "SageMaker Ground Truth, whose labeling jobs are started with the CreateLabelingJob API, builds labeled training datasets with a private, vendor, or Amazon Mechanical Turk workforce and writes the results to an output manifest. Ground Truth has not been open to new customers since July 30, 2026, but existing customers such as this team can keep using it.",
    optionRationale: {
      a: "Ground Truth is the AWS data labeling service, including bounding-box tasks and managed human workforces.",
      b: "Model Monitor watches an already deployed endpoint for drift; it does not create labels.",
      c: "Feature Store stores and serves engineered features; it does not annotate images.",
      d: "Clarify measures bias and explains predictions; it does not produce labels.",
      e: "DetectLabels returns labels a pretrained model already recognizes and cannot create human-verified bounding boxes for the company's own product categories.",
      f: "Glue crawlers infer schemas for a data catalog and have nothing to do with image annotation.",
      g: "Automatic model tuning searches hyperparameter ranges after a labeled dataset already exists.",
      h: "CreateLabelingJob is the Ground Truth API that runs a bounding-box labeling job with an assigned human workforce and writes the labels to an output manifest.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/sms.html",
    referenceLabel: "Training data labeling with Amazon SageMaker Ground Truth",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml10",
    domain: "ai-ml-fundamentals",
    text: "A team splits its dataset into training, validation, and test sets. What is the role of the validation set, as distinct from the test set?",
    options: [
      { id: "a", text: "It is used to tune hyperparameters and choose between candidate models during development, while the test set is held back for a final unbiased performance estimate." },
      { id: "b", text: "It is used to update the model weights, while the test set tunes hyperparameters." },
      { id: "c", text: "It holds the labels while the training set holds only the features." },
      { id: "d", text: "It is required only for unsupervised learning." },
      { id: "e", text: "It removes the need for a test set when the dataset is very large." },
      { id: "f", text: "It is the live production traffic sent to the endpoint after deployment." },
      { id: "g", text: "It is a backup copy of the training data kept for disaster recovery." },
      { id: "h", text: "It guides early stopping and model selection, while the test set is kept for one final evaluation." },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "The validation set guides decisions made during development, such as hyperparameter values, when to stop training, and which model to keep, so the test set can stay untouched and give an honest estimate of performance on unseen data.",
    optionRationale: {
      a: "This is the standard division of labor: validation for tuning and selection, test for a single final unbiased estimate.",
      b: "Weights are learned from the training set, not the validation set.",
      c: "All three splits contain both features and labels in supervised learning.",
      d: "Unsupervised learning has no labeled target to validate against; splits like this belong to supervised workflows.",
      e: "Once the validation set has influenced model choices, it is no longer unbiased, so a separate test set is still needed.",
      f: "Production traffic arrives after deployment and is not part of the dataset split.",
      g: "A validation set exists to measure generalization, not to protect against data loss.",
      h: "Deciding when to stop training and which candidate to keep are validation-set jobs, which leaves the test set untouched for a single final measurement.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-mlconcepts.html",
    referenceLabel: "Overview of machine learning with Amazon SageMaker AI",
  },
  {
    id: "aif-ml11",
    domain: "ai-ml-fundamentals",
    text: "A model scores 99% accuracy on its training data but only 62% on held-out test data. Which TWO statements about this result are correct?",
    options: [
      { id: "a", text: "The model is overfitting the training data." },
      { id: "b", text: "Adding regularization, simplifying the model, or gathering more diverse training data can narrow the gap." },
      { id: "c", text: "The model is underfitting and needs a more complex algorithm." },
      { id: "d", text: "The gap proves that the test set labels are wrong." },
      { id: "e", text: "Training for many more epochs on the same data is the recommended fix." },
      { id: "f", text: "Overfitting can occur only with deep learning models." },
      { id: "g", text: "A model that scores far higher on training data than on test data will still generalize well in production." },
      { id: "h", text: "Early stopping based on validation performance can help prevent this." },
      { id: "i", text: "Cross-validation can help detect this problem before deployment." },
      { id: "j", text: "Training on a smaller subset of the data will narrow the gap." },
    ],
    correctOptionIds: ["a", "b", "h", "i"],
    answerType: "multi",
    explanation: "A large gap between training and test performance is the classic signature of overfitting; cross-validation helps detect it, and reducing model complexity, adding regularization, stopping training early, or training on more representative data helps prevent it.",
    optionRationale: {
      a: "Near-perfect training accuracy with much weaker test accuracy is the definition of overfitting.",
      b: "Regularization, a simpler model, and more varied training data all reduce memorization of the training set.",
      c: "Underfitting shows up as poor performance on both training and test data, which is not the case here.",
      d: "A training-to-test gap points to the model memorizing the training set, not to mislabeled test data.",
      e: "More epochs on the same data usually deepens memorization and makes overfitting worse.",
      f: "Any model family can overfit, including decision trees and linear models with too many features.",
      g: "Test performance is the better predictor of production behavior, so poor generalization should be expected.",
      h: "Stopping training once validation performance stops improving keeps the model from going on to memorize noise in the training set.",
      i: "K-fold cross-validation scores the model on data held out from each training round, which exposes a gap between training and validation performance.",
      j: "Less training data makes it easier for the model to memorize examples, which usually widens the gap rather than narrowing it.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/overfitting/",
    referenceLabel: "What is overfitting? (AWS)",
  },
  {
    id: "aif-ml12",
    domain: "ai-ml-fundamentals",
    text: "A lender scores its entire portfolio of 8 million loan applications once each night and writes the predictions to Amazon S3. No interactive response is required, and the team wants to avoid paying for idle infrastructure between runs. Which Amazon SageMaker AI inference option fits best?",
    options: [
      { id: "a", text: "Batch transform" },
      { id: "b", text: "A real-time inference endpoint left running 24 hours a day" },
      { id: "c", text: "Asynchronous inference" },
      { id: "d", text: "Serverless inference" },
      { id: "e", text: "A multi-model real-time endpoint" },
      { id: "f", text: "Self-managed model containers on Amazon EC2 behind an Application Load Balancer" },
      { id: "g", text: "The Amazon SageMaker Feature Store online store" },
      { id: "h", text: "Offline batch inference" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Batch transform, the SageMaker AI option for offline batch inference, provisions compute, scores a whole dataset read from Amazon S3, writes the results back to S3, and then releases the resources, which suits scheduled offline scoring.",
    optionRationale: {
      a: "Batch transform is designed for scoring a large stored dataset on a schedule, with no persistent endpoint to pay for.",
      b: "An always-on endpoint bills continuously for capacity the workload only needs once a night.",
      c: "Asynchronous inference handles individual long-running or large-payload requests arriving over time, not one scheduled pass over an entire dataset.",
      d: "Serverless inference targets intermittent request-response traffic; it is not the tool for scoring millions of records from S3 in one job.",
      e: "A multi-model endpoint saves cost when hosting many models behind one endpoint, but it is still an always-on real-time endpoint.",
      f: "Running your own containers reintroduces the undifferentiated heavy lifting that batch transform already manages.",
      g: "The Feature Store online store serves feature values with low latency; it does not run inference.",
      h: "Offline batch inference, which SageMaker AI runs as a batch transform job, scores the whole stored dataset in one pass with no persistent endpoint to pay for.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/batch-transform.html",
    referenceLabel: "Amazon SageMaker AI: Batch transform",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml13",
    domain: "ai-ml-fundamentals",
    text: "A media company needs inference on video files where a single request carries a payload of several hundred megabytes and can take up to ten minutes to process. Requests arrive sporadically, and the caller is content to be notified when each result is ready. Which Amazon SageMaker AI inference option fits best?",
    options: [
      { id: "a", text: "Asynchronous inference" },
      { id: "b", text: "A real-time inference endpoint" },
      { id: "c", text: "Serverless inference" },
      { id: "d", text: "Batch transform on a fixed nightly schedule" },
      { id: "e", text: "Amazon SageMaker Inference Recommender" },
      { id: "f", text: "A shadow variant on an existing endpoint" },
      { id: "g", text: "Amazon SageMaker Canvas" },
      { id: "h", text: "Queue-based inference that can scale to zero" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Asynchronous inference queues incoming requests, supports large payloads and long processing times, notifies the caller through Amazon SNS when a result is ready, and can scale instances down to zero when the queue is empty.",
    optionRationale: {
      a: "Queuing, large payload support, long processing times, and scale-to-zero between requests are exactly what asynchronous inference provides.",
      b: "Real-time endpoints cap request payload size and duration at roughly 6 MB and 60 seconds, so these requests would fail.",
      c: "Serverless inference has a smaller maximum payload and the same short request timeout, and it offers no queue for long-running work.",
      d: "Batch transform processes a whole dataset on a schedule; here individual requests arrive sporadically and each needs its own result.",
      e: "Inference Recommender benchmarks instance types and endpoint configurations; it does not serve production traffic.",
      f: "A shadow variant mirrors traffic to a candidate model for comparison and does not change payload or timeout limits.",
      g: "Canvas is a no-code interface for business users, not a programmatic inference option.",
      h: "This describes SageMaker AI Asynchronous Inference, which queues each large, long-running request, writes the result to Amazon S3, and can scale instances to zero between requests.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/async-inference.html",
    referenceLabel: "Amazon SageMaker AI: Asynchronous inference",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml14",
    domain: "ai-ml-fundamentals",
    text: "A hospital builds a classifier that screens patients for a rare but serious condition. Missing a patient who truly has the condition is far more damaging than sending a healthy patient for one extra test. Which evaluation metric should the team prioritize?",
    options: [
      { id: "a", text: "Recall, also called sensitivity or the true positive rate" },
      { id: "b", text: "Precision" },
      { id: "c", text: "Accuracy" },
      { id: "d", text: "Specificity" },
      { id: "e", text: "Root mean squared error" },
      { id: "f", text: "R-squared" },
      { id: "g", text: "Inference latency at the 99th percentile" },
      { id: "h", text: "False negative rate" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Recall is the share of truly positive cases the model catches and the false negative rate is the share it misses, so these are the metrics to optimize when false negatives, such as a missed diagnosis, are the expensive error.",
    optionRationale: {
      a: "Recall directly measures how many sick patients the model finds, which is what the hospital cannot afford to miss.",
      b: "Precision measures how many flagged patients really have the condition, which controls false alarms rather than missed cases.",
      c: "With a rare condition, a model that predicts negative for everyone can still post very high accuracy while catching nobody.",
      d: "Specificity measures how well true negatives are identified and says nothing about missed positive cases.",
      e: "Root mean squared error applies to regression, where the target is a continuous number.",
      f: "R-squared measures explained variance in a regression model, not classification quality.",
      g: "Latency is an operational service level, not a measure of predictive quality.",
      h: "The false negative rate is the share of truly sick patients the model misses; it equals one minus recall, so driving it down is the same priority.",
    },
    referenceUrl: "https://docs.aws.amazon.com/machine-learning/latest/dg/binary-model-insights.html",
    referenceLabel: "AWS docs: Binary classification model insights",
  },
  {
    id: "aif-ml15",
    domain: "ai-ml-fundamentals",
    text: "A spam filter marks a legitimate customer email as spam. In the confusion matrix for this classifier, where spam is the positive class, how is that outcome counted, and which metric does it degrade?",
    options: [
      { id: "a", text: "It is a false positive, and it lowers precision." },
      { id: "b", text: "It is a false negative, and it lowers recall." },
      { id: "c", text: "It is a true positive, and it raises precision." },
      { id: "d", text: "It is a true negative, and it raises specificity." },
      { id: "e", text: "It is a false positive, and it lowers recall." },
      { id: "f", text: "It is excluded from the confusion matrix because the label is ambiguous." },
      { id: "g", text: "It only affects the area under the ROC curve, not precision or recall." },
      { id: "h", text: "It is a Type I error, and it lowers precision." },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "The email is actually negative but was predicted positive, which is a false positive, also called a Type I error, and false positives are the term in the denominator of precision.",
    optionRationale: {
      a: "Predicting positive for an actually negative record is a false positive, and more false positives means lower precision.",
      b: "A false negative is the opposite mistake: real spam that the filter lets through.",
      c: "A true positive is real spam correctly caught, which is not what happened here.",
      d: "A true negative is a legitimate email correctly delivered, which is also not what happened.",
      e: "The classification is right but the metric is wrong; recall is reduced by false negatives, not false positives.",
      f: "Every prediction falls into one of the four confusion matrix cells; none are excluded.",
      g: "A false positive lowers precision directly, and the ROC curve is built from the same counts, so the effect is not confined to AUC.",
      h: "A Type I error is another name for a false positive, and every false positive lowers precision.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-model-quality-metrics.html",
    referenceLabel: "Amazon SageMaker AI: Model quality metrics",
  },
  {
    id: "aif-ml16",
    domain: "ai-ml-fundamentals",
    text: "Before a training job starts, an engineer sets the learning rate and the maximum tree depth; during the job, the algorithm computes the split thresholds and leaf values from the data. Which statement correctly distinguishes hyperparameters from model parameters?",
    options: [
      { id: "a", text: "Hyperparameters are set before training and control the learning process, while parameters are the values the algorithm learns from the training data." },
      { id: "b", text: "Hyperparameters are learned from the data, while parameters are chosen by the engineer." },
      { id: "c", text: "Hyperparameters and parameters are two names for the same values." },
      { id: "d", text: "Hyperparameters are used only at inference time." },
      { id: "e", text: "Parameters must be set by hand for every prediction request." },
      { id: "f", text: "Hyperparameters are the model artifacts written to Amazon S3 when training finishes." },
      { id: "g", text: "Parameters are the instance type and instance count of the training cluster." },
      { id: "h", text: "Hyperparameters are external settings given to the training job, while parameters are internal values fitted to the data." },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Hyperparameters such as learning rate, tree depth, or epoch count are configuration chosen before training, while parameters such as weights, coefficients, and split thresholds are learned during training; SageMaker AI automatic model tuning searches hyperparameter ranges for you.",
    optionRationale: {
      a: "This is the standard distinction: configuration chosen up front versus values learned from data.",
      b: "The statement reverses the two definitions.",
      c: "They are different things; conflating them is the misconception this question tests.",
      d: "Hyperparameters shape the training run itself, not the inference call.",
      e: "Learned parameters are baked into the model artifact and are not set per request.",
      f: "The trained artifact holds the learned parameters; hyperparameters are inputs to the job, not its output.",
      g: "Instance type and count are infrastructure settings for the training job, not model parameters.",
      h: "Hyperparameters are supplied from outside the model as job settings, whereas parameters such as weights and split thresholds are internal values fitted during training.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/hyperparameter-tuning/",
    referenceLabel: "What is hyperparameter tuning? (AWS)",
  },
  {
    id: "aif-ml17",
    domain: "ai-ml-fundamentals",
    text: "A utility forecasts daily electricity demand in megawatt hours and wants an error metric that penalizes a few very large misses more heavily than many small ones. Which metric should the team report?",
    options: [
      { id: "a", text: "Root mean squared error (RMSE)" },
      { id: "b", text: "Mean absolute error (MAE)" },
      { id: "c", text: "Accuracy" },
      { id: "d", text: "F1 score" },
      { id: "e", text: "Precision" },
      { id: "f", text: "Area under the ROC curve (AUC)" },
      { id: "g", text: "A confusion matrix" },
      { id: "h", text: "Mean squared error (MSE)" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "RMSE and MSE square each error before averaging, so large deviations dominate the score, which is what the team wants; MAE is the alternative regression metric that weights every error in proportion to its size.",
    optionRationale: {
      a: "Squaring the errors makes RMSE grow quickly with large misses, which is exactly the penalty the team asked for.",
      b: "MAE averages absolute errors and treats a single huge miss the same as an equivalent total of small ones.",
      c: "Accuracy counts correct labels and does not apply to a continuous target such as megawatt hours.",
      d: "The F1 score balances precision and recall for classification problems.",
      e: "Precision is a classification metric describing how many positive predictions were correct.",
      f: "AUC summarizes a classifier's ranking ability across thresholds and has no meaning for regression.",
      g: "A confusion matrix tabulates predicted versus actual class labels, which a forecast of a continuous value does not produce.",
      h: "MSE squares each error before averaging, so a few very large misses raise it far more than many small ones.",
    },
    referenceUrl: "https://docs.aws.amazon.com/machine-learning/latest/dg/regression-model-insights.html",
    referenceLabel: "AWS docs: Regression model insights",
  },
  {
    id: "aif-ml18",
    domain: "ai-ml-fundamentals",
    text: "Several teams each rebuild the same customer features, such as 30-day spend and days since last order, in slightly different ways, and the values computed for training no longer match the values computed at inference time. Which AWS capability is designed to store, share, and serve consistent features for both training and real-time inference?",
    options: [
      { id: "a", text: "Amazon SageMaker Feature Store" },
      { id: "b", text: "Amazon SageMaker Model Registry" },
      { id: "c", text: "Amazon SageMaker Ground Truth" },
      { id: "d", text: "The AWS Glue Data Catalog" },
      { id: "e", text: "Amazon SageMaker Experiments" },
      { id: "f", text: "Amazon S3 Lifecycle configuration" },
      { id: "g", text: "Amazon SageMaker Model Monitor" },
      { id: "h", text: "A feature group with online and offline stores" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "SageMaker Feature Store organizes curated features into feature groups, each with an offline store for building training datasets and an online store for low-latency lookups at inference time, which keeps both paths consistent.",
    optionRationale: {
      a: "Feature Store centralizes feature definitions and serves the same values to training and inference, removing training-serving skew.",
      b: "Model Registry versions trained models and their approval status, not feature values.",
      c: "Ground Truth produces labels for training data, not engineered features.",
      d: "The Glue Data Catalog stores table metadata for analytics and cannot serve feature values to an endpoint with low latency.",
      e: "Experiments tracks training runs and their metrics so results can be compared.",
      f: "S3 Lifecycle configuration transitions or expires objects on a schedule and has no feature semantics.",
      g: "Model Monitor detects drift on a deployed endpoint after the fact rather than preventing inconsistent features.",
      h: "A feature group with both an online and an offline store is the SageMaker Feature Store resource that serves the same feature values to training and to real-time inference.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store.html",
    referenceLabel: "Amazon SageMaker AI Feature Store",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml19",
    domain: "ai-ml-fundamentals",
    text: "A data scientist wants a visual, low-code way to import data, inspect column distributions, fix missing values, encode categorical columns, and then export the resulting transformation flow into a training pipeline. Which Amazon SageMaker AI capability does this?",
    options: [
      { id: "a", text: "Amazon SageMaker Data Wrangler" },
      { id: "b", text: "Amazon SageMaker Model Monitor" },
      { id: "c", text: "Amazon SageMaker Ground Truth" },
      { id: "d", text: "Amazon SageMaker Clarify" },
      { id: "e", text: "Amazon SageMaker automatic model tuning" },
      { id: "f", text: "Amazon Athena federated queries" },
      { id: "g", text: "Amazon Quick Sight" },
      { id: "h", text: "Amazon SageMaker Canvas" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Data Wrangler, which now also runs inside SageMaker Canvas, gives a visual interface for importing, profiling, and transforming machine learning data, and the finished flow can be exported as code or into a SageMaker Pipelines training pipeline.",
    optionRationale: {
      a: "Data Wrangler is the visual data preparation capability for machine learning data in SageMaker AI.",
      b: "Model Monitor watches deployed endpoints for drift and does not prepare training data.",
      c: "Ground Truth produces labels; it does not clean or encode columns.",
      d: "Clarify reports bias metrics and feature attributions rather than transforming data.",
      e: "Automatic model tuning searches hyperparameter ranges during training.",
      f: "Athena federated queries read data from other sources with SQL but provide no visual transformation flow to export.",
      g: "Quick Sight (formerly QuickSight) builds business intelligence dashboards and does not produce machine learning transformation flows.",
      h: "Canvas includes Data Wrangler data flows for visual profiling and transformation, and a finished flow can be exported to SageMaker Pipelines.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/data-wrangler.html",
    referenceLabel: "Prepare ML data with Amazon SageMaker Data Wrangler",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml20",
    domain: "ai-ml-fundamentals",
    text: "A business analyst with no coding experience wants to build a customer churn prediction model from a spreadsheet and generate predictions through a point-and-click interface. Which Amazon SageMaker AI capability should the analyst use?",
    options: [
      { id: "a", text: "Amazon SageMaker Canvas" },
      { id: "b", text: "Amazon SageMaker Studio notebooks" },
      { id: "c", text: "Amazon SageMaker Pipelines" },
      { id: "d", text: "Amazon SageMaker JumpStart" },
      { id: "e", text: "Amazon SageMaker Feature Store" },
      { id: "f", text: "The SageMaker AI Python SDK in a local development environment" },
      { id: "g", text: "Amazon SageMaker Model Monitor" },
      { id: "h", text: "The visual AutoML workspace in SageMaker AI" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "SageMaker Canvas is the no-code visual interface that lets business users import tabular data, build a model, and generate predictions without writing any code.",
    optionRationale: {
      a: "Canvas is aimed precisely at business analysts who want models and predictions through a visual interface.",
      b: "Studio notebooks are an integrated development environment for people who write code.",
      c: "Pipelines orchestrates repeatable machine learning workflows and is authored by engineers.",
      d: "JumpStart offers pretrained models and solution templates inside Studio; it is not a point-and-click model builder for a spreadsheet.",
      e: "Feature Store stores and serves engineered features and builds no models by itself.",
      f: "Using the Python SDK requires exactly the coding skills the analyst does not have.",
      g: "Model Monitor tracks drift on deployed endpoints rather than building a first model.",
      h: "The visual AutoML workspace in SageMaker AI is SageMaker Canvas, which builds a model from uploaded tabular data and generates predictions without any code.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/canvas.html",
    referenceLabel: "Amazon SageMaker Canvas",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-ml21",
    domain: "ai-ml-fundamentals",
    text: "A model has been in production for six months and its accuracy is slipping as customer behavior changes. Which TWO Amazon SageMaker AI capabilities directly help the team either detect this drift or govern which retrained version is approved for deployment?",
    options: [
      { id: "a", text: "Managed MLflow in Amazon SageMaker AI, to compare retrained versions and set their lifecycle stage" },
      { id: "b", text: "Amazon SageMaker Model Registry, to catalog model versions with an approval status" },
      { id: "c", text: "Amazon SageMaker Ground Truth, to draw bounding boxes on training images" },
      { id: "d", text: "The Amazon SageMaker Feature Store online store, to serve features with low latency" },
      { id: "e", text: "AWS CloudTrail, to record the AWS API calls made in the account" },
      { id: "f", text: "Amazon SageMaker Canvas, to let business users build models without code" },
      { id: "g", text: "AWS Trusted Advisor, to recommend cost and security improvements" },
      { id: "h", text: "Amazon SageMaker automatic model tuning, to search hyperparameter ranges" },
      { id: "i", text: "Amazon SageMaker Pipelines, to register a retrained model only if it passes an evaluation check" },
      { id: "j", text: "Amazon SageMaker Model Cards, to record a model's intended use, risk rating, and approval status" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Model Registry approval status, SageMaker Model Cards, an evaluation gate in SageMaker Pipelines, and MLflow lifecycle stages in SageMaker AI govern which retrained version is documented and approved for deployment. For detecting the drift itself, SageMaker Model Monitor closed to new customers on July 30, 2026, and AWS now points to its open-source SageMaker AI monitoring solutions, which compute drift metrics on captured endpoint data, log them to SageMaker AI MLflow, and alert through Amazon SNS.",
    optionRationale: {
      a: "MLflow in SageMaker AI records each retrained version's evaluation metrics and, with Model Registry sync, manages its lifecycle stage and status through aliases, which governs which version is promoted.",
      b: "Model Registry stores model versions and their approval status, which is how a retrained model is governed before deployment.",
      c: "Ground Truth labels training data and plays no part in detecting drift or approving versions.",
      d: "The online store serves feature values quickly but does not detect drift or manage versions.",
      e: "CloudTrail gives an audit trail of API activity, not model quality signals.",
      f: "Canvas is a no-code model building interface, not a monitoring or governance tool.",
      g: "Trusted Advisor checks account-level cost, performance, and security posture, not model behavior.",
      h: "Automatic model tuning improves a training run's hyperparameters; it does not observe production drift.",
      i: "A condition step in Pipelines can gate model registration and approval on evaluation metrics, which governs which retrained version moves forward.",
      j: "Model Cards document each model's intended use, risk rating, and evaluation results, with a status that reviewers set to Approved as part of governance.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html",
    referenceLabel: "Model Registration Deployment with Model Registry",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
    diagram: `flowchart LR
  A[Collect data] --> B[Prepare and label]
  B --> C[Train]
  C --> D[Evaluate]
  D --> E[Register and approve version]
  E --> F[Deploy endpoint]
  F --> G[Monitor drift]
  G --> B`,
  },
  {
    id: "aif-ml22",
    domain: "ai-ml-fundamentals",
    text: "A finance team must decide whether a new requirement needs machine learning. The rule is fixed by regulation: any transfer above 10,000 dollars requires a second approver, with no exceptions, and every decision must be explained exactly. What is the most appropriate recommendation?",
    options: [
      { id: "a", text: "Implement it as deterministic business logic, because the rule is known, fixed, and must be fully auditable, so machine learning would add cost and uncertainty with no benefit." },
      { id: "b", text: "Train a binary classifier so the system can learn the threshold from historical transfers." },
      { id: "c", text: "Use a foundation model to judge each transfer from a natural language prompt." },
      { id: "d", text: "Use an anomaly detection model to flag transfers above the threshold." },
      { id: "e", text: "Use machine learning anyway, so the system will adapt automatically to future regulations." },
      { id: "f", text: "Use a clustering model to group transfers by amount and approve each group." },
      { id: "g", text: "Use a recommendation engine to suggest what the second approver should decide." },
      { id: "h", text: "Apply the limit with a rules engine, because a fixed rule that must be explained exactly needs no learned model." },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Machine learning suits problems whose rules are unknown, complex, or changing; when a rule is explicit, stable, and must be explained exactly, deterministic code is cheaper, faster, and fully auditable.",
    optionRationale: {
      a: "A known, fixed, legally mandated threshold is a textbook case for deterministic logic rather than a learned model.",
      b: "A classifier would approximate a threshold that is already stated exactly, introducing errors a regulator would not accept.",
      c: "A foundation model adds latency, cost, and non-determinism to a decision that must be exact and repeatable.",
      d: "Anomaly detection finds unusual records; a transfer above 10,000 dollars is a defined rule, not an anomaly.",
      e: "Models do not adapt to regulations on their own; a changed regulation means a code change either way.",
      f: "Clustering produces groups with no guaranteed relation to the regulatory threshold.",
      g: "A recommendation engine ranks items for users and cannot enforce a compliance rule.",
      h: "A rules engine applies the stated limit exactly and records why each decision was made, which a learned model cannot guarantee.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/machine-learning-lens/machine-learning-lens.html",
    referenceLabel: "AWS Well-Architected Machine Learning Lens",
  },
  {
    id: "aif-ml23",
    domain: "ai-ml-fundamentals",
    text: "A mortgage processor receives scanned loan application forms as PDFs and images and needs the printed text, the handwritten entries, and the form field key-value pairs and tables extracted into structured data. Which AWS AI service is purpose-built for this?",
    options: [
      { id: "a", text: "Amazon Textract" },
      { id: "b", text: "Amazon Rekognition" },
      { id: "c", text: "Amazon Comprehend" },
      { id: "d", text: "Amazon Transcribe" },
      { id: "e", text: "Amazon Translate" },
      { id: "f", text: "Amazon Kendra" },
      { id: "g", text: "Amazon Personalize" },
      { id: "h", text: "Amazon Fraud Detector" },
      { id: "i", text: "Amazon Bedrock Data Automation" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Amazon Textract extracts printed and handwritten text together with form key-value pairs, tables, and query answers from scanned documents, and Amazon Bedrock Data Automation offers generative AI-powered extraction of the same kinds of structured data.",
    optionRationale: {
      a: "Textract is the document extraction service that returns text, form fields, and tables from scans and PDFs.",
      b: "Rekognition analyzes images and video for objects, scenes, faces, and moderation labels, not document form fields.",
      c: "Comprehend finds entities, sentiment, and topics in text that has already been extracted, so it runs after Textract rather than instead of it.",
      d: "Transcribe converts speech in audio or video into text, and there is no audio here.",
      e: "Translate converts text between languages and cannot read a scanned form.",
      f: "Kendra is an intelligent enterprise search service that answers natural-language questions over documents rather than extracting fields into structured data.",
      g: "Personalize generates recommendations from user interaction data.",
      h: "Fraud Detector scores events such as new account sign-ups or transactions for fraud risk.",
      i: "Bedrock Data Automation uses generative AI to extract text, handwriting, key-value pairs, and tables from scanned documents into structured output.",
    },
    referenceUrl: "https://aws.amazon.com/textract/",
    referenceLabel: "Amazon Textract",
  },
  {
    id: "aif-ml24",
    domain: "ai-ml-fundamentals",
    text: "A contact center stores customer support calls as audio files and wants a dashboard showing the topics customers raise and whether their language is positive or negative. Which TWO AWS services could each handle one step of this pipeline with the least custom modeling?",
    options: [
      { id: "a", text: "Amazon Transcribe, to convert the call audio into text" },
      { id: "b", text: "Amazon Comprehend, to detect sentiment and key phrases in the transcripts" },
      { id: "c", text: "Amazon Polly, to convert the transcripts back into speech" },
      { id: "d", text: "Amazon Translate, to translate the transcripts into other languages" },
      { id: "e", text: "Amazon Rekognition, to analyze the call audio for objects" },
      { id: "f", text: "Amazon Personalize, to recommend products to each caller" },
      { id: "g", text: "Amazon Lex, to build a chatbot that answers incoming calls" },
      { id: "h", text: "Amazon Fraud Detector, to score each call for fraud risk" },
      { id: "i", text: "Amazon Bedrock, to label each transcript's topics and sentiment with a foundation model" },
      { id: "j", text: "Amazon Quick Sight (formerly QuickSight), to chart the topic and sentiment results" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Transcribe turns recorded speech into text, Comprehend's sentiment and key phrase detection or a foundation model on Amazon Bedrock then pulls out the sentiment and the topics raised, and Amazon Quick Sight presents the results, so no custom model has to be trained. Comprehend's separate topic modeling feature closed to new customers on April 30, 2026, and AWS points to Bedrock models for identifying topics.",
    optionRationale: {
      a: "Speech-to-text is the required first step, and Transcribe is the AWS managed service for it.",
      b: "Comprehend's sentiment analysis and key phrase extraction surface each call's tone and main talking points from the resulting text without any model training.",
      c: "Polly performs text to speech, which is the opposite of what this pipeline needs.",
      d: "Translation is useful for multilingual content but does not produce topics or sentiment.",
      e: "Rekognition analyzes images and video, not audio recordings.",
      f: "Personalize produces product recommendations and has no role in analyzing call content.",
      g: "Lex builds conversational bots; the calls here are already recorded and simply need analysis.",
      h: "Fraud Detector scores business events for fraud risk, which is not the topic and sentiment dashboard being asked for.",
      i: "A pretrained foundation model on Bedrock can be prompted to pull topics and sentiment from each transcript with no model training.",
      j: "Quick Sight, the business intelligence capability of Amazon Quick, turns the topic and sentiment output into the visual view the contact center wants.",
    },
    referenceUrl: "https://aws.amazon.com/transcribe/",
    referenceLabel: "Amazon Transcribe",
  },
  {
    id: "aif-ml25",
    domain: "ai-ml-fundamentals",
    text: "A retailer's data science team reports that a new recommendation model raised offline precision at 10 from 0.31 to 0.38. The executive sponsor asks how the project itself will be judged. Which of the following is a business metric rather than a model metric?",
    options: [
      { id: "a", text: "Incremental revenue per active user attributed to the recommendations" },
      { id: "b", text: "Precision at 10 on the held-out test set" },
      { id: "c", text: "Area under the ROC curve" },
      { id: "d", text: "Training loss at the final epoch" },
      { id: "e", text: "Root mean squared error on the validation set" },
      { id: "f", text: "The F1 score of the ranking model" },
      { id: "g", text: "Average GPU utilization during the training job" },
      { id: "h", text: "Checkout conversion rate for shoppers shown the recommendations" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Model metrics such as precision, AUC, loss, and RMSE measure predictive quality, while business metrics such as incremental revenue per user, cost per prediction, conversion rate, retention, and customer satisfaction measure whether the project delivers value.",
    optionRationale: {
      a: "Incremental revenue per active user expresses the business outcome the project is funded to produce.",
      b: "Precision at 10 is a model quality measure computed on a test set.",
      c: "AUC summarizes how well the model ranks positives above negatives, which is a model metric.",
      d: "Training loss is an internal optimization signal, not a business outcome.",
      e: "RMSE measures prediction error on validation data and says nothing about revenue.",
      f: "The F1 score balances precision and recall and remains a model metric.",
      g: "GPU utilization is an infrastructure efficiency measure for the training job.",
      h: "Checkout conversion rate measures whether shoppers actually buy more, which is the commercial outcome the project exists to improve.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/machine-learning-lens/machine-learning-lens.html",
    referenceLabel: "AWS Well-Architected Machine Learning Lens",
  },
];
