import { Question } from "../../types.js";

export const aiSecurityGovernanceQuestions: Question[] = [
  {
    id: "aif-sec1",
    domain: "ai-security-governance",
    text: "An application on Amazon EC2 has to call one specific Amazon Bedrock foundation model. Security asks for the narrowest set of permissions that still lets the call succeed. What should the team configure?",
    options: [
      { id: "a", text: "An IAM role attached to the instance whose policy allows bedrock:InvokeModel on the ARN of that one model" },
      { id: "b", text: "An IAM role attached to the instance with the AdministratorAccess managed policy, so no call is ever blocked" },
      { id: "c", text: "An IAM user with long-lived access keys pasted into the application's configuration file" },
      { id: "d", text: "An IAM role whose policy allows bedrock:* on all resources, so future models need no policy change" },
      { id: "e", text: "A security group on the instance that allows all outbound traffic on every port" },
      { id: "f", text: "A service quota increase for Amazon Bedrock in the Region" },
      { id: "g", text: "A public read policy on the Amazon S3 bucket that holds the application code" },
      { id: "h", text: "An AWS KMS key policy that allows kms:Decrypt to every principal in the account" },
      { id: "i", text: "An instance profile whose role may call only bedrock:InvokeModel on that model's ARN" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Least privilege means granting the specific action on the specific resource. For Amazon Bedrock that is an identity-based policy allowing bedrock:InvokeModel on the ARN of the model the application actually uses, delivered to the EC2 instance through an instance profile so no long-lived credentials exist on disk. Wildcards, administrator access, and network or quota changes either grant far more than the task needs or do not grant permission at all.",
    optionRationale: {
      a: "An instance role scoped to one action on one model ARN is the textbook least-privilege grant, and the role supplies short-lived credentials automatically.",
      b: "AdministratorAccess grants every action on every service, which is the opposite of the narrowest workable permission.",
      c: "Long-lived access keys in a configuration file are a credential-management risk, and an IAM user is unnecessary when an instance role is available.",
      d: "bedrock:* on all resources permits model customisation, deletion, and every other Bedrock action, far beyond invoking one model.",
      e: "A security group controls network reachability; it grants no API permission, so the call would still be denied.",
      f: "A quota increase raises how many requests are allowed, not whether the caller is authorised to make them.",
      g: "Making a code bucket public exposes data and has no bearing on whether the application may call the model.",
      h: "A permissive KMS key policy weakens encryption controls and does not authorise a Bedrock invocation.",
      i: "An instance profile hands the application a role scoped to one action on one model, which grants exactly what the call needs and no more.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/security-iam.html",
    referenceLabel: "Identity and access management for Amazon Bedrock",
    consoleUrl: "https://console.aws.amazon.com/iam/",
    consoleLabel: "AWS IAM console",
  },
  {
    id: "aif-sec2",
    domain: "ai-security-governance",
    text: "An ML administrator wants least-privilege Amazon SageMaker AI permissions for job functions such as data scientist and MLOps engineer, built from predefined personas and ML activities rather than hand-written IAM policies. Which SageMaker AI capability does that?",
    options: [
      { id: "a", text: "Amazon SageMaker Role Manager, which builds IAM roles from personas and the activities each persona performs" },
      { id: "b", text: "Amazon SageMaker Model Monitor, which detects drift in the data a deployed endpoint receives" },
      { id: "c", text: "Amazon SageMaker Clarify, which measures bias and explains feature contributions" },
      { id: "d", text: "Amazon SageMaker Feature Store, which stores and serves curated features for training and inference" },
      { id: "e", text: "Amazon SageMaker Pipelines, which orchestrates the steps of an ML workflow" },
      { id: "f", text: "Amazon SageMaker Model Registry, which versions models and tracks their approval status" },
      { id: "g", text: "AWS Organizations service control policies, which set the maximum permissions available to member accounts" },
      { id: "h", text: "Amazon SageMaker Ground Truth, which manages human data-labeling jobs" },
      { id: "i", text: "Amazon SageMaker Role Manager, whose generated roles can still be reviewed and edited in IAM" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "SageMaker Role Manager turns a persona, such as data scientist or MLOps engineer, plus the ML activities that persona needs, into a scoped IAM role, so teams do not write machine learning IAM policies from scratch. The result is an ordinary IAM role that can still be reviewed and edited. AWS has since closed Role Manager to new customers while existing customers continue to use it, but it remains the SageMaker AI feature associated with persona-based least-privilege roles.",
    optionRationale: {
      a: "Persona-based role creation from predefined activities is exactly what Role Manager does.",
      b: "Model Monitor watches live inference data for drift and quality problems; it grants no permissions.",
      c: "Clarify reports bias metrics and feature attributions, which is a fairness and explainability tool.",
      d: "Feature Store is a repository for engineered features, unrelated to access control.",
      e: "Pipelines automates the sequence of ML steps; it does not define who may run them.",
      f: "Model Registry catalogues model versions and approval states, not user permissions.",
      g: "Service control policies cap what an account may do but never grant a persona its permissions, and they operate at account level rather than per job function.",
      h: "Ground Truth coordinates human labeling workforces and has nothing to do with IAM personas.",
      i: "Role Manager produces ordinary IAM roles from personas and their ML activities, so the result stays reviewable and editable in IAM like any other role.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/role-manager.html",
    referenceLabel: "Amazon SageMaker Role Manager",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-sec3",
    domain: "ai-security-governance",
    text: "An insurer trains a model in Amazon SageMaker AI on claims data held in Amazon S3. The security team requires the data to be encrypted both while it is stored and while it moves during training. Which TWO measures each contribute to meeting that requirement?",
    options: [
      { id: "a", text: "Encrypt the training bucket with server-side encryption using an AWS KMS customer managed key" },
      { id: "b", text: "Require TLS for every request to the bucket and the training job, so data in transit is encrypted" },
      { id: "c", text: "Enable S3 Versioning so that earlier copies of each object are retained" },
      { id: "d", text: "Compress the training data with gzip before uploading it" },
      { id: "e", text: "Enable S3 Transfer Acceleration so uploads complete faster" },
      { id: "f", text: "Run the training job on Spot Instances to lower its cost" },
      { id: "g", text: "Publish the training job's metrics to Amazon CloudWatch" },
      { id: "h", text: "Copy the data to the training instance's local disk before the job starts" },
      { id: "i", text: "Encrypt the training job's attached storage volumes with an AWS KMS key" },
      { id: "j", text: "Enable inter-container traffic encryption for distributed training" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Encryption at rest and in transit are separate controls, and each applies at more than one point: at rest, SSE-KMS protects the objects in the bucket and a KMS key protects the training job's storage volumes; in transit, TLS protects the transfer from Amazon S3 and inter-container traffic encryption protects data exchanged between training instances. The other options change durability, speed, or cost and leave the data no better protected.",
    optionRationale: {
      a: "SSE-KMS with a customer managed key encrypts the objects at rest in the bucket, and the key policy gives the customer an auditable say over who can decrypt.",
      b: "Requiring TLS encrypts the data as it moves between the bucket and the training job, and it can be enforced rather than merely recommended.",
      c: "Versioning protects against accidental overwrite and deletion; an unencrypted object simply gains unencrypted versions.",
      d: "Compression reduces size. It is not encryption, and the content remains readable to anyone who obtains the file.",
      e: "Transfer Acceleration routes uploads over the AWS edge network for speed; it changes nothing about encryption.",
      f: "Spot Instances reduce training cost and have no security effect.",
      g: "CloudWatch metrics tell you how the job performed; they do not protect the data.",
      h: "Copying data onto a local disk moves it without adding any protection, and may spread it further.",
      i: "Data the job copies onto its ML storage volumes stays encrypted at rest there when the volumes use a KMS key.",
      j: "Inter-container traffic encryption protects data exchanged between the training instances as it moves during a distributed job.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/encryption-at-rest.html",
    referenceLabel: "Protect data at rest using encryption (Amazon SageMaker AI)",
    consoleUrl: "https://console.aws.amazon.com/kms/",
    consoleLabel: "AWS KMS console",
  },
  {
    id: "aif-sec4",
    domain: "ai-security-governance",
    text: "Before a dataset already sitting in Amazon S3 is used to fine-tune a model, the governance team wants an automated scan that reports which objects in the bucket contain personal data such as names, card numbers, and national identifiers. Which AWS service is purpose-built for that?",
    options: [
      { id: "a", text: "Amazon Macie, which discovers and classifies sensitive data in Amazon S3" },
      { id: "b", text: "Amazon GuardDuty, which analyses account and network telemetry for signs of malicious activity" },
      { id: "c", text: "Amazon Inspector, which scans workloads for known software vulnerabilities" },
      { id: "d", text: "AWS Config, which records resource configurations and evaluates them against rules" },
      { id: "e", text: "AWS CloudTrail, which records the API calls made in the account" },
      { id: "f", text: "AWS Artifact, which provides AWS compliance reports and agreements" },
      { id: "g", text: "Amazon S3 Storage Lens, which reports storage usage and activity trends across buckets" },
      { id: "h", text: "AWS Secrets Manager, which stores and rotates application credentials" },
      { id: "i", text: "Amazon Macie, running a sensitive data discovery job with managed data identifiers" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Amazon Macie uses managed and custom data identifiers to scan objects in Amazon S3 and report where sensitive data, including personally identifiable information, is stored. Running Macie over a candidate training set before fine-tuning is the standard way to find personal data that should be removed, masked, or brought under a stricter access policy first.",
    optionRationale: {
      a: "Sensitive data discovery in S3 is precisely what Macie is for, and its findings name the bucket and object.",
      b: "GuardDuty looks for threat activity such as compromised credentials; it does not classify the contents of objects.",
      c: "Inspector reports software vulnerabilities and unintended network exposure in workloads, not personal data in files.",
      d: "Config records how resources are configured, for example whether a bucket blocks public access, not what the objects contain.",
      e: "CloudTrail records who called which API; it says nothing about the data inside a bucket.",
      f: "Artifact is a download portal for AWS's own audit reports and agreements.",
      g: "Storage Lens summarises storage metrics such as object counts and request rates, not data sensitivity.",
      h: "Secrets Manager holds credentials for applications; it does not scan datasets.",
      i: "A Macie sensitive data discovery job inspects the bucket's objects with managed data identifiers for names, card numbers, and national IDs, and reports each finding by object.",
    },
    referenceUrl: "https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html",
    referenceLabel: "What is Amazon Macie?",
    consoleUrl: "https://console.aws.amazon.com/macie/",
    consoleLabel: "Amazon Macie console",
  },
  {
    id: "aif-sec5",
    domain: "ai-security-governance",
    text: "A bank's application runs in a private subnet with no internet gateway and no NAT gateway, and it must call Amazon Bedrock without the traffic traversing the public internet. What should the team configure?",
    options: [
      { id: "a", text: "An interface VPC endpoint for Amazon Bedrock, powered by AWS PrivateLink, so calls stay on the AWS network" },
      { id: "b", text: "A NAT gateway in a public subnet so the private subnet can reach the public Bedrock endpoint" },
      { id: "c", text: "An internet gateway attached to the VPC with a default route from the private subnet" },
      { id: "d", text: "A gateway VPC endpoint, which is the endpoint type offered for Amazon S3 and Amazon DynamoDB" },
      { id: "e", text: "An AWS Site-to-Site VPN connection between the VPC and the on-premises data centre" },
      { id: "f", text: "An Amazon CloudFront distribution placed in front of the Bedrock endpoint" },
      { id: "g", text: "A security group rule that allows outbound HTTPS to 0.0.0.0/0" },
      { id: "h", text: "AWS Direct Connect from the VPC to the Bedrock service endpoint" },
      { id: "i", text: "AWS PrivateLink, giving the subnet a private IP entry point to the Bedrock API" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "AWS PrivateLink creates an interface VPC endpoint: an elastic network interface with a private IP address inside the subnet that represents the service. Calls to Amazon Bedrock then resolve to that private address and never leave the AWS network, which satisfies a policy that forbids internet transit and works in a subnet with no internet path at all.",
    optionRationale: {
      a: "An interface endpoint backed by PrivateLink is the supported way to reach Bedrock privately from a VPC.",
      b: "A NAT gateway still sends the request out to the public service endpoint, which is what the policy forbids.",
      c: "An internet gateway exposes the subnet to the internet, moving in the opposite direction from the requirement.",
      d: "Gateway endpoints exist only for Amazon S3 and DynamoDB; Bedrock is reached through an interface endpoint.",
      e: "Site-to-Site VPN connects the VPC to an on-premises network and does nothing for reaching an AWS service privately.",
      f: "CloudFront is a content delivery network for distributing content to clients, not a private path to an API.",
      g: "An outbound rule to the whole internet would only matter if there were an internet path, and it provides no privacy.",
      h: "Direct Connect is a dedicated link between a data centre and AWS, not a connection between a VPC and a service.",
      i: "PrivateLink places an endpoint network interface with a private IP address in the subnet, so Bedrock calls stay on the AWS network.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/usingVPC.html",
    referenceLabel: "Protect your data using Amazon VPC and AWS PrivateLink (Amazon Bedrock)",
    consoleUrl: "https://console.aws.amazon.com/vpc/",
    consoleLabel: "Amazon VPC console",
  },
  {
    id: "aif-sec6",
    domain: "ai-security-governance",
    text: "A legal team asks whether the prompts and completions its staff send to a third-party foundation model on Amazon Bedrock could end up in that model's future training data. Which statement is correct?",
    options: [
      { id: "a", text: "Amazon Bedrock does not use customer prompts or model responses to train the base foundation models, and it does not share them with the model providers" },
      { id: "b", text: "Prompts are added to the provider's next training run unless the customer opts out in the Bedrock console" },
      { id: "c", text: "Prompts are used for training whenever the model is invoked under on-demand, pay-per-token pricing" },
      { id: "d", text: "Fine-tuning data supplied by the customer is merged into the shared base model and becomes available to other customers" },
      { id: "e", text: "Prompt content is used for training but is anonymised first, so no agreement with the provider is needed" },
      { id: "f", text: "Amazon Bedrock stores every prompt in an AWS-owned public bucket so that usage can be audited" },
      { id: "g", text: "Prompts are used for training only when the response exceeds the model's default output length" },
      { id: "h", text: "Model providers have no access to the accounts where Bedrock runs their models, so they never receive customer prompts" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Amazon Bedrock does not use a customer's inputs or outputs to train the underlying foundation models, and that data is not shared with the third-party model providers. When a customer fine-tunes a model, Bedrock creates a private copy of the base model in the customer's account; the tuned weights are the customer's and are not folded back into the shared base model.",
    optionRationale: {
      a: "This is the stated Bedrock privacy position: customer inputs and outputs do not train the base models and are not passed to providers.",
      b: "There is no opt-out to configure, because prompts are not used for base model training in the first place.",
      c: "Pricing model has no bearing on data use; on-demand invocations are treated the same way.",
      d: "Fine-tuning produces a private copy of the model that only the customer can use; it does not change the shared base model.",
      e: "Anonymisation is irrelevant here, since the prompts are not used for training at all.",
      f: "Nothing is published to a public bucket. Customers who want a record enable model invocation logging to their own destination.",
      g: "Response length has no connection to how data is used.",
      h: "Bedrock hosts each provider's models in AWS-operated model deployment accounts that the provider cannot access, so prompts and completions never reach the provider.",
    },
    referenceUrl: "https://aws.amazon.com/bedrock/security-compliance/",
    referenceLabel: "Amazon Bedrock security and privacy (AWS)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-sec7",
    domain: "ai-security-governance",
    text: "A company builds a customer-facing application on Amazon Bedrock. Under the AWS shared responsibility model, which TWO tasks are the customer's responsibility rather than AWS's?",
    options: [
      { id: "a", text: "Deciding which data may be placed in a prompt, and classifying that data before it is sent" },
      { id: "b", text: "Writing the IAM policies that decide which principals may invoke the model" },
      { id: "c", text: "Patching the operating systems of the hosts that run the managed inference fleet" },
      { id: "d", text: "Providing physical security for the data centres where the service runs" },
      { id: "e", text: "Replacing failed hardware in the racks that serve the model" },
      { id: "f", text: "Undergoing the SOC 2 audit of the underlying AWS infrastructure" },
      { id: "g", text: "Operating the network backbone that connects AWS Regions and Availability Zones" },
      { id: "h", text: "Maintaining the power and cooling systems of each Availability Zone" },
      { id: "i", text: "Configuring guardrails that filter what the model returns to the application's users" },
      { id: "j", text: "Setting encryption and retention for the logs and data the application stores" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "AWS is responsible for security of the cloud, which for a managed service such as Amazon Bedrock includes the facilities, hardware, network, and the software that runs the service. The customer is responsible for security in the cloud: what data they send and how it is classified, encrypted, and retained, who is allowed to call the service, and which guardrails filter its output.",
    optionRationale: {
      a: "Choosing and classifying the data that goes into a prompt is entirely a customer decision; AWS cannot make it.",
      b: "Access control through IAM is the customer's configuration of the service, which is squarely security in the cloud.",
      c: "Patching the hosts behind a managed service is AWS's responsibility; customers never see those instances.",
      d: "Physical data centre security is the classic AWS-side responsibility.",
      e: "Hardware replacement in AWS facilities is performed by AWS.",
      f: "AWS undergoes the audits of its infrastructure; the customer's role is to obtain the resulting report, through AWS Artifact.",
      g: "The global network infrastructure is operated by AWS.",
      h: "Facility power and cooling belong to AWS's security of the cloud.",
      i: "Choosing and configuring content controls such as guardrails is part of the customer's security in the cloud for the application they build.",
      j: "Encryption keys, log retention, and storage settings for the customer's own data are configured by the customer, not by AWS.",
    },
    referenceUrl: "https://aws.amazon.com/compliance/shared-responsibility-model/",
    referenceLabel: "Shared Responsibility Model (AWS)",
  },
  {
    id: "aif-sec8",
    domain: "ai-security-governance",
    text: "An ML team has dozens of datasets spread across Amazon S3 and cannot tell which tables and columns exist or what format each one uses. They want a central technical metadata store that crawlers can populate automatically and that ETL and query engines can read. Which service provides it?",
    options: [
      { id: "a", text: "The AWS Glue Data Catalog, a central metadata repository of databases, tables, and schemas that crawlers can populate" },
      { id: "b", text: "Amazon S3 Inventory, which produces a scheduled report listing the objects in a bucket" },
      { id: "c", text: "Amazon SageMaker Feature Store, which stores curated features for training and inference" },
      { id: "d", text: "AWS CloudTrail, which records the API activity in the account" },
      { id: "e", text: "Amazon CloudWatch Logs, which stores and searches application log events" },
      { id: "f", text: "AWS Config, which records the configuration history of AWS resources" },
      { id: "g", text: "AWS Secrets Manager, which stores and rotates credentials" },
      { id: "h", text: "Amazon S3 Storage Lens, which reports storage usage and activity trends" },
      { id: "i", text: "The AWS Glue Data Catalog, which acts as a Hive-compatible metastore for Athena and EMR" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "The AWS Glue Data Catalog holds the technical metadata for a data estate: databases, tables, columns, data types, partitions, and the location of the underlying files. Crawlers infer that schema from the data and keep the catalogue current, and services such as AWS Glue ETL, Amazon Athena, and Amazon EMR read it. A populated catalogue is the starting point for data governance, because you cannot control or trace data you cannot enumerate.",
    optionRationale: {
      a: "A crawler-populated catalogue of databases, tables, and schemas shared across analytics services is exactly the Glue Data Catalog.",
      b: "S3 Inventory lists objects and a few object-level attributes; it does not describe table schemas or column types.",
      c: "Feature Store holds engineered feature values for models, which is a narrower purpose than cataloguing the whole data estate.",
      d: "CloudTrail records who called which API, not the structure of the data.",
      e: "CloudWatch Logs stores log events from applications and services, not dataset schemas.",
      f: "Config tracks the configuration of AWS resources such as buckets, not the schema of the data inside them.",
      g: "Secrets Manager stores credentials and has no role in describing datasets.",
      h: "Storage Lens reports storage metrics and trends rather than schema metadata.",
      i: "The Glue Data Catalog is the shared, Apache Hive-compatible metastore from which query and ETL engines read table definitions that crawlers keep current.",
    },
    referenceUrl: "https://docs.aws.amazon.com/glue/latest/dg/catalog-and-crawler.html",
    referenceLabel: "Data discovery and cataloging in AWS Glue",
    consoleUrl: "https://console.aws.amazon.com/glue/",
    consoleLabel: "AWS Glue console",
  },
  {
    id: "aif-sec9",
    domain: "ai-security-governance",
    text: "An auditor asks the ML team to show, for a model now serving production traffic, exactly which dataset version, processing job, and training job produced it. Which practice answers that question directly?",
    options: [
      { id: "a", text: "Lineage tracking, which records the datasets, processing steps, and jobs that produced each model artefact, as Amazon SageMaker ML Lineage Tracking does automatically" },
      { id: "b", text: "Amazon SageMaker Model Monitor schedules, which compare live traffic against a baseline to detect drift" },
      { id: "c", text: "Amazon S3 Versioning on the data bucket alone, which keeps object versions but records nothing about the jobs that used them" },
      { id: "d", text: "Automatic model tuning, which searches hyperparameter combinations for the best objective metric" },
      { id: "e", text: "Provisioned Throughput, which reserves inference capacity for a model" },
      { id: "f", text: "An Amazon CloudFront distribution that caches the model's responses at the edge" },
      { id: "g", text: "Increasing the training instance size so that jobs finish sooner" },
      { id: "h", text: "Amazon Bedrock Guardrails, which filter harmful content in prompts and responses" },
      { id: "i", text: "Provenance records linking the deployed model back to its source data and the jobs that built it" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Lineage is the recorded chain from source data through processing and training to a specific model artefact and endpoint. SageMaker creates lineage entities for trial components, datasets, and models as jobs run, so a question such as \"which data produced this model?\" is answered from records rather than from memory. The same discipline underpins source citation in retrieval systems and the documentation of data origins that auditors expect.",
    optionRationale: {
      a: "Recording the datasets and jobs behind each artefact is the definition of lineage tracking, and it is what an auditor's question needs.",
      b: "Model Monitor reports on the data a deployed endpoint sees now; it cannot say what produced the model.",
      c: "Versioning preserves object copies but stores no link between an object version and the job that consumed it.",
      d: "Automatic model tuning selects hyperparameters; it is an optimisation technique, not a provenance record.",
      e: "Provisioned Throughput is a capacity purchase for inference and holds no metadata about training.",
      f: "CloudFront caching affects delivery latency, not traceability of a model's inputs.",
      g: "A larger instance shortens training time and records nothing about provenance.",
      h: "Guardrails screen content at inference time and say nothing about which data trained the model.",
      i: "Model provenance, recorded as lineage, traces an artifact back through its training and processing jobs to the exact data used, which is what the auditor asked for.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/lineage-tracking.html",
    referenceLabel: "Amazon SageMaker ML Lineage Tracking",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-sec10",
    domain: "ai-security-governance",
    text: "Overnight, an IAM role used by a training pipeline begins making API calls from an unfamiliar location and in a pattern the account has never seen before. Which AWS service is designed to detect that kind of activity continuously, from sources such as CloudTrail events, DNS logs, and VPC flow logs?",
    options: [
      { id: "a", text: "Amazon GuardDuty, a managed threat detection service that analyses account and network telemetry" },
      { id: "b", text: "Amazon Inspector, which scans EC2 instances, container images, and Lambda functions for known vulnerabilities" },
      { id: "c", text: "Amazon Macie, which discovers and classifies sensitive data in Amazon S3" },
      { id: "d", text: "AWS Artifact, which distributes AWS audit reports and agreements" },
      { id: "e", text: "AWS Trusted Advisor, which checks an account against best practices in six categories" },
      { id: "f", text: "AWS Config, which records resource configuration changes and evaluates rules" },
      { id: "g", text: "AWS Audit Manager, which collects evidence and maps it to compliance frameworks" },
      { id: "h", text: "AWS KMS, which creates and controls encryption keys" },
      { id: "i", text: "Amazon GuardDuty, which uses machine learning and threat intelligence to generate findings" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "GuardDuty continuously consumes CloudTrail management and data events, VPC flow logs, and DNS query logs, and applies threat intelligence and anomaly detection to them. Credential use from an unusual location, or an unusual API pattern for a role, produces a finding without the customer writing any detection logic. It is the detective control in an ML account, alongside preventive controls such as IAM and encryption.",
    optionRationale: {
      a: "Continuous threat detection from account and network telemetry, including anomalous credential use, is GuardDuty's purpose.",
      b: "Inspector finds software vulnerabilities and network exposure; it does not analyse API behaviour for threats.",
      c: "Macie classifies sensitive data at rest and does not evaluate credential activity.",
      d: "Artifact is a document portal, with no detection capability at all.",
      e: "Trusted Advisor performs best-practice checks on configuration and usage rather than detecting live threats.",
      f: "Config records configuration state and rule compliance; it does not flag anomalous API behaviour as a threat.",
      g: "Audit Manager gathers evidence for audits, which is a compliance workflow, not real-time detection.",
      h: "KMS manages keys and enforces key policies; it does not detect suspicious account activity.",
      i: "GuardDuty applies anomaly detection and threat intelligence to CloudTrail, DNS, and flow log data, which is how it flags credential misuse like this.",
    },
    referenceUrl: "https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html",
    referenceLabel: "What is Amazon GuardDuty?",
    consoleUrl: "https://console.aws.amazon.com/guardduty/",
    consoleLabel: "Amazon GuardDuty console",
  },
  {
    id: "aif-sec11",
    domain: "ai-security-governance",
    text: "A team packages its training and inference code as container images in Amazon ECR. Security asks for continuous scanning of those images for known software vulnerabilities (CVEs) in the operating system and language packages. Which service does that?",
    options: [
      { id: "a", text: "Amazon Inspector, which continuously scans container images, EC2 instances, and Lambda functions for known vulnerabilities" },
      { id: "b", text: "Amazon GuardDuty, which analyses account telemetry for malicious or unauthorised behaviour" },
      { id: "c", text: "Amazon Macie, which discovers and classifies sensitive data in Amazon S3" },
      { id: "d", text: "AWS Shield, which protects applications against distributed denial of service attacks" },
      { id: "e", text: "AWS WAF, which filters HTTP requests against configurable rules" },
      { id: "f", text: "AWS Config, which records configuration changes of AWS resources" },
      { id: "g", text: "AWS CloudTrail, which records the API calls made in the account" },
      { id: "h", text: "AWS Secrets Manager, which stores and rotates credentials" },
      { id: "i", text: "Amazon ECR enhanced scanning, which rescans images as new CVEs are published" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Amazon Inspector performs automated, continuous vulnerability management. When enhanced scanning is enabled for Amazon ECR, Inspector scans images on push and rescans them as new CVEs are published, so an ML image built months ago is re-evaluated without anyone rebuilding it. Findings carry a severity score and the fixed package version, which is what a remediation backlog needs.",
    optionRationale: {
      a: "Continuous CVE scanning of container images is one of Inspector's core scan types.",
      b: "GuardDuty detects threat activity from telemetry; it does not inventory software packages for CVEs.",
      c: "Macie classifies data at rest and does not examine container images.",
      d: "Shield mitigates DDoS attacks against endpoints, not vulnerabilities inside an image.",
      e: "AWS WAF inspects web requests at the application layer, which has nothing to do with image contents.",
      f: "Config tracks whether resources match a desired configuration, not which CVEs a package carries.",
      g: "CloudTrail is an audit log of API activity, not a vulnerability scanner.",
      h: "Secrets Manager stores credentials; it performs no scanning.",
      i: "ECR enhanced scanning is powered by Amazon Inspector and continuously rescans repository images for operating system and language package vulnerabilities.",
    },
    referenceUrl: "https://docs.aws.amazon.com/inspector/latest/user/scanning-ecr.html",
    referenceLabel: "Scanning Amazon ECR container images with Amazon Inspector",
    consoleUrl: "https://console.aws.amazon.com/inspector/v2/",
    consoleLabel: "Amazon Inspector console",
  },
  {
    id: "aif-sec12",
    domain: "ai-security-governance",
    text: "A company runs ML workloads in several AWS accounts. Findings arrive separately from GuardDuty, Inspector, and Macie, and the CISO wants one place that aggregates them across accounts and also scores the environment against standards such as the AWS Foundational Security Best Practices and CIS benchmarks. Which service provides that view?",
    options: [
      { id: "a", text: "AWS Security Hub, which aggregates findings from AWS security services and runs automated standards checks" },
      { id: "b", text: "Amazon GuardDuty, which produces its own threat findings but does not aggregate other services' findings or run standards checks" },
      { id: "c", text: "AWS Audit Manager, which collects evidence for audits against compliance frameworks" },
      { id: "d", text: "AWS Artifact, which provides AWS's own audit reports for download" },
      { id: "e", text: "Amazon CloudWatch dashboards, which chart metrics published by AWS services" },
      { id: "f", text: "AWS Organizations, which centrally manages accounts and applies service control policies" },
      { id: "g", text: "AWS Control Tower, which sets up and governs a multi-account landing zone" },
      { id: "h", text: "AWS Trusted Advisor, which checks an account against best practices in six categories" },
      { id: "i", text: "AWS Security Hub CSPM, which consolidates findings and scores accounts against standards" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Security Hub is the aggregation point for security findings. It ingests findings from GuardDuty, Inspector, Macie, and partner products in a common format, deduplicates and prioritises them across accounts and Regions, and continuously scores the environment against security standards. It is the single pane of glass the question describes; the individual detectors remain the source of the findings.",
    optionRationale: {
      a: "Cross-account aggregation of findings plus automated standards checks is exactly what Security Hub does.",
      b: "GuardDuty is one of the sources Security Hub aggregates, and it runs no standards checks of its own.",
      c: "Audit Manager builds evidence packages for an auditor against a framework; it is not a live security findings console.",
      d: "Artifact distributes AWS's compliance documents and has no view of the customer's findings.",
      e: "CloudWatch dashboards visualise metrics, not normalised security findings from multiple services.",
      f: "Organizations manages account structure and permission guardrails; it does not collect security findings.",
      g: "Control Tower provisions and governs accounts with controls, but the aggregated findings view still comes from Security Hub.",
      h: "Trusted Advisor performs best-practice checks across six categories and does not ingest findings from GuardDuty, Inspector, or Macie.",
      i: "Security Hub CSPM ingests findings from GuardDuty, Inspector, and Macie across accounts and runs standards such as AWS Foundational Security Best Practices and the CIS benchmark.",
    },
    referenceUrl: "https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html",
    referenceLabel: "Introduction to AWS Security Hub CSPM",
    consoleUrl: "https://console.aws.amazon.com/securityhub/",
    consoleLabel: "AWS Security Hub console",
  },
  {
    id: "aif-sec13",
    domain: "ai-security-governance",
    text: "An agent built on Amazon Bedrock can call an internal API that issues customer refunds. A guardrail already screens prompts and responses. Which additional control best limits the damage if a prompt injection still succeeds?",
    options: [
      { id: "a", text: "Scope the agent's execution role to that single refund operation and require an explicit human confirmation before the action is carried out" },
      { id: "b", text: "Raise the model's temperature so that an injected instruction is followed less predictably" },
      { id: "c", text: "Increase the maximum response length so that answers are never truncated" },
      { id: "d", text: "Encrypt the stored conversation history with an AWS KMS customer managed key" },
      { id: "e", text: "Move the system prompt from the application code into an Amazon S3 object" },
      { id: "f", text: "Switch to a smaller, cheaper model so that less context is processed" },
      { id: "g", text: "Buy Provisioned Throughput for the model so that refund requests are never throttled" },
      { id: "h", text: "Put an Amazon CloudFront distribution in front of the application" },
      { id: "i", text: "Validate each refund in the API itself against business limits, such as amount caps" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Prompt injection cannot be eliminated by filtering alone, so an agent's security is layered: screen the input, then assume screening may fail and make the consequence survivable with a narrowly scoped execution role, business-rule checks enforced by the refund API itself, and human confirmation before irreversible actions. The other options change cost, sampling, or delivery and leave the blast radius untouched.",
    optionRationale: {
      a: "Least privilege on the agent's role plus human approval of the consequential action bounds the damage of any successful injection.",
      b: "A higher temperature only makes output more random; the injected instruction can still be obeyed, and unpredictability is not a control.",
      c: "Output length has no bearing on whether an instruction hidden in the input is followed.",
      d: "Encrypting stored history protects the log if it is stolen, but it does nothing about an action the agent takes now.",
      e: "Where the system prompt is stored does not stop a model from being argued out of following it.",
      f: "A smaller model is not inherently more resistant to injection, and may well be less resistant.",
      g: "Provisioned Throughput reserves capacity. It is a performance purchase with no security effect.",
      h: "CloudFront caches and delivers content; it does not sit between the agent and the refund API.",
      i: "Checks enforced by the refund service, whatever the agent asks for, cap what a hijacked agent can do.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-injection.html",
    referenceLabel: "Prompt injection security (Amazon Bedrock)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-sec14",
    domain: "ai-security-governance",
    text: "A prospective customer's security questionnaire asks for AWS's latest SOC 2 Type II report and its ISO 27001 certificate, covering the infrastructure the company's AI workload runs on. Where does an AWS account holder obtain those documents?",
    options: [
      { id: "a", text: "AWS Artifact, the self-service portal for AWS compliance reports, certifications, and agreements" },
      { id: "b", text: "AWS Audit Manager, which collects evidence about the customer's own workloads" },
      { id: "c", text: "AWS Config, which records the configuration of the customer's resources" },
      { id: "d", text: "AWS Security Hub, which aggregates security findings across accounts" },
      { id: "e", text: "AWS Trusted Advisor, which checks the account against best practices" },
      { id: "f", text: "Amazon Inspector, which reports software vulnerabilities in workloads" },
      { id: "g", text: "AWS CloudTrail, which records API activity in the account" },
      { id: "h", text: "Amazon Macie, which reports sensitive data found in Amazon S3" },
      { id: "i", text: "The Reports page of AWS Artifact in the AWS Management Console" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "AWS Artifact is where AWS publishes its third-party audit artefacts: SOC 1, SOC 2, and SOC 3 reports, ISO certificates, PCI documents, and agreements such as the AWS GDPR data processing addendum. The reports cover AWS's side of the shared responsibility model, so they evidence the infrastructure, while the customer still has to evidence their own configuration and processes separately.",
    optionRationale: {
      a: "Artifact is the on-demand download portal for AWS audit reports and certifications.",
      b: "Audit Manager assesses the customer's workloads and produces the customer's evidence, not AWS's certificates.",
      c: "Config records configuration history for the customer's resources and issues no compliance reports about AWS.",
      d: "Security Hub aggregates findings about the customer's environment, not AWS's audit documents.",
      e: "Trusted Advisor reports best-practice checks on the account and has no audit reports.",
      f: "Inspector reports vulnerabilities in the customer's workloads.",
      g: "CloudTrail records the account's API activity; it holds no AWS certifications.",
      h: "Macie reports on sensitive data in the customer's buckets.",
      i: "AWS Artifact Reports is where account holders download AWS's SOC reports and ISO certificates on demand.",
    },
    referenceUrl: "https://docs.aws.amazon.com/artifact/latest/ug/what-is-aws-artifact.html",
    referenceLabel: "What is AWS Artifact?",
    consoleUrl: "https://console.aws.amazon.com/artifact/",
    consoleLabel: "AWS Artifact console",
  },
  {
    id: "aif-sec15",
    domain: "ai-security-governance",
    text: "An ML platform team must show an external auditor that its own AWS environment meets a framework such as ISO 27001. They want AWS to collect the supporting evidence from their accounts continuously, map it to the framework's controls, and assemble an assessment report. Which service is built for that?",
    options: [
      { id: "a", text: "AWS Audit Manager, which runs framework-based assessments, collects evidence automatically, and produces assessment reports" },
      { id: "b", text: "AWS Artifact, which supplies AWS's own audit reports rather than evidence about the customer's workloads" },
      { id: "c", text: "AWS Config, which evaluates resource configuration against rules but does not assemble an auditor-ready assessment report" },
      { id: "d", text: "Amazon CloudWatch, which collects metrics and log events from workloads" },
      { id: "e", text: "AWS CloudTrail, which records the API calls made in the account" },
      { id: "f", text: "AWS Trusted Advisor, which checks the account against best practices in six categories" },
      { id: "g", text: "Amazon GuardDuty, which detects threats from account and network telemetry" },
      { id: "h", text: "AWS Control Tower, which sets up and governs a multi-account environment" },
      { id: "i", text: "AWS Audit Manager, assessing the accounts with a prebuilt standard framework" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Audit Manager turns a framework into an assessment: it maps controls to AWS data sources, gathers evidence from CloudTrail, Config, Security Hub, and API calls on a schedule, and packages the result as a report with the evidence attached. That is the difference between the services here, several of which produce the raw signals that Audit Manager consumes.",
    optionRationale: {
      a: "Continuous evidence collection mapped to a framework's controls, ending in an assessment report, is Audit Manager's purpose.",
      b: "Artifact provides AWS's audits of AWS, which is the other half of the shared responsibility model.",
      c: "Config rules and conformance packs report compliant and non-compliant resources; they do not gather multi-source evidence into an assessment.",
      d: "CloudWatch collects operational telemetry, which may become evidence but is not an audit workflow.",
      e: "CloudTrail is one of the evidence sources Audit Manager reads, not the assessment tool itself.",
      f: "Trusted Advisor's checks are best-practice advice, not a framework-mapped assessment.",
      g: "GuardDuty detects threats and does not manage audits.",
      h: "Control Tower governs how accounts are provisioned and controlled; the audit evidence workflow is Audit Manager's.",
      i: "Audit Manager's prebuilt frameworks, including ISO 27001, map controls to evidence it gathers automatically and produce an assessment report.",
    },
    referenceUrl: "https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html",
    referenceLabel: "What is AWS Audit Manager?",
    consoleUrl: "https://console.aws.amazon.com/auditmanager/",
    consoleLabel: "AWS Audit Manager console",
  },
  {
    id: "aif-sec16",
    domain: "ai-security-governance",
    text: "A governance lead wants ongoing automated checking of the AWS account itself, for example that the buckets holding training data are not publicly accessible and that the account follows AWS best practices, instead of a manual review once a quarter. Which TWO services provide that continuous checking?",
    options: [
      { id: "a", text: "AWS Config rules, which continuously evaluate resource configurations and flag non-compliant resources" },
      { id: "b", text: "AWS Trusted Advisor, which continuously inspects the account against best-practice checks for cost optimization, performance, security, fault tolerance, service limits, and operational excellence" },
      { id: "c", text: "AWS Artifact, which is a download portal for AWS audit reports" },
      { id: "d", text: "Amazon SageMaker Model Monitor, which checks a deployed endpoint's data for drift" },
      { id: "e", text: "AWS KMS, which creates and controls encryption keys" },
      { id: "f", text: "Amazon CloudFront, which caches content at edge locations" },
      { id: "g", text: "AWS Cost Explorer, which analyses spending trends over time" },
      { id: "h", text: "Amazon EventBridge, which routes events between AWS services" },
      { id: "i", text: "AWS Security Hub CSPM, which evaluates the account against security standards" },
      { id: "j", text: "IAM Access Analyzer, which flags buckets shared publicly or outside the account" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Continuous compliance needs something that watches configuration as it changes: AWS Config evaluates each change against rules such as the check for S3 public read access, Trusted Advisor and Security Hub CSPM run ongoing best-practice and standards checks, and IAM Access Analyzer flags buckets exposed publicly or outside the account. All of them run continuously, which is what separates them from a point-in-time review.",
    optionRationale: {
      a: "Config rules evaluate resources as they change and report compliant and non-compliant resources over time.",
      b: "Trusted Advisor continuously checks the account against AWS best practices, including security checks such as public access.",
      c: "Artifact hands over AWS's audit documents; it evaluates nothing in the customer's account.",
      d: "Model Monitor watches the data an endpoint receives, which is model quality rather than account compliance.",
      e: "KMS manages keys. It enforces key policies but performs no compliance evaluation.",
      f: "CloudFront is a content delivery network with no compliance role.",
      g: "Cost Explorer analyses spend and cannot tell you whether a bucket is public.",
      h: "EventBridge routes events, including compliance events from Config, but it does not evaluate anything itself.",
      i: "Security Hub CSPM continuously evaluates resources against standards such as AWS Foundational Security Best Practices, including controls for public S3 buckets.",
      j: "IAM Access Analyzer continuously monitors resource policies and reports buckets that grant public or cross-account access.",
    },
    referenceUrl: "https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config.html",
    referenceLabel: "Evaluating resources with AWS Config rules",
    consoleUrl: "https://console.aws.amazon.com/config/",
    consoleLabel: "AWS Config console",
  },
  {
    id: "aif-sec17",
    domain: "ai-security-governance",
    text: "Six weeks after an incident, the security team must establish which IAM principal invoked a particular foundation model, at what time, and from which source IP address. Which service holds that record?",
    options: [
      { id: "a", text: "AWS CloudTrail, which records the API calls made in the account, including Amazon Bedrock InvokeModel events" },
      { id: "b", text: "Amazon CloudWatch metrics, which aggregate numeric measures such as invocation count and latency but do not identify the caller" },
      { id: "c", text: "AWS Config, which records configuration changes to resources rather than individual API invocations" },
      { id: "d", text: "AWS Artifact, which distributes AWS compliance reports" },
      { id: "e", text: "Amazon Macie, which finds sensitive data in Amazon S3" },
      { id: "f", text: "AWS Trusted Advisor, which reports best-practice checks for the account" },
      { id: "g", text: "Amazon Inspector, which reports software vulnerabilities in workloads" },
      { id: "h", text: "AWS Secrets Manager, which stores credentials and their rotation history" },
      { id: "i", text: "AWS CloudTrail event history, which keeps the last 90 days of management events" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "CloudTrail answers \"who did what, when, and from where\". Each event records the principal, the event time, the source IP address, and the request parameters, and Amazon Bedrock is integrated with CloudTrail so that calls such as InvokeModel appear there. Event history covers the last 90 days in the console; a trail delivering to Amazon S3 keeps events for as long as the retention policy says.",
    optionRationale: {
      a: "Attributing an API call to a principal, a time, and a source IP address is exactly what a CloudTrail event provides.",
      b: "CloudWatch metrics are aggregated numbers; no metric identifies which principal made a call.",
      c: "Config captures the configuration state of resources over time, and a model invocation is not a configuration change.",
      d: "Artifact holds AWS's audit documents and no record of the account's activity.",
      e: "Macie reports on sensitive data at rest, not on who called an API.",
      f: "Trusted Advisor offers best-practice checks, not an activity log.",
      g: "Inspector reports vulnerabilities in workloads and logs no API calls.",
      h: "Secrets Manager tracks its own secrets and rotations, not Bedrock invocations.",
      i: "Bedrock logs InvokeModel as a management event, so CloudTrail event history still shows the principal, time, and source IP address six weeks later.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/logging-using-cloudtrail.html",
    referenceLabel: "Monitor Amazon Bedrock API calls using CloudTrail",
    consoleUrl: "https://console.aws.amazon.com/cloudtrail/",
    consoleLabel: "AWS CloudTrail console",
    cliExample: {
      description: "Look up recent Bedrock model invocations recorded by CloudTrail.",
      command: "aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=InvokeModel --max-results 3 --query 'Events[].{time:EventTime,user:Username}'",
      sampleOutput: "[\n  { \"time\": \"2026-09-22T08:14:02+00:00\", \"user\": \"data-scientist\" }\n]",
    },
  },
  {
    id: "aif-sec18",
    domain: "ai-security-governance",
    text: "Compliance asks the team to retain the full text of the prompts and completions exchanged with Amazon Bedrock so that a reviewer can sample real conversations later. Which capability produces that record?",
    options: [
      { id: "a", text: "Model invocation logging, which delivers the full request and response data to Amazon CloudWatch Logs, an Amazon S3 bucket, or both" },
      { id: "b", text: "AWS CloudTrail events, which record that InvokeModel was called but not the prompt and completion text" },
      { id: "c", text: "Amazon CloudWatch metrics such as Invocations and InvocationLatency, which are numeric only" },
      { id: "d", text: "Amazon Bedrock Guardrails, which filter content at inference time but do not archive the conversation" },
      { id: "e", text: "AWS Config, which records configuration changes to AWS resources" },
      { id: "f", text: "Amazon Macie, which classifies sensitive data already stored in Amazon S3" },
      { id: "g", text: "AWS X-Ray, which traces a request through the components of an application" },
      { id: "h", text: "Amazon S3 server access logging, which records the requests made to a bucket" },
      { id: "i", text: "Invocation logging in the Amazon Bedrock settings, with text data included in the logs" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Model invocation logging is the Bedrock setting that captures invocation data, including the prompt and the model's response, and delivers it to CloudWatch Logs or Amazon S3. It is off by default and is enabled deliberately, because the logged data will contain whatever the prompts contain, so the destination needs its own encryption, access control, and retention policy.",
    optionRationale: {
      a: "Delivering full invocation input and output to CloudWatch Logs or S3 is exactly what model invocation logging does.",
      b: "CloudTrail records the API call and its metadata for audit, not the prompt body or the completion.",
      c: "Metrics are aggregated numbers and hold no text.",
      d: "Guardrails block or mask content as it passes; retaining the conversation is a separate concern.",
      e: "Config records the configuration of resources, not the content of model calls.",
      f: "Macie scans data already stored somewhere; it does not create the record in the first place.",
      g: "X-Ray traces latency and call paths through an application, without capturing model payloads.",
      h: "S3 server access logging records bucket requests, which is unrelated to Bedrock invocations.",
      i: "Turning on model invocation logging with text data included records each prompt and completion in CloudWatch Logs or Amazon S3 for later review.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/model-invocation-logging.html",
    referenceLabel: "Monitor model invocation using CloudWatch Logs and Amazon S3 (Amazon Bedrock)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-sec19",
    domain: "ai-security-governance",
    text: "An EU retailer must keep the customer personal data used by its generative AI application inside the European Union to satisfy its GDPR commitments. Which approach meets that requirement?",
    options: [
      { id: "a", text: "Deploy the workload in an EU AWS Region and keep the data stores and services it uses within that Region, since the customer chooses the Region and AWS does not move the content elsewhere without instruction" },
      { id: "b", text: "Deploy in any Region and tag the resources \"EU only\", since tags are evaluated before data is stored" },
      { id: "c", text: "Enable cross-Region replication from the EU bucket to a US Region so that a durable second copy exists" },
      { id: "d", text: "Rely on AWS to place the data automatically in whichever Region is closest to each user" },
      { id: "e", text: "Encrypt the data with AWS KMS, which removes any residency obligation for the encrypted copies" },
      { id: "f", text: "Store the data in a global Amazon S3 bucket that belongs to no particular Region" },
      { id: "g", text: "Enable Amazon CloudFront so the content is cached at edge locations worldwide" },
      { id: "h", text: "Download AWS's SOC 2 report from AWS Artifact, which certifies the residency of the workload" },
      { id: "i", text: "Deploy only in EU Regions and use a service control policy to deny requests to other Regions" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Data residency on AWS is achieved by choosing the Region and keeping the architecture inside it. The customer selects where content is stored, and AWS does not move it to another Region unless the customer configures something that does so. Controls such as IAM and service control policy conditions on aws:RequestedRegion, or AWS Control Tower data residency controls, can enforce that choice rather than leave it to convention.",
    optionRationale: {
      a: "Selecting an EU Region and confining the workload's services and storage to it is the mechanism that delivers residency.",
      b: "A tag is metadata. It does not constrain where a service stores data.",
      c: "Cross-Region replication to the United States deliberately copies the data out of the EU, breaking the requirement.",
      d: "AWS does not relocate customer content by proximity; the Region is the customer's choice, and automatic movement is not how the platform works.",
      e: "Encryption protects confidentiality wherever the data sits; it does not change where the data is.",
      f: "Every S3 bucket is created in a specific Region; there is no global, Region-less bucket.",
      g: "Caching at worldwide edge locations distributes copies of content more widely, which works against the requirement.",
      h: "An audit report describes AWS's controls; it cannot certify where a particular workload placed its data.",
      i: "Running in EU Regions with a service control policy on aws:RequestedRegion keeps the workload's data in the EU and blocks resources from being created elsewhere.",
    },
    referenceUrl: "https://aws.amazon.com/compliance/gdpr-center/",
    referenceLabel: "GDPR Center (AWS Compliance)",
  },
  {
    id: "aif-sec20",
    domain: "ai-security-governance",
    text: "A data governance policy states that raw prompt logs held in Amazon S3 may be kept for 90 days and must then be deleted automatically, with no manual step. Which mechanism implements that?",
    options: [
      { id: "a", text: "An S3 Lifecycle configuration with an expiration rule that deletes objects 90 days after creation" },
      { id: "b", text: "S3 Versioning, which retains previous versions of objects rather than removing them" },
      { id: "c", text: "S3 Object Lock in compliance mode, which prevents objects from being deleted for a fixed retention period" },
      { id: "d", text: "An IAM policy that denies s3:GetObject on objects older than 90 days" },
      { id: "e", text: "AWS Backup, which copies data into a backup vault on a schedule" },
      { id: "f", text: "Amazon Macie, which reports which objects contain sensitive data" },
      { id: "g", text: "AWS Config, which records configuration changes to the bucket" },
      { id: "h", text: "S3 Transfer Acceleration, which speeds up long-distance uploads" },
      { id: "i", text: "An S3 Lifecycle expiration action filtered to the log objects by prefix or tag" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Retention limits are part of data governance, and on Amazon S3 they are implemented with an S3 Lifecycle configuration. An expiration rule, optionally scoped by prefix or tag, deletes objects a set number of days after creation, so the policy is enforced by the platform rather than by someone remembering to run a clean-up script.",
    optionRationale: {
      a: "A lifecycle expiration rule is the built-in, automatic deletion mechanism, and it can be scoped to the prompt log prefix.",
      b: "Versioning keeps more copies rather than fewer, which works against a deletion requirement.",
      c: "Object Lock in compliance mode forbids deletion for the retention period, the opposite of what the policy asks for.",
      d: "IAM policies control who may call an API; they cannot express object age, and denying reads does not delete anything.",
      e: "AWS Backup creates and retains backup copies; it does not expire objects in the source bucket.",
      f: "Macie classifies data and reports findings; it deletes nothing.",
      g: "Config records the bucket's configuration history and performs no data management action.",
      h: "Transfer Acceleration affects upload speed and nothing else.",
      i: "An expiration action in a lifecycle rule, scoped by prefix or tag, makes S3 delete matching objects automatically once they reach the set age.",
    },
    referenceUrl: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html",
    referenceLabel: "Managing the lifecycle of objects (Amazon S3)",
    consoleUrl: "https://console.aws.amazon.com/s3/",
    consoleLabel: "Amazon S3 console",
  },
  {
    id: "aif-sec21",
    domain: "ai-security-governance",
    text: "A team takes an existing third-party foundation model and fine-tunes it on the company's own labelled data, then serves the tuned model to internal users. Using the AWS Generative AI Security Scoping Matrix, which scope describes this workload?",
    options: [
      { id: "a", text: "Scope 4, fine-tuned models: an existing foundation model tuned with the organisation's own data" },
      { id: "b", text: "Scope 1, consumer application: staff use a public, third-party generative AI service" },
      { id: "c", text: "Scope 2, enterprise application: a business application with generative AI features, used under an enterprise agreement" },
      { id: "d", text: "Scope 3, pre-trained models: an application built on an existing model whose weights are not changed" },
      { id: "e", text: "Scope 5, self-trained models: a model trained from scratch on the organisation's own data" },
      { id: "f", text: "Scope 6, agentic applications: any workload in which the model can call tools" },
      { id: "g", text: "The matrix has a single scope for all generative AI workloads, so no classification is needed" },
      { id: "h", text: "Scope 4, fine-tuned models: the organization's data changes the weights of a model it did not pre-train" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "The Generative AI Security Scoping Matrix has five scopes, ordered by how much of the model and data the organisation owns: Scope 1 consumer application, Scope 2 enterprise application, Scope 3 pre-trained models, Scope 4 fine-tuned models, and Scope 5 self-trained models. Tuning someone else's foundation model on your own data is Scope 4, which brings training data governance and the protection of the tuned weights into the security picture alongside the usual application controls.",
    optionRationale: {
      a: "Fine-tuning an existing model with the organisation's data is the definition of Scope 4.",
      b: "Scope 1 covers staff using a public consumer service, where the organisation controls neither the model nor the data handling.",
      c: "Scope 2 covers a vendor's business application with generative AI features, not a model the customer tunes.",
      d: "Scope 3 covers building on a pre-trained model without changing its weights, which is what fine-tuning does change.",
      e: "Scope 5 is training a model from scratch on your own data, which is a much larger undertaking than tuning an existing one.",
      f: "There is no Scope 6; the matrix stops at five scopes, and tool use does not create a new one.",
      g: "The whole point of the matrix is that different scopes carry different security responsibilities.",
      h: "Adjusting the weights of a model someone else pre-trained, using the organization's own data, is what places a workload in Scope 4.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/security/securing-generative-ai-an-introduction-to-the-generative-ai-security-scoping-matrix/",
    referenceLabel: "Introduction to the Generative AI Security Scoping Matrix (AWS Security Blog)",
  },
  {
    id: "aif-sec22",
    domain: "ai-security-governance",
    text: "An architect wants AWS's documented design guidance for machine learning workloads: the lifecycle phases, design principles, and best practices, set out against the Well-Architected pillars. Which resource should they read?",
    options: [
      { id: "a", text: "The AWS Well-Architected Machine Learning Lens" },
      { id: "b", text: "The Generative AI Security Scoping Matrix, which classifies a workload by how much of the model and data the organisation owns" },
      { id: "c", text: "AWS Artifact, which provides AWS's compliance reports and agreements" },
      { id: "d", text: "AWS Trusted Advisor, which checks an account against best-practice rules" },
      { id: "e", text: "The AWS Health Dashboard, which reports the status of AWS services and events affecting the account" },
      { id: "f", text: "Amazon SageMaker Model Cards, which document a single model's intended use and evaluation results" },
      { id: "g", text: "The AWS Pricing Calculator, which estimates the cost of a planned architecture" },
      { id: "h", text: "AWS Config conformance packs, which group configuration rules for an account" },
      { id: "i", text: "The Machine Learning Lens, also offered in the Lens Catalog of the AWS Well-Architected Tool" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "The Well-Architected Framework is extended by lenses that apply its pillars to a specific domain. The Machine Learning Lens covers the ML lifecycle, from business goal framing and data preparation through model development, deployment, and monitoring, and gives design principles and best practices for each pillar. It is architectural guidance to read and apply, not a service to switch on.",
    optionRationale: {
      a: "The Machine Learning Lens is the Well-Architected document that covers ML workload design against the pillars.",
      b: "The Scoping Matrix classifies a generative AI workload for security purposes; it is not lifecycle design guidance.",
      c: "Artifact distributes audit reports and has no architectural content.",
      d: "Trusted Advisor checks a live account rather than offering design guidance for a workload being planned.",
      e: "The Health Dashboard reports service events and outages.",
      f: "A Model Card documents one model; it is not a design framework for ML workloads.",
      g: "The Pricing Calculator estimates cost and says nothing about design practice.",
      h: "Conformance packs bundle Config rules for compliance checking, not design guidance.",
      i: "The Machine Learning Lens applies the Well-Architected pillars to each phase of the ML lifecycle, and it is also available as an official lens in the Well-Architected Tool.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/machine-learning-lens/machine-learning-lens.html",
    referenceLabel: "Machine Learning Lens (AWS Well-Architected Framework)",
  },
  {
    id: "aif-sec23",
    domain: "ai-security-governance",
    text: "An executive sponsor asks for a framework that helps the organisation prepare for AI adoption across business, people, governance, platform, security, and operations perspectives, including capabilities such as AI strategy, skills, and responsible AI oversight. Which AWS resource is that?",
    options: [
      { id: "a", text: "The AWS Cloud Adoption Framework for Artificial Intelligence, Machine Learning, and Generative AI (CAF-AI)" },
      { id: "b", text: "The AWS Well-Architected Machine Learning Lens, which gives technical design guidance for ML workloads" },
      { id: "c", text: "The Generative AI Security Scoping Matrix, which classifies a workload by how much of the model and data the organisation owns" },
      { id: "d", text: "AWS Artifact, which distributes AWS's audit reports and agreements" },
      { id: "e", text: "The AWS shared responsibility model, which divides security duties between AWS and the customer" },
      { id: "f", text: "AWS Audit Manager, which collects evidence for compliance assessments" },
      { id: "g", text: "AWS Control Tower, which provisions and governs a multi-account environment" },
      { id: "h", text: "Amazon SageMaker Model Dashboard, which lists deployed models and their monitoring status" },
      { id: "i", text: "The AI-focused extension of the AWS Cloud Adoption Framework, mapping foundational capabilities to each perspective" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "The AWS Cloud Adoption Framework organises transformation around six perspectives: business, people, governance, platform, security, and operations. CAF-AI applies that structure to artificial intelligence, describing the capabilities an organisation should build in each perspective, such as AI strategy, talent and culture, data and model governance, and responsible AI. It addresses the organisation, whereas the Well-Architected lenses address the workload.",
    optionRationale: {
      a: "CAF-AI is the adoption framework built on the six CAF perspectives and applied to AI, ML, and generative AI.",
      b: "The Machine Learning Lens is workload design guidance, not an organisational adoption framework.",
      c: "The Scoping Matrix is a security classification tool for a single workload.",
      d: "Artifact is a compliance document portal with no adoption guidance.",
      e: "The shared responsibility model allocates security duties; it does not describe organisational capabilities.",
      f: "Audit Manager is a service for running compliance assessments, not a framework for adoption.",
      g: "Control Tower is a service that builds and governs a landing zone, which is a technical implementation rather than an adoption framework.",
      h: "Model Dashboard is a SageMaker feature for overseeing deployed models.",
      i: "CAF-AI extends the Cloud Adoption Framework's perspectives with the foundational capabilities an organization needs for AI, ML, and generative AI.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/aws-caf-for-ai/aws-caf-for-ai.html",
    referenceLabel: "AWS Cloud Adoption Framework for AI, ML, and Generative AI",
  },
  {
    id: "aif-sec24",
    domain: "ai-security-governance",
    text: "A company is establishing governance for the AI systems it deploys. Beyond the technical controls already in place, which TWO practices belong in its governance protocols?",
    options: [
      { id: "a", text: "A defined review cadence in which each deployed model is re-assessed on a schedule against its documented risk and performance criteria" },
      { id: "b", text: "Role-specific training, so the people who build, operate, and approve AI systems understand the policies they have to follow" },
      { id: "c", text: "Auto scaling the inference endpoint so that it absorbs traffic spikes" },
      { id: "d", text: "Choosing a model with a larger context window so that fewer requests are needed" },
      { id: "e", text: "Caching frequently repeated prompts to reduce token cost" },
      { id: "f", text: "Using Spot Instances for training jobs to lower their cost" },
      { id: "g", text: "Raising the temperature setting so that responses vary more between users" },
      { id: "h", text: "Quantising the model so that it fits on a smaller instance type" },
      { id: "i", text: "A named owner for each AI system who is accountable for its risks and approves changes" },
      { id: "j", text: "Transparency standards that define what is disclosed to users about each AI system" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Governance protocols are the human and procedural side of responsible AI: written policies, clear accountability, a schedule on which models and their risks are reviewed, transparency standards for what gets disclosed, and training so that the people involved know what is expected. Without them, technical controls drift, because no one is obliged to look at them again. The remaining options are performance and cost decisions, which belong to operations rather than governance.",
    optionRationale: {
      a: "A scheduled re-assessment against documented criteria is how a governance programme keeps deployed models within policy over time.",
      b: "Training the builders, operators, and approvers is what makes a written policy take effect in practice.",
      c: "Auto scaling is a capacity and availability measure with no governance content.",
      d: "Context window size is a model selection trade-off about prompt capacity and cost.",
      e: "Prompt caching is a cost optimisation.",
      f: "Spot Instances reduce training cost and say nothing about oversight.",
      g: "Temperature changes output randomness; varying responses is not a governance practice.",
      h: "Quantisation is an efficiency technique for serving a model on smaller hardware.",
      i: "Clear accountability, with a named owner answerable for each system, is a core element of an AI governance protocol.",
      j: "Agreed standards for what is disclosed about AI systems belong in governance, because they make transparency a policy rather than an individual choice.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/responsible-ai-lens.html",
    referenceLabel: "Responsible AI Lens (AWS Well-Architected Framework)",
  },
  {
    id: "aif-sec25",
    domain: "ai-security-governance",
    text: "A governance team wants a single page in Amazon SageMaker AI that lists every model in the account together with its endpoints, the monitoring jobs attached to each one, and any model that has no monitor configured. Which feature gives them that view?",
    options: [
      { id: "a", text: "Amazon SageMaker Model Dashboard, a central view of models, endpoints, and their monitoring status" },
      { id: "b", text: "Amazon SageMaker Model Cards, which document one model's intended use, risk rating, and evaluation results" },
      { id: "c", text: "Amazon SageMaker Role Manager, which builds persona-based IAM roles" },
      { id: "d", text: "Amazon SageMaker Feature Store, which stores and serves curated features" },
      { id: "e", text: "Amazon SageMaker Ground Truth, which manages human data-labeling jobs" },
      { id: "f", text: "Amazon CloudWatch alarms, which notify when a single metric breaches a threshold" },
      { id: "g", text: "AWS Config, which records configuration changes to AWS resources" },
      { id: "h", text: "AWS Trusted Advisor, which checks the account against best practices" },
      { id: "i", text: "Amazon SageMaker Model Dashboard, which shows monitor alerts and job status for every deployed model" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Model Dashboard is the oversight view in SageMaker AI: one place listing the account's models with their endpoints, data quality, model quality, bias, and explainability monitors, and a flag where a monitor is missing or a job has failed. Model Cards are the complementary artefact, documenting an individual model in depth, while the dashboard answers the portfolio question of what is running and what is unwatched.",
    optionRationale: {
      a: "A single view of all models, their endpoints, and their monitoring status is exactly what Model Dashboard provides.",
      b: "A Model Card documents one model thoroughly; it does not enumerate the account's whole model estate.",
      c: "Role Manager creates IAM roles from personas and has no model inventory.",
      d: "Feature Store holds feature data, not model and monitor status.",
      e: "Ground Truth manages labeling workforces and jobs.",
      f: "A CloudWatch alarm watches one metric; it is not an inventory of models and their monitors.",
      g: "Config records AWS resource configuration history rather than SageMaker model monitoring coverage.",
      h: "Trusted Advisor checks account best practices and knows nothing about model monitors.",
      i: "Model Dashboard brings every model's endpoints, monitoring jobs, and alerts into one view, including models that have no monitor set up.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-dashboard.html",
    referenceLabel: "Amazon SageMaker Model Dashboard",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
];
