import { Question } from "../../types.js";

export const genaiFundamentalsQuestions: Question[] = [
  {
    id: "aif-gen1",
    domain: "genai-fundamentals",
    text: "A developer is estimating the monthly bill for a summarization feature that calls a large language model on Amazon Bedrock, where on-demand pricing charges per input token and per output token. What is a token?",
    options: [
      { id: "a", text: "A word or part of a word that the model handles as one unit" },
      { id: "b", text: "A single character of the prompt" },
      { id: "c", text: "One complete request to the model, however long the text is" },
      { id: "d", text: "A numeric vector that captures the meaning of a sentence" },
      { id: "e", text: "A temporary security credential issued by AWS STS" },
      { id: "f", text: "One layer of the model's neural network" },
      { id: "g", text: "An API key that authorizes the Bedrock call" },
      { id: "h", text: "A unit of text from the model's fixed vocabulary" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Models break text into tokens, each roughly a word or a fragment of a word, and on-demand Bedrock pricing counts both the tokens sent in the prompt and the tokens generated in the response, so prompt length affects cost as much as response length.",
    optionRationale: {
      a: "A token is the unit of text the model processes, typically a short word or a word fragment.",
      b: "Tokenizers usually group several characters together, so a token is larger than one character.",
      c: "Billing is per token, not per request, which is why long prompts cost more than short ones.",
      d: "A numeric vector that captures meaning is an embedding, a different concept from a token.",
      e: "STS issues credentials for authentication; it has nothing to do with how text is counted.",
      f: "Layers are part of the model architecture and are not what the service meters.",
      g: "An API key or IAM credential authorizes the call; the token count measures the text in it.",
      h: "A model splits text into entries from the fixed vocabulary it was trained with, and each of those entries, typically a word or a piece of a word, is one token.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/key-definitions.html",
    referenceLabel: "Amazon Bedrock key terminology",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen2",
    domain: "genai-fundamentals",
    text: "A team converts each product description into a list of 1,024 floating point numbers, arranged so that descriptions with similar meaning sit close together in that numeric space. What are these numeric representations called?",
    options: [
      { id: "a", text: "Embeddings" },
      { id: "b", text: "Tokens" },
      { id: "c", text: "One-hot encodings" },
      { id: "d", text: "Model weights" },
      { id: "e", text: "Hyperparameters" },
      { id: "f", text: "Model checkpoints" },
      { id: "g", text: "Prompt templates" },
      { id: "h", text: "Dense vectors" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "An embedding is a dense vector that represents text, an image, or another input so that distance between vectors reflects similarity in meaning; embedding models such as Amazon Titan Text Embeddings and Cohere Embed produce them.",
    optionRationale: {
      a: "Embeddings are exactly this: vectors positioned so that semantically similar inputs are near each other.",
      b: "Tokens are the chunks of text fed to the model, not the vector that represents their meaning.",
      c: "A one-hot encoding is a sparse vector with a single 1 per category and carries no notion of similarity.",
      d: "Model weights are the learned parameters inside the model, not a representation of one input.",
      e: "Hyperparameters are settings chosen before training, such as learning rate or batch size.",
      f: "A checkpoint is a saved copy of a model's state during or after training.",
      g: "A prompt template is reusable text with placeholders, not a numeric representation.",
      h: "A fixed-length list of floating point values positioned by meaning is a dense vector, which is the form a semantic embedding takes.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/embeddings-in-machine-learning/",
    referenceLabel: "What are embeddings in machine learning? (AWS)",
  },
  {
    id: "aif-gen3",
    domain: "genai-fundamentals",
    text: "An analyst pastes a 200-page contract into a single prompt and the model rejects the request because the input is too long. Which model characteristic does this limit describe?",
    options: [
      { id: "a", text: "The context window, which is the maximum number of tokens the model can take in and generate for one request" },
      { id: "b", text: "The temperature setting" },
      { id: "c", text: "The knowledge cutoff date of the training data" },
      { id: "d", text: "The requests-per-minute service quota" },
      { id: "e", text: "The number of parameters in the model" },
      { id: "f", text: "The dimension of the model's embeddings" },
      { id: "g", text: "The top-k value used during sampling" },
      { id: "h", text: "The model's maximum sequence length" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "The context window, also called the maximum sequence length, is the fixed token budget a model can attend to in one call, covering the prompt and the generated response together; oversized input must be split into smaller pieces or sent to a model with a larger window.",
    optionRationale: {
      a: "Exceeding the token budget for a single request is precisely a context window limit.",
      b: "Temperature changes how randomly tokens are sampled and has no effect on how much text fits.",
      c: "A knowledge cutoff limits what the model knows about, not how much text it can read at once.",
      d: "A requests-per-minute quota throttles how often you can call the model, not the size of one call.",
      e: "Parameter count describes model size; a large model can still have a small context window.",
      f: "Embedding dimension is the length of a vector produced by an embedding model.",
      g: "Top-k restricts which candidate tokens are sampled and does not change the input limit.",
      h: "Maximum sequence length is the most tokens the model can process in one pass, so an oversized contract exceeds it and is rejected.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/large-language-model/",
    referenceLabel: "What is a large language model? (AWS)",
  },
  {
    id: "aif-gen4",
    domain: "genai-fundamentals",
    text: "A bank's case summarizer must produce the most consistent and focused wording it can for the same input, avoiding creative rephrasing. Which inference parameter change best supports that goal?",
    options: [
      { id: "a", text: "Lower the temperature" },
      { id: "b", text: "Raise the temperature" },
      { id: "c", text: "Raise top-p toward 1.0" },
      { id: "d", text: "Raise top-k to a much larger value" },
      { id: "e", text: "Increase the maximum response length" },
      { id: "f", text: "Add more stop sequences" },
      { id: "g", text: "Choose a model with a larger context window" },
      { id: "h", text: "Set top-k to 1" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Temperature scales the probability distribution the model samples from, so a low value concentrates probability on the most likely tokens and yields focused, repeatable wording; setting top-k to 1 goes further by always choosing the single most likely token.",
    optionRationale: {
      a: "A lower temperature makes the highest-probability tokens far more likely, giving consistent, conservative output.",
      b: "Raising temperature increases randomness, which is the opposite of what a summarizer needs here.",
      c: "A top-p near 1.0 admits almost the whole distribution, so more unusual tokens can be sampled.",
      d: "A larger top-k widens the candidate pool and therefore increases variety.",
      e: "Maximum response length caps how long the answer may be; it does not affect word choice.",
      f: "Stop sequences end generation at a marker; they do not make the wording more consistent.",
      g: "A larger context window lets you send more input and says nothing about output consistency.",
      h: "With top-k set to 1 the model always picks the single most likely token, which is greedy decoding and gives the most repeatable wording.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/inference-parameters.html",
    referenceLabel: "Influence response generation with inference parameters",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen5",
    domain: "genai-fundamentals",
    text: "A developer wants the model to sample only from the smallest set of next tokens whose probabilities add up to 0.9. Which inference parameter does this?",
    options: [
      { id: "a", text: "Top-p" },
      { id: "b", text: "Top-k" },
      { id: "c", text: "Temperature" },
      { id: "d", text: "Maximum response length" },
      { id: "e", text: "Stop sequences" },
      { id: "f", text: "Number of provisioned model units" },
      { id: "g", text: "Nucleus sampling" },
      { id: "h", text: "Frequency penalty" },
    ],
    correctOptionIds: ["a", "g"],
    answerType: "single",
    explanation: "Top-p, also called nucleus sampling, keeps the shortest list of candidate tokens whose cumulative probability reaches the given value, so the size of the candidate set changes with the model's confidence; top-k instead keeps a fixed number of candidates regardless of their probabilities.",
    optionRationale: {
      a: "Top-p is defined by a cumulative probability threshold, exactly as described.",
      b: "Top-k keeps a fixed count of the most likely tokens, not a probability total.",
      c: "Temperature reshapes the whole distribution rather than truncating it at a probability sum.",
      d: "Maximum response length limits output tokens and has no role in choosing candidates.",
      e: "Stop sequences tell the model where to stop generating text.",
      f: "Model units are a Provisioned Throughput capacity setting, not an inference parameter.",
      g: "Nucleus sampling is the other name for top-p, which keeps the smallest set of tokens whose cumulative probability reaches the threshold.",
      h: "A frequency penalty lowers the likelihood of tokens that have already appeared rather than truncating candidates at a probability total.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/inference-parameters.html",
    referenceLabel: "Influence response generation with inference parameters",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen6",
    domain: "genai-fundamentals",
    text: "Why did transformer-based architectures largely replace earlier recurrent networks for large language models?",
    options: [
      { id: "a", text: "Self-attention lets the model weigh how every token in the input relates to every other token and process them in parallel, so training scales to huge corpora and long-range context is preserved" },
      { id: "b", text: "Transformers process one token at a time in strict order, which trains faster than parallel designs" },
      { id: "c", text: "Transformers need no training data, because attention is a hand-written rule set" },
      { id: "d", text: "Transformers remove the need for accelerated hardware such as GPUs" },
      { id: "e", text: "Transformers store the training corpus verbatim and look up the matching answer" },
      { id: "f", text: "Transformers train only on labeled data, which is why they are more accurate" },
      { id: "g", text: "Transformers return the identical output for the same input every time" },
      { id: "h", text: "Without recurrence, all positions in a sequence can be trained in parallel, which made scaling to huge datasets practical" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "The transformer's attention mechanism computes relationships between all positions in a sequence at once, which removes the sequential bottleneck of recurrent networks, allows massive parallel training, and keeps distant context available.",
    optionRationale: {
      a: "Parallel processing plus attention over the whole sequence is the transformer's defining advantage.",
      b: "Strictly sequential processing is the recurrent network behavior that transformers avoid.",
      c: "Transformers are trained statistically on very large text corpora; attention weights are learned.",
      d: "Training and serving large transformers is hardware-hungry and usually needs GPUs or custom accelerators.",
      e: "Models learn statistical patterns rather than storing a retrievable copy of the corpus.",
      f: "Pre-training uses vast amounts of unlabeled text; labels are only used for later customization.",
      g: "Sampling makes generative output vary between calls unless decoding is heavily constrained.",
      h: "Dropping step-by-step recurrence allows parallel computation across the sequence on accelerators, which is what made training on web-scale corpora feasible.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/transformers-in-artificial-intelligence/",
    referenceLabel: "What are transformers in artificial intelligence? (AWS)",
  },
  {
    id: "aif-gen7",
    domain: "genai-fundamentals",
    text: "A marketing team wants a model that creates original product imagery from a written description. Which model family is designed for this, and how does it work at a high level?",
    options: [
      { id: "a", text: "A diffusion model, which starts from random noise and removes the noise step by step, guided by the text prompt, until an image emerges" },
      { id: "b", text: "A large language model, which predicts the next word in a sequence of text" },
      { id: "c", text: "A convolutional image classifier, which assigns each image one category label" },
      { id: "d", text: "A linear regression model, which fits a line through labeled pixels" },
      { id: "e", text: "A k-means clustering model, which groups similar images together" },
      { id: "f", text: "A recurrent network, which converts recorded speech into text" },
      { id: "g", text: "A decision tree, which splits pixels on threshold rules" },
      { id: "h", text: "A generative adversarial network, where a generator creates images and a discriminator judges their realism" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Text-to-image generation is done mainly by diffusion models, which learn to reverse a noising process and are steered by the prompt while denoising, and also by generative adversarial networks; Amazon Nova Canvas and Stability AI's Stable Diffusion models are available through the Amazon Bedrock API.",
    optionRationale: {
      a: "Iterative denoising from random noise, conditioned on a prompt, is how diffusion image models work.",
      b: "A language model generates text; it does not produce pixels.",
      c: "A classifier labels an existing image and creates nothing new.",
      d: "Linear regression predicts a number from features and cannot synthesize an image.",
      e: "Clustering groups existing images without generating any.",
      f: "Speech-to-text converts audio into words, which is a different task entirely.",
      g: "A decision tree makes rule-based predictions and has no generative capability.",
      h: "Generative adversarial networks pit a generator against a discriminator and can create realistic images from text prompts.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/stable-diffusion/",
    referenceLabel: "What is Stable Diffusion? (AWS)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen8",
    domain: "genai-fundamentals",
    text: "A logistics company wants one model that can accept a photograph of a damaged pallet together with a written question about it and answer in text. Which kind of model is needed?",
    options: [
      { id: "a", text: "A multimodal foundation model, which accepts more than one input type, such as text and images, in the same request" },
      { id: "b", text: "A text-only large language model" },
      { id: "c", text: "An embedding model, which returns a vector for each input" },
      { id: "d", text: "A text-to-speech model" },
      { id: "e", text: "A text-to-image diffusion model" },
      { id: "f", text: "A tabular gradient boosting model" },
      { id: "g", text: "A speech-to-text transcription model" },
      { id: "h", text: "A vision-language model" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Multimodal models, such as vision-language models, take combinations of input types, such as an image plus a text question, and respond in text; Amazon Nova understanding models and Anthropic Claude models on Amazon Bedrock support image and text input through the same API.",
    optionRationale: {
      a: "Accepting an image and a text question together in one request is the definition of a multimodal model.",
      b: "A text-only model cannot take the photograph as input.",
      c: "An embedding model returns vectors for search or comparison rather than an answer in words.",
      d: "Text-to-speech produces audio from text and does not analyze an image.",
      e: "A diffusion model generates an image from text, which is the reverse of what is required.",
      f: "Gradient boosting works on structured columns, not on photographs and free-text questions.",
      g: "Transcription turns audio into text and does not process images.",
      h: "A vision-language model takes an image and text together and generates a text answer, which is exactly the requirement.",
    },
    referenceUrl: "https://docs.aws.amazon.com/nova/latest/userguide/what-is-nova.html",
    referenceLabel: "What is Amazon Nova?",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen9",
    domain: "genai-fundamentals",
    text: "A data science manager is explaining to stakeholders how a foundation model differs from the task-specific models the team has built before. Which statement is accurate?",
    options: [
      { id: "a", text: "A foundation model is pretrained on a very large, mostly unlabeled corpus and can then be adapted to many different downstream tasks, whereas a task-specific model is trained on labeled data for one task" },
      { id: "b", text: "A foundation model is always smaller and cheaper to run than a task-specific model" },
      { id: "c", text: "A foundation model needs no evaluation, because it was already validated by its provider" },
      { id: "d", text: "A foundation model has to be retrained from scratch for every new prompt" },
      { id: "e", text: "Task-specific models cannot be deployed behind an API endpoint" },
      { id: "f", text: "Foundation models work only on images, while task-specific models work only on text" },
      { id: "g", text: "A foundation model requires a labeled example for every output it could ever produce" },
      { id: "h", text: "A foundation model adapts to new tasks through prompting or fine-tuning, while a task-specific model is limited to its trained task" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Foundation models are pretrained once at great expense on broad unlabeled data and are general enough to serve many tasks through prompting or customization, while a task-specific model is trained on labeled examples of one narrow task.",
    optionRationale: {
      a: "Broad unlabeled pre-training plus adaptability to many tasks is what makes a model a foundation model.",
      b: "Foundation models are usually far larger and more expensive per prediction than a narrow model.",
      c: "You still have to evaluate a foundation model on your own data and task before trusting it.",
      d: "Prompting uses the already-trained model; no retraining happens per request.",
      e: "Task-specific models are routinely hosted behind real-time endpoints.",
      f: "Both kinds of model span text, images, audio, and tabular data.",
      g: "Needing a label for every possible output describes supervised learning, not foundation models.",
      h: "Adaptability to many downstream tasks without training a new model from scratch is the defining trait of a foundation model.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/foundation-models/",
    referenceLabel: "What are foundation models? (AWS)",
  },
  {
    id: "aif-gen10",
    domain: "genai-fundamentals",
    text: "A bank is deciding which backlog items to build on a text foundation model. Which TWO tasks are the strongest fit for a generative text model?",
    options: [
      { id: "a", text: "Producing a short plain-language summary of a long customer complaint thread" },
      { id: "b", text: "Drafting a reply to a customer question in natural language for an agent to review and send" },
      { id: "c", text: "Calculating the exact interest owed on each loan account at month end" },
      { id: "d", text: "Storing 20 TB of transaction records for a seven-year regulatory retention period" },
      { id: "e", text: "Applying the fixed rule that any transfer above 10,000 dollars needs a second approver" },
      { id: "f", text: "Distributing web traffic evenly across two Availability Zones" },
      { id: "g", text: "Producing a general ledger total that must reconcile to the cent every night" },
      { id: "h", text: "Translating customer messages into the language the support agent reads" },
      { id: "i", text: "Answering staff questions about internal policy documents through a chat assistant" },
      { id: "j", text: "Assigning unique sequential account numbers to newly opened accounts" },
    ],
    correctOptionIds: ["a", "b", "h", "i"],
    answerType: "multi",
    explanation: "Generative text models are strong at summarization, drafting, translation, classification of free text, and conversational assistance; exact arithmetic, durable storage, fixed rules, and traffic distribution belong to conventional software that is deterministic and auditable.",
    optionRationale: {
      a: "Summarizing long free text into a short readable form is a core generative language task.",
      b: "Drafting a natural language reply for human review is a standard assisted-response use case.",
      c: "Interest is a deterministic calculation that must be exact, so ordinary code is the right tool.",
      d: "Long-term retention is a storage requirement met by services such as Amazon S3.",
      e: "A fixed, regulated threshold should be enforced by explicit business logic, not a sampled model.",
      f: "Traffic distribution is handled by a load balancer, not by any model.",
      g: "A ledger total must reconcile exactly, which rules out a probabilistic generator.",
      h: "Translation between natural languages is a strong generative text task that needs fluent output rather than exact computation.",
      i: "Conversational question answering over policy text plays to a generative model's language strengths, especially when grounded in the source documents.",
      j: "Account numbers must never collide or skip, which calls for a database sequence rather than a probabilistic generator.",
    },
    referenceUrl: "https://aws.amazon.com/generative-ai/",
    referenceLabel: "Generative AI on AWS",
  },
  {
    id: "aif-gen11",
    domain: "genai-fundamentals",
    text: "Developers want inline code suggestions inside their IDE, the ability to ask questions about their existing repository in natural language, and help drafting routine framework upgrades. Which AWS service is purpose-built for this?",
    options: [
      { id: "a", text: "The Kiro IDE" },
      { id: "b", text: "Amazon Q Business" },
      { id: "c", text: "PartyRock" },
      { id: "d", text: "Amazon SageMaker JumpStart" },
      { id: "e", text: "Amazon Comprehend" },
      { id: "f", text: "Amazon Kendra" },
      { id: "g", text: "AWS CodePipeline" },
      { id: "h", text: "Kiro" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Kiro is the AWS agentic development environment, available as an IDE and a CLI, with inline suggestions, chat about your own code, and agents that plan and apply multi-file changes such as framework upgrades. It succeeds Amazon Q Developer, which stopped accepting new sign-ups on May 15, 2026 and whose IDE plugins reach end of support on April 30, 2027.",
    optionRationale: {
      a: "The Kiro IDE offers inline suggestions and agentic chat grounded in the open project, and it can plan and apply multi-file changes such as a framework upgrade.",
      b: "Q Business answers employee questions over enterprise content; it is not a coding assistant.",
      c: "PartyRock is a no-code playground for building small generative AI apps, not an IDE companion.",
      d: "JumpStart is a model hub for deploying and tuning models, not a coding assistant.",
      e: "Comprehend extracts entities, sentiment, and key phrases from text.",
      f: "Kendra provides intelligent enterprise search over documents.",
      g: "CodePipeline automates build and release stages; it writes no code for you.",
      h: "Kiro is the AWS agentic IDE and CLI, with inline coding assistance, chat about your own codebase, and agent-driven help with code upgrades.",
    },
    referenceUrl: "https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/q-developer-ide-end-of-support.html",
    referenceLabel: "Amazon Q Developer IDE plugins end of support (move to Kiro)",
  },
  {
    id: "aif-gen12",
    domain: "genai-fundamentals",
    text: "A retailer wants to generate on-brand lifestyle imagery from text prompts, with no ML infrastructure to manage and no model training. Which approach fits best?",
    options: [
      { id: "a", text: "Call a text-to-image model, such as a Stability AI model, through the Amazon Bedrock API" },
      { id: "b", text: "Train a convolutional neural network from scratch in Amazon SageMaker AI" },
      { id: "c", text: "Use Amazon Rekognition to generate the images" },
      { id: "d", text: "Use Amazon Textract to generate the images" },
      { id: "e", text: "Use Amazon Polly to render the images" },
      { id: "f", text: "Use Amazon Q Developer to generate the images in the IDE" },
      { id: "g", text: "Use Amazon Comprehend to create the images" },
      { id: "h", text: "Use Stability AI Style Guide on Amazon Bedrock with a reference image of the brand's look" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Amazon Bedrock offers image generation models, such as Stability AI's Stable Diffusion 3.5 Large and Stable Image models, through a serverless API, so a team can generate images from prompts, optionally guided by a reference image in the brand's style, without provisioning infrastructure or training anything. Amazon Nova Canvas, which also generated images on Bedrock, is a Legacy model that new customers cannot adopt and that reaches end of life on September 30, 2026.",
    optionRationale: {
      a: "Bedrock provides managed access to text-to-image models, which is exactly the requirement.",
      b: "Training a network from scratch is slow and expensive and is not needed when pretrained models exist.",
      c: "Rekognition analyzes existing images and video; it does not create new images.",
      d: "Textract extracts text and data from scanned documents.",
      e: "Polly converts text into lifelike speech, producing audio rather than images.",
      f: "Q Developer assists with code; it is not an image generation service.",
      g: "Comprehend performs natural language processing on text.",
      h: "Style Guide on Amazon Bedrock takes a text prompt and a reference image, extracts the image's style, and generates new images in that style serverlessly with no training.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/stable-image-services.html",
    referenceLabel: "Stability AI Image Services on Amazon Bedrock (Style Guide)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen13",
    domain: "genai-fundamentals",
    text: "A legal team tests an assistant built on a foundation model and finds that it cites a court case that does not exist, stated with complete confidence. What is this behavior, and what does it imply for the design?",
    options: [
      { id: "a", text: "A hallucination: the model can generate fluent content that is simply untrue, so output used in a regulated process must be grounded in trusted sources and reviewed by a person" },
      { id: "b", text: "Overfitting: the model memorized its training set, so it needs more training epochs" },
      { id: "c", text: "Data drift: the production data has moved away from the training data, so the endpoint must be scaled up" },
      { id: "d", text: "A throttling error: the account needs a higher requests-per-minute quota" },
      { id: "e", text: "Underfitting: the model is too small, so the context window must be enlarged" },
      { id: "f", text: "Label leakage: the target value was present among the input features" },
      { id: "g", text: "A cold start: the endpoint needs to warm up before its answers become accurate" },
      { id: "h", text: "A confabulation: the model made up a plausible fact, so regulated use needs grounding in trusted sources and human review" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "A hallucination, also called a confabulation, is confident, plausible-sounding output that is factually wrong; because the model optimizes for likely text rather than truth, high-risk uses need authoritative source material supplied with the request and human review of the result.",
    optionRationale: {
      a: "Inventing a convincing but non-existent citation is the textbook example of a hallucination.",
      b: "Overfitting describes a model that performs well on training data and poorly on new data, and more epochs would worsen it.",
      c: "Drift concerns changing input distributions over time, not a fabricated fact in one answer.",
      d: "Throttling returns an error rather than a wrong answer.",
      e: "Underfitting means the model fails to capture patterns; the context window is unrelated to truthfulness.",
      f: "Label leakage is a supervised training data problem, not a generation behavior.",
      g: "Cold start affects latency on the first request, not factual accuracy.",
      h: "Confabulation is the term NIST and others use for confidently generated false content, the same failure as a hallucination.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/generative-ai-lens.html",
    referenceLabel: "AWS Well-Architected Generative AI Lens",
  },
  {
    id: "aif-gen14",
    domain: "genai-fundamentals",
    text: "A QA engineer raises a defect: sending the identical prompt to the identical foundation model twice returns two differently worded answers. What is the most accurate response?",
    options: [
      { id: "a", text: "This is expected behavior, because the model samples each next token from a probability distribution; lowering temperature and top-p makes responses far more consistent, though identical text is still not guaranteed" },
      { id: "b", text: "The model is faulty and must be redeployed" },
      { id: "c", text: "The model's knowledge cutoff has passed, so its answers change over time" },
      { id: "d", text: "The account is being throttled, which silently truncates responses" },
      { id: "e", text: "Two different model versions must be serving the traffic; nothing else can cause this" },
      { id: "f", text: "The context window was exceeded, so the prompt was silently cut in half" },
      { id: "g", text: "The model must be fine-tuned before it can return consistent answers" },
      { id: "h", text: "This is expected from a probabilistic model, so tests should check meaning and format rather than exact wording" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Generative models are nondeterministic by design: the next token is sampled from a distribution, so wording varies between calls. Test suites therefore assert on meaning, format, or required content rather than exact string equality.",
    optionRationale: {
      a: "Sampling explains the variation, and the decoding parameters control how much of it there is.",
      b: "Varying wording is normal model behavior and is not evidence of a broken deployment.",
      c: "The knowledge cutoff is fixed for a model version and does not change answers call by call.",
      d: "Throttling produces an explicit error rather than quietly reworded output.",
      e: "Even a single model version produces varied wording, so this is not the only possible cause.",
      f: "Exceeding the context window raises a validation error instead of silently truncating.",
      g: "Fine-tuning changes style and task behavior but does not remove sampling randomness.",
      h: "Sampled output naturally varies in wording, so the right fix is to change the test's assertions rather than treat the variation as a defect.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/inference-parameters.html",
    referenceLabel: "Influence response generation with inference parameters",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen15",
    domain: "genai-fundamentals",
    text: "A support assistant built on a foundation model gives wrong details about a product the company launched last month, although it answers questions about older products correctly. What is the most likely explanation?",
    options: [
      { id: "a", text: "The model's training data has a cutoff date, so it never saw the new product; the application has to supply those facts with the request or use a model customized with them" },
      { id: "b", text: "The temperature is set too low, which removes recent facts" },
      { id: "c", text: "The context window is too large, which dilutes the answer" },
      { id: "d", text: "The model is overfitted to the new product" },
      { id: "e", text: "The model needs Provisioned Throughput before it can answer accurately" },
      { id: "f", text: "Tokenization has failed for the product name" },
      { id: "g", text: "The embedding dimension is too small for recent data" },
      { id: "h", text: "The launch postdates the training data, so the model has to be given those facts" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "A foundation model only knows what was in its training corpus up to its knowledge cutoff, so anything newer must be provided at request time or added through customization; the model will otherwise answer from stale or invented knowledge.",
    optionRationale: {
      a: "A knowledge cutoff is exactly why a model is confidently wrong about very recent events.",
      b: "Temperature controls randomness of wording and cannot add facts the model never saw.",
      c: "A larger context window is a capacity to send more input, never a cause of wrong facts.",
      d: "Overfitting requires the model to have trained on the product, which is the opposite of the situation.",
      e: "Provisioned Throughput buys capacity; it has no effect on what the model knows.",
      f: "Tokenization handles unfamiliar words routinely by splitting them into sub-word pieces.",
      g: "Embedding dimension is a property of embedding models and unrelated to training recency.",
      h: "The model learned nothing after its training data was collected, so newer product facts have to be supplied with the request or through customization.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/generative-ai/",
    referenceLabel: "What is generative AI? (AWS)",
  },
  {
    id: "aif-gen16",
    domain: "genai-fundamentals",
    text: "An architect is writing the risk section of a design that uses a text foundation model. Which TWO of these are genuine limitations of foundation models that the design must allow for?",
    options: [
      { id: "a", text: "Output can be factually wrong while reading as confident and authoritative" },
      { id: "b", text: "It is difficult to explain exactly why the model produced one particular output" },
      { id: "c", text: "The model cannot accept an input longer than a single sentence" },
      { id: "d", text: "The model returns the identical response for a prompt every time, so experiments cannot be varied" },
      { id: "e", text: "Foundation models cannot be invoked through an API" },
      { id: "f", text: "The model must be retrained before each request it serves" },
      { id: "g", text: "Generated text cannot be logged or reviewed afterwards" },
      { id: "h", text: "Its knowledge stops at a training cutoff date, so recent events are unknown to it" },
      { id: "i", text: "Output can reflect social biases present in the training data" },
      { id: "j", text: "The model cannot follow instructions given in a system prompt" },
    ],
    correctOptionIds: ["a", "b", "h", "i"],
    answerType: "multi",
    explanation: "Real designs must allow for factual unreliability, low interpretability, a knowledge cutoff after which the model knows nothing new, and biases absorbed from training data; these push teams toward grounding, human review, evaluation, and logging.",
    optionRationale: {
      a: "Confident but incorrect output, commonly called hallucination, is a well-known limitation.",
      b: "Interpretability is genuinely hard for large models, which complicates audit and debugging.",
      c: "Models accept thousands to hundreds of thousands of tokens, far more than one sentence.",
      d: "Generative models are nondeterministic; identical repeated output is not the normal behavior.",
      e: "API invocation is the usual way to use them, for example through Amazon Bedrock.",
      f: "Inference uses the already-trained model; nothing is retrained per request.",
      g: "Requests and responses can and should be logged for review and troubleshooting.",
      h: "A model only knows what was in its training data, so anything after the cutoff has to be supplied by the application.",
      i: "Models absorb biases from the large corpora they are trained on, so outputs need evaluation and guardrails for fairness.",
      j: "System prompts and instructions are a standard, effective way to steer foundation model behavior.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/foundation-models/",
    referenceLabel: "What are foundation models? (AWS)",
  },
  {
    id: "aif-gen17",
    domain: "genai-fundamentals",
    text: "A team is documenting the foundation model lifecycle for its governance board. Which sequence describes that lifecycle correctly?",
    options: [
      { id: "a", text: "Select data, pre-train the model, customize it for the use case, evaluate it, deploy it, then collect feedback that feeds the next round of customization" },
      { id: "b", text: "Customize the model, select data, deploy it, pre-train it, then evaluate it" },
      { id: "c", text: "Deploy the model, evaluate it, pre-train it, then select data" },
      { id: "d", text: "Pre-train the model, select data, deploy it, then customize it" },
      { id: "e", text: "Select data, deploy the model, pre-train it, customize it, then evaluate it" },
      { id: "f", text: "Evaluate the model, pre-train it, select data, collect feedback, then deploy it" },
      { id: "g", text: "Select a pre-trained model, customize it, evaluate it, deploy it, then gather feedback for the next iteration" },
      { id: "h", text: "Select data, customize the model, pre-train it, deploy it, then evaluate it" },
    ],
    correctOptionIds: ["a", "g"],
    answerType: "single",
    explanation: "Data selection comes first, pre-training produces the general model, customization adapts it to the use case, evaluation decides whether it is good enough, deployment puts it in front of users, and feedback from real use drives the next iteration; teams that start from an existing pre-trained model simply begin at model selection.",
    optionRationale: {
      a: "This is the accepted order, and the loop back from feedback is what makes it a lifecycle.",
      b: "Customization cannot precede the pre-training that creates the model being customized.",
      c: "Deploying before any data is chosen or the model is trained is not a workable order.",
      d: "Pre-training cannot happen before the training data has been selected.",
      e: "Deployment belongs after evaluation, not before the model has even been trained.",
      f: "Evaluation needs a trained model to measure, so it cannot come first.",
      g: "Teams that start from an existing foundation model begin at model selection, and the remaining stages follow in the same order with feedback closing the loop.",
      h: "Customization adapts an already pre-trained model, so it cannot precede pre-training, and evaluation belongs before deployment.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/generative-ai-lens.html",
    referenceLabel: "AWS Well-Architected Generative AI Lens",
    diagram: `flowchart LR
  A[Select data] --> B[Pre-train foundation model]
  B --> C[Customize for the use case]
  C --> D[Evaluate]
  D --> E[Deploy]
  E --> F[Collect feedback]
  F --> C`,
  },
  {
    id: "aif-gen18",
    domain: "genai-fundamentals",
    text: "A team wants to try foundation models from several different providers behind one API, with no servers to provision or patch, and wants to be able to switch models later with minimal code change. Which AWS service is designed for this?",
    options: [
      { id: "a", text: "Amazon Bedrock" },
      { id: "b", text: "Amazon EC2 GPU instances running a self-managed inference server" },
      { id: "c", text: "Amazon EKS with a self-hosted model serving stack" },
      { id: "d", text: "Amazon Comprehend" },
      { id: "e", text: "Amazon Kendra" },
      { id: "f", text: "Amazon Q Business" },
      { id: "g", text: "AWS Glue" },
      { id: "h", text: "The Amazon Bedrock Converse API" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Amazon Bedrock is a fully managed, serverless service that exposes foundation models from several providers, including Amazon, Anthropic, Cohere, Meta, Mistral AI, AI21 Labs, and Stability AI, through a single API, and its Converse API uses one request format for all of them, so teams can compare models and change their choice without rebuilding the application.",
    optionRationale: {
      a: "A single managed API across many model providers is exactly what Bedrock offers.",
      b: "Self-managed GPU instances mean provisioning, patching, and scaling the serving stack yourself.",
      c: "Running models on EKS gives control but leaves all the operational work with the team.",
      d: "Comprehend performs fixed natural language processing tasks and offers no model choice.",
      e: "Kendra is an intelligent search service over enterprise documents.",
      f: "Q Business is a ready-made assistant application, not a multi-provider model API.",
      g: "Glue is a data integration and ETL service.",
      h: "The Converse API gives every supported Bedrock model the same serverless request format, so switching providers is mostly a change of model ID.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html",
    referenceLabel: "What is Amazon Bedrock?",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen19",
    domain: "genai-fundamentals",
    text: "A media company will run a steady, high volume of Amazon Bedrock captioning requests all day for the next six months and needs a guaranteed level of model throughput with a predictable monthly cost. Which purchasing option fits best?",
    options: [
      { id: "a", text: "Buy Provisioned Throughput for the model, which reserves model units for a committed term at an hourly rate" },
      { id: "b", text: "Stay on on-demand pricing, which charges per input and output token with no commitment" },
      { id: "c", text: "Buy Amazon EC2 Reserved Instances for the Bedrock capacity" },
      { id: "d", text: "Request a higher requests-per-minute service quota, which reserves capacity for the account" },
      { id: "e", text: "Switch the traffic to batch inference, which guarantees interactive throughput" },
      { id: "f", text: "Lower the temperature so that each response consumes fewer tokens" },
      { id: "g", text: "Buy an EC2 Savings Plan, which also covers Bedrock token usage" },
      { id: "h", text: "Use the Amazon Bedrock Reserved service tier, which guarantees tokens-per-minute capacity for a fixed monthly price" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "On-demand invocation charges per token with no commitment and shares capacity with other customers, while Provisioned Throughput reserves model units for a committed term and the Reserved service tier reserves tokens-per-minute capacity at a fixed monthly price, both of which suit sustained high-volume traffic that needs predictable capacity and cost.",
    optionRationale: {
      a: "Provisioned Throughput is the Bedrock option that reserves capacity at a fixed hourly price for a term.",
      b: "On-demand is flexible but gives no throughput guarantee and a bill that varies with usage.",
      c: "Bedrock is serverless; there are no EC2 instances for you to reserve.",
      d: "A quota increase raises a limit but does not reserve dedicated model capacity.",
      e: "Batch inference trades latency for a lower price on large offline jobs; it is not for interactive traffic.",
      f: "Temperature changes wording, not the throughput available to the workload.",
      g: "EC2 Savings Plans cover compute usage, not Bedrock model invocation.",
      h: "The Reserved tier reserves guaranteed tokens-per-minute capacity for a one- or three-month term at a fixed price billed monthly.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/prov-throughput.html",
    referenceLabel: "Increase model invocation capacity with Provisioned Throughput",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen20",
    domain: "genai-fundamentals",
    text: "Which TWO advantages does consuming foundation models through Amazon Bedrock offer compared with hosting an open weights model yourself on GPU instances?",
    options: [
      { id: "a", text: "There is no inference infrastructure to provision, patch, or scale, because access is through a managed API" },
      { id: "b", text: "A single API lets the team compare models from several providers and switch between them with little rework" },
      { id: "c", text: "Bedrock removes the need to evaluate the quality of model output" },
      { id: "d", text: "Bedrock guarantees that every generated answer is factually correct" },
      { id: "e", text: "Bedrock is free of charge for production traffic" },
      { id: "f", text: "Every AWS Region offers exactly the same set of Bedrock models" },
      { id: "g", text: "Every prompt sent to Bedrock is used to train the provider's base model, so the model keeps improving" },
      { id: "h", text: "On-demand pricing is per token, so the team pays nothing for idle GPU capacity between requests" },
      { id: "i", text: "Managed features such as Guardrails and Knowledge Bases can be added without building them" },
      { id: "j", text: "Bedrock gives the team administrator access to the GPU servers that run each model" },
    ],
    correctOptionIds: ["a", "b", "h", "i"],
    answerType: "multi",
    explanation: "Bedrock's value is operational and strategic: AWS runs the serving infrastructure with per-token pricing and built-in features such as Guardrails and Knowledge Bases, and one API spanning many providers keeps the choice of model reversible. It does not remove the need to evaluate output, it is not free, model availability differs by Region, and your prompts and completions are not used to train the base models.",
    optionRationale: {
      a: "Serverless access removes the provisioning, patching, and scaling work of self-hosting.",
      b: "One API across providers is what makes swapping models cheap later on.",
      c: "Evaluating output for accuracy and fitness remains the customer's responsibility.",
      d: "No service can guarantee factual correctness of generated text.",
      e: "Bedrock charges per token on demand or per model unit for Provisioned Throughput.",
      f: "Model availability varies by Region, which is a real planning constraint.",
      g: "Amazon Bedrock does not use your prompts or completions to train the base foundation models.",
      h: "Pay-per-token billing charges only for actual use, whereas self-hosted GPU instances bill for every hour they run, busy or idle.",
      i: "Bedrock ships safety filtering, managed retrieval, and evaluation as built-in features that a self-hosting team would have to build and run itself.",
      j: "Bedrock is serverless, so AWS runs the hosts and customers never get access to the underlying servers.",
    },
    referenceUrl: "https://aws.amazon.com/bedrock/",
    referenceLabel: "Amazon Bedrock",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-gen21",
    domain: "genai-fundamentals",
    text: "A company wants an internal assistant that employees can ask questions in plain language, answering from the company's own documents in Amazon S3 and SharePoint, respecting each employee's existing access permissions, and it wants to build this with as little custom code as possible. Which service fits best?",
    options: [
      { id: "a", text: "A chat agent in Amazon Quick" },
      { id: "b", text: "Amazon Q Developer" },
      { id: "c", text: "PartyRock" },
      { id: "d", text: "A custom application built directly on the Amazon Bedrock API" },
      { id: "e", text: "Amazon Lex" },
      { id: "f", text: "Amazon Polly" },
      { id: "g", text: "Amazon Transcribe" },
      { id: "h", text: "Amazon Quick" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Amazon Quick, the successor to Amazon Q Business (closed to new customers on July 30, 2026), is a managed generative AI assistant for employees: it ships with connectors to common enterprise content sources such as Amazon S3 and SharePoint, can enforce the document-level permissions users already have in those sources, and its chat agents are configured rather than coded.",
    optionRationale: {
      a: "Quick chat agents answer from knowledge bases built on connectors such as Amazon S3 and SharePoint, and with document-level ACLs enabled each employee sees only content they can already access.",
      b: "Q Developer is aimed at writing and maintaining software, not at answering general employee questions.",
      c: "PartyRock is a playground for experimenting with app ideas, not an enterprise assistant over internal data.",
      d: "Building on Bedrock is possible but means writing the ingestion, retrieval, and permission handling yourself, which contradicts the low-code requirement.",
      e: "Lex builds scripted conversational bots around intents and slots.",
      f: "Polly converts text to speech.",
      g: "Transcribe converts speech to text.",
      h: "Amazon Quick, the successor to Q Business, connects to sources such as Amazon S3 and SharePoint, enforces document-level permissions, and answers employees' questions with no custom code.",
    },
    referenceUrl: "https://docs.aws.amazon.com/quick/latest/userguide/what-is.html",
    referenceLabel: "What is Amazon Quick?",
  },
  {
    id: "aif-gen22",
    domain: "genai-fundamentals",
    text: "A product manager who does not write code and has no AWS account wants to try out a small generative AI app idea in a browser before asking engineering to fund it. Which option is designed for that?",
    options: [
      { id: "a", text: "PartyRock, a hands-on Amazon Bedrock playground for building and sharing generative AI apps without writing code" },
      { id: "b", text: "An Amazon SageMaker Studio notebook" },
      { id: "c", text: "A Lambda function that calls the Amazon Bedrock InvokeModel API" },
      { id: "d", text: "An Amazon EC2 instance launched from a Deep Learning AMI" },
      { id: "e", text: "Amazon Q Developer inside an IDE" },
      { id: "f", text: "AWS CloudShell with the AWS CLI" },
      { id: "g", text: "An Amazon SageMaker JumpStart endpoint deployment" },
      { id: "h", text: "A prompt-driven Bedrock app builder that uses a social sign-in" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "PartyRock is a browser playground built on Amazon Bedrock where anyone can sign in with a social login and then assemble and share a small generative AI app from prompts alone, which makes it the usual starting point for non-developers exploring an idea.",
    optionRationale: {
      a: "No code, no AWS account, and a browser interface match this requirement precisely.",
      b: "A Studio notebook requires an AWS account and Python.",
      c: "Writing a Lambda function is development work and needs an account.",
      d: "Launching and managing an EC2 instance is well beyond a no-code exploration.",
      e: "Q Developer lives in a developer's IDE and assumes the user writes code.",
      f: "CloudShell is a command line environment inside the AWS Management Console.",
      g: "Deploying a JumpStart endpoint means managing SageMaker AI infrastructure and cost.",
      h: "This describes PartyRock, which builds a shareable generative AI app from plain-language prompts and needs only a Google, Apple, or Amazon login rather than an AWS account.",
    },
    referenceUrl: "https://partyrock.aws/",
    referenceLabel: "PartyRock, an Amazon Bedrock playground",
  },
  {
    id: "aif-gen23",
    domain: "genai-fundamentals",
    text: "A regulated customer must run a specific open weights foundation model on infrastructure inside its own account and VPC, choosing the instance type and pinning the exact model version. Which AWS capability is the best starting point?",
    options: [
      { id: "a", text: "Amazon SageMaker JumpStart, which deploys a pretrained foundation model to a SageMaker AI endpoint in the customer's own account" },
      { id: "b", text: "On-demand invocation of a serverless model in Amazon Bedrock" },
      { id: "c", text: "PartyRock" },
      { id: "d", text: "Amazon Q Business" },
      { id: "e", text: "Amazon Comprehend custom classification" },
      { id: "f", text: "Amazon Rekognition Custom Labels" },
      { id: "g", text: "Amazon Polly with a custom lexicon" },
      { id: "h", text: "Amazon Bedrock Marketplace" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "SageMaker JumpStart and Amazon Bedrock Marketplace both deploy a chosen pretrained model to a SageMaker AI endpoint the customer owns, so the team picks the instance type, keeps the model version fixed, and runs inference inside its own VPC.",
    optionRationale: {
      a: "JumpStart gives account-level control of the hosting, the instance type, and the model version.",
      b: "On-demand invocation of a serverless Bedrock model leaves AWS to choose and run the infrastructure, so the team cannot select instances or place the model in its own VPC.",
      c: "PartyRock is a public playground with no infrastructure control at all.",
      d: "Q Business is a managed assistant application, not a way to host a chosen model.",
      e: "Comprehend custom classification trains a text classifier and is not a foundation model host.",
      f: "Rekognition Custom Labels trains an image classifier for your own labels.",
      g: "A Polly lexicon adjusts pronunciation in speech synthesis.",
      h: "Bedrock Marketplace deploys a chosen model to a SageMaker AI endpoint in the customer's own account, with the instance type, instance count, and VPC settings the team selects.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/jumpstart-foundation-models.html",
    referenceLabel: "Amazon SageMaker JumpStart foundation models",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker AI console",
  },
  {
    id: "aif-gen24",
    domain: "genai-fundamentals",
    text: "An executive sponsor asks how the success of a new generative AI customer assistant will be reported to the business. Which TWO of these are business value metrics rather than model or infrastructure metrics?",
    options: [
      { id: "a", text: "Customer satisfaction score for conversations the assistant handled" },
      { id: "b", text: "Average revenue per user among customers who used the assistant" },
      { id: "c", text: "Average number of tokens consumed per request" },
      { id: "d", text: "The p99 latency of the inference endpoint in milliseconds" },
      { id: "e", text: "GPU utilization across the inference fleet" },
      { id: "f", text: "The model's score on a held-out summarization benchmark" },
      { id: "g", text: "The number of Provisioned Throughput model units purchased" },
      { id: "h", text: "Purchase conversion rate for chats handled by the assistant" },
      { id: "i", text: "Support cost saved per conversation the assistant resolved" },
      { id: "j", text: "Average time to first token for each response" },
    ],
    correctOptionIds: ["a", "b", "h", "i"],
    answerType: "multi",
    explanation: "Business value metrics for generative AI include user satisfaction, conversion rate, average revenue per user, and efficiency or cost savings; token counts, latency, hardware utilization, benchmark scores, and purchased capacity are operational and model metrics that support those outcomes without replacing them.",
    optionRationale: {
      a: "Customer satisfaction measures the outcome the assistant exists to improve.",
      b: "Average revenue per user is a standard business value metric for a customer-facing feature.",
      c: "Tokens per request is a cost and efficiency measure of the implementation.",
      d: "Endpoint latency is an operational service level measure.",
      e: "GPU utilization describes infrastructure efficiency.",
      f: "A benchmark score measures model quality rather than business outcome.",
      g: "Purchased model units are a capacity and cost input, not a result.",
      h: "Conversion rate shows whether assisted customers go on to buy, which is a direct measure of business value.",
      i: "Cost savings from conversations resolved without a human agent are a standard business value metric for an assistant.",
      j: "Time to first token is a latency measure of the serving stack, not a business outcome.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/machine-learning-lens/machine-learning-lens.html",
    referenceLabel: "AWS Well-Architected Machine Learning Lens",
  },
  {
    id: "aif-gen25",
    domain: "genai-fundamentals",
    text: "An interactive feature sorts short support messages into one of eight categories, must answer within about a second, and will handle 30 million messages a month. The team prototyped with the largest and most capable model on Amazon Bedrock and is now worried about cost and latency. What is the best first step?",
    options: [
      { id: "a", text: "Test a smaller, lower-cost model on the same task and keep it if its accuracy is good enough, because smaller models generally cost less per token and respond faster" },
      { id: "b", text: "Keep the largest model, because a larger model is always more accurate on every task" },
      { id: "c", text: "Move the traffic to batch inference, even though each message needs an immediate answer" },
      { id: "d", text: "Increase the maximum response length so that fewer calls are needed" },
      { id: "e", text: "Raise the temperature so that the responses come back shorter" },
      { id: "f", text: "Send all 30 million messages in one prompt to a model with a very large context window" },
      { id: "g", text: "Self-host the largest model on GPU instances, which is always cheaper than a managed API" },
      { id: "h", text: "Run an Amazon Bedrock model evaluation job comparing smaller models with the prototype on labeled sample messages" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Model choice is a trade-off between quality, latency, and price per token, and a short, well-defined classification task rarely needs the most capable model; the standard practice is to try a smaller and cheaper model against a representative test set and move up only if quality falls short.",
    optionRationale: {
      a: "Right-sizing the model to the task is the normal way to cut both cost and latency without harming outcomes.",
      b: "Larger models cost more and respond more slowly, and simple tasks often do not benefit from them.",
      c: "Batch inference lowers price by relaxing latency, which this interactive requirement forbids.",
      d: "A longer allowed response can increase output tokens and cost, and does not reduce the number of messages.",
      e: "Temperature affects randomness, not response length or price.",
      f: "One giant prompt would exceed any context window and would not return per-message answers.",
      g: "Self-hosting adds GPU capacity, operations, and idle time costs, and is not automatically cheaper.",
      h: "Evaluating cheaper, faster models against the prototype on representative labeled data shows whether a smaller model is accurate enough before switching.",
    },
    referenceUrl: "https://aws.amazon.com/bedrock/pricing/",
    referenceLabel: "Amazon Bedrock pricing",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
];
