import { Question } from "../../types.js";

export const responsibleAiQuestions: Question[] = [
  {
    id: "aif-ra1",
    domain: "responsible-ai",
    text: "An audit of a deployed loan model finds that applicants from one demographic group are approved far less often than comparable applicants from another group. Which AWS responsible AI dimension does this finding sit under?",
    options: [
      { id: "a", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "b", text: "Controllability: having mechanisms to monitor and steer the system's behaviour" },
      { id: "c", text: "Veracity and robustness: producing correct outputs even with unexpected or adversarial inputs" },
      { id: "d", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "e", text: "Transparency: enabling stakeholders to make informed choices about engaging with the system" },
      { id: "f", text: "Governance: building responsible practices into the AI supply chain across providers and deployers" },
      { id: "g", text: "Safety: reducing harmful system output and misuse" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS defines responsible AI through eight core dimensions: fairness, explainability, privacy and security, safety, controllability, veracity and robustness, governance, and transparency. An outcome that differs systematically between demographic groups is the definition of a fairness concern, and it is investigated with bias metrics rather than with a safety or privacy control.",
    optionRationale: {
      a: "Unequal outcomes across groups of stakeholders is exactly what the fairness dimension covers.",
      b: "Controllability is about being able to monitor, steer, and stop the system, not about the distribution of its outcomes.",
      c: "Veracity and robustness is about staying correct under odd or hostile input; the audit found a skew, not an error under stress.",
      d: "Privacy and security concerns how data and models are obtained and protected, which the finding says nothing about.",
      e: "Transparency is about telling stakeholders enough to make informed choices, which is a disclosure duty rather than the unequal outcome itself.",
      f: "Governance is about embedding practices and accountability across the AI supply chain, not about a specific measured disparity.",
      g: "Safety concerns harmful output and misuse, such as toxic or dangerous content, which is a different failure mode.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/responsible-ai.html",
    referenceLabel: "Responsible AI (AWS Well-Architected Generative AI Lens)",
  },
  {
    id: "aif-ra2",
    domain: "responsible-ai",
    text: "Which TWO of the following are core dimensions of responsible AI as AWS defines them?",
    options: [
      { id: "a", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "b", text: "Veracity and robustness: achieving correct system outputs even with unexpected or adversarial inputs" },
      { id: "c", text: "Elasticity: adding and removing capacity automatically as demand changes" },
      { id: "d", text: "Loose coupling: reducing the dependencies between components of an application" },
      { id: "e", text: "Statelessness: keeping no session data on the compute tier" },
      { id: "f", text: "Multi-tenancy: serving several customers from one set of shared infrastructure" },
      { id: "g", text: "Eventual consistency: allowing replicas to converge on a value over time" },
      { id: "h", text: "Provisioned Throughput: reserving model capacity for a predictable inference rate" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "AWS's own responsible AI framework lists eight dimensions: fairness, explainability, privacy and security, safety, controllability, veracity and robustness, governance, and transparency. The remaining options are general cloud architecture or service terms and describe how a system is built or billed, not how its AI risks are assessed.",
    optionRationale: {
      a: "Controllability is one of the eight named dimensions and carries exactly this definition.",
      b: "Veracity and robustness is one of the eight named dimensions and carries exactly this definition.",
      c: "Elasticity is a general cloud characteristic about capacity, not a responsible AI dimension.",
      d: "Loose coupling is an architectural design principle unrelated to the AI risk framework.",
      e: "Statelessness is an application design property, not a responsible AI dimension.",
      f: "Multi-tenancy describes an infrastructure sharing model rather than an AI risk dimension.",
      g: "Eventual consistency is a distributed data property and has nothing to do with responsible AI.",
      h: "Provisioned Throughput is an Amazon Bedrock purchasing option for reserved inference capacity.",
    },
    referenceUrl: "https://aws.amazon.com/ai/responsible-ai/",
    referenceLabel: "Responsible AI: Building AI Responsibly (AWS)",
  },
  {
    id: "aif-ra3",
    domain: "responsible-ai",
    text: "A company is launching a customer-facing assistant. Legal asks that every user be told plainly that they are talking to an AI system, and that the published help pages describe what the assistant is meant to be used for and where it should not be relied on. Which AWS responsible AI dimension are these measures serving?",
    options: [
      { id: "a", text: "Transparency: enabling stakeholders to make informed choices about their engagement with an AI system" },
      { id: "b", text: "Explainability: understanding and evaluating the reasons behind an individual system output" },
      { id: "c", text: "Veracity and robustness: achieving correct outputs even with unexpected or adversarial inputs" },
      { id: "d", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "e", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "f", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "g", text: "Safety: reducing harmful system output and misuse" },
    ],
    correctOptionIds: ["a"],
    explanation: "Transparency is about giving the people who interact with or are affected by an AI system enough information to decide how to engage with it: disclosing that the counterpart is an AI, and publishing intended uses and known limitations. Explainability is the neighbouring but distinct dimension of accounting for why the system produced a particular output.",
    optionRationale: {
      a: "Disclosure of AI use plus published intended uses and limitations is the textbook transparency measure.",
      b: "Explainability would mean showing why a specific answer was produced, which these measures do not attempt.",
      c: "Veracity and robustness concerns correctness under difficult inputs, not what users are told up front.",
      d: "Controllability concerns the operator's ability to monitor and steer the system, not user disclosure.",
      e: "Privacy and security concerns how data and models are handled, which the requirement does not address.",
      f: "Fairness concerns differing impacts across groups, which is not what legal asked for here.",
      g: "Safety concerns preventing harmful output and misuse rather than informing users about scope.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raigt01-bp01.html",
    referenceLabel: "RAIGT01-BP01 Develop a transparency strategy (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra4",
    domain: "responsible-ai",
    text: "Before an AI system goes live, the operations team is told it must be able to watch what the system is doing, constrain it to agreed behaviour, and shut it down or roll it back quickly if it starts behaving in a way the business did not intend. Which AWS responsible AI dimension does this requirement belong to?",
    options: [
      { id: "a", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "b", text: "Transparency: enabling stakeholders to make informed choices about their engagement with an AI system" },
      { id: "c", text: "Explainability: understanding and evaluating system outputs" },
      { id: "d", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "e", text: "Veracity and robustness: achieving correct system outputs even with unexpected or adversarial inputs" },
      { id: "f", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "g", text: "Governance: incorporating responsible practices across the AI supply chain" },
    ],
    correctOptionIds: ["a"],
    explanation: "Controllability is the dimension that covers the operator's ability to observe an AI system in production, keep it inside agreed boundaries, and intervene, including stopping or reverting it. It is the practical counterpart to governance: governance sets the policy across the supply chain, controllability is the mechanism that lets a team act on that policy at run time.",
    optionRationale: {
      a: "Monitoring, steering, and being able to stop or roll back the system is the definition of controllability.",
      b: "Transparency is about what stakeholders are told, not about the levers the operator holds.",
      c: "Explainability would mean accounting for individual outputs, which this requirement does not ask for.",
      d: "Fairness concerns differing impacts across groups, which is a separate assessment.",
      e: "Veracity and robustness concerns correctness under difficult input, not operator intervention.",
      f: "Privacy and security concerns the handling of data and models rather than run-time control.",
      g: "Governance sets the policies and accountability across providers and deployers; the mechanism that enforces them at run time is controllability.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/responsible-ai-lens.html",
    referenceLabel: "Responsible AI Lens (AWS Well-Architected Framework)",
  },
  {
    id: "aif-ra5",
    domain: "responsible-ai",
    text: "A claims triage assistant has to keep producing correct results when the text it receives contains typos, unusual formatting, or wording deliberately crafted to confuse it. Which AWS responsible AI dimension names that property?",
    options: [
      { id: "a", text: "Veracity and robustness: achieving correct system outputs even with unexpected or adversarial inputs" },
      { id: "b", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "c", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "d", text: "Transparency: enabling stakeholders to make informed choices about their engagement with an AI system" },
      { id: "e", text: "Explainability: understanding and evaluating system outputs" },
      { id: "f", text: "Governance: incorporating responsible practices across the AI supply chain" },
      { id: "g", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
    ],
    correctOptionIds: ["a"],
    explanation: "Veracity is about the system producing correct output, and robustness is about it continuing to do so when the input is noisy, out of distribution, or hostile. AWS pairs them into a single dimension because a system that is accurate only on clean input is not trustworthy in production.",
    optionRationale: {
      a: "Staying correct under unexpected and adversarial input is precisely veracity and robustness.",
      b: "Controllability is about the operator's ability to monitor and steer the system, not its resilience to odd input.",
      c: "Fairness concerns differing outcomes across groups of people, which this requirement does not mention.",
      d: "Transparency concerns what stakeholders are told about the system.",
      e: "Explainability concerns accounting for why an output was produced, not whether it survives noisy input.",
      f: "Governance concerns practices and accountability across the AI supply chain.",
      g: "Privacy and security concerns how data and models are obtained and protected.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/responsible-ai.html",
    referenceLabel: "Responsible AI (AWS Well-Architected Generative AI Lens)",
  },
  {
    id: "aif-ra6",
    domain: "responsible-ai",
    text: "A resume screening model is trained on ten years of the company's own hiring decisions. Those past decisions favoured one group of candidates, and the new model reproduces the same pattern even though no demographic field was included as a feature. What is the most likely source of the model's bias?",
    options: [
      { id: "a", text: "The historical training data encodes past human decisions, so the model learns the pattern in them, and correlated features act as proxies for the attribute that was left out" },
      { id: "b", text: "The model is overfitting because it was trained for too many epochs" },
      { id: "c", text: "The inference temperature is set too high" },
      { id: "d", text: "The model is underfitting because it has too few parameters" },
      { id: "e", text: "The endpoint instance type is too small for the request volume" },
      { id: "f", text: "The model's context window is too short for a resume" },
      { id: "g", text: "The learning rate was set too low during training" },
    ],
    correctOptionIds: ["a"],
    explanation: "A supervised model learns the relationship present in its labels. When the labels are historical human decisions that were themselves skewed, the model reproduces that skew, and dropping the sensitive attribute does not help because other features, such as postcode or the name of a school, correlate with it and serve as proxies. The fix is upstream, in how the dataset is assembled and reviewed, not in a training hyperparameter.",
    optionRationale: {
      a: "Learning from biased historical labels, with correlated features acting as proxies, is the classic source of this behaviour.",
      b: "Overfitting means the model memorises its training set and generalises poorly; here it generalises the bias faithfully, which is a data problem.",
      c: "Temperature is a generative sampling setting and does not apply to a tabular classifier's group outcomes.",
      d: "Underfitting means the model is too simple to capture the signal, which would show up as poor accuracy overall, not a consistent group skew.",
      e: "Instance size affects latency and throughput, never which candidates the model favours.",
      f: "Context window length is a property of a language model's input and would truncate text, not skew outcomes by group.",
      g: "A low learning rate slows convergence; it does not create a demographic pattern.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp03-bp02.html",
    referenceLabel: "RAIDP03-BP02 Minimize unwanted bias in your datasets (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra7",
    domain: "responsible-ai",
    text: "An image classification model performs well overall but its error rate is several times higher for one group of users. On review, that group accounted for about two percent of the training images, although it makes up a quarter of the user base. Which source of bias does this describe?",
    options: [
      { id: "a", text: "Sampling bias: the group is under-represented in the training data, so the model had too few examples to learn that part of the input space" },
      { id: "b", text: "The model is overfitting to the validation set" },
      { id: "c", text: "The model has too many features and needs dimensionality reduction" },
      { id: "d", text: "The confusion matrix was calculated on the wrong split" },
      { id: "e", text: "The inference endpoint needs a larger instance type" },
      { id: "f", text: "The model needs a longer context window" },
      { id: "g", text: "The model's temperature setting is too low" },
    ],
    correctOptionIds: ["a"],
    explanation: "When a dataset does not reflect the population the system will serve, the model learns the under-represented part of the input space poorly and its error rate there is higher. The remedy is to validate representativeness before training and to collect or augment data for the thin slices, then re-measure per-group performance rather than relying on a single overall accuracy figure.",
    optionRationale: {
      a: "A training distribution that does not match the user population is the definition of sampling bias, and it explains the per-group error gap.",
      b: "Overfitting to the validation set would degrade performance broadly rather than for one specific group.",
      c: "Feature count is unrelated to which group the model serves poorly.",
      d: "A miscomputed matrix would be a measurement error; the stem states the training data composition is the difference.",
      e: "Instance sizing changes latency and cost, never accuracy for a subgroup.",
      f: "Context window applies to language model input length, not to image classification accuracy.",
      g: "Temperature is a generative sampling parameter and does not apply to a classifier's per-group error rate.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp02-bp01.html",
    referenceLabel: "RAIDP02-BP01 Validate the representativeness of datasets for the use case (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra8",
    domain: "responsible-ai",
    text: "A content moderation dataset was sampled so that every user community is represented in proportion to its share of the platform. Even so, the trained model flags posts written in one regional dialect as abusive far more often than equivalent posts in standard usage. Reviewers find the annotation guidelines never defined how to treat dialect, and annotators applied their own judgement. What is the source of this bias?",
    options: [
      { id: "a", text: "Labeling bias introduced by the annotation process, because vague guidelines let annotators apply inconsistent, subjective judgements to the labels" },
      { id: "b", text: "Sampling bias, because the dataset does not reflect the user population" },
      { id: "c", text: "Overfitting, because the model memorised the training set" },
      { id: "d", text: "Data drift, because the input distribution has moved since training" },
      { id: "e", text: "An inference temperature that is set too high" },
      { id: "f", text: "An undersized endpoint instance type" },
      { id: "g", text: "A learning rate that was set too high during training" },
    ],
    correctOptionIds: ["a"],
    explanation: "Bias can enter at collection, at labeling, or through the choice of target variable. Here the collection step is stated to be proportionate, so the skew came from the labels: without clear, tested instructions, annotators fall back on personal judgement, and the model faithfully learns their inconsistency. Written guidelines, annotator training, and measuring agreement between annotators are the standard mitigations, and Amazon SageMaker Ground Truth supports them with labeling instructions and annotation consolidation.",
    optionRationale: {
      a: "Subjective labels produced under vague guidelines are the definition of labeling bias, and the stem rules out the alternatives.",
      b: "The stem explicitly says the sample matches the population in proportion, so sampling is not the cause.",
      c: "Overfitting is about failing to generalise beyond the training data; here the model generalises the labelers' judgement accurately.",
      d: "Data drift is a change in production input after deployment, whereas this flaw was baked in before training.",
      e: "Temperature is a generative sampling setting and does not affect a moderation classifier's labels.",
      f: "Instance sizing affects latency and cost, not which posts are flagged.",
      g: "A high learning rate can destabilise training but cannot create a dialect-specific pattern that the labels did not contain.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/sms.html",
    referenceLabel: "Training data labeling using humans with Amazon SageMaker Ground Truth",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra9",
    domain: "responsible-ai",
    text: "Before any training job runs, a team wants to measure whether its labeled dataset is already skewed with respect to a demographic attribute, for example whether one group is under-represented or receives the positive label less often than another. Which capability produces those measurements?",
    options: [
      { id: "a", text: "An Amazon SageMaker Clarify pre-training bias analysis, which computes metrics such as class imbalance and difference in proportions of labels for the facet you nominate" },
      { id: "b", text: "Amazon SageMaker Model Monitor, which compares live endpoint traffic against a baseline" },
      { id: "c", text: "Amazon Bedrock Guardrails" },
      { id: "d", text: "An Amazon SageMaker model card" },
      { id: "e", text: "Amazon Augmented AI (A2I)" },
      { id: "f", text: "A SageMaker automatic model tuning job" },
      { id: "g", text: "Amazon Comprehend sentiment analysis over the dataset" },
      { id: "h", text: "An Amazon Bedrock model evaluation job" },
    ],
    correctOptionIds: ["a"],
    explanation: "SageMaker Clarify runs as a processing job and has two bias modes. The pre-training mode looks only at the dataset and its labels, before a model exists, and reports metrics such as class imbalance and difference in proportions of labels across the facet you nominate. That is exactly the question of whether the data itself is skewed.",
    optionRationale: {
      a: "Pre-training bias metrics are computed on the dataset alone, which is what the team needs before training starts.",
      b: "Model Monitor needs a deployed endpoint and live traffic, so it cannot be used before a model exists.",
      c: "Guardrails filter content in Amazon Bedrock prompts and responses; they do not analyse a training dataset.",
      d: "A model card documents a model once it exists; it does not compute dataset statistics.",
      e: "A2I routes production predictions to human reviewers and has no dataset analysis function.",
      f: "Automatic model tuning searches hyperparameters for better accuracy and reports no bias metrics.",
      g: "Comprehend returns sentiment for text and says nothing about demographic skew in labels.",
      h: "A Bedrock evaluation job scores generative model output, not the balance of a labeled training set.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-data-bias.html",
    referenceLabel: "Pre-training bias metrics in Amazon SageMaker Clarify",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra10",
    domain: "responsible-ai",
    text: "A model has finished training. The compliance team now asks a different question: do the model's own predictions fall differently across a demographic facet, for example does one group receive the favourable predicted outcome less often than another? Which analysis answers that?",
    options: [
      { id: "a", text: "An Amazon SageMaker Clarify post-training bias analysis, which compares the model's predictions across the facet using metrics such as difference in positive proportions in predicted labels" },
      { id: "b", text: "A Clarify pre-training bias analysis, which examines the dataset and its labels and never looks at the model's predictions" },
      { id: "c", text: "Overall accuracy on the held-out test set" },
      { id: "d", text: "Root mean squared error on the held-out test set" },
      { id: "e", text: "A Model Monitor data quality baseline over the training data" },
      { id: "f", text: "An Amazon Augmented AI human review loop" },
      { id: "g", text: "An Amazon Bedrock guardrail with a denied topic" },
      { id: "h", text: "The model's parameter count" },
    ],
    correctOptionIds: ["a"],
    explanation: "Clarify's post-training bias metrics run after training and compare outcomes that the model predicts for each facet value, with measures such as difference in positive proportions in predicted labels, disparate impact, and accuracy difference. Pre-training metrics cannot answer this because they only see the dataset, and a single overall accuracy figure hides differences between groups entirely.",
    optionRationale: {
      a: "Post-training bias metrics are defined over the model's predictions across the facet, which is precisely the question asked.",
      b: "Pre-training metrics describe the dataset before a model exists and therefore cannot describe predictions.",
      c: "A single accuracy number aggregates over everyone and conceals differences between groups.",
      d: "RMSE summarises numeric error for a regression model and reports nothing per group.",
      e: "A data quality baseline captures statistics and constraints for drift detection, not outcome disparity.",
      f: "A2I routes individual predictions to human reviewers; it does not compute group statistics.",
      g: "Guardrails screen generative content in Amazon Bedrock and compute no bias metrics.",
      h: "Parameter count describes model size and measures nothing about fairness.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-post-training-bias.html",
    referenceLabel: "Post-training data and model bias metrics in Amazon SageMaker Clarify",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra11",
    domain: "responsible-ai",
    text: "A declined applicant asks why the model rejected their specific application. The team needs, for that one prediction, a signed contribution from each input feature showing how much it pushed the decision toward or away from approval. Which Amazon SageMaker Clarify output provides it?",
    options: [
      { id: "a", text: "Feature attributions computed with Shapley values (SHAP), which assign each feature a contribution to that individual prediction" },
      { id: "b", text: "The confusion matrix for the test set" },
      { id: "c", text: "The model's overall accuracy" },
      { id: "d", text: "The pre-training class imbalance metric for the dataset" },
      { id: "e", text: "The F1 score of the classifier" },
      { id: "f", text: "The area under the ROC curve" },
      { id: "g", text: "The training job's loss curve" },
      { id: "h", text: "The number of training epochs the job completed" },
    ],
    correctOptionIds: ["a"],
    explanation: "SageMaker Clarify explains predictions with SHAP, a model-agnostic method that distributes the difference between a prediction and a baseline across the input features. Clarify reports both global attributions, which rank feature importance across the dataset, and local attributions for an individual record, which is what an adverse-action explanation needs.",
    optionRationale: {
      a: "SHAP feature attribution is designed to attribute a single prediction to its input features, which is exactly what the applicant is owed.",
      b: "A confusion matrix summarises correct and incorrect predictions across a whole dataset, not one decision.",
      c: "Accuracy is a single aggregate figure and explains nothing about an individual case.",
      d: "Class imbalance describes the dataset's composition before training, not this prediction.",
      e: "F1 balances precision and recall over a set of predictions and is not per-record.",
      f: "AUC-ROC summarises ranking quality across thresholds for the whole model.",
      g: "A loss curve shows how training progressed, which tells the applicant nothing.",
      h: "Epoch count is a training detail with no bearing on why one application was declined.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-shapley-values.html",
    referenceLabel: "Feature attributions that use Shapley values (Amazon SageMaker Clarify)",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra12",
    domain: "responsible-ai",
    text: "Amazon SageMaker Model Monitor can watch a deployed endpoint for data quality drift and model quality drift. Which TWO additional monitoring types does it offer that speak directly to responsible AI?",
    options: [
      { id: "a", text: "Bias drift, which recomputes bias metrics on live inference data and compares them with a baseline" },
      { id: "b", text: "Feature attribution drift, which detects when the relative importance of the model's input features shifts away from the baseline" },
      { id: "c", text: "Prompt injection attempts found in the request payload" },
      { id: "d", text: "The per-request token price charged for the endpoint" },
      { id: "e", text: "Changes made to the endpoint's IAM execution role policy" },
      { id: "f", text: "Changes to the default encryption setting of the model artifact's Amazon S3 bucket" },
      { id: "g", text: "The number of Amazon Bedrock guardrail versions in the account" },
      { id: "h", text: "The query latency of the application's vector store" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Model Monitor supports four monitor types: data quality, model quality, bias drift, and feature attribution drift. The last two are backed by SageMaker Clarify: bias drift re-measures fairness metrics against the constraints captured at baseline, and feature attribution drift compares the ranked SHAP importances of live traffic with the baseline, which catches a model whose reasoning has moved even while its headline accuracy looks stable.",
    optionRationale: {
      a: "Bias drift monitoring is one of the four Model Monitor types and is the one that keeps fairness under watch after launch.",
      b: "Feature attribution drift is the fourth type and tracks how the model's explanation profile changes over time.",
      c: "Prompt attack detection is an Amazon Bedrock Guardrails policy, not a SageMaker Model Monitor type.",
      d: "Cost per request is reported through billing and Cost Explorer, not by Model Monitor.",
      e: "IAM policy changes are recorded by AWS CloudTrail and assessed by AWS Config, not by Model Monitor.",
      f: "Bucket encryption settings are an Amazon S3 and AWS Config concern, outside Model Monitor's scope.",
      g: "Guardrail versions live in Amazon Bedrock and have no relationship to a SageMaker endpoint monitor.",
      h: "Vector store latency is an application performance metric, typically watched in Amazon CloudWatch.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor.html",
    referenceLabel: "Data and model quality monitoring with Amazon SageMaker Model Monitor",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra13",
    domain: "responsible-ai",
    text: "A credit model's fairness was assessed and signed off at launch. A year later the applicant population has shifted noticeably. The team wants a scheduled job that recomputes bias metrics on the live endpoint's traffic, compares them with the constraints captured at launch, and raises an alert when they move outside the agreed range. What should they set up?",
    options: [
      { id: "a", text: "An Amazon SageMaker Model Monitor bias drift monitoring schedule, which uses SageMaker Clarify to compare captured inference data against the baseline constraints and emits Amazon CloudWatch metrics" },
      { id: "b", text: "Re-run the original Clarify pre-training bias analysis on the training dataset that was used a year ago" },
      { id: "c", text: "Attach an Amazon Bedrock guardrail to the credit model's endpoint" },
      { id: "d", text: "Create an Amazon SageMaker model card and update it once a year" },
      { id: "e", text: "Send every prediction to an Amazon Augmented AI human review loop" },
      { id: "f", text: "Create an Amazon CloudWatch billing alarm on the endpoint's monthly cost" },
      { id: "g", text: "Enable AWS CloudTrail data events for the endpoint" },
    ],
    correctOptionIds: ["a"],
    explanation: "Bias measured once at launch goes stale as the population changes. Model Monitor's bias drift monitor enables data capture on the endpoint, runs a scheduled Clarify job over the captured records, and compares the resulting metrics with the baseline constraints, publishing CloudWatch metrics that an alarm can act on. That is continuous fairness monitoring rather than a one-off assessment.",
    optionRationale: {
      a: "A scheduled bias drift monitor over captured live traffic is exactly the mechanism for detecting fairness drift after launch.",
      b: "Re-running the analysis on last year's training data measures the same old dataset and can never reveal a shift in today's applicants.",
      c: "Amazon Bedrock guardrails screen generative text content; they do not compute bias metrics and are not attached to a SageMaker endpoint serving a tabular credit model.",
      d: "A model card is documentation of the model; it records findings but detects nothing on its own.",
      e: "Reviewing every prediction by hand is not a metric comparison and would not scale for a credit decisioning endpoint.",
      f: "A billing alarm watches spend and says nothing about fairness.",
      g: "CloudTrail data events log who called the endpoint, which is an audit trail rather than a bias measurement.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-model-monitor-bias-drift.html",
    referenceLabel: "Monitor bias drift for models in production (Amazon SageMaker AI)",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra14",
    domain: "responsible-ai",
    text: "An insurer extracts fields from scanned claim forms automatically. Any extraction whose confidence score falls below a set threshold must be sent to a trained reviewer, shown in a review interface, and the reviewer's corrected value must flow back into the downstream workflow. Which AWS service is built for this?",
    options: [
      { id: "a", text: "Amazon Augmented AI (A2I), which defines a human review workflow with an activation condition on confidence, a worker task template, and a workforce, and returns the reviewed result to Amazon S3" },
      { id: "b", text: "Amazon SageMaker Ground Truth, which builds labeled datasets for training rather than reviewing live production predictions" },
      { id: "c", text: "Amazon SageMaker Model Monitor" },
      { id: "d", text: "Amazon SageMaker Clarify" },
      { id: "e", text: "An Amazon Bedrock guardrail with a sensitive information filter" },
      { id: "f", text: "Raise the confidence threshold and discard every extraction that falls below it" },
      { id: "g", text: "Post each low-confidence extraction to Amazon Mechanical Turk and collect the answers yourself" },
    ],
    correctOptionIds: ["a"],
    explanation: "Amazon A2I is the managed human-in-the-loop service for production inference. You define a flow definition with the conditions under which a prediction is sent for review, a worker task template for the reviewer interface, and a workforce that can be your own employees, a vendor, or Amazon Mechanical Turk. A2I creates a human loop for each qualifying prediction and writes the reviewed output to Amazon S3, which is what keeps a person in the loop where the model is least certain.",
    optionRationale: {
      a: "Confidence-triggered review with a task template, a workforce, and a returned result is exactly what A2I provides.",
      b: "Ground Truth annotates datasets used to train a model; it is not triggered by a production prediction's confidence.",
      c: "Model Monitor detects drift against a baseline and routes nothing to a person.",
      d: "Clarify measures bias and produces feature attributions; it has no review workflow.",
      e: "A sensitive information filter masks PII in Amazon Bedrock traffic and has no bearing on extraction confidence.",
      f: "Discarding uncertain extractions loses the claim data entirely, which is the opposite of reviewing it.",
      g: "Mechanical Turk can supply the workforce, but on its own you would still have to build the triggering conditions, the review interface, and the result handling that A2I gives you.",
    },
    diagram: `flowchart LR
  D[Scanned claim] --> M[Model extracts fields]
  M --> C{Confidence below threshold?}
  C -- No --> W[Downstream workflow]
  C -- Yes --> H[A2I human loop]
  H --> R[Reviewer corrects value]
  R --> W`,
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/a2i-use-augmented-ai-a2i-human-review-loops.html",
    referenceLabel: "Using Amazon Augmented AI for human review",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra15",
    domain: "responsible-ai",
    text: "What does reinforcement learning from human feedback (RLHF) contribute to a foundation model?",
    options: [
      { id: "a", text: "People rank or rate candidate responses, those preferences train a reward model, and the reward model is then used to further train the foundation model so its output aligns better with human judgements of helpfulness and harmlessness" },
      { id: "b", text: "It produces the labels for a supervised training dataset before any model exists" },
      { id: "c", text: "It compresses the model's weights so that inference uses less memory" },
      { id: "d", text: "It caches previous responses so that repeated questions are answered without calling the model" },
      { id: "e", text: "It guarantees that the model's answers are factually correct" },
      { id: "f", text: "It encrypts prompts and responses in transit" },
      { id: "g", text: "It increases the number of tokens the model can accept in one request" },
    ],
    correctOptionIds: ["a"],
    explanation: "RLHF adds human preference to training. Reviewers compare candidate responses to the same prompt, their rankings are used to fit a reward model that scores responses the way people would, and the foundation model is then optimised against that reward. It is the standard way of aligning a model with human expectations, but it shifts the model's behaviour toward preferred answers rather than proving any answer true.",
    optionRationale: {
      a: "Human rankings, a learned reward model, and further training against that reward is the definition of RLHF.",
      b: "Producing labels for a supervised dataset is data annotation, for example with SageMaker Ground Truth.",
      c: "Shrinking weights describes quantisation or distillation, which are efficiency techniques.",
      d: "Reusing earlier responses describes caching, a latency and cost optimisation.",
      e: "Alignment to human preference reduces unhelpful and harmful output but cannot guarantee factual correctness.",
      f: "Encryption in transit is a transport security control configured outside the model.",
      g: "The context window is fixed by the model architecture and is not changed by RLHF.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/reinforcement-learning-from-human-feedback/",
    referenceLabel: "What is RLHF (reinforcement learning from human feedback)? (AWS)",
  },
  {
    id: "aif-ra16",
    domain: "responsible-ai",
    text: "Clinicians will act on the output of a triage model. The design team is deciding how the prediction should be presented. Which approach best reflects human-centered design for explainable AI?",
    options: [
      { id: "a", text: "Show the prediction together with the factors that contributed most to it and how confident the model is, and let the clinician record a different decision" },
      { id: "b", text: "Show only the final recommendation, so that clinicians are not distracted by the model's reasoning" },
      { id: "c", text: "Hide the confidence score, because an uncertain number would undermine trust in the system" },
      { id: "d", text: "Apply the model's recommendation automatically and notify the clinician afterwards, to remove human error from the process" },
      { id: "e", text: "Raise the model's temperature so the wording of the recommendation sounds more natural" },
      { id: "f", text: "Publish the model's weights on the intranet so that any clinician can inspect them" },
      { id: "g", text: "Increase the training batch size so the model converges on a more confident answer" },
    ],
    correctOptionIds: ["a"],
    explanation: "Human-centered design starts from the person who has to act. In a high-consequence workflow that means giving the reviewer the information needed for an informed judgement, which is the contributing factors, the model's uncertainty, and comparable cases, and keeping the human able to disagree. Oversight that is designed into the interface is what makes explainability useful rather than merely available.",
    optionRationale: {
      a: "Contributing factors, a confidence signal, and a genuine override are exactly the elements that make human oversight effective.",
      b: "Withholding the reasoning leaves the clinician unable to judge whether the recommendation applies to this patient.",
      c: "Concealing uncertainty invites over-reliance on the model precisely when it is least reliable.",
      d: "Removing the human from a high-consequence clinical decision is the opposite of human-centered design.",
      e: "Temperature changes the phrasing of generated text and adds nothing to the clinician's understanding.",
      f: "Raw weights are not interpretable by a clinician and disclose nothing useful about an individual case.",
      g: "Batch size is a training hyperparameter and has no effect on how the output is presented or understood.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raiuc04-bp02.html",
    referenceLabel: "RAIUC04-BP02 Identify human oversight opportunities (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra17",
    domain: "responsible-ai",
    text: "A retail bank's assistant must never give personalised investment advice, however a customer phrases the request, and the same rule has to hold across the three different foundation models the bank calls. Which control enforces this most reliably?",
    options: [
      { id: "a", text: "Configure a denied topic in an Amazon Bedrock guardrail, describing the topic and giving sample phrasings in natural language, and apply that one guardrail to every model the application calls" },
      { id: "b", text: "Add a line to each system prompt telling the model not to give investment advice, and rely on the model to obey it" },
      { id: "c", text: "Fine-tune each of the three models so that it refuses investment questions" },
      { id: "d", text: "Lower the temperature so that the model's answers become more conservative" },
      { id: "e", text: "Enable a contextual grounding check so that answers stay close to the retrieved passages" },
      { id: "f", text: "Enable a sensitive information filter so that account numbers are masked in responses" },
      { id: "g", text: "Buy Provisioned Throughput for the three models" },
    ],
    correctOptionIds: ["a"],
    explanation: "A denied topic is defined in natural language with a short description and example utterances, and the guardrail blocks matching content in both the prompt and the response, returning your configured message instead. Because a guardrail is a separate resource evaluated around the model, one guardrail can be applied to several models and to agents, which gives a single, auditable place where the bank's policy lives.",
    optionRationale: {
      a: "A denied topic applied through one shared guardrail enforces the policy outside the model and consistently across all three.",
      b: "A prompt instruction is guidance the model may fail to follow, and it has to be duplicated and kept in step in three places.",
      c: "Fine-tuning three models to refuse is expensive, slow to change, and still probabilistic rather than an enforced block.",
      d: "Temperature changes how varied the wording is; it does not stop the model discussing a subject.",
      e: "A contextual grounding check reduces claims unsupported by retrieved passages, which is about factual grounding rather than a forbidden subject.",
      f: "A sensitive information filter masks personal data and does nothing about the topic of the conversation.",
      g: "Provisioned Throughput reserves inference capacity and applies no content policy at all.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-denied-topics.html",
    referenceLabel: "Block denied topics to help remove harmful content (Amazon Bedrock Guardrails)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
    cliExample: {
      description: "List the guardrails defined in the account so the shared policy can be reused.",
      command: "aws bedrock list-guardrails --query 'guardrails[].{name:name,status:status}' --output table",
      sampleOutput: "|  bank-assistant-policy  |  READY  |",
    },
  },
  {
    id: "aif-ra18",
    domain: "responsible-ai",
    text: "A public-facing assistant occasionally returns insults and hateful phrasing. The safety team wants to set, per harmful category, how aggressively such content is blocked, and to have the check applied to both what users send and what the model returns. Which Amazon Bedrock Guardrails policy does this?",
    options: [
      { id: "a", text: "Content filters, which let you set a filter strength for categories such as hate, insults, sexual content, violence, and misconduct, and apply it to prompts and to responses" },
      { id: "b", text: "The denied topics policy, which blocks specific subjects you describe yourself rather than offering tunable strengths for standard harm categories" },
      { id: "c", text: "The word filter, which blocks an exact list of words and phrases you supply" },
      { id: "d", text: "The sensitive information filter, which blocks or masks personally identifiable information" },
      { id: "e", text: "The contextual grounding check, which scores how far a response is supported by the passages supplied to it" },
      { id: "f", text: "Provisioned Throughput for the model" },
      { id: "g", text: "Prompt caching for the model" },
    ],
    correctOptionIds: ["a"],
    explanation: "Content filters are the harmful-content policy inside a guardrail. Each category has a configurable strength, so a team can be strict about hate and more permissive elsewhere, and the filter is evaluated on the input and on the output. This is the control that supports the safety dimension of responsible AI for a public audience.",
    optionRationale: {
      a: "Per-category, adjustable filtering of harmful content on both prompt and response is exactly what content filters provide.",
      b: "Denied topics block subjects you define in your own words and have no per-category harm strengths.",
      c: "A word filter is an exact match list, which cannot cover the many ways an insult can be phrased.",
      d: "Sensitive information filters address personal data leakage, not toxicity.",
      e: "The contextual grounding check targets unsupported claims in retrieval-based answers.",
      f: "Provisioned Throughput reserves capacity and enforces no content policy.",
      g: "Prompt caching reduces cost and latency for a repeated prompt prefix and filters nothing.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-content-filters.html",
    referenceLabel: "Block harmful words and conversations with content filters (Amazon Bedrock Guardrails)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-ra19",
    domain: "responsible-ai",
    text: "An internal model risk committee wants, for each version of each model the company builds, a single record holding the intended use, a risk rating, the datasets and training details, the evaluation results, and the reviewer's sign-off, so that it can be produced on demand during an audit. Which AWS capability is purpose-built for that record?",
    options: [
      { id: "a", text: "Amazon SageMaker Model Cards, which capture intended uses, risk rating, training and evaluation details, and an approval status for each model version" },
      { id: "b", text: "An AWS AI Service Card, which AWS publishes about its own AI services rather than about a model your team builds" },
      { id: "c", text: "An Amazon Bedrock guardrail" },
      { id: "d", text: "Amazon SageMaker Model Monitor" },
      { id: "e", text: "A SageMaker Clarify bias report on its own" },
      { id: "f", text: "AWS Artifact" },
      { id: "g", text: "A plain text README stored beside the model artifact in Amazon S3" },
    ],
    correctOptionIds: ["a"],
    explanation: "A SageMaker model card is a structured, versioned document attached to a model: model overview and owner, intended uses and risk rating, training details and datasets, evaluation results and metrics, and a status that moves from draft to pending review to approved. It is the governance artifact that turns scattered notes into something an auditor can be handed.",
    optionRationale: {
      a: "Model cards are designed to hold exactly these fields per model version, with an approval status for sign-off.",
      b: "AI Service Cards are AWS's transparency documents for AWS AI services and models; you do not author one for your own model.",
      c: "A guardrail filters content at inference time and documents nothing.",
      d: "Model Monitor detects drift on a live endpoint; it records no intended use or risk rating.",
      e: "A bias report is one useful input to a model card, not the record of intended use and approval.",
      f: "AWS Artifact provides AWS compliance reports and agreements, not documentation of your models.",
      g: "A free-form README has no schema, no version linkage, and no approval workflow, which is what the committee needs.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-cards.html",
    referenceLabel: "Amazon SageMaker Model Cards",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
    cliExample: {
      description: "List the model cards in the account with their approval status.",
      command: "aws sagemaker list-model-cards --query 'ModelCardSummaries[].{Name:ModelCardName,Status:ModelCardStatus}' --output table",
      sampleOutput: "|  claims-triage-v3  |  Approved  |",
    },
  },
  {
    id: "aif-ra20",
    domain: "responsible-ai",
    text: "Before approving a customer-facing feature built on an AWS AI service, a risk reviewer asks for AWS's own published account of that service's intended use cases, its limitations, the responsible AI design choices behind it, and best practices for deploying it well. What should the team point the reviewer to?",
    options: [
      { id: "a", text: "The AWS AI Service Card for that service, which AWS publishes as a responsible AI transparency document covering intended uses, limitations, design choices, and deployment best practices" },
      { id: "b", text: "An Amazon SageMaker model card, which the team authors about a model it builds itself" },
      { id: "c", text: "AWS Artifact, which provides AWS audit reports and compliance agreements" },
      { id: "d", text: "The service's API reference, which documents request and response syntax" },
      { id: "e", text: "AWS Trusted Advisor checks for the account" },
      { id: "f", text: "A SageMaker Clarify explainability report for the service" },
      { id: "g", text: "An AWS Config conformance pack" },
    ],
    correctOptionIds: ["a"],
    explanation: "AWS AI Service Cards are AWS's transparency resource for its own AI services and models. Each card sets out the use cases the service is intended for, how machine learning is used, key limitations, the responsible AI design choices AWS made across dimensions such as fairness, explainability, veracity and robustness, privacy and security, safety, controllability, governance, and transparency, and guidance on deploying and optimising the service. It is the right artifact for assessing a supplied service, as opposed to a model you trained yourself.",
    optionRationale: {
      a: "An AI Service Card is precisely the AWS-published document containing intended uses, limitations, and responsible design choices for an AWS AI service.",
      b: "A model card documents a model your own team builds and would not describe AWS's design choices for its service.",
      c: "AWS Artifact supplies compliance reports such as SOC and ISO attestations, not AI transparency documentation.",
      d: "An API reference explains how to call the service, not how it behaves or where it should not be used.",
      e: "Trusted Advisor inspects your account for cost, security, and quota recommendations.",
      f: "Clarify explains models you train and deploy in SageMaker, not a managed AWS AI service.",
      g: "A Config conformance pack evaluates your resource configurations against rules.",
    },
    referenceUrl: "https://aws.amazon.com/ai/responsible-ai/resources/",
    referenceLabel: "Responsible AI tools and resources, including AWS AI Service Cards (AWS)",
  },
  {
    id: "aif-ra21",
    domain: "responsible-ai",
    text: "In responsible AI, how do interpretability and explainability differ?",
    options: [
      { id: "a", text: "Interpretability is the degree to which a person can understand the model's mechanism by inspecting the model itself, whereas explainability is being able to account for the model's outputs, typically with post-hoc techniques, even when the mechanism stays opaque" },
      { id: "b", text: "Interpretability is the ability to account for outputs after the fact, whereas explainability means a person can read the model's internal logic directly" },
      { id: "c", text: "They are two names for the same property, so the terms can be used interchangeably" },
      { id: "d", text: "Interpretability means the model is accurate, and explainability means the model is fair" },
      { id: "e", text: "Interpretability measures how quickly the model returns a prediction, and explainability measures how much it costs" },
      { id: "f", text: "Interpretability applies only to generative models and explainability only to classifiers" },
      { id: "g", text: "Explainability is measured with ROUGE and interpretability with BLEU" },
    ],
    correctOptionIds: ["a"],
    explanation: "A model is interpretable when a person can follow its mechanism directly, as with a small decision tree or a linear model whose coefficients can be read. A model is explainable when its behaviour can be accounted for, usually with post-hoc methods such as SHAP feature attribution, even though the internals are too complex to read. Explainability techniques therefore let a team reason about an opaque model without making that model interpretable.",
    optionRationale: {
      a: "Understanding the mechanism directly versus accounting for outputs after the fact is the accepted distinction.",
      b: "This reverses the two definitions.",
      c: "The terms are related but distinct; treating them as identical loses the point that an opaque model can still be explained.",
      d: "Accuracy and fairness are separate properties and neither term means either of them.",
      e: "Latency and cost are operational measures unconnected to these terms.",
      f: "Both concepts apply across model types, including classic classifiers and foundation models.",
      g: "ROUGE and BLEU are text generation quality metrics and measure neither concept.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/model-explainability-aws-ai-ml/interpretability-versus-explainability.html",
    referenceLabel: "Interpretability versus explainability (AWS model explainability whitepaper)",
  },
  {
    id: "aif-ra22",
    domain: "responsible-ai",
    text: "A regulator requires that a lender be able to show, from the structure of the model itself, how each declined application was decided. The data science team has two candidates: a shallow decision tree whose rules can be read directly, and a deep ensemble that scores two points higher on accuracy but whose internals cannot be followed. How should the team resolve the trade-off?",
    options: [
      { id: "a", text: "Choose the inherently interpretable decision tree, because the regulatory need for a model whose logic can be inspected outweighs a small accuracy gain" },
      { id: "b", text: "Always choose the model with the highest accuracy, because predictive performance is the only criterion that matters" },
      { id: "c", text: "Deploy the ensemble and skip the documentation, since the accuracy gain justifies it" },
      { id: "d", text: "There is no trade-off, because deep ensembles are inherently interpretable" },
      { id: "e", text: "Deploy the ensemble and raise its inference temperature, which makes any model interpretable" },
      { id: "f", text: "Deploy the ensemble and train it for more epochs, which will make its logic readable" },
      { id: "g", text: "Deploy the ensemble and tell the regulator that explanations are impossible for modern models" },
    ],
    correctOptionIds: ["a"],
    explanation: "Model choice is a responsible AI decision, not only an accuracy decision. There is a genuine tension between predictive power and transparency: simpler model families are easier to inspect, while higher-capacity models often score better and are opaque. Where a regulator requires the logic itself to be inspectable, post-hoc explanation of an opaque model does not satisfy the requirement, so the interpretable model wins despite the small loss in accuracy.",
    optionRationale: {
      a: "Weighing a hard transparency requirement against a marginal accuracy gain and choosing the inspectable model is the correct resolution.",
      b: "Treating accuracy as the only criterion ignores the regulatory, fairness, and transparency constraints on the workload.",
      c: "Skipping documentation would breach the requirement outright and leave the lender unable to justify decisions.",
      d: "Deep ensembles combine many high-capacity models and are a standard example of an opaque one.",
      e: "Temperature is a generative sampling setting and has nothing to do with a credit classifier's transparency.",
      f: "More epochs changes the fitted weights, never the readability of the model's structure.",
      g: "Explanations are possible for opaque models through post-hoc methods, so the claim is untrue as well as unhelpful.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/explainable-ai/",
    referenceLabel: "What is explainable AI? (AWS)",
  },
  {
    id: "aif-ra23",
    domain: "responsible-ai",
    text: "A team is assembling the training dataset for a model that will serve a broad public audience. Which TWO practices most directly reduce unwanted bias in that dataset?",
    options: [
      { id: "a", text: "Check that every group the system will serve appears in the data in sufficient numbers, and collect more data for the groups that are thin" },
      { id: "b", text: "Write explicit labeling guidelines, train the annotators on them, and measure agreement between annotators" },
      { id: "c", text: "Increase the learning rate so the model converges faster on the data already collected" },
      { id: "d", text: "Train for more epochs on the same data" },
      { id: "e", text: "Drop the validation split so that all records can be used for training" },
      { id: "f", text: "Duplicate the existing majority-group records to make the dataset larger" },
      { id: "g", text: "Raise the model's inference temperature" },
      { id: "h", text: "Deploy the model on a larger instance type" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "Unwanted bias is addressed in the data, before training. Validating that the dataset represents the population the system will serve prevents whole groups being learned poorly, and disciplined labeling, with written guidelines and measured inter-annotator agreement, stops subjective judgements entering through the labels. Training settings and infrastructure choices cannot undo either problem.",
    optionRationale: {
      a: "Representativeness across the groups the system serves is the first defence against unequal error rates.",
      b: "Clear guidelines and measured annotator agreement keep subjective judgement out of the labels.",
      c: "The learning rate governs the speed and stability of optimisation, not the composition of the data.",
      d: "More passes over a skewed dataset reinforces the skew rather than correcting it.",
      e: "Removing the validation split destroys the team's ability to detect the problem and adds no new data.",
      f: "Duplicating majority records makes the imbalance worse, not better.",
      g: "Temperature is a generative sampling setting applied at inference and has no effect on the dataset.",
      h: "Instance size affects throughput and cost only.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp03.html",
    referenceLabel: "Dataset issues (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra24",
    domain: "responsible-ai",
    text: "A marketing team wants to publish copy written by a foundation model without review. Which TWO risks should the legal and risk team raise?",
    options: [
      { id: "a", text: "Generated text may reproduce material that closely resembles copyrighted work, which can expose the company to an intellectual property claim" },
      { id: "b", text: "A confident but fabricated statement about a product, published and acted on by customers, can cause real harm and damage trust in the brand" },
      { id: "c", text: "Using a foundation model transfers all legal liability for the published content to the model provider" },
      { id: "d", text: "Text produced by a foundation model is automatically in the public domain, so competitors may reuse it freely" },
      { id: "e", text: "Foundation models cannot produce text in more than one language, so international campaigns will fail" },
      { id: "f", text: "Organisations that use foundation models are exempt from data protection law for the resulting content" },
      { id: "g", text: "The model's context window shrinks each time it is called, so later copy will be shorter" },
      { id: "h", text: "Enabling prompt caching voids the provider's service terms" },
    ],
    correctOptionIds: ["a", "b"],
    explanation: "The two risks that most often bite an unreviewed generative workflow are intellectual property, because generated output can resemble protected material, and veracity, because a fluent hallucination published as fact can mislead customers and erode trust. Neither risk is removed by using a managed service, so review of high-visibility output, grounding in approved source material, and content policy controls remain the team's responsibility.",
    optionRationale: {
      a: "Output that resembles copyrighted work is a recognised intellectual property risk of generative AI.",
      b: "A fluent, confident falsehood published without review is the hallucination risk and directly damages customer trust.",
      c: "Responsibility for how output is used stays with the customer; provider indemnities are limited and conditional and do not remove that duty.",
      d: "Copyright status of generated content is unsettled and varies by jurisdiction; it is not automatically public domain.",
      e: "Many foundation models are explicitly multilingual, so this is simply untrue.",
      f: "No exemption from data protection law exists for content produced with AI.",
      g: "The context window is a fixed property of the model and does not shrink with use.",
      h: "Prompt caching is a supported cost and latency feature, not a terms violation.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/machine-learning/aws-reaffirms-its-commitment-to-responsible-generative-ai/",
    referenceLabel: "AWS reaffirms its commitment to responsible generative AI",
  },
  {
    id: "aif-ra25",
    domain: "responsible-ai",
    text: "A sustainability review asks the team to cut the environmental footprint of a new generative AI feature. Which choice reduces it the most?",
    options: [
      { id: "a", text: "Start from an existing pre-trained foundation model and adapt it with prompting or light customisation, because pre-training a model from scratch consumes far more compute and energy than anything downstream" },
      { id: "b", text: "Pre-train a new model from scratch on the company's own corpus so that it is exactly the right size" },
      { id: "c", text: "Always select the model with the largest parameter count available" },
      { id: "d", text: "Raise the maximum response length on every request so that answers are never truncated" },
      { id: "e", text: "Run inference on the largest available accelerated instance whatever the traffic level" },
      { id: "f", text: "Turn off auto scaling so that capacity is always provisioned for the annual peak" },
      { id: "g", text: "Replicate the training dataset into every AWS Region for faster access" },
    ],
    correctOptionIds: ["a"],
    explanation: "Pre-training dominates the energy cost of a foundation model, so the single largest sustainability lever is to reuse a model somebody has already trained and adapt it, rather than training one from scratch. After that, choosing the smallest model that meets the requirement, using optimised inference, and letting capacity scale with demand keep the running footprint down.",
    optionRationale: {
      a: "Avoiding a from-scratch pre-training run removes by far the largest block of compute and energy in the lifecycle.",
      b: "Pre-training from scratch is the most energy-intensive option available and is what the review would want avoided.",
      c: "A larger model costs more compute for every single request, increasing the footprint rather than reducing it.",
      d: "A higher output ceiling means more tokens generated per call, which increases energy use.",
      e: "Over-provisioned accelerators idle at low traffic and waste energy.",
      f: "Provisioning permanently for peak leaves capacity running and consuming power when it is not needed.",
      g: "Copying data into every Region multiplies the storage and replication footprint without reducing compute.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/gensus03-bp01.html",
    referenceLabel: "GENSUS03-BP01 Leverage smaller models and optimized inference techniques to reduce carbon footprint",
  },
];
