import { Question } from "../../types.js";

export const responsibleAiQuestions: Question[] = [
  {
    id: "aif-ra1",
    domain: "responsible-ai",
    text: "An audit of a deployed loan model finds that applicants from one demographic group are approved far less often than comparable applicants from another group. Which AWS responsible AI dimension does this finding sit under?",
    options: [
      { id: "a", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "b", text: "Controllability: having mechanisms to monitor and steer the system's behaviour" },
      { id: "c", text: "Veracity and robustness: producing correct outputs even with unexpected or adversarial inputs" },
      { id: "d", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "e", text: "Transparency: enabling stakeholders to make informed choices about engaging with the system" },
      { id: "f", text: "Governance: building responsible practices into the AI supply chain across providers and deployers" },
      { id: "g", text: "Safety: reducing harmful system output and misuse" },
      { id: "h", text: "Fairness: checking that outcomes do not systematically favor one population over another" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "AWS defines responsible AI through eight core dimensions: fairness, explainability, privacy and security, safety, controllability, veracity and robustness, governance, and transparency. An outcome that differs systematically between demographic groups is the definition of a fairness concern, and it is investigated with bias metrics rather than with a safety or privacy control.",
    optionRationale: {
      a: "Unequal outcomes across groups of stakeholders is exactly what the fairness dimension covers.",
      b: "Controllability is about being able to monitor, steer, and stop the system, not about the distribution of its outcomes.",
      c: "Veracity and robustness is about staying correct under odd or hostile input; the audit found a skew, not an error under stress.",
      d: "Privacy and security concerns how data and models are obtained and protected, which the finding says nothing about.",
      e: "Transparency is about telling stakeholders enough to make informed choices, which is a disclosure duty rather than the unequal outcome itself.",
      f: "Governance is about embedding practices and accountability across the AI supply chain, not about a specific measured disparity.",
      g: "Safety concerns harmful output and misuse, such as toxic or dangerous content, which is a different failure mode.",
      h: "A systematic gap in approval rates between comparable groups is exactly what the fairness dimension evaluates, using bias metrics.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/responsible-ai.html",
    referenceLabel: "Responsible AI (AWS Well-Architected Generative AI Lens)",
  },
  {
    id: "aif-ra2",
    domain: "responsible-ai",
    text: "Which TWO of the following are core dimensions of responsible AI as AWS defines them?",
    options: [
      { id: "a", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "b", text: "Veracity and robustness: achieving correct system outputs even with unexpected or adversarial inputs" },
      { id: "c", text: "Elasticity: adding and removing capacity automatically as demand changes" },
      { id: "d", text: "Loose coupling: reducing the dependencies between components of an application" },
      { id: "e", text: "Statelessness: keeping no session data on the compute tier" },
      { id: "f", text: "Multi-tenancy: serving several customers from one set of shared infrastructure" },
      { id: "g", text: "Eventual consistency: allowing replicas to converge on a value over time" },
      { id: "h", text: "Provisioned Throughput: reserving model capacity for a predictable inference rate" },
      { id: "i", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "j", text: "Explainability: understanding and evaluating system outputs" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "AWS's own responsible AI framework lists eight dimensions: fairness, explainability, privacy and security, safety, controllability, veracity and robustness, governance, and transparency. The remaining options are general cloud architecture or service terms and describe how a system is built or billed, not how its AI risks are assessed.",
    optionRationale: {
      a: "Controllability is one of the eight named dimensions and carries exactly this definition.",
      b: "Veracity and robustness is one of the eight named dimensions and carries exactly this definition.",
      c: "Elasticity is a general cloud characteristic about capacity, not a responsible AI dimension.",
      d: "Loose coupling is an architectural design principle unrelated to the AI risk framework.",
      e: "Statelessness is an application design property, not a responsible AI dimension.",
      f: "Multi-tenancy describes an infrastructure sharing model rather than an AI risk dimension.",
      g: "Eventual consistency is a distributed data property and has nothing to do with responsible AI.",
      h: "Provisioned Throughput is an Amazon Bedrock purchasing option for reserved inference capacity.",
      i: "Fairness is one of the eight named dimensions and carries exactly this definition.",
      j: "Explainability is one of the eight named dimensions and carries exactly this definition.",
    },
    referenceUrl: "https://aws.amazon.com/ai/responsible-ai/",
    referenceLabel: "Responsible AI: Building AI Responsibly (AWS)",
  },
  {
    id: "aif-ra3",
    domain: "responsible-ai",
    text: "A company is launching a customer-facing assistant. Legal asks that every user be told plainly that they are talking to an AI system, and that the published help pages describe what the assistant is meant to be used for and where it should not be relied on. Which AWS responsible AI dimension are these measures serving?",
    options: [
      { id: "a", text: "Transparency: enabling stakeholders to make informed choices about their engagement with an AI system" },
      { id: "b", text: "Explainability: understanding and evaluating the reasons behind an individual system output" },
      { id: "c", text: "Veracity and robustness: achieving correct outputs even with unexpected or adversarial inputs" },
      { id: "d", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "e", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "f", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "g", text: "Safety: reducing harmful system output and misuse" },
      { id: "h", text: "Transparency: sharing clear information about an AI system so people can calibrate their trust in it" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Transparency is about giving the people who interact with or are affected by an AI system enough information to decide how to engage with it: disclosing that the counterpart is an AI, and publishing intended uses and known limitations. Explainability is the neighbouring but distinct dimension of accounting for why the system produced a particular output.",
    optionRationale: {
      a: "Disclosure of AI use plus published intended uses and limitations is the textbook transparency measure.",
      b: "Explainability would mean showing why a specific answer was produced, which these measures do not attempt.",
      c: "Veracity and robustness concerns correctness under difficult inputs, not what users are told up front.",
      d: "Controllability concerns the operator's ability to monitor and steer the system, not user disclosure.",
      e: "Privacy and security concerns how data and models are handled, which the requirement does not address.",
      f: "Fairness concerns differing impacts across groups, which is not what legal asked for here.",
      g: "Safety concerns preventing harmful output and misuse rather than informing users about scope.",
      h: "Giving people the information they need to decide how far to trust and use an AI system is the purpose of the transparency dimension.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raigt01-bp01.html",
    referenceLabel: "RAIGT01-BP01 Develop a transparency strategy (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra4",
    domain: "responsible-ai",
    text: "Before an AI system goes live, the operations team is told it must be able to watch what the system is doing, constrain it to agreed behaviour, and shut it down or roll it back quickly if it starts behaving in a way the business did not intend. Which AWS responsible AI dimension does this requirement belong to?",
    options: [
      { id: "a", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "b", text: "Transparency: enabling stakeholders to make informed choices about their engagement with an AI system" },
      { id: "c", text: "Explainability: understanding and evaluating system outputs" },
      { id: "d", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "e", text: "Veracity and robustness: achieving correct system outputs even with unexpected or adversarial inputs" },
      { id: "f", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "g", text: "Governance: incorporating responsible practices across the AI supply chain" },
      { id: "h", text: "Controllability: keeping human oversight effective by being able to adjust or intervene in the system" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Controllability is the dimension that covers the operator's ability to observe an AI system in production, keep it inside agreed boundaries, and intervene, including stopping or reverting it. It is the practical counterpart to governance: governance sets the policy across the supply chain, controllability is the mechanism that lets a team act on that policy at run time.",
    optionRationale: {
      a: "Monitoring, steering, and being able to stop or roll back the system is the definition of controllability.",
      b: "Transparency is about what stakeholders are told, not about the levers the operator holds.",
      c: "Explainability would mean accounting for individual outputs, which this requirement does not ask for.",
      d: "Fairness concerns differing impacts across groups, which is a separate assessment.",
      e: "Veracity and robustness concerns correctness under difficult input, not operator intervention.",
      f: "Privacy and security concerns the handling of data and models rather than run-time control.",
      g: "Governance sets the policies and accountability across providers and deployers; the mechanism that enforces them at run time is controllability.",
      h: "Human oversight backed by the ability to adjust or intervene in a live system is what the controllability dimension describes.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/responsible-ai-lens.html",
    referenceLabel: "Responsible AI Lens (AWS Well-Architected Framework)",
  },
  {
    id: "aif-ra5",
    domain: "responsible-ai",
    text: "A claims triage assistant has to keep producing correct results when the text it receives contains typos, unusual formatting, or wording deliberately crafted to confuse it. Which AWS responsible AI dimension names that property?",
    options: [
      { id: "a", text: "Veracity and robustness: achieving correct system outputs even with unexpected or adversarial inputs" },
      { id: "b", text: "Controllability: having mechanisms to monitor and steer AI system behaviour" },
      { id: "c", text: "Fairness: considering the impact of the system on different groups of stakeholders" },
      { id: "d", text: "Transparency: enabling stakeholders to make informed choices about their engagement with an AI system" },
      { id: "e", text: "Explainability: understanding and evaluating system outputs" },
      { id: "f", text: "Governance: incorporating responsible practices across the AI supply chain" },
      { id: "g", text: "Privacy and security: obtaining, using, and protecting data and models appropriately" },
      { id: "h", text: "Veracity and robustness: delivering reliable, truthful results consistently, even in unexpected situations" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Veracity is about the system producing correct output, and robustness is about it continuing to do so when the input is noisy, out of distribution, or hostile. AWS pairs them into a single dimension because a system that is accurate only on clean input is not trustworthy in production.",
    optionRationale: {
      a: "Staying correct under unexpected and adversarial input is precisely veracity and robustness.",
      b: "Controllability is about the operator's ability to monitor and steer the system, not its resilience to odd input.",
      c: "Fairness concerns differing outcomes across groups of people, which this requirement does not mention.",
      d: "Transparency concerns what stakeholders are told about the system.",
      e: "Explainability concerns accounting for why an output was produced, not whether it survives noisy input.",
      f: "Governance concerns practices and accountability across the AI supply chain.",
      g: "Privacy and security concerns how data and models are obtained and protected.",
      h: "Consistently reliable and truthful output, including under unexpected conditions, is the veracity and robustness dimension.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/responsible-ai.html",
    referenceLabel: "Responsible AI (AWS Well-Architected Generative AI Lens)",
  },
  {
    id: "aif-ra6",
    domain: "responsible-ai",
    text: "A resume screening model is trained on ten years of the company's own hiring decisions. Those past decisions favoured one group of candidates, and the new model reproduces the same pattern even though no demographic field was included as a feature. What is the most likely source of the model's bias?",
    options: [
      { id: "a", text: "The historical training data encodes past human decisions, so the model learns the pattern in them, and correlated features act as proxies for the attribute that was left out" },
      { id: "b", text: "The model is overfitting because it was trained for too many epochs" },
      { id: "c", text: "The inference temperature is set too high" },
      { id: "d", text: "The model is underfitting because it has too few parameters" },
      { id: "e", text: "The endpoint instance type is too small for the request volume" },
      { id: "f", text: "The model's context window is too short for a resume" },
      { id: "g", text: "The learning rate was set too low during training" },
      { id: "h", text: "Historical bias in the labels, carried through proxy features for the omitted attribute" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "A supervised model learns the relationship present in its labels. When the labels are historical human decisions that were themselves skewed, the model reproduces that skew, and dropping the sensitive attribute does not help because other features, such as postcode or the name of a school, correlate with it and serve as proxies. The fix is upstream, in how the dataset is assembled and reviewed, not in a training hyperparameter.",
    optionRationale: {
      a: "Learning from biased historical labels, with correlated features acting as proxies, is the classic source of this behaviour.",
      b: "Overfitting means the model memorises its training set and generalises poorly; here it generalises the bias faithfully, which is a data problem.",
      c: "Temperature is a generative sampling setting and does not apply to a tabular classifier's group outcomes.",
      d: "Underfitting means the model is too simple to capture the signal, which would show up as poor accuracy overall, not a consistent group skew.",
      e: "Instance size affects latency and throughput, never which candidates the model favours.",
      f: "Context window length is a property of a language model's input and would truncate text, not skew outcomes by group.",
      g: "A low learning rate slows convergence; it does not create a demographic pattern.",
      h: "Labels that record past skewed decisions carry historical bias, and features correlated with the omitted attribute let the model reproduce it.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp03-bp02.html",
    referenceLabel: "RAIDP03-BP02 Minimize unwanted bias in your datasets (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra7",
    domain: "responsible-ai",
    text: "An image classification model performs well overall but its error rate is several times higher for one group of users. On review, that group accounted for about two percent of the training images, although it makes up a quarter of the user base. Which source of bias does this describe?",
    options: [
      { id: "a", text: "Sampling bias: the group is under-represented in the training data, so the model had too few examples to learn that part of the input space" },
      { id: "b", text: "The model is overfitting to the validation set" },
      { id: "c", text: "The model has too many features and needs dimensionality reduction" },
      { id: "d", text: "The confusion matrix was calculated on the wrong split" },
      { id: "e", text: "The inference endpoint needs a larger instance type" },
      { id: "f", text: "The model needs a longer context window" },
      { id: "g", text: "The model's temperature setting is too low" },
      { id: "h", text: "Representation bias: the group is too thinly covered in the training data" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "When a dataset does not reflect the population the system will serve, the model learns the under-represented part of the input space poorly and its error rate there is higher. The remedy is to validate representativeness before training and to collect or augment data for the thin slices, then re-measure per-group performance rather than relying on a single overall accuracy figure.",
    optionRationale: {
      a: "A training distribution that does not match the user population is the definition of sampling bias, and it explains the per-group error gap.",
      b: "Overfitting to the validation set would degrade performance broadly rather than for one specific group.",
      c: "Feature count is unrelated to which group the model serves poorly.",
      d: "A miscomputed matrix would be a measurement error; the stem states the training data composition is the difference.",
      e: "Instance sizing changes latency and cost, never accuracy for a subgroup.",
      f: "Context window applies to language model input length, not to image classification accuracy.",
      g: "Temperature is a generative sampling parameter and does not apply to a classifier's per-group error rate.",
      h: "Representation bias is the term for a training set in which part of the served population has too few examples, which produces the per-group error gap described.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp02-bp01.html",
    referenceLabel: "RAIDP02-BP01 Validate the representativeness of datasets for the use case (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra8",
    domain: "responsible-ai",
    text: "A content moderation dataset was sampled so that every user community is represented in proportion to its share of the platform. Even so, the trained model flags posts written in one regional dialect as abusive far more often than equivalent posts in standard usage. Reviewers find the annotation guidelines never defined how to treat dialect, and annotators applied their own judgement. What is the source of this bias?",
    options: [
      { id: "a", text: "Labeling bias introduced by the annotation process, because vague guidelines let annotators apply inconsistent, subjective judgements to the labels" },
      { id: "b", text: "Sampling bias, because the dataset does not reflect the user population" },
      { id: "c", text: "Overfitting, because the model memorised the training set" },
      { id: "d", text: "Data drift, because the input distribution has moved since training" },
      { id: "e", text: "An inference temperature that is set too high" },
      { id: "f", text: "An undersized endpoint instance type" },
      { id: "g", text: "A learning rate that was set too high during training" },
      { id: "h", text: "Annotator bias, where labelers' subjective views became the ground truth" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Bias can enter at collection, at labeling, or through the choice of target variable. Here the collection step is stated to be proportionate, so the skew came from the labels: without clear, tested instructions, annotators fall back on personal judgement, and the model faithfully learns their inconsistency. Written guidelines, annotator training, gold-standard test items, and measuring agreement between annotators are the standard mitigations, as the AWS Well-Architected Responsible AI Lens recommends.",
    optionRationale: {
      a: "Subjective labels produced under vague guidelines are the definition of labeling bias, and the stem rules out the alternatives.",
      b: "The stem explicitly says the sample matches the population in proportion, so sampling is not the cause.",
      c: "Overfitting is about failing to generalise beyond the training data; here the model generalises the labelers' judgement accurately.",
      d: "Data drift is a change in production input after deployment, whereas this flaw was baked in before training.",
      e: "Temperature is a generative sampling setting and does not affect a moderation classifier's labels.",
      f: "Instance sizing affects latency and cost, not which posts are flagged.",
      g: "A high learning rate can destabilise training but cannot create a dialect-specific pattern that the labels did not contain.",
      h: "Inconsistent, subjective judgements by the people producing the labels are annotator bias, and the model learned them as if they were correct.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp02-bp03.html",
    referenceLabel: "RAIDP02-BP03 Validate the quality of human and generated labels (Responsible AI Lens)",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra9",
    domain: "responsible-ai",
    text: "Before any training job runs, a team wants to measure whether its labeled dataset is already skewed with respect to a demographic attribute, for example whether one group is under-represented or receives the positive label less often than another. Which capability produces those measurements?",
    options: [
      { id: "a", text: "A pre-training bias analysis that computes metrics such as class imbalance on the labeled dataset" },
      { id: "b", text: "Amazon SageMaker Model Monitor, which compares live endpoint traffic against a baseline" },
      { id: "c", text: "Amazon Bedrock Guardrails" },
      { id: "d", text: "An Amazon SageMaker model card" },
      { id: "e", text: "Amazon Augmented AI (A2I)" },
      { id: "f", text: "A SageMaker automatic model tuning job" },
      { id: "g", text: "Amazon Comprehend sentiment analysis over the dataset" },
      { id: "h", text: "An Amazon Bedrock model evaluation job" },
      { id: "i", text: "A Data Wrangler bias report in Amazon SageMaker Canvas" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Pre-training bias metrics look only at the dataset and its labels, before a model exists, and report measures such as class imbalance and difference in proportions of labels across the facet you nominate. SageMaker Clarify computed them in processing jobs but closed to new customers on July 30, 2026, and AWS now recommends computing the same published formulas directly with pandas and scikit-learn; the bias report in Data Wrangler within SageMaker Canvas also produces them without code. That is exactly the question of whether the data itself is skewed.",
    optionRationale: {
      a: "A pre-training bias analysis looks only at the labeled dataset, so it measures skew such as class imbalance and difference in proportions of labels before any training runs; the metrics are published formulas a team can compute directly with pandas and scikit-learn.",
      b: "Model Monitor needs a deployed endpoint and live traffic, so it cannot be used before a model exists.",
      c: "Guardrails filter content in Amazon Bedrock prompts and responses; they do not analyse a training dataset.",
      d: "A model card documents a model once it exists; it does not compute dataset statistics.",
      e: "A2I routes production predictions to human reviewers and has no dataset analysis function.",
      f: "Automatic model tuning searches hyperparameters for better accuracy and reports no bias metrics.",
      g: "Comprehend returns sentiment for text and says nothing about demographic skew in labels.",
      h: "A Bedrock evaluation job scores generative model output, not the balance of a labeled training set.",
      i: "The Data Wrangler bias report computes pre-training bias metrics, such as class imbalance, on the dataset for a chosen label and facet before any model exists.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-data-bias.html",
    referenceLabel: "Pre-training bias metrics in Amazon SageMaker Clarify",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra10",
    domain: "responsible-ai",
    text: "A model has finished training. The compliance team now asks a different question: do the model's own predictions fall differently across a demographic facet, for example does one group receive the favourable predicted outcome less often than another? Which analysis answers that?",
    options: [
      { id: "a", text: "A post-training bias analysis that compares the model's predictions across the facet groups" },
      { id: "b", text: "A Clarify pre-training bias analysis, which examines the dataset and its labels and never looks at the model's predictions" },
      { id: "c", text: "Overall accuracy on the held-out test set" },
      { id: "d", text: "Root mean squared error on the held-out test set" },
      { id: "e", text: "A Model Monitor data quality baseline over the training data" },
      { id: "f", text: "An Amazon Augmented AI human review loop" },
      { id: "g", text: "An Amazon Bedrock guardrail with a denied topic" },
      { id: "h", text: "The model's parameter count" },
      { id: "i", text: "Disparate impact measured on the model's predictions across the facet" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "Post-training bias metrics run after training and compare the outcomes the model predicts for each facet value, with measures such as difference in positive proportions in predicted labels, disparate impact, and accuracy difference. SageMaker Clarify computed them but closed to new customers on July 30, 2026, and AWS now recommends computing the same published formulas directly from the predictions with pandas and scikit-learn. Pre-training metrics cannot answer this because they only see the dataset, and a single overall accuracy figure hides differences between groups entirely.",
    optionRationale: {
      a: "Post-training bias metrics, such as difference in positive proportions in predicted labels, are defined over the model's predictions across the facet, which is precisely the question asked.",
      b: "Pre-training metrics describe the dataset before a model exists and therefore cannot describe predictions.",
      c: "A single accuracy number aggregates over everyone and conceals differences between groups.",
      d: "RMSE summarises numeric error for a regression model and reports nothing per group.",
      e: "A data quality baseline captures statistics and constraints for drift detection, not outcome disparity.",
      f: "A2I routes individual predictions to human reviewers; it does not compute group statistics.",
      g: "Guardrails screen generative content in Amazon Bedrock and compute no bias metrics.",
      h: "Parameter count describes model size and measures nothing about fairness.",
      i: "Disparate impact is a post-training bias metric that compares the rates of favorable predicted outcomes between the facet groups.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-post-training-bias.html",
    referenceLabel: "Post-training data and model bias metrics in Amazon SageMaker Clarify",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra11",
    domain: "responsible-ai",
    text: "A declined applicant asks why the model rejected their specific application. The team needs, for that one prediction, a signed contribution from each input feature showing how much it pushed the decision toward or away from approval. Which explainability output provides it?",
    options: [
      { id: "a", text: "Feature attributions computed with Shapley values (SHAP), which assign each feature a contribution to that individual prediction" },
      { id: "b", text: "The confusion matrix for the test set" },
      { id: "c", text: "The model's overall accuracy" },
      { id: "d", text: "The pre-training class imbalance metric for the dataset" },
      { id: "e", text: "The F1 score of the classifier" },
      { id: "f", text: "The area under the ROC curve" },
      { id: "g", text: "The training job's loss curve" },
      { id: "h", text: "The number of training epochs the job completed" },
      { id: "i", text: "Local feature attributions for the individual record" },
    ],
    correctOptionIds: ["a", "i"],
    answerType: "single",
    explanation: "SHAP is a model-agnostic method that distributes the difference between a prediction and a baseline across the input features. It yields global attributions, which rank feature importance across the dataset, and local attributions for an individual record, which is what an adverse-action explanation needs. SageMaker Clarify, which is built on the SHAP library, closed to new customers on July 30, 2026, and AWS now recommends using the SHAP library directly.",
    optionRationale: {
      a: "SHAP feature attribution is designed to attribute a single prediction to its input features, which is exactly what the applicant is owed.",
      b: "A confusion matrix summarises correct and incorrect predictions across a whole dataset, not one decision.",
      c: "Accuracy is a single aggregate figure and explains nothing about an individual case.",
      d: "Class imbalance describes the dataset's composition before training, not this prediction.",
      e: "F1 balances precision and recall over a set of predictions and is not per-record.",
      f: "AUC-ROC summarises ranking quality across thresholds for the whole model.",
      g: "A loss curve shows how training progressed, which tells the applicant nothing.",
      h: "Epoch count is a training detail with no bearing on why one application was declined.",
      i: "Local explanations, such as SHAP values for a single record, attribute that one prediction to its input features, giving each feature a signed contribution.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-shapley-values.html",
    referenceLabel: "Feature attributions that use Shapley values (Amazon SageMaker Clarify)",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra12",
    domain: "responsible-ai",
    text: "Amazon SageMaker Model Monitor watches a deployed endpoint on a schedule. Which TWO of the following are monitoring types it offers?",
    options: [
      { id: "a", text: "Bias drift, which recomputes bias metrics on live inference data and compares them with a baseline" },
      { id: "b", text: "Feature attribution drift, which detects when the relative importance of the model's input features shifts away from the baseline" },
      { id: "c", text: "Prompt injection attempts found in the request payload" },
      { id: "d", text: "The per-request token price charged for the endpoint" },
      { id: "e", text: "Changes made to the endpoint's IAM execution role policy" },
      { id: "f", text: "Changes to the default encryption setting of the model artifact's Amazon S3 bucket" },
      { id: "g", text: "The number of Amazon Bedrock guardrail versions in the account" },
      { id: "h", text: "The query latency of the application's vector store" },
      { id: "i", text: "Data quality, which compares live input statistics with a baseline to detect drift" },
      { id: "j", text: "Model quality, which compares predictions with ground truth labels to track accuracy" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Model Monitor supports four monitor types: data quality, model quality, bias drift, and feature attribution drift. The first two compare live inputs and prediction accuracy with a baseline, while the last two are backed by SageMaker Clarify and keep fairness and the model's explanation profile under watch after launch. Model Monitor closed to new customers on July 30, 2026; existing customers keep using it, and AWS points new users to its open-source SageMaker AI monitoring solutions with Amazon CloudWatch.",
    optionRationale: {
      a: "Bias drift monitoring is one of the four Model Monitor types and is the one that keeps fairness under watch after launch.",
      b: "Feature attribution drift is the fourth type and tracks how the model's explanation profile changes over time.",
      c: "Prompt attack detection is an Amazon Bedrock Guardrails policy, not a SageMaker Model Monitor type.",
      d: "Cost per request is reported through billing and Cost Explorer, not by Model Monitor.",
      e: "IAM policy changes are recorded by AWS CloudTrail and assessed by AWS Config, not by Model Monitor.",
      f: "Bucket encryption settings are an Amazon S3 and AWS Config concern, outside Model Monitor's scope.",
      g: "Guardrail versions live in Amazon Bedrock and have no relationship to a SageMaker endpoint monitor.",
      h: "Vector store latency is an application performance metric, typically watched in Amazon CloudWatch.",
      i: "Data quality monitoring is one of the four Model Monitor types and flags drift in the statistics of live input data.",
      j: "Model quality monitoring is one of the four Model Monitor types and tracks metrics such as accuracy by merging predictions with ground truth.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor.html",
    referenceLabel: "Data and model quality monitoring with Amazon SageMaker Model Monitor",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra13",
    domain: "responsible-ai",
    text: "A credit model's fairness was assessed and signed off at launch. A year later the applicant population has shifted noticeably. The team wants to check on an ongoing basis whether the model's outcomes for each group have drifted from what was approved at launch, and to be alerted when they move outside the agreed range. What should they set up?",
    options: [
      { id: "a", text: "An EventBridge-scheduled job that recomputes bias metrics on captured endpoint traffic and alerts through Amazon SNS" },
      { id: "b", text: "Re-run the original Clarify pre-training bias analysis on the training dataset that was used a year ago" },
      { id: "c", text: "Attach an Amazon Bedrock guardrail to the credit model's endpoint" },
      { id: "d", text: "Create an Amazon SageMaker model card and update it once a year" },
      { id: "e", text: "Send every prediction to an Amazon Augmented AI human review loop" },
      { id: "f", text: "Create an Amazon CloudWatch billing alarm on the endpoint's monthly cost" },
      { id: "g", text: "Enable AWS CloudTrail data events for the endpoint" },
      { id: "h", text: "Capture endpoint traffic and schedule a job that compares per-facet outcome metrics with the launch baseline" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Bias measured once at launch goes stale as the population changes. Continuous fairness monitoring captures the endpoint's inference data, runs a scheduled job, for example triggered by Amazon EventBridge, that recomputes the bias metrics for each facet, compares them with the thresholds agreed at launch, and alerts through Amazon SNS when a gap crosses them. SageMaker Model Monitor's bias drift monitor offered this as a managed feature but closed to new customers on July 30, 2026, and AWS now points to its open-source SageMaker AI monitoring solutions, which run this pattern with Evidently AI and SageMaker AI MLflow.",
    optionRationale: {
      a: "Recomputing the bias metrics on a schedule over captured live traffic, comparing them with the launch thresholds, and alerting on a breach is the continuous fairness check the team needs, and it is the pattern AWS's open-source SageMaker AI monitoring solutions use.",
      b: "Re-running the analysis on last year's training data measures the same old dataset and can never reveal a shift in today's applicants.",
      c: "Amazon Bedrock guardrails screen generative text content; they do not compute bias metrics and are not attached to a SageMaker endpoint serving a tabular credit model.",
      d: "A model card is documentation of the model; it records findings but detects nothing on its own.",
      e: "Reviewing every prediction by hand is not a metric comparison and would not scale for a credit decisioning endpoint.",
      f: "A billing alarm watches spend and says nothing about fairness.",
      g: "CloudTrail data events log who called the endpoint, which is an audit trail rather than a bias measurement.",
      h: "Recomputing per-facet metrics such as selection rate on the captured inference data at each run, and alerting when the gap moves outside the agreed range, detects fairness drift as the population changes.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-availability-change.html",
    referenceLabel: "Amazon SageMaker Model Monitor availability change (replacing bias drift monitoring)",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
  },
  {
    id: "aif-ra14",
    domain: "responsible-ai",
    text: "An insurer extracts fields from scanned claim forms automatically. Any extraction whose confidence score falls below a set threshold must wait for a trained reviewer to check it, and the reviewer's corrected value must flow back into the downstream workflow. Which approach fits this requirement?",
    options: [
      { id: "a", text: "An AWS Step Functions workflow that pauses on a callback task token until the reviewer returns the corrected value" },
      { id: "b", text: "Amazon SageMaker Ground Truth, which builds labeled datasets for training rather than reviewing live production predictions" },
      { id: "c", text: "Amazon SageMaker Model Monitor" },
      { id: "d", text: "Amazon SageMaker Clarify" },
      { id: "e", text: "An Amazon Bedrock guardrail with a sensitive information filter" },
      { id: "f", text: "Raise the confidence threshold and discard every extraction that falls below it" },
      { id: "g", text: "Post each low-confidence extraction to Amazon Mechanical Turk and collect the answers yourself" },
      { id: "h", text: "A Step Functions Choice state on the confidence score that sends uncertain extractions to a human review task" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Amazon Augmented AI (A2I), the managed human review service that Amazon Textract integrates with, closed to new customers on July 30, 2026, so a new build orchestrates the review loop itself. In AWS Step Functions, a Choice state compares each extraction's confidence score with the threshold, and a task using the .waitForTaskToken callback pattern pauses the execution while a trained reviewer checks the value in the insurer's own review application. When the application returns the token with the corrected value, the workflow resumes and passes it downstream, keeping a person in the loop where the model is least certain.",
    optionRationale: {
      a: "A task using the .waitForTaskToken callback pattern pauses the execution at the review step, and when the reviewer's application returns the token with the corrected value, the workflow resumes with it.",
      b: "Ground Truth annotates datasets used to train a model; it is not triggered by a production prediction's confidence.",
      c: "Model Monitor detects drift against a baseline and routes nothing to a person.",
      d: "Clarify measures bias and produces feature attributions; it has no review workflow.",
      e: "A sensitive information filter masks PII in Amazon Bedrock traffic and has no bearing on extraction confidence.",
      f: "Discarding uncertain extractions loses the claim data entirely, which is the opposite of reviewing it.",
      g: "Mechanical Turk closed to new customers on July 30, 2026 and closes permanently on September 30, 2026, and a public crowd is not a trained reviewer for personal claim data in any case.",
      h: "The Choice state compares each confidence score with the threshold and routes only the uncertain extractions to a review task, which waits for the reviewer's decision before passing the corrected value downstream.",
    },
    diagram: "flowchart LR\n  D[Scanned claim] --> M[Model extracts fields]\n  M --> C{Confidence below threshold?}\n  C -- No --> W[Downstream workflow]\n  C -- Yes --> H[Review task waits for callback]\n  H --> R[Reviewer corrects value]\n  R --> W",
    referenceUrl: "https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html",
    referenceLabel: "Service integration patterns in Step Functions (wait for a callback with a task token)",
    consoleUrl: "https://console.aws.amazon.com/states/",
    consoleLabel: "AWS Step Functions console",
  },
  {
    id: "aif-ra15",
    domain: "responsible-ai",
    text: "What does reinforcement learning from human feedback (RLHF) contribute to a foundation model?",
    options: [
      { id: "a", text: "People rank or rate candidate responses, those preferences train a reward model, and the reward model is then used to further train the foundation model so its output aligns better with human judgements of helpfulness and harmlessness" },
      { id: "b", text: "It produces the labels for a supervised training dataset before any model exists" },
      { id: "c", text: "It compresses the model's weights so that inference uses less memory" },
      { id: "d", text: "It caches previous responses so that repeated questions are answered without calling the model" },
      { id: "e", text: "It guarantees that the model's answers are factually correct" },
      { id: "f", text: "It encrypts prompts and responses in transit" },
      { id: "g", text: "It increases the number of tokens the model can accept in one request" },
      { id: "h", text: "It aligns the model with human preferences, making responses more helpful and less likely to be harmful" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "RLHF adds human preference to training. Reviewers compare candidate responses to the same prompt, their rankings are used to fit a reward model that scores responses the way people would, and the foundation model is then optimised against that reward. It is the standard way of aligning a model with human expectations, but it shifts the model's behaviour toward preferred answers rather than proving any answer true.",
    optionRationale: {
      a: "Human rankings, a learned reward model, and further training against that reward is the definition of RLHF.",
      b: "Producing labels for a supervised dataset is data annotation, for example with SageMaker Ground Truth.",
      c: "Shrinking weights describes quantisation or distillation, which are efficiency techniques.",
      d: "Reusing earlier responses describes caching, a latency and cost optimisation.",
      e: "Alignment to human preference reduces unhelpful and harmful output but cannot guarantee factual correctness.",
      f: "Encryption in transit is a transport security control configured outside the model.",
      g: "The context window is fixed by the model architecture and is not changed by RLHF.",
      h: "Aligning a model's behavior with what people prefer, typically toward helpful and harmless output, is the contribution RLHF is used for.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/reinforcement-learning-from-human-feedback/",
    referenceLabel: "What is RLHF (reinforcement learning from human feedback)? (AWS)",
  },
  {
    id: "aif-ra16",
    domain: "responsible-ai",
    text: "Clinicians will act on the output of a triage model. The design team is deciding how the prediction should be presented. Which approach best reflects human-centered design for explainable AI?",
    options: [
      { id: "a", text: "Show the prediction together with the factors that contributed most to it and how confident the model is, and let the clinician record a different decision" },
      { id: "b", text: "Show only the final recommendation, so that clinicians are not distracted by the model's reasoning" },
      { id: "c", text: "Hide the confidence score, because an uncertain number would undermine trust in the system" },
      { id: "d", text: "Apply the model's recommendation automatically and notify the clinician afterwards, to remove human error from the process" },
      { id: "e", text: "Raise the model's temperature so the wording of the recommendation sounds more natural" },
      { id: "f", text: "Publish the model's weights on the intranet so that any clinician can inspect them" },
      { id: "g", text: "Increase the training batch size so the model converges on a more confident answer" },
      { id: "h", text: "Pair each prediction with similar past cases and their outcomes, and keep the final decision with the clinician" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Human-centered design starts from the person who has to act. In a high-consequence workflow that means giving the reviewer the information needed for an informed judgement, which is the contributing factors, the model's uncertainty, and comparable cases, and keeping the human able to disagree. Oversight that is designed into the interface is what makes explainability useful rather than merely available.",
    optionRationale: {
      a: "Contributing factors, a confidence signal, and a genuine override are exactly the elements that make human oversight effective.",
      b: "Withholding the reasoning leaves the clinician unable to judge whether the recommendation applies to this patient.",
      c: "Concealing uncertainty invites over-reliance on the model precisely when it is least reliable.",
      d: "Removing the human from a high-consequence clinical decision is the opposite of human-centered design.",
      e: "Temperature changes the phrasing of generated text and adds nothing to the clinician's understanding.",
      f: "Raw weights are not interpretable by a clinician and disclose nothing useful about an individual case.",
      g: "Batch size is a training hyperparameter and has no effect on how the output is presented or understood.",
      h: "Comparable cases give the clinician an example-based explanation to weigh, and keeping the decision with them preserves meaningful human oversight.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raiuc04-bp02.html",
    referenceLabel: "RAIUC04-BP02 Identify human oversight opportunities (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra17",
    domain: "responsible-ai",
    text: "A retail bank's assistant must never give personalised investment advice, however a customer phrases the request, and the same rule has to hold across the three different foundation models the bank calls. Which control enforces this most reliably?",
    options: [
      { id: "a", text: "Configure a denied topic in an Amazon Bedrock guardrail, describing the topic and giving sample phrasings in natural language, and apply that one guardrail to every model the application calls" },
      { id: "b", text: "Add a line to each system prompt telling the model not to give investment advice, and rely on the model to obey it" },
      { id: "c", text: "Fine-tune each of the three models so that it refuses investment questions" },
      { id: "d", text: "Lower the temperature so that the model's answers become more conservative" },
      { id: "e", text: "Enable a contextual grounding check so that answers stay close to the retrieved passages" },
      { id: "f", text: "Enable a sensitive information filter so that account numbers are masked in responses" },
      { id: "g", text: "Buy Provisioned Throughput for the three models" },
      { id: "h", text: "Screen every prompt and response through the ApplyGuardrail API with one guardrail holding that denied topic" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "A denied topic is defined in natural language with a short description and example utterances, and the guardrail blocks matching content in both the prompt and the response, returning your configured message instead. Because a guardrail is a separate resource evaluated around the model, one guardrail can be applied to several models, to agents, or to any text through the ApplyGuardrail API, which gives a single, auditable place where the bank's policy lives.",
    optionRationale: {
      a: "A denied topic applied through one shared guardrail enforces the policy outside the model and consistently across all three.",
      b: "A prompt instruction is guidance the model may fail to follow, and it has to be duplicated and kept in step in three places.",
      c: "Fine-tuning three models to refuse is expensive, slow to change, and still probabilistic rather than an enforced block.",
      d: "Temperature changes how varied the wording is; it does not stop the model discussing a subject.",
      e: "A contextual grounding check reduces claims unsupported by retrieved passages, which is about factual grounding rather than a forbidden subject.",
      f: "A sensitive information filter masks personal data and does nothing about the topic of the conversation.",
      g: "Provisioned Throughput reserves inference capacity and applies no content policy at all.",
      h: "The ApplyGuardrail API evaluates text against a guardrail independently of which model produced it, so one denied topic enforces the rule across all three models.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-denied-topics.html",
    referenceLabel: "Block denied topics to help remove harmful content (Amazon Bedrock Guardrails)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
    cliExample: {
      description: "List the guardrails defined in the account so the shared policy can be reused.",
      command: "aws bedrock list-guardrails --query 'guardrails[].{name:name,status:status}' --output table",
      sampleOutput: "|  bank-assistant-policy  |  READY  |",
    },
  },
  {
    id: "aif-ra18",
    domain: "responsible-ai",
    text: "A public-facing assistant occasionally returns insults and hateful phrasing. The safety team wants to set, per harmful category, how aggressively such content is blocked, and to have the check applied to both what users send and what the model returns. Which Amazon Bedrock Guardrails policy does this?",
    options: [
      { id: "a", text: "Content filters, which let you set a filter strength for categories such as hate, insults, sexual content, violence, and misconduct, and apply it to prompts and to responses" },
      { id: "b", text: "The denied topics policy, which blocks specific subjects you describe yourself rather than offering tunable strengths for standard harm categories" },
      { id: "c", text: "The word filter, which blocks an exact list of words and phrases you supply" },
      { id: "d", text: "The sensitive information filter, which blocks or masks personally identifiable information" },
      { id: "e", text: "The contextual grounding check, which scores how far a response is supported by the passages supplied to it" },
      { id: "f", text: "Provisioned Throughput for the model" },
      { id: "g", text: "Prompt caching for the model" },
      { id: "h", text: "The guardrail's content policy, with a strength from None to High for each harm category" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Content filters are the harmful-content policy inside a guardrail. Each category has a configurable strength, so a team can be strict about hate and more permissive elsewhere, and the filter is evaluated on the input and on the output. This is the control that supports the safety dimension of responsible AI for a public audience.",
    optionRationale: {
      a: "Per-category, adjustable filtering of harmful content on both prompt and response is exactly what content filters provide.",
      b: "Denied topics block subjects you define in your own words and have no per-category harm strengths.",
      c: "A word filter is an exact match list, which cannot cover the many ways an insult can be phrased.",
      d: "Sensitive information filters address personal data leakage, not toxicity.",
      e: "The contextual grounding check targets unsupported claims in retrieval-based answers.",
      f: "Provisioned Throughput reserves capacity and enforces no content policy.",
      g: "Prompt caching reduces cost and latency for a repeated prompt prefix and filters nothing.",
      h: "The content policy is the guardrail's harmful-content filter set, where each category gets its own strength and is evaluated on prompts and responses.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-content-filters.html",
    referenceLabel: "Block harmful words and conversations with content filters (Amazon Bedrock Guardrails)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-ra19",
    domain: "responsible-ai",
    text: "An internal model risk committee wants, for each version of each model the company builds, a single record holding the intended use, a risk rating, the datasets and training details, the evaluation results, and the reviewer's sign-off, so that it can be produced on demand during an audit. Which AWS capability is purpose-built for that record?",
    options: [
      { id: "a", text: "Amazon SageMaker Model Cards, which capture intended uses, risk rating, training and evaluation details, and an approval status for each model version" },
      { id: "b", text: "An AWS AI Service Card, which AWS publishes about its own AI services rather than about a model your team builds" },
      { id: "c", text: "An Amazon Bedrock guardrail" },
      { id: "d", text: "Amazon SageMaker Model Monitor" },
      { id: "e", text: "A SageMaker Clarify bias report on its own" },
      { id: "f", text: "AWS Artifact" },
      { id: "g", text: "A plain text README stored beside the model artifact in Amazon S3" },
      { id: "h", text: "A SageMaker model card per model version, exportable as a PDF" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "A SageMaker model card is a structured, versioned document attached to a model: model overview and owner, intended uses and risk rating, training details and datasets, evaluation results and metrics, and a status that moves from draft to pending review to approved. It is the governance artifact that turns scattered notes into something an auditor can be handed.",
    optionRationale: {
      a: "Model cards are designed to hold exactly these fields per model version, with an approval status for sign-off.",
      b: "AI Service Cards are AWS's transparency documents for AWS AI services and models; you do not author one for your own model.",
      c: "A guardrail filters content at inference time and documents nothing.",
      d: "Model Monitor detects drift on a live endpoint; it records no intended use or risk rating.",
      e: "A bias report is one useful input to a model card, not the record of intended use and approval.",
      f: "AWS Artifact provides AWS compliance reports and agreements, not documentation of your models.",
      g: "A free-form README has no schema, no version linkage, and no approval workflow, which is what the committee needs.",
      h: "A model card records intended use, risk rating, training and evaluation details, and approval status, and can be exported as a PDF to hand to an auditor.",
    },
    referenceUrl: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-cards.html",
    referenceLabel: "Amazon SageMaker Model Cards",
    consoleUrl: "https://console.aws.amazon.com/sagemaker/",
    consoleLabel: "Amazon SageMaker console",
    cliExample: {
      description: "List the model cards in the account with their approval status.",
      command: "aws sagemaker list-model-cards --query 'ModelCardSummaries[].{Name:ModelCardName,Status:ModelCardStatus}' --output table",
      sampleOutput: "|  claims-triage-v3  |  Approved  |",
    },
  },
  {
    id: "aif-ra20",
    domain: "responsible-ai",
    text: "Before approving a customer-facing feature built on an AWS AI service, a risk reviewer asks for AWS's own published account of that service's intended use cases, its limitations, the responsible AI design choices behind it, and best practices for deploying it well. What should the team point the reviewer to?",
    options: [
      { id: "a", text: "The AWS AI Service Card for that service, which AWS publishes as a responsible AI transparency document covering intended uses, limitations, design choices, and deployment best practices" },
      { id: "b", text: "An Amazon SageMaker model card, which the team authors about a model it builds itself" },
      { id: "c", text: "AWS Artifact, which provides AWS audit reports and compliance agreements" },
      { id: "d", text: "The service's API reference, which documents request and response syntax" },
      { id: "e", text: "AWS Trusted Advisor checks for the account" },
      { id: "f", text: "A SageMaker Clarify explainability report for the service" },
      { id: "g", text: "An AWS Config conformance pack" },
      { id: "h", text: "The AI Service Card that AWS maintains for the service among its responsible AI resources" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "AWS AI Service Cards are AWS's transparency resource for its own AI services and models. Each card sets out the use cases the service is intended for, how machine learning is used, key limitations, the responsible AI design choices AWS made across dimensions such as fairness, explainability, veracity and robustness, privacy and security, safety, controllability, governance, and transparency, and guidance on deploying and optimising the service. It is the right artifact for assessing a supplied service, as opposed to a model you trained yourself.",
    optionRationale: {
      a: "An AI Service Card is precisely the AWS-published document containing intended uses, limitations, and responsible design choices for an AWS AI service.",
      b: "A model card documents a model your own team builds and would not describe AWS's design choices for its service.",
      c: "AWS Artifact supplies compliance reports such as SOC and ISO attestations, not AI transparency documentation.",
      d: "An API reference explains how to call the service, not how it behaves or where it should not be used.",
      e: "Trusted Advisor inspects your account for cost, security, and quota recommendations.",
      f: "Clarify explains models you train and deploy in SageMaker, not a managed AWS AI service.",
      g: "A Config conformance pack evaluates your resource configurations against rules.",
      h: "AWS maintains AI Service Cards for its AI services, each setting out intended uses, limitations, responsible AI design choices, and deployment best practices.",
    },
    referenceUrl: "https://aws.amazon.com/ai/responsible-ai/resources/",
    referenceLabel: "Responsible AI tools and resources, including AWS AI Service Cards (AWS)",
  },
  {
    id: "aif-ra21",
    domain: "responsible-ai",
    text: "In responsible AI, how do interpretability and explainability differ?",
    options: [
      { id: "a", text: "Interpretability is the degree to which a person can understand the model's mechanism by inspecting the model itself, whereas explainability is being able to account for the model's outputs, typically with post-hoc techniques, even when the mechanism stays opaque" },
      { id: "b", text: "Interpretability is the ability to account for outputs after the fact, whereas explainability means a person can read the model's internal logic directly" },
      { id: "c", text: "They are two names for the same property, so the terms can be used interchangeably" },
      { id: "d", text: "Interpretability means the model is accurate, and explainability means the model is fair" },
      { id: "e", text: "Interpretability measures how quickly the model returns a prediction, and explainability measures how much it costs" },
      { id: "f", text: "Interpretability applies only to generative models and explainability only to classifiers" },
      { id: "g", text: "Explainability is measured with ROUGE and interpretability with BLEU" },
      { id: "h", text: "Interpretability comes from a model simple enough to read directly; explainability uses methods such as SHAP to account for an opaque model" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "A model is interpretable when a person can follow its mechanism directly, as with a small decision tree or a linear model whose coefficients can be read. A model is explainable when its behaviour can be accounted for, usually with post-hoc methods such as SHAP feature attribution, even though the internals are too complex to read. Explainability techniques therefore let a team reason about an opaque model without making that model interpretable.",
    optionRationale: {
      a: "Understanding the mechanism directly versus accounting for outputs after the fact is the accepted distinction.",
      b: "This reverses the two definitions.",
      c: "The terms are related but distinct; treating them as identical loses the point that an opaque model can still be explained.",
      d: "Accuracy and fairness are separate properties and neither term means either of them.",
      e: "Latency and cost are operational measures unconnected to these terms.",
      f: "Both concepts apply across model types, including classic classifiers and foundation models.",
      g: "ROUGE and BLEU are text generation quality metrics and measure neither concept.",
      h: "A readable model structure versus post-hoc methods that account for a model you cannot read is the accepted distinction between the two terms.",
    },
    referenceUrl: "https://docs.aws.amazon.com/whitepapers/latest/model-explainability-aws-ai-ml/interpretability-versus-explainability.html",
    referenceLabel: "Interpretability versus explainability (AWS model explainability whitepaper)",
  },
  {
    id: "aif-ra22",
    domain: "responsible-ai",
    text: "A regulator requires that a lender be able to show, from the structure of the model itself, how each declined application was decided. The data science team has two candidates: a shallow decision tree whose rules can be read directly, and a deep ensemble that scores two points higher on accuracy but whose internals cannot be followed. How should the team resolve the trade-off?",
    options: [
      { id: "a", text: "Choose the inherently interpretable decision tree, because the regulatory need for a model whose logic can be inspected outweighs a small accuracy gain" },
      { id: "b", text: "Always choose the model with the highest accuracy, because predictive performance is the only criterion that matters" },
      { id: "c", text: "Deploy the ensemble and skip the documentation, since the accuracy gain justifies it" },
      { id: "d", text: "There is no trade-off, because deep ensembles are inherently interpretable" },
      { id: "e", text: "Deploy the ensemble and raise its inference temperature, which makes any model interpretable" },
      { id: "f", text: "Deploy the ensemble and train it for more epochs, which will make its logic readable" },
      { id: "g", text: "Deploy the ensemble and tell the regulator that explanations are impossible for modern models" },
      { id: "h", text: "Deploy the decision tree, since post-hoc explanations of the ensemble would not expose the logic the regulator requires" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Model choice is a responsible AI decision, not only an accuracy decision. There is a genuine tension between predictive power and transparency: simpler model families are easier to inspect, while higher-capacity models often score better and are opaque. Where a regulator requires the logic itself to be inspectable, post-hoc explanation of an opaque model does not satisfy the requirement, so the interpretable model wins despite the small loss in accuracy.",
    optionRationale: {
      a: "Weighing a hard transparency requirement against a marginal accuracy gain and choosing the inspectable model is the correct resolution.",
      b: "Treating accuracy as the only criterion ignores the regulatory, fairness, and transparency constraints on the workload.",
      c: "Skipping documentation would breach the requirement outright and leave the lender unable to justify decisions.",
      d: "Deep ensembles combine many high-capacity models and are a standard example of an opaque one.",
      e: "Temperature is a generative sampling setting and has nothing to do with a credit classifier's transparency.",
      f: "More epochs changes the fitted weights, never the readability of the model's structure.",
      g: "Explanations are possible for opaque models through post-hoc methods, so the claim is untrue as well as unhelpful.",
      h: "Post-hoc explanations describe an opaque model's outputs without making its structure inspectable, so only the tree satisfies the requirement despite its small accuracy loss.",
    },
    referenceUrl: "https://aws.amazon.com/what-is/explainable-ai/",
    referenceLabel: "What is explainable AI? (AWS)",
  },
  {
    id: "aif-ra23",
    domain: "responsible-ai",
    text: "A team is assembling the training dataset for a model that will serve a broad public audience. Which TWO practices most directly reduce unwanted bias in that dataset?",
    options: [
      { id: "a", text: "Check that every group the system will serve appears in the data in sufficient numbers, and collect more data for the groups that are thin" },
      { id: "b", text: "Write explicit labeling guidelines, train the annotators on them, and measure agreement between annotators" },
      { id: "c", text: "Increase the learning rate so the model converges faster on the data already collected" },
      { id: "d", text: "Train for more epochs on the same data" },
      { id: "e", text: "Drop the validation split so that all records can be used for training" },
      { id: "f", text: "Duplicate the existing majority-group records to make the dataset larger" },
      { id: "g", text: "Raise the model's inference temperature" },
      { id: "h", text: "Deploy the model on a larger instance type" },
      { id: "i", text: "Audit historical labels for past discriminatory decisions before using them as the training target" },
      { id: "j", text: "Check features for proxies of sensitive attributes, such as neighborhood, and remove or transform them" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Unwanted bias is addressed in the data, before training: check that every group is represented, label with written guidelines and measured annotator agreement, audit historical labels for past discrimination, and remove features that act as proxies for sensitive attributes. Training settings and infrastructure choices cannot undo problems built into the data.",
    optionRationale: {
      a: "Representativeness across the groups the system serves is the first defence against unequal error rates.",
      b: "Clear guidelines and measured annotator agreement keep subjective judgement out of the labels.",
      c: "The learning rate governs the speed and stability of optimisation, not the composition of the data.",
      d: "More passes over a skewed dataset reinforces the skew rather than correcting it.",
      e: "Removing the validation split destroys the team's ability to detect the problem and adds no new data.",
      f: "Duplicating majority records makes the imbalance worse, not better.",
      g: "Temperature is a generative sampling setting applied at inference and has no effect on the dataset.",
      h: "Instance size affects throughput and cost only.",
      i: "Historical decisions used as labels carry past bias into the model, so reviewing and correcting them before training removes that bias at its source.",
      j: "Features that stand in for a sensitive attribute let bias through even when the attribute itself is dropped, so removing or transforming them reduces it.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/raidp03.html",
    referenceLabel: "Dataset issues (AWS Well-Architected Responsible AI Lens)",
  },
  {
    id: "aif-ra24",
    domain: "responsible-ai",
    text: "A marketing team wants to publish copy written by a foundation model without review. Which TWO risks should the legal and risk team raise?",
    options: [
      { id: "a", text: "Generated text may reproduce material that closely resembles copyrighted work, which can expose the company to an intellectual property claim" },
      { id: "b", text: "A confident but fabricated statement about a product, published and acted on by customers, can cause real harm and damage trust in the brand" },
      { id: "c", text: "Using a foundation model transfers all legal liability for the published content to the model provider" },
      { id: "d", text: "Text produced by a foundation model is automatically in the public domain, so competitors may reuse it freely" },
      { id: "e", text: "Foundation models cannot produce text in more than one language, so international campaigns will fail" },
      { id: "f", text: "Organisations that use foundation models are exempt from data protection law for the resulting content" },
      { id: "g", text: "The model's context window shrinks each time it is called, so later copy will be shorter" },
      { id: "h", text: "Enabling prompt caching voids the provider's service terms" },
      { id: "i", text: "Copy can repeat biases or stereotypes from the training data, alienating groups of customers" },
      { id: "j", text: "Output can expose personal or confidential information that appeared in prompts or training data" },
    ],
    correctOptionIds: ["a", "b", "i", "j"],
    answerType: "multi",
    explanation: "Unreviewed generative output carries several legal and reputational risks: it can resemble copyrighted material, state fabricated facts with confidence, echo biases or stereotypes, or expose personal or confidential data. None of these is removed by using a managed service, so review of high-visibility output, grounding in approved source material, and content policy controls remain the team's responsibility.",
    optionRationale: {
      a: "Output that resembles copyrighted work is a recognised intellectual property risk of generative AI.",
      b: "A fluent, confident falsehood published without review is the hallucination risk and directly damages customer trust.",
      c: "Responsibility for how output is used stays with the customer; provider indemnities are limited and conditional and do not remove that duty.",
      d: "Copyright status of generated content is unsettled and varies by jurisdiction; it is not automatically public domain.",
      e: "Many foundation models are explicitly multilingual, so this is simply untrue.",
      f: "No exemption from data protection law exists for content produced with AI.",
      g: "The context window is a fixed property of the model and does not shrink with use.",
      h: "Prompt caching is a supported cost and latency feature, not a terms violation.",
      i: "Biased or stereotyped content published under the brand is a recognized fairness and reputational risk of unreviewed generative output.",
      j: "Generated text can disclose personal or confidential data, which creates a privacy and confidentiality risk the legal team must weigh.",
    },
    referenceUrl: "https://aws.amazon.com/blogs/machine-learning/aws-reaffirms-its-commitment-to-responsible-generative-ai/",
    referenceLabel: "AWS reaffirms its commitment to responsible generative AI",
  },
  {
    id: "aif-ra25",
    domain: "responsible-ai",
    text: "A sustainability review asks the team to cut the environmental footprint of a new generative AI feature. Which choice reduces it the most?",
    options: [
      { id: "a", text: "Start from an existing pre-trained foundation model and adapt it with prompting or light customisation, because pre-training a model from scratch consumes far more compute and energy than anything downstream" },
      { id: "b", text: "Pre-train a new model from scratch on the company's own corpus so that it is exactly the right size" },
      { id: "c", text: "Always select the model with the largest parameter count available" },
      { id: "d", text: "Raise the maximum response length on every request so that answers are never truncated" },
      { id: "e", text: "Run inference on the largest available accelerated instance whatever the traffic level" },
      { id: "f", text: "Turn off auto scaling so that capacity is always provisioned for the annual peak" },
      { id: "g", text: "Replicate the training dataset into every AWS Region for faster access" },
      { id: "h", text: "Use a pre-trained model from Amazon Bedrock or SageMaker JumpStart, adapting it only as far as needed" },
    ],
    correctOptionIds: ["a", "h"],
    answerType: "single",
    explanation: "Pre-training dominates the energy cost of a foundation model, so the single largest sustainability lever is to reuse a model somebody has already trained and adapt it, rather than training one from scratch. After that, choosing the smallest model that meets the requirement, using optimised inference, and letting capacity scale with demand keep the running footprint down.",
    optionRationale: {
      a: "Avoiding a from-scratch pre-training run removes by far the largest block of compute and energy in the lifecycle.",
      b: "Pre-training from scratch is the most energy-intensive option available and is what the review would want avoided.",
      c: "A larger model costs more compute for every single request, increasing the footprint rather than reducing it.",
      d: "A higher output ceiling means more tokens generated per call, which increases energy use.",
      e: "Over-provisioned accelerators idle at low traffic and waste energy.",
      f: "Provisioning permanently for peak leaves capacity running and consuming power when it is not needed.",
      g: "Copying data into every Region multiplies the storage and replication footprint without reducing compute.",
      h: "Reusing a model that has already been pre-trained avoids the largest energy cost in the lifecycle, the pre-training run itself.",
    },
    referenceUrl: "https://docs.aws.amazon.com/wellarchitected/latest/generative-ai-lens/gensus03-bp01.html",
    referenceLabel: "GENSUS03-BP01 Leverage smaller models and optimized inference techniques to reduce carbon footprint",
  },
  {
    id: "aif-ra26",
    domain: "responsible-ai",
    text: "An HR team is launching an assistant that answers employees' questions about parental leave. Eligibility under the written leave policy depends on several interacting conditions, such as length of service, contract type, and weekly hours, and a wrong answer could have legal consequences. The team wants every answer checked against that policy with mathematically verifiable reasoning, so that answers contradicting the policy are flagged and correct ones come with the rules that support them. Which capability is built for this?",
    options: [
      { id: "a", text: "The contextual grounding check in Amazon Bedrock Guardrails, which scores how well each answer is supported by the source passages supplied with it" },
      { id: "b", text: "A denied topic in an Amazon Bedrock guardrail that blocks questions about parental leave" },
      { id: "c", text: "Automated Reasoning checks in Amazon Bedrock Guardrails, using a policy created from the leave document" },
      { id: "d", text: "An Amazon Bedrock knowledge base that retrieves the relevant policy passages before the model answers" },
      { id: "e", text: "Content filters in Amazon Bedrock Guardrails set to High for every harm category" },
      { id: "f", text: "Fine-tuning the model on several years of answers that HR staff have given to leave questions" },
      { id: "g", text: "Setting the temperature to 0 so that the model's answers vary as little as possible" },
      { id: "h", text: "A guardrail with an Automated Reasoning policy, which turns the leave rules into formal logic and returns a finding such as valid or invalid for each answer" },
      { id: "i", text: "A sensitive information filter that masks employee IDs in the assistant's answers" },
    ],
    correctOptionIds: ["c", "h"],
    answerType: "single",
    explanation: "Automated Reasoning checks, a safeguard in Amazon Bedrock Guardrails, turn a source document such as an HR or eligibility policy into formal logic rules and variables, then validate each model response against them. Every response receives a finding such as valid or invalid, together with the rules and variable assignments behind it, so factual errors are caught by mathematically verifiable reasoning rather than by a probabilistic score. The checks run in detect mode, returning findings the application uses to serve, rewrite, or clarify an answer, and they complement content filters and contextual grounding checks rather than replacing them.",
    optionRationale: {
      a: "The grounding check compares an answer with supplied passages and applies a score threshold; it gives no formal proof and does not say which policy rules make an answer correct.",
      b: "A denied topic would stop the assistant answering leave questions at all, instead of checking whether its answers are correct.",
      c: "Automated Reasoning checks extract formal rules and variables from the policy document and validate each response against them, flagging contradictions and citing the rules that make an answer valid.",
      d: "Retrieval gives the model the right passages to draw on, which can reduce errors, but it does not verify the finished answer against the policy's rules.",
      e: "Content filters screen for harmful categories such as hate and violence and say nothing about whether a leave answer is correct.",
      f: "Fine-tuning shapes how the model answers, but its output stays probabilistic and comes with no proof that it follows the policy.",
      g: "A low temperature makes the wording more consistent, not more correct; a wrong answer can be repeated just as consistently, and nothing is checked against the policy.",
      h: "An Automated Reasoning policy attached to a guardrail returns a finding for each answer with the rules and variable values behind it, which is mathematically verifiable feedback rather than a model's judgment.",
      i: "A sensitive information filter protects personal data in the output and does not test whether the answer follows the leave rules.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-automated-reasoning-checks.html",
    referenceLabel: "What are Automated Reasoning checks in Amazon Bedrock Guardrails?",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
  {
    id: "aif-ra27",
    domain: "responsible-ai",
    text: "Before choosing between two foundation models for a public-facing career advice assistant, a nonprofit wants each model scored on the same set of prompts for how often its responses contain toxic or demeaning content, especially in responses about people of different genders, ethnicities, or religions. The scoring must be automatic, with no human review team. Which approach fits?",
    options: [
      { id: "a", text: "An Amazon Bedrock guardrail with content filters set to High, which blocks harmful content in production" },
      { id: "b", text: "A model evaluation job in Amazon Bedrock that uses a judge model with the built-in Harmfulness and Stereotyping metrics" },
      { id: "c", text: "A model evaluation job in Amazon Bedrock in which staff from the nonprofit rate each response" },
      { id: "d", text: "The built-in robustness metric, which measures how much responses change when the prompt is slightly altered" },
      { id: "e", text: "A post-training bias analysis that computes disparate impact on the models' predicted labels" },
      { id: "f", text: "ROUGE scores that compare each response with a human-written reference answer" },
      { id: "g", text: "A programmatic Amazon Bedrock model evaluation job that computes the built-in toxicity metric on datasets such as RealToxicityPrompts and BOLD" },
      { id: "h", text: "Amazon SageMaker Model Monitor bias drift monitoring on the deployed endpoint" },
      { id: "i", text: "The built-in Faithfulness metric, which checks whether a response adds information not found in the prompt" },
    ],
    correctOptionIds: ["b", "g"],
    answerType: "single",
    explanation: "Amazon Bedrock evaluations can score candidate models on responsible AI qualities before one is chosen. A programmatic evaluation job computes a toxicity metric, and its built-in datasets include RealToxicityPrompts, which tries to provoke racist, sexist, or otherwise toxic language, and BOLD, which probes fairness across domains such as gender, race, and religious ideology. An evaluation job that uses a judge model offers built-in Harmfulness and Stereotyping metrics, with an explanation for each score. Running both candidates through the same prompts gives comparable scores, which is a different job from a guardrail that filters harmful content once the application is live.",
    optionRationale: {
      a: "A guardrail is a run-time control that blocks content; it produces no score for comparing candidate models, and it would hide the very behavior the team wants to measure.",
      b: "A judge model scores every response with the built-in Harmfulness and Stereotyping metrics and explains each score, so the two candidates can be compared automatically on the same prompts.",
      c: "A human-based evaluation job relies on people rating responses, which the requirement for fully automatic scoring rules out.",
      d: "Robustness measures how stable responses are when the prompt is perturbed; it does not detect toxic or demeaning content.",
      e: "Disparate impact compares favorable predicted labels between groups for a classifier; free-text responses have no predicted labels, and the metric does not detect toxic language.",
      f: "ROUGE measures word overlap with a reference answer and says nothing about whether a response is toxic.",
      g: "The programmatic toxicity metric scores responses automatically, and its built-in datasets are designed to provoke toxic language and to probe fairness across gender, race, and religion.",
      h: "Bias drift monitoring watches a deployed model's predictions change over time; it cannot compare candidates before one is chosen, and it does not measure toxic language.",
      i: "Faithfulness checks whether a response stays within the information it was given, which is a grounding measure rather than a toxicity or stereotyping measure.",
    },
    referenceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/model-evaluation-metrics.html",
    referenceLabel: "Use metrics to understand model performance (Amazon Bedrock)",
    consoleUrl: "https://console.aws.amazon.com/bedrock/",
    consoleLabel: "Amazon Bedrock console",
  },
];
