import path from "node:path";
import { fileURLToPath } from "node:url";
import { imageCatalog, type ImageEntry } from "../../dist/image-catalog.js";
import type { AssignConfig } from "./assign-media.mts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** Assignment settings for images; `extra` adds unmerged sourcing entries for previews. */
export function imageAssignConfig(extra: ImageEntry[] = []): AssignConfig<ImageEntry> {
  const catalog = [...imageCatalog, ...extra];
  return {
    catalog,
    catalogFor: (certId) => catalog.filter((e) => e.certs.includes(certId as ImageEntry["certs"][number])),
    label: (e) => e.caption,
    noun: "image",
    maxPerEntry: 6,
    runnerUpRatio: 0.75,
    weakScore: 30,
    answerHitBonus: 1.5,
    outPath: path.join(root, "src", "image-assignments.ts"),
    constName: "imageAssignments",
    header: [
      "GENERATED by `npm run images:assign` (scripts/assign-images.mts). Do not edit by hand.",
      "Maps question id -> image id from the catalog in image-catalog.ts.",
    ],
  };
}
