import path from "node:path";
import { fileURLToPath } from "node:url";
import { videoCatalog, type VideoEntry } from "../../dist/videos.js";
import type { AssignConfig } from "./assign-media.mts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** A video may serve at most this many questions before the rebalance looks for alternatives. */
const MAX_PER_VIDEO = 5;
/** A runner-up must score at least this fraction of the best match to be used instead. */
const RUNNER_UP_RATIO = 0.75;
/** Matches scoring below this are reported as weak so new videos can be sourced. */
const WEAK_SCORE = 30;
/** Keyword hits in the correct answer mark the tested service or concept, so such videos win. */
const ANSWER_HIT_BONUS = 1.5;

/** Assignment settings for videos; `extra` adds unmerged sourcing entries for previews. */
export function videoAssignConfig(extra: VideoEntry[] = []): AssignConfig<VideoEntry> {
  const catalog = [...videoCatalog, ...extra];
  return {
    catalog,
    catalogFor: (certId) => catalog.filter((v) => v.cert === certId),
    label: (v) => v.label,
    noun: "video",
    maxPerEntry: MAX_PER_VIDEO,
    runnerUpRatio: RUNNER_UP_RATIO,
    weakScore: WEAK_SCORE,
    answerHitBonus: ANSWER_HIT_BONUS,
    outPath: path.join(root, "src", "video-assignments.ts"),
    constName: "videoAssignments",
    header: [
      "GENERATED by `npm run videos:assign` (scripts/assign-videos.mts). Do not edit by hand.",
      "Maps question id -> YouTube video id from the catalog in videos.ts.",
    ],
  };
}
