/**
 * Assigns every question a YouTube video from the curated catalog and writes the result to
 * src/video-assignments.ts.
 *
 * Compared with the runtime matcher this pass knows the whole question bank, so it can:
 *  - weight each keyword by rarity (IDF): "step functions" hits a handful of questions and is
 *    decisive, "function" hits hundreds and is nearly noise;
 *  - spread questions across videos: when a video is over-subscribed, questions that also
 *    match a close runner-up are moved to the less-used video so more links are unique.
 *
 * Run after `tsc` (it imports the compiled dist/ output). Prints a report of shared videos,
 * weak matches and unmatched questions to help spot gaps in the catalog.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { certifications } from "../dist/certifications.js";
import { catalogFor, countHits, entryScore, haystacksFor, videoCatalog, type VideoEntry } from "../dist/videos.js";
import type { Question } from "../dist/types.js";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

/** Which cert a question belongs to, so candidates are drawn only from that cert's catalog. */
const certOf = new Map<Question, (typeof certifications)[number]>();
for (const cert of certifications) for (const q of cert.questions) certOf.set(q, cert);
const questionBank: Question[] = certifications.flatMap((c) => c.questions);

/** A video may serve at most this many questions before we look for alternatives. */
const MAX_PER_VIDEO = 5;
/** A runner-up must score at least this fraction of the best match to be used instead. */
const RUNNER_UP_RATIO = 0.75;
/** Matches scoring below this are reported as weak so new videos can be sourced. */
const WEAK_SCORE = 30;
/**
 * Multiplier for entries with at least one keyword hit in the correct answer text. The answer
 * names the service or concept being tested, so such entries are almost always the better pick.
 */
const ANSWER_HIT_BONUS = 1.5;

interface Candidate {
  entry: VideoEntry;
  score: number;
}

const haystacks = new Map<Question, ReturnType<typeof haystacksFor>>();
for (const q of questionBank) haystacks.set(q, haystacksFor(q));

// Document frequency of each keyword across the bank.
const df = new Map<string, number>();
for (const entry of videoCatalog) {
  for (const keyword of entry.keywords) {
    const k = keyword.toLowerCase();
    if (df.has(k)) continue;
    let n = 0;
    for (const h of haystacks.values()) {
      if (countHits(k, h.stem) + countHits(k, h.answers) + countHits(k, h.explanation) > 0) n++;
    }
    df.set(k, n);
  }
}
const N = questionBank.length;
const idf = (k: string) => Math.log(1 + N / ((df.get(k) ?? 0) + 1));

const candidates = new Map<Question, Candidate[]>();
for (const q of questionBank) {
  const h = haystacks.get(q)!;
  const scored: Candidate[] = [];
  for (const entry of catalogFor(certOf.get(q)!.id)) {
    let score = entryScore(entry, h, idf);
    if (score <= 0) continue;
    const hitsAnswer = entry.keywords.some((k) => countHits(k.toLowerCase(), h.answers) > 0);
    if (hitsAnswer) score *= ANSWER_HIT_BONUS;
    scored.push({ entry, score });
  }
  scored.sort((a, b) => b.score - a.score);
  candidates.set(q, scored.slice(0, 6));
}

const assignment = new Map<Question, Candidate>();
const load = new Map<string, number>();
const bump = (id: string, delta: number) => load.set(id, (load.get(id) ?? 0) + delta);

for (const q of questionBank) {
  const best = candidates.get(q)![0];
  if (best) {
    assignment.set(q, best);
    bump(best.entry.id, 1);
  }
}

// Rebalance: move questions off over-subscribed videos when a close alternative has room.
let moved = 0;
for (let pass = 0; pass < 10; pass++) {
  let movedThisPass = 0;
  for (const q of questionBank) {
    const current = assignment.get(q);
    if (!current || (load.get(current.entry.id) ?? 0) <= MAX_PER_VIDEO) continue;
    const best = candidates.get(q)![0].score;
    const alternatives = candidates
      .get(q)!
      .filter((c) => c.entry.id !== current.entry.id && c.score >= best * RUNNER_UP_RATIO)
      .filter((c) => (load.get(c.entry.id) ?? 0) < MAX_PER_VIDEO)
      .sort((a, b) => (load.get(a.entry.id) ?? 0) - (load.get(b.entry.id) ?? 0) || b.score - a.score);
    const target = alternatives[0];
    if (!target) continue;
    bump(current.entry.id, -1);
    bump(target.entry.id, 1);
    assignment.set(q, target);
    movedThisPass++;
  }
  moved += movedThisPass;
  if (movedThisPass === 0) break;
}

// Write the generated module.
const lines = questionBank
  .filter((q) => assignment.has(q))
  .map((q) => `  ${JSON.stringify(q.id)}: ${JSON.stringify(assignment.get(q)!.entry.id)},`);
const out = `/**
 * GENERATED by \`npm run videos:assign\` (scripts/assign-videos.mts). Do not edit by hand.
 * Maps question id -> YouTube video id from the catalog in videos.ts.
 */
export const videoAssignments: Record<string, string> = {
${lines.join("\n")}
};
`;
await writeFile(path.join(root, "src", "video-assignments.ts"), out);

// Report.
const byVideo = new Map<string, Question[]>();
for (const [q, c] of assignment) {
  const list = byVideo.get(c.entry.id) ?? [];
  list.push(q);
  byVideo.set(c.entry.id, list);
}
const label = (id: string) => videoCatalog.find((v) => v.id === id)!.label;
const unmatched = questionBank.filter((q) => !assignment.has(q));
const weak = questionBank.filter((q) => assignment.has(q) && assignment.get(q)!.score < WEAK_SCORE);
const unused = videoCatalog.filter((v) => !byVideo.has(v.id));

console.log(`questions ${N}, catalog ${videoCatalog.length}, videos used ${byVideo.size}, moved ${moved}`);
console.log(`unique (1 question): ${[...byVideo.values()].filter((l) => l.length === 1).length}`);
for (const cert of certifications) {
  const qs = cert.questions;
  const done = qs.filter((q) => assignment.has(q)).length;
  console.log(`${cert.id}: ${done}/${qs.length} assigned`);
}
console.log(`\nMost shared videos:`);
for (const [id, qs] of [...byVideo.entries()].sort((a, b) => b[1].length - a[1].length).slice(0, 25)) {
  console.log(`  ${String(qs.length).padStart(3)}  ${label(id)}  [${qs.map((q) => q.id).join(" ")}]`);
}
console.log(`\nUnused catalog entries (${unused.length}):`);
for (const v of unused) console.log(`  ${v.label}`);
console.log(`\nWeak matches (${weak.length}):`);
for (const q of weak) console.log(`  ${q.id}  ${Math.round(assignment.get(q)!.score)}  ${label(assignment.get(q)!.entry.id)}  |  ${q.text.slice(0, 110)}`);
console.log(`\nUnmatched (${unmatched.length}):`);
for (const q of unmatched) console.log(`  ${q.id}  ${q.text.slice(0, 110)}`);
