/**
 * Generates sw.js with a precache manifest of every static asset the app needs offline.
 * The cache name embeds a hash of all file contents, so any change produces a new cache
 * and the activate step evicts the old one.
 */
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const ROOT_FILES = ["index.html", "styles.css", "manifest.webmanifest"];
const DIRS = ["dist", "fonts", "icons", "vendor"];

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files: string[] = [];
for (const f of ROOT_FILES) files.push(path.join(root, f));
for (const d of DIRS) {
  try {
    await stat(path.join(root, d));
    files.push(...(await walk(path.join(root, d))));
  } catch {
    /* optional dir */
  }
}

const hash = createHash("sha256");
const urls: string[] = [];
for (const file of files.sort()) {
  const rel = path.relative(root, file).split(path.sep).join("/");
  if (rel.endsWith(".map") || rel.endsWith(".d.ts")) continue;
  hash.update(rel);
  hash.update(await readFile(file));
  urls.push("./" + rel);
}
urls.unshift("./");
const version = hash.digest("hex").slice(0, 12);

const sw = `/* Generated by scripts/build-sw.mts. Do not edit by hand. */
const CACHE = "awsquiz-${version}";
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // App shell: serve index.html for navigations so deep links work offline.
  if (request.mode === "navigate") {
    event.respondWith(
      caches.match("./index.html").then((cached) => cached ?? fetch(request))
    );
    return;
  }

  // Everything else: cache first, fall back to network and store the result.
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    })
  );
});
`;

await writeFile(path.join(root, "sw.js"), sw);
console.log(`sw.js written: ${urls.length} precached files, cache awsquiz-${version}`);
