import { Certification, CertificationId, certifications } from "./certifications.js";
import { imageAssignments } from "./image-assignments.js";
import { ImageEntry, domainImageFallback, imageCatalog } from "./image-catalog.js";
import { entryScore, haystacksFor } from "./matching.js";
import { Question } from "./types.js";

export function imageCatalogFor(certId: CertificationId): ImageEntry[] {
  return imageCatalog.filter((e) => e.certs.includes(certId));
}

/**
 * Picks an image from an explicit catalog, in priority order:
 * 1. the reviewed assignment generated by `scripts/assign-images.mts`;
 * 2. live keyword scoring, for questions added since the assignments were last generated;
 * 3. the domain fallback.
 */
export function pickImage(question: Question, catalog: ImageEntry[], assignedId?: string, fallbackId?: string): ImageEntry | undefined {
  const assigned = catalog.find((e) => e.id === assignedId);
  if (assigned) return assigned;

  const h = haystacksFor(question);
  let best: ImageEntry | undefined;
  let bestScore = 0;
  for (const entry of catalog) {
    const score = entryScore(entry, h);
    if (score > bestScore) {
      bestScore = score;
      best = entry;
    }
  }
  return best ?? catalog.find((e) => e.id === fallbackId);
}

export function resolveImage(question: Question, certId: CertificationId): ImageEntry {
  // Validation at module load guarantees every domain's fallback is in its cert's catalog.
  return pickImage(question, imageCatalogFor(certId), imageAssignments[question.id], domainImageFallback[question.domain])!;
}

/**
 * Catalog rules: well-formed entries, a fallback for every domain that lists the domain's cert,
 * and assignments that point at entries listing the question's cert. Returns every problem
 * found, so tests can assert on them.
 */
export function imageCatalogProblems(
  catalog: ImageEntry[],
  fallback: Record<string, string>,
  assignments: Record<string, string>,
  certs: Pick<Certification, "id" | "domains" | "questions">[]
): string[] {
  const problems: string[] = [];
  const byId = new Map<string, ImageEntry>();
  for (const e of catalog) {
    if (byId.has(e.id)) problems.push(`duplicate image id ${e.id}`);
    byId.set(e.id, e);
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(e.id)) problems.push(`image ${e.id}: id must be a kebab-case slug`);
    if (!e.url.startsWith("https://")) problems.push(`image ${e.id}: url must start with https://`);
    if (!e.sourceUrl.startsWith("https://")) problems.push(`image ${e.id}: sourceUrl must start with https://`);
    for (const field of ["alt", "caption", "credit"] as const) {
      if (!e[field].trim()) problems.push(`image ${e.id}: ${field} is empty`);
    }
    if (e.certs.length === 0) problems.push(`image ${e.id}: certs is empty`);
  }
  for (const cert of certs) {
    for (const d of cert.domains) {
      const entry = byId.get(fallback[d.id]);
      if (!entry) problems.push(`domain ${d.id}: no fallback image`);
      else if (!entry.certs.includes(cert.id)) problems.push(`domain ${d.id}: fallback ${entry.id} does not list ${cert.id}`);
    }
    for (const q of cert.questions) {
      const id = assignments[q.id];
      if (id === undefined) continue;
      const entry = byId.get(id);
      if (!entry) problems.push(`question ${q.id}: assigned image ${id} is not in the catalog`);
      else if (!entry.certs.includes(cert.id)) problems.push(`question ${q.id}: assigned image ${id} does not list ${cert.id}`);
    }
  }
  return problems;
}

const catalogProblems = imageCatalogProblems(imageCatalog, domainImageFallback, imageAssignments, certifications);
if (catalogProblems.length > 0) throw new Error(`image catalog:\n  ${catalogProblems.join("\n  ")}`);
