/**
 * GENERATED by `npm run images:assign` (scripts/assign-images.mts). Do not edit by hand.
 * Maps question id -> image id from the catalog in image-catalog.ts.
 */
export const imageAssignments: Record<string, string> = {
};
