import { Domain, Question } from "./types.js";

/** A curated YouTube video covering one CLF-C02 topic. */
export interface VideoEntry {
  /** YouTube video ID (the `v=` query parameter). */
  id: string;
  label: string;
  /** Case-insensitive phrases that indicate a question is about this topic. Longer phrases score higher. */
  keywords: string[];
}

/**
 * Curated catalog of verified YouTube videos, keyed by topic.
 * Every ID was checked live against YouTube's oEmbed endpoint when added.
 */
export const videoCatalog: VideoEntry[] = [
  // Cloud concepts
  { id: "mxT233EdY5c", label: "What is Cloud Computing? (AWS)", keywords: ["cloud computing", "on-premises", "on premises", "capital expense", "variable expense", "trade capital", "economies of scale", "pay-as-you-go", "agility", "elasticity"] },
  { id: "a9__D53WsUs", label: "What is AWS? (AWS)", keywords: ["what is aws", "aws cloud", "benefits of aws"] },
  { id: "ZgR2tvXCDC4", label: "6 Pillars of the AWS Well-Architected Framework", keywords: ["well-architected", "well architected", "six pillars", "five pillars", "pillars"] },
  { id: "WuL_MueH4Xk", label: "AWS Cloud Adoption Framework (CAF) Breakdown", keywords: ["cloud adoption framework", "caf", "perspectives"] },
  { id: "0hlZvybbaGk", label: "AWS Global Infrastructure Overview", keywords: ["region", "regions", "global infrastructure", "data center", "data centers", "geographic", "closest to"] },
  { id: "PHjYRn_mrs0", label: "AWS Edge Locations and CloudFront", keywords: ["edge location", "edge locations", "points of presence", "point of presence", "regional edge cache"] },
  { id: "bJCmZn9fASM", label: "7 Rs Migration Strategies and AWS Migration Services", keywords: ["migration", "migrate", "migrating", "replatform", "refactor", "repurchase", "retire", "retain", "relocate", "7 rs", "six rs", "seven rs", "migration strategy", "migration strategies"] },
  { id: "ppG2FFB0mMQ", label: "AWS Outposts: Overview and How It Works", keywords: ["outposts", "hybrid", "on-premises hardware", "own data center"] },
  { id: "QMcqZ_vIXfE", label: "Console, CLI, or SDK Explained", keywords: ["aws cli", "command line interface", "sdk", "software development kit", "management console", "cloudshell", "infrastructure as code", "programmatic access"] },
  { id: "BtJAsvJOlhM", label: "168 AWS Services in 2 Minutes", keywords: [] },

  // Security and compliance
  { id: "9Pk2J_5qnlk", label: "Learn AWS IAM in Less Than 10 Minutes (AWS)", keywords: ["iam", "identity and access management", "least privilege", "permissions", "principal", "authentication", "authorization"] },
  { id: "miij_0HkBws", label: "AWS IAM Roles (AWS)", keywords: ["iam role", "iam roles", "iam user", "iam users", "iam group", "iam groups", "access key", "access keys", "temporary credentials", "sts", "assume role"] },
  { id: "MiPItT74ZLs", label: "Service Control Policies (SCPs) Explained", keywords: ["service control polic", "scp", "scps", "restrict what", "maximum permissions", "guardrails across"] },
  { id: "zbI8owkUDrc", label: "AWS Root User Explained in 5 Minutes", keywords: ["root user", "root account"] },
  { id: "di95GQdEc0w", label: "AWS Multi-Factor Authentication (MFA) Explained", keywords: ["mfa", "multi-factor", "multi factor", "password policy", "access analyzer", "phishing-resistant", "passkey", "passkeys", "fido"] },
  { id: "zSUUBAxjIbk", label: "AWS Key Management Service (KMS)", keywords: ["kms", "key management service", "encryption key", "encryption keys", "cloudhsm", "hsm", "encryption at rest", "encrypt", "envelope encryption"] },
  { id: "jcE2gyVkhYo", label: "AWS Shield Explained: DDoS Protection, Standard vs Advanced", keywords: ["shield", "waf", "web application firewall", "ddos", "sql injection", "cross-site scripting", "layer 7", "layer 3", "layer 4"] },
  { id: "M4aOKikd7-s", label: "Amazon GuardDuty Deep Dive", keywords: ["guardduty", "threat detection", "malicious", "compromised", "unusual api"] },
  { id: "Cn1ss-YZa9E", label: "Amazon Inspector: 7 Things You Need To Know", keywords: ["inspector", "vulnerability", "vulnerabilities"] },
  { id: "S5X0PnBwp9I", label: "CloudWatch vs CloudTrail: What's the Difference?", keywords: ["cloudwatch vs cloudtrail", "cloudwatch and cloudtrail", "cloudtrail and cloudwatch", "difference between cloudwatch"] },
  { id: "qHdFoYSrUvk", label: "AWS Config Tutorial (Stephane Maarek)", keywords: ["aws config", "config rule", "config rules", "configuration history", "configuration change", "configuration changes", "compliance of resources"] },
  { id: "O307zdIOmWo", label: "Using AWS Artifact to Retrieve Compliance Reports", keywords: ["artifact", "compliance report", "compliance reports", "soc", "pci", "hipaa", "iso 27001", "audit report", "audit reports", "attestation"] },
  { id: "ItzzgWe7elE", label: "AWS Secrets Manager Step-by-Step", keywords: ["secrets manager", "rotate", "rotation", "database credentials", "secret", "secrets"] },
  { id: "nBusvrDEjdk", label: "AWS Security Hub Demo", keywords: ["security hub", "security findings", "security posture", "cis benchmark"] },
  { id: "RR4MtDl09Vk", label: "What is Amazon Macie?", keywords: ["macie", "sensitive data", "personally identifiable", "pii"] },
  { id: "EAWWTjjQWz8", label: "Amazon Cognito: User Pool vs Identity Pool", keywords: ["cognito", "user pool", "identity pool", "sign-up", "sign-in", "social identity"] },
  { id: "Nk77te-cksQ", label: "What is AWS Certificate Manager?", keywords: ["certificate manager", "acm", "ssl", "tls", "certificate", "certificates", "in transit"] },
  { id: "pyiJbkJROTE", label: "Understanding AWS Control Tower", keywords: ["control tower", "landing zone", "guardrail", "guardrails", "multi-account"] },

  // Compute
  { id: "t48aVpw6kkI", label: "What is Amazon EC2? (AWS)", keywords: ["ec2", "elastic compute cloud", "virtual server", "virtual servers", "user data", "key pair"] },
  { id: "4gQ5SOfBUm4", label: "EC2 Instance Types Explained", keywords: ["instance type", "instance types", "compute optimized", "memory optimized", "storage optimized", "accelerated computing", "general purpose", "burstable"] },
  { id: "rcWgcFMlwFw", label: "EC2 Auto Scaling: How it Works", keywords: ["auto scaling", "autoscaling", "scale out", "scale in", "scaling policy", "scaling policies", "horizontal scaling", "vertical scaling", "launch template"] },
  { id: "WBUS5777CYw", label: "AWS ELB: The 3 Elastic Load Balancer Types", keywords: ["load balancer", "load balancing", "elb", "alb", "nlb", "application load balancer", "network load balancer", "health check", "health checks"] },
  { id: "eOBq__h4OJ4", label: "Introduction to AWS Lambda", keywords: ["lambda", "serverless", "function", "functions", "event-driven"] },
  { id: "aOZD7gsyxLM", label: "ECS vs EKS vs Fargate", keywords: ["ecs", "elastic container service", "container", "containers", "docker", "task definition", "cluster"] },
  { id: "SrwxAScdyT0", label: "Introduction to AWS Elastic Beanstalk", keywords: ["elastic beanstalk", "beanstalk", "platform as a service", "paas"] },
  { id: "FRN27b1VLXg", label: "AWS Lightsail Explained: Simplified Cloud VPS", keywords: ["lightsail"] },
  { id: "T4aAWrGHmxQ", label: "How AWS Batch Works", keywords: ["aws batch", "batch job", "batch jobs", "batch processing"] },
  { id: "juCUwETXv0I", label: "What is AWS Compute Optimizer?", keywords: ["compute optimizer", "rightsizing", "right-sizing", "right sizing", "over-provisioned", "underutilized"] },

  // Storage
  { id: "R0fqpQd9mSM", label: "Amazon S3 Explained in 10 Minutes", keywords: ["s3", "simple storage service", "bucket", "buckets", "object storage", "unlimited storage", "objects"] },
  { id: "w5ocEIDR5WE", label: "Amazon S3 Storage Classes", keywords: ["storage class", "storage classes", "s3 standard", "infrequent access", "intelligent-tiering", "intelligent tiering", "one zone"] },
  { id: "Fo_cTVelDKk", label: "S3 Storage Classes Explained (Demo)", keywords: ["s3 standard-ia", "s3 one zone-ia", "s3 express", "reduced redundancy"] },
  { id: "Uw_bGnIr1B8", label: "Amazon S3 Lifecycle Rules: Transition and Expiration", keywords: ["lifecycle", "lifecycle policy", "lifecycle rule", "transition", "expire", "expiration"] },
  { id: "gMzVi7Z8zBo", label: "Amazon S3 Glacier Storage Classes", keywords: ["glacier", "archive", "archival", "deep archive", "retrieval", "vault lock"] },
  { id: "smF92POVrhE", label: "EBS vs EFS vs Instance Store", keywords: ["instance store", "ephemeral", "fsx", "fsx for windows", "fsx for lustre", "ebs vs efs", "storage options", "storage types"] },
  { id: "zxlV86Wh7EQ", label: "AWS Storage Gateway Explained", keywords: ["storage gateway", "file gateway", "volume gateway", "tape gateway", "on-premises storage"] },
  { id: "zXyudn7KeZM", label: "AWS Snow Family Explained", keywords: ["snow family", "snowball", "snowcone", "snowmobile", "petabyte", "petabytes", "physical device", "limited bandwidth", "offline transfer", "datasync", "transfer family"] },
  { id: "2nMvqrG8cDc", label: "AWS Backup Explained", keywords: ["aws backup", "backup plan", "backup plans", "backups", "backup vault", "centralized backup", "centrally manage backups"] },

  // Databases
  { id: "eMzCI7S1P9M", label: "Understanding Amazon RDS", keywords: ["rds", "relational database service", "relational database", "mysql", "postgresql", "sql server", "oracle", "mariadb", "managed database", "automated backups", "patching the database"] },
  { id: "l7IpsIzMa6E", label: "What is Amazon Aurora", keywords: ["aurora"] },
  { id: "kxW3-k7NXwo", label: "What is Amazon DynamoDB?", keywords: ["dynamodb", "nosql", "key-value", "key value", "document database", "single-digit millisecond", "dax", "documentdb", "keyspaces", "timestream", "qldb", "ledger", "mongodb", "cassandra"] },
  { id: "dSybACt3fX8", label: "How Does ElastiCache Work?", keywords: ["elasticache", "redis", "memcached", "in-memory", "in memory", "caching", "cache layer", "memorydb"] },
  { id: "lWwFJV_9PoE", label: "Data Warehousing with Amazon Redshift", keywords: ["redshift", "data warehouse", "data warehousing", "olap", "analytics queries", "columnar"] },

  // Networking
  { id: "7_NNlnH7sAg", label: "Amazon VPC Basics", keywords: ["vpc", "virtual private cloud", "subnet", "subnets", "route table", "route tables", "vpc peering", "cidr", "elastic ip", "isolated network", "logically isolated"] },
  { id: "JWoNu2Mtpdg", label: "Security Groups vs Network ACLs", keywords: ["security group", "security groups", "network acl", "network acls", "nacl", "nacls", "stateful", "stateless", "inbound rule", "inbound rules", "outbound rule"] },
  { id: "JRZiQFVWpi8", label: "Amazon Route 53 Basics", keywords: ["route 53", "route53", "dns", "domain name", "domain registration", "routing policy", "routing policies", "hosted zone", "latency-based", "failover routing", "geolocation"] },
  { id: "A_1pXqChn3s", label: "Hybrid Cloud with AWS VPN and Direct Connect", keywords: ["direct connect", "site-to-site vpn", "site to site vpn", "vpn", "dedicated network connection", "private connection", "virtual private gateway", "client vpn"] },
  { id: "yRyr_TjtiDg", label: "Global Networking with AWS Transit Gateway", keywords: ["transit gateway", "hub-and-spoke", "hub and spoke", "connect multiple vpcs", "thousands of vpcs"] },
  { id: "K-zh-SKfjLA", label: "What is AWS Global Accelerator?", keywords: ["global accelerator", "anycast", "static ip", "static ips", "aws global network"] },
  { id: "1XcpQHfTOvs", label: "What is Amazon API Gateway?", keywords: ["api gateway", "rest api", "restful", "http api", "websocket", "throttling", "api keys", "appsync", "graphql"] },

  // Application integration and deployment
  { id: "ApQsmIOzar8", label: "SQS vs SNS vs EventBridge: Which One Should You Use?", keywords: ["decouple", "decoupling", "decoupled", "loosely coupled", "message", "messages", "messaging", "mq", "amazon mq", "activemq", "rabbitmq", "sqs vs sns"] },
  { id: "wdJ5DN15jus", label: "AWS Step Functions Explained in 90 Seconds", keywords: ["step functions", "state machine", "workflow", "workflows", "orchestrat"] },
  { id: "Omppm_YUG2g", label: "Introduction to AWS CloudFormation", keywords: ["cloudformation", "template", "templates", "stack", "stacks", "provision resources", "repeatable", "declarative", "json or yaml", "yaml", "change set", "change sets", "drift"] },
  { id: "JGfWDFX3iAw", label: "What Are CodePipeline, CodeBuild and CodeDeploy Used For?", keywords: ["codepipeline", "codecommit", "codebuild", "codedeploy", "codestar", "codeartifact", "ci/cd", "continuous integration", "continuous delivery", "continuous deployment", "devops", "cloud9", "blue/green", "blue-green", "canary", "source control"] },
  { id: "pSVK-ingvfc", label: "AWS Systems Manager Introduction", keywords: ["systems manager", "patch manager", "run command", "patching", "patch", "ops center", "opscenter", "fleet", "maintenance window", "automation document"] },
  { id: "HkbjHtG_d7w", label: "What is AWS Amplify?", keywords: ["amplify", "mobile app", "mobile application", "web and mobile", "full-stack", "frontend"] },

  // Monitoring and support
  { id: "3qXSHMTZPKM", label: "AWS CloudWatch Explained: Metrics, Alarms and Monitoring", keywords: ["cloudwatch", "metric", "metrics", "monitor", "monitoring", "dashboard", "custom metric", "custom metrics"] },
  { id: "Ueh7vyXNtog", label: "AWS X-Ray: Distributed Tracing for Beginners", keywords: ["x-ray", "xray", "tracing", "trace", "traces", "distributed application", "microservices", "bottleneck", "bottlenecks"] },
  { id: "uEIrFbesvP8", label: "AWS Trusted Advisor", keywords: ["trusted advisor", "best practice checks", "best-practice checks", "service limits", "service quotas", "quota"] },
  { id: "mHIba-3Cedo", label: "AWS Health Dashboard and Trusted Advisor", keywords: ["health dashboard", "personal health", "service health", "scheduled maintenance", "planned maintenance", "aws health"] },
  { id: "gkkcM37m5Zc", label: "AWS Support Plans: Everything You Need To Know", keywords: ["support plan", "support plans", "enterprise support", "enterprise on-ramp", "infrastructure event management", "support case", "support cases", "aws iq", "support tier", "support tiers"] },

  // Billing and pricing
  { id: "-t148tYgnJU", label: "EC2 Pricing: On-Demand, Spot, Reserved, Savings Plans", keywords: ["on-demand", "on demand", "dedicated host", "dedicated hosts", "dedicated instance", "dedicated instances", "capacity reservation", "pricing model", "pricing models", "purchasing option", "purchasing options", "pay by the second", "per-second"] },
  { id: "uCGgXw1o2Ks", label: "EC2 Costs: On-Demand vs Savings Plans vs Reserved", keywords: ["all upfront", "partial upfront", "no upfront", "upfront payment", "payment option", "payment options"] },
  { id: "xjq-1CdvgQ8", label: "Savings Plans: Pricing Model for AWS Compute", keywords: ["savings plan", "savings plans", "compute savings", "ec2 instance savings", "hourly commitment"] },
  { id: "YAet7EnpvYI", label: "AWS Free Tier Explained in 2 Minutes", keywords: ["free tier", "always free", "12 months free", "12-month", "trial", "free credits"] },
  { id: "oE8TNKGmc40", label: "AWS Cost Explorer", keywords: ["cost explorer", "cost categories", "visualize", "spending trends", "forecast", "billing conductor", "cost anomaly", "anomaly detection", "usage over time"] },
  { id: "O0sofGVT7uw", label: "AWS Budgets: Set Up Billing Alerts", keywords: ["aws budgets", "budget", "budgets", "billing alarm", "billing alert", "billing alerts", "alert when", "exceeds", "spending limit", "monthly spend"] },
  { id: "PQFztryprPQ", label: "Estimate Costs with the AWS Pricing Calculator", keywords: ["pricing calculator", "estimate", "estimates", "total cost of ownership", "tco", "cost estimate"] },
  { id: "Rpf-_k0lQEQ", label: "Consolidated Billing for AWS", keywords: ["consolidated billing", "single bill", "volume discount", "volume discounts", "tiered pricing", "aggregate usage", "payer account", "multiple accounts"] },
  { id: "4obiejTAlFQ", label: "What is AWS Marketplace", keywords: ["marketplace", "third-party software", "third party software", "isv", "software vendor", "private offer", "saas subscription"] },

  // Analytics, AI and ML
  { id: "Qv_Tr_BCFCQ", label: "Introduction to Amazon SageMaker", keywords: ["sagemaker", "machine learning", "ml model", "ml models", "train and deploy", "kendra", "personalize", "forecast service", "fraud detector", "build, train", "jupyter", "notebook"] },
  { id: "_vdK5PgcNvc", label: "Introducing Amazon Bedrock", keywords: ["bedrock", "generative ai", "foundation model", "foundation models", "large language model", "llm", "titan", "claude", "anthropic", "prompt"] },
  { id: "S0XXbFp5Lf0", label: "Athena, Kinesis, and Glue Explained", keywords: ["data lake", "lake formation", "opensearch", "elasticsearch", "msk", "managed streaming for kafka", "kafka", "big data analytics"] },
  { id: "QuwaBOESGiU", label: "An Introduction to Amazon EMR", keywords: ["emr", "elastic mapreduce", "hadoop", "spark", "big data", "data pipeline"] },
  { id: "2V1bHRLRG-w", label: "Introducing Amazon QuickSight", keywords: ["quicksight", "business intelligence", "bi tool", "dashboards", "visualization", "visualizations"] },
  // Added: more specific videos so fewer questions share the same link
  { id: "tv7SsA2eVHE", label: "AWS Operational Excellence Pillar Explained", keywords: ["operational excellence", "runbook", "runbooks", "operations as code", "learn from failures", "small, reversible"] },
  { id: "bubRYxwipzk", label: "AWS Reliability Pillar Explained", keywords: ["reliability pillar", "reliability", "recover from failure", "recover from failures", "automatically recover", "test recovery"] },
  { id: "hwG3jS5_8jo", label: "Well-Architected Security Pillar", keywords: ["security pillar", "traceability", "security at all layers", "strong identity foundation", "protect data in transit and at rest"] },
  { id: "V2EjQbFxSgM", label: "AWS Performance Efficiency Pillar Explained", keywords: ["performance efficiency", "go global in minutes", "serverless architectures", "experiment more often", "mechanical sympathy"] },
  { id: "HCe_V9NIB_E", label: "AWS Cost Optimization Pillar", keywords: ["cost optimization", "cloud financial management", "unnecessary cost", "measure overall efficiency", "adopt a consumption model"] },
  { id: "tNDquSJp904", label: "AWS Sustainability Pillar", keywords: ["sustainability", "environmental impact", "carbon", "energy"] },
  { id: "n4BTqappip0", label: "Navigating Best Practices with the AWS Well-Architected Tool", keywords: ["well-architected tool", "well architected tool", "review workloads", "architecture review"] },
  { id: "o13js0hIO_o", label: "Simplify the AWS Shared Responsibility Model (AWS)", keywords: ["shared responsibility", "security of the cloud", "security in the cloud", "responsible for", "customer's responsibility", "aws is responsible", "customer is responsible", "physical security"] },
  { id: "V1dffu8QOlU", label: "Understanding High Availability and Fault Tolerance", keywords: ["high availability", "highly available", "fault tolerance", "fault tolerant", "fault-tolerant", "single point of failure", "redundancy", "redundant"] },
  { id: "Fi1KaVrWYTE", label: "AWS Global Infrastructure Explained in 3 Minutes", keywords: ["availability zone", "availability zones", "multiple availability zones", "isolated locations", "low-latency links", "one or more discrete"] },
  { id: "GfUcmVP1gWo", label: "AWS Local Zones: Product Overview", keywords: ["local zone", "local zones", "closer to end users", "latency-sensitive applications"] },
  { id: "EhMqwPqPzcY", label: "AWS Wavelength: Edge Computing for 5G Networks", keywords: ["wavelength", "5g", "telecommunications", "mobile edge"] },
  { id: "zOnhkotoBII", label: "AWS CAF: 6 Perspectives, 4 Phases and 4 Domains", keywords: ["business perspective", "people perspective", "governance perspective", "platform perspective", "operations perspective", "security perspective", "envision phase", "align phase", "transformation domains", "caf perspectives"] },
  { id: "AT-nHW3_SVI", label: "Introduction to Amazon CloudFront (AWS)", keywords: ["cloudfront", "content delivery", "cdn", "distribution", "cache content", "origin", "low latency delivery", "deliver content"] },
  { id: "v2oiElpOzNk", label: "AWS Migration Hub Explained", keywords: ["migration hub", "track migration", "track the progress", "migration progress"] },
  { id: "KVV5Hd70Uc8", label: "Introduction to AWS Application Migration Service (AWS)", keywords: ["application migration service", "mgn", "lift and shift", "lift-and-shift", "rehost", "server migration"] },
  { id: "QMkhABGobI4", label: "AWS Database Migration Explained in 2 Minutes", keywords: ["database migration service", "dms", "schema conversion", "sct", "heterogeneous", "homogeneous", "migrate a database", "migrate databases"] },
  { id: "tbZvgSRTSuk", label: "AWS DataSync Explained", keywords: ["datasync", "online data transfer", "transfer large amounts", "nfs to s3"] },
  { id: "bxSD1Nha2k8", label: "AWS Snowball Edge Overview (AWS)", keywords: ["snowball edge", "edge computing", "disconnected environments", "rugged"] },
  { id: "nlb8yo7SZ2I", label: "An Introduction to AWS CDK", keywords: ["cdk", "cloud development kit", "familiar programming language", "programming languages", "typescript", "python code"] },

  { id: "IpByb6Z6Yh0", label: "AWS IAM Policies Tutorial: JSON Policies for Beginners", keywords: ["iam policy", "iam policies", "policy document", "json policy", "allow or deny", "explicit deny", "inline policy", "inline policies", "managed policy", "managed policies", "customer managed", "aws managed", "policy statement"] },
  { id: "t8P8ffqWrsY", label: "AWS IAM Permissions Boundary", keywords: ["permissions boundary", "permission boundary", "permissions boundaries", "delegate permissions"] },
  { id: "gpquYmcpZpo", label: "What is AWS IAM Identity Center?", keywords: ["identity center", "single sign-on", "sso", "federation", "federated", "active directory", "saml", "identity provider", "corporate credentials", "existing corporate"] },
  { id: "T4NK8fv8YdI", label: "Introducing AWS Organizations (AWS)", keywords: ["aws organizations", "organizations", "organizational unit", "organizational units", "management account", "member account", "member accounts", "multiple aws accounts", "multi-account", "centrally manage accounts"] },
  { id: "utq0rTCCI-8", label: "IAM vs S3 Bucket Policy vs Access Control List", keywords: ["bucket policy", "bucket policies", "block public access", "public access", "acl", "acls", "access point", "access points", "publicly accessible", "presigned", "pre-signed"] },
  { id: "84BhFGIxIqg", label: "What is Amazon Detective? (AWS)", keywords: ["detective", "root cause", "investigate", "investigation", "security investigations"] },
  { id: "Y7-37tkO1CA", label: "AWS Network Firewall Explainer (AWS)", keywords: ["network firewall", "intrusion", "vpc-level firewall", "stateful inspection"] },
  { id: "FGhKpPDBvXc", label: "Getting Started with AWS Firewall Manager (AWS)", keywords: ["firewall manager", "centrally manage firewall", "centrally configure", "firewall rules across"] },
  { id: "CXbdsp9ThvM", label: "AWS CloudTrail Basics", keywords: ["cloudtrail", "api call", "api calls", "audit", "auditing", "who made", "who deleted", "event history", "management events", "record actions", "governance, compliance"] },
  { id: "cUEFGKaZOyU", label: "AWS Session Manager Overview (AWS)", keywords: ["session manager", "without ssh", "no ssh", "bastion", "bastion host", "ssh keys", "inbound ports", "browser-based shell"] },
  { id: "zxi3M_rIE2k", label: "AWS Systems Manager Parameter Store Tutorial", keywords: ["parameter store", "configuration data", "hierarchical storage", "plaintext or encrypted"] },
  { id: "cx87pMvMg10", label: "AWS Abuse (Cloud Practitioner)", keywords: ["aws abuse", "abuse", "abusive", "abuse team"] },
  { id: "1eaRm11vgaw", label: "AWS Tagging Best Practices", keywords: ["tag", "tags", "tagging", "resource groups", "key-value pair", "key-value pairs", "metadata"] },

  { id: "E956xeOt050", label: "Amazon EKS Explained", keywords: ["eks", "kubernetes", "elastic kubernetes", "k8s"] },
  { id: "BRCQltXQEoU", label: "AWS Fargate Tutorial: Serverless Containers", keywords: ["fargate", "serverless container", "serverless containers", "serverless compute engine for containers", "without managing ec2"] },
  { id: "GtbTmvMcKRg", label: "Amazon ECR Explained (AWS)", keywords: ["ecr", "container registry", "container image", "container images", "docker image", "docker images", "store images"] },
  { id: "_LLqbAe7YTs", label: "Lambda Pricing Explained in 5 Minutes", keywords: ["lambda pricing", "per request", "number of requests", "execution time", "duration", "15 minutes", "15-minute", "memory allocated", "compute time", "1 ms", "millisecond increments"] },
  { id: "LIouXADhGz0", label: "AWS Lambda Triggers: Complete Guide to Event Sources", keywords: ["trigger", "triggers", "triggered", "event source", "event sources", "invoke", "invoked", "invokes", "invocation", "s3 event", "upload to s3", "in response to events"] },
  { id: "fw33RsNWSR0", label: "EC2 Spot Instances Explained", keywords: ["spot instance", "spot instances", "spot fleet", "spot", "interrupt", "interrupted", "interruption", "fault-tolerant workloads", "flexible start", "up to 90%", "unused capacity", "spare capacity"] },
  { id: "XrmdkRQZhUQ", label: "Introduction to Amazon EC2 Reserved Instances (AWS)", keywords: ["reserved instance", "reserved instances", "steady-state", "steady state", "predictable usage", "1-year", "3-year", "one-year", "three-year", "convertible", "standard reserved", "up to 72%", "commit to"] },

  { id: "kAaPjE9-a2A", label: "Amazon S3: Cross-Region Replication and Versioning (AWS)", keywords: ["versioning", "cross-region replication", "replication", "accidental deletion", "accidentally deleted", "previous version", "previous versions", "overwritten", "mfa delete"] },
  { id: "-l83oqcaTHg", label: "How to Host a Static Website on AWS S3", keywords: ["static website", "static web", "static content", "website hosting", "html, css", "host a website"] },
  { id: "77qLAl-lRpo", label: "Amazon Elastic Block Store (EBS) Overview (AWS)", keywords: ["ebs", "elastic block store", "block storage", "ebs volume", "ebs volumes", "snapshot", "snapshots", "iops", "gp3", "gp2", "io2", "io1", "persistent block", "attached to a single"] },
  { id: "vAV4ASDnbN0", label: "Amazon EFS Overview (AWS)", keywords: ["efs", "elastic file system", "nfs", "shared file", "shared file system", "multiple ec2 instances", "file system", "concurrently", "thousands of ec2"] },
  { id: "GAMUCIJR5as", label: "Get Started with AWS Elastic Disaster Recovery (AWS)", keywords: ["elastic disaster recovery", "drs", "cloudendure", "continuous replication"] },
  { id: "qZd6TokRWf0", label: "AWS Disaster Recovery Strategies Explained", keywords: ["pilot light", "warm standby", "multi-site", "active-active", "backup and restore", "disaster recovery", "rpo", "rto", "recovery point", "recovery time", "recovery point objective", "recovery time objective"] },

  { id: "fW_prKJR79Y", label: "Multi-AZ vs Read Replicas: Amazon RDS Tutorial", keywords: ["multi-az", "multi az", "read replica", "read replicas", "standby", "synchronous", "asynchronous", "failover", "read-heavy", "read traffic", "offload read"] },
  { id: "YmR2_zlQO5w", label: "Introduction to Amazon Neptune Graph Database (AWS)", keywords: ["neptune", "graph database", "graph", "highly connected", "social network", "recommendation engine", "fraud graph"] },

  { id: "2htfhgcySfs", label: "AWS Internet Gateway vs NAT Gateway in 3 Minutes", keywords: ["internet gateway", "nat gateway", "nat instance", "outbound internet", "private subnet", "private subnets", "public subnet", "public subnets", "access the internet", "internet access"] },
  { id: "WPRqAx3EWnw", label: "Gateway Endpoint vs Interface Endpoint in AWS", keywords: ["vpc endpoint", "vpc endpoints", "gateway endpoint", "interface endpoint", "without traversing", "public internet", "privately connect", "private connectivity"] },

  { id: "oR8KY1YXykU", label: "AWS SQS Explained: How Queues Make Apps Scalable", keywords: ["sqs", "simple queue service", "queue", "queues", "message queue", "dead-letter", "dead letter", "fifo", "visibility timeout", "polling", "at-least-once", "exactly-once"] },
  { id: "3oMpDoYwqpM", label: "Amazon SNS Tutorial: Simple Notification Service Explained", keywords: ["sns", "simple notification service", "topic", "topics", "push notification", "push notifications", "sms", "email notification", "email notifications", "pub/sub", "publish", "subscribe", "subscribers", "fan-out", "fan out", "notify"] },
  { id: "TXh5oU_yo9M", label: "Intro to Amazon EventBridge (AWS)", keywords: ["eventbridge", "event bus", "event rule", "event rules", "scheduled event", "saas applications", "cloudwatch events", "event-driven", "event driven", "route events"] },
  { id: "hLLgkTUmwOU", label: "Amazon Kinesis Data Streams Fundamentals (AWS)", keywords: ["kinesis", "data streams", "streaming data", "real-time data", "real time data", "data firehose", "firehose", "clickstream", "video streams", "real-time analytics", "ingest streaming"] },
  { id: "qgWMfNSN9f4", label: "What is AWS Glue? (AWS)", keywords: ["glue", "etl", "data catalog", "crawler", "crawlers", "extract, transform", "prepare data", "data integration"] },
  { id: "q9yxcWcHH4Q", label: "Amazon Athena Explained: Query S3 with SQL", keywords: ["athena", "query data in s3", "standard sql", "serverless query", "query s3", "sql queries", "query data directly", "pay per query"] },
  { id: "A6-jv3gZa4U", label: "Introduction to AWS Service Catalog (AWS)", keywords: ["service catalog", "approved products", "portfolio", "portfolios", "approved it services", "catalog of"] },
  { id: "HmXkLtSYHtk", label: "Tag AWS Resources to Divide Up Your Bill (AWS)", keywords: ["cost allocation tag", "cost allocation tags", "cost center", "cost centers", "divide up", "by department", "by project", "by team", "chargeback", "showback"] },
  { id: "NfONXHkTefA", label: "How Do I Use the AWS Cost and Usage Report? (AWS)", keywords: ["cost and usage report", "cur", "most comprehensive", "most detailed", "granular billing", "hourly line items"] },

  { id: "dIfJ0-ichVs", label: "AWS Support Plans Explained: Which Plan Is Right for You?", keywords: ["developer support", "business support", "basic support", "cloud support associates", "cloud support engineers", "12 hours", "24 hours", "1 hour", "15 minutes", "general guidance", "system impaired", "production system", "business hours", "24x7", "24/7 phone", "third-party software support"] },
  { id: "bWwlNaF6Jw8", label: "What Is the Role of a Technical Account Manager? (AWS)", keywords: ["technical account manager", "tam", "concierge", "designated", "proactive guidance", "account team"] },
  { id: "_C0NHqtRFdw", label: "Introducing AWS re:Post (AWS)", keywords: ["re:post", "repost", "knowledge center", "community", "question-and-answer", "q&a"] },
  { id: "VjtcENUtn-A", label: "AWS Partner Network (APN) Overview", keywords: ["professional services", "partner network", "apn", "consulting partner", "consulting partners", "technology partner", "aws partner", "aws partners", "system integrator", "proserve"] },

  { id: "fnFpE6UEd_I", label: "What Is Amazon Rekognition? (AWS)", keywords: ["rekognition", "image analysis", "facial", "face", "faces", "image and video", "object detection", "objects in images", "content moderation", "celebrity", "video analysis"] },
  { id: "BKgTJCJ0eGg", label: "What is Amazon Comprehend? (AWS)", keywords: ["comprehend", "natural language processing", "nlp", "sentiment", "sentiment analysis", "key phrases", "entities", "insights from text", "customer reviews"] },
  { id: "XUd5M_mQaA0", label: "Text to Speech with Amazon Polly", keywords: ["polly", "text to speech", "text-to-speech", "lifelike speech", "spoken audio", "voice"] },
  { id: "AaPIdNEz3xk", label: "Amazon Transcribe, Translate and Polly", keywords: ["transcribe", "speech to text", "speech-to-text", "translate", "translation", "translates", "languages", "transcription", "call recordings", "subtitles"] },
  { id: "uYu1OR8wU8A", label: "Amazon Lex Explained: Conversational AI Chatbots", keywords: ["lex", "chatbot", "chatbots", "conversational", "voice and text", "alexa", "conversational interfaces", "bots"] },
  { id: "5Cs4_e2CJRo", label: "What is Amazon Textract? (AWS)", keywords: ["textract", "extract text", "scanned document", "scanned documents", "ocr", "forms and tables", "handwriting", "extract data from documents"] },
  { id: "fQITLL5WncE", label: "Discover Amazon Q: AWS Generative AI Assistant (AWS)", keywords: ["amazon q", "q developer", "q business", "codewhisperer", "coding assistant", "generative ai assistant", "code suggestions"] },

  { id: "ROshw2gIdB8", label: "What is AWS CloudWatch? Monitoring and Alerts Explained", keywords: ["cloudwatch alarm", "cloudwatch alarms", "alarm", "alarms", "cpu utilization", "metric alarm", "alarm state", "trigger an action", "above a threshold"] },
  { id: "F6CpeUOPEPA", label: "AWS CloudWatch Logs Explained", keywords: ["cloudwatch logs", "log group", "log groups", "log stream", "log streams", "application logs", "logs insights", "log data", "log files", "centralize logs", "retention period"] },
  // Added: every video below is under 10 minutes; more specific topics so fewer questions share a link
  // Cloud concepts and global infrastructure
  { id: "Kv3b48fKcUY", label: "How to Choose the Right AWS Region", keywords: ["choose a region", "choosing a region", "which aws region", "which region", "data residency", "data sovereignty", "gdpr", "sovereignty", "never leaves", "proximity", "close to its users", "close to customers", "service availability", "govcloud", "china", "partition", "opt-in", "disabled by default"] },
  { id: "yrOcNcVVTE4", label: "AWS Availability Zones: Beginner Overview", keywords: ["loss of a single", "single data center", "single facility", "multiple data centers", "three availability zones", "two availability zones", "across availability zones", "az failure", "spread across"] },
  { id: "qitCPVnsdCA", label: "How Do AWS Regions and Availability Zones Work?", keywords: ["inter-region", "between regions", "aws backbone", "private backbone", "aws-owned", "global network", "copy an ami", "copy the ami", "ami to another region", "global service", "global services", "is a global"] },
  { id: "3WIJ4axzFlU", label: "Public Cloud vs Private Cloud vs Hybrid Cloud", keywords: ["public cloud", "private cloud", "hybrid cloud", "deployment model", "deployment models", "cloud-based", "multi-cloud", "multicloud", "both providers", "cloud bursting", "burst to the cloud", "bursts to the cloud", "virtualization platform"] },
  { id: "E-iV44wUbNI", label: "CapEx vs OpEx Explained: AWS, Azure and GCP", keywords: ["capex", "opex", "capital expenditure", "operational expenditure", "upfront purchases", "upfront investment", "large upfront", "depreciated", "usage-based", "hardware purchases", "buying hardware"] },
  { id: "22mtNlfGEc8", label: "Key Cloud Economics: Elasticity, Availability and Agility", keywords: ["scalability and elasticity", "scalability", "provisioned quickly", "provision resources in minutes", "speed and ease", "guessing capacity", "guess at", "guessing at", "stop guessing", "overprovision", "over-provision", "experiment"] },
  { id: "Qn6mGayIw6o", label: "AWS Data Transfer Costs Explained", keywords: ["data transfer", "data transfer out", "transfer out", "dto", "egress", "inbound data transfer", "data transfer charges", "transfer charges", "transfer in is free"] },
  { id: "n8BQ83lG8lQ", label: "AWS Pricing Models and Cost Calculator (AWS)", keywords: ["pricing model", "pricing models", "fundamental ways", "pay for what you use", "pay only for", "no upfront", "pay less when", "reserve capacity", "pay less as aws grows", "pricing philosophy", "three fundamental", "drivers of cost"] },

  // Migration
  { id: "Q1UcuaJQnSE", label: "Fast Track Your Business Case with Migration Evaluator (AWS)", keywords: ["migration evaluator", "business case", "data-driven", "total cost of ownership", "tco", "actual utilization", "rough estimate", "projected savings"] },
  { id: "5tt6Y89oH74", label: "AWS Application Discovery Service Explained", keywords: ["application discovery", "discovery service", "discovery agent", "agentless collector", "inventory its servers", "inventory of the servers", "network dependencies", "dependency mapping", "dependencies between"] },
  { id: "NZ-SbhGOGC0", label: "AWS Migration Methodology, Process and Tools (AWS)", keywords: ["three-phase", "three phase", "assess phase", "mobilize", "migrate and modernize", "wave", "waves", "group applications", "grouping applications", "groups applications", "portfolio assessment", "portfolio"] },
  { id: "Zv_q7_S2op0", label: "AWS Migration Acceleration Program (MAP) Overview (AWS)", keywords: ["migration acceleration program", "map program", "proven methodology", "migration program", "aws program", "funding", "partner-led"] },
  { id: "zACe0LLkWVA", label: "AWS Mainframe Modernization Features", keywords: ["mainframe", "cobol", "mainframe modernization", "legacy system"] },

  // Identity and access
  { id: "xK69zkQpEcg", label: "IAM Credentials Report (Cybr)", keywords: ["credential report", "credentials report", "access advisor", "last accessed", "unused credentials", "unused access keys", "unused permissions", "last used"] },
  { id: "9jzwEUHKmVI", label: "IAM Roles vs IAM Users: Stop Using Long-Term Keys", keywords: ["long-term access key", "long-term access keys", "long-lived", "long-term credentials", "embedded", "embed", "hardcoded", "hard-coded", "instance profile", "role attached", "attached to the instance", "attach an iam role", "without embedding", "without storing"] },
  { id: "2r-zBXyFL8o", label: "How to Rotate AWS Access Keys", keywords: ["rotate the key", "rotate access key", "rotate access keys", "rotate the access key", "key rotation", "rotating", "committed", "public github", "public repository", "exposed", "leaked", "deactivate", "compromised"] },
  { id: "Qrm84k9vRXg", label: "Cross-Account IAM Roles Hands-On", keywords: ["cross-account", "cross account", "account a", "account b", "another aws account", "other account", "trust policy", "external id", "third-party vendor", "third party vendor", "saas vendor", "assumes a role in"] },
  { id: "tPQsI8n6er0", label: "EC2 Instance Metadata Tutorial (Stephane Maarek)", keywords: ["instance metadata", "metadata service", "imds", "imdsv2", "169.254.169.254", "its own instance id"] },
  { id: "8KLh1idp-1M", label: "IAM Policy Evaluation Logic: Explicit Deny (AWS)", keywords: ["explicit deny", "implicit deny", "implicitly denied", "denied by default", "default deny", "evaluation logic", "policy evaluation", "conflicting", "overrides", "allow and a deny", "does not attach any policy", "effective permissions"] },
  { id: "yOKrd-lt0gM", label: "Managed vs Inline IAM Policies (Cybr)", keywords: ["aws managed policy", "aws managed policies", "customer managed policy", "customer managed policies", "inline policy", "inline policies", "managed policies", "ready-made policy", "reuse a policy", "readonlyaccess"] },
  { id: "FNbHpOTwifQ", label: "Test IAM Policies with the IAM Policy Simulator", keywords: ["policy simulator", "simulate", "simulator", "test a policy", "test the policy", "before attaching", "which api calls", "confirm exactly which"] },

  // Encryption, detection and audit
  { id: "MWhKuoHV57Q", label: "KMS Key Types: AWS Owned vs AWS Managed vs Customer Managed", keywords: ["aws owned key", "aws owned keys", "aws managed key", "aws managed keys", "customer managed key", "customer managed keys", "key policy", "key policies", "cmk", "key material", "import key material", "rotation of the key", "automatic key rotation", "schedule key deletion", "delete a kms key", "kms key deletion", "retire a customer managed"] },
  { id: "Nvim7tQ22_k", label: "Multi-Region KMS Keys Explained", keywords: ["multi-region key", "multi-region keys", "replicate the key", "replica key", "kms key in another region", "keys are regional", "kms keys are regional", "decrypt in another region", "re-encrypt"] },
  { id: "FvWQlMVY4g4", label: "EBS Encryption: Secure Data at Rest", keywords: ["ebs encryption", "encrypted ebs", "encrypted snapshot", "encrypted snapshots", "unencrypted volume", "unencrypted snapshot", "encrypt an existing", "share a snapshot", "share the snapshot", "snapshot with another account", "copy the snapshot"] },
  { id: "nUI7G9UzyN8", label: "What is AWS WAF? (AWS)", keywords: ["rate-based", "rate based", "rate limit", "rate limiting", "requests per minute", "credential-stuffing", "credential stuffing", "bots", "bot control", "geo match", "geo-match", "geographic match", "block requests from", "block web requests", "ip set", "ip address ranges"] },
  { id: "FupObkKT2Uo", label: "AWS CloudTrail Advanced Features", keywords: ["cloudtrail lake", "sql-style queries", "sql-style", "event data store", "seven years", "retain aws api activity", "retain events", "query across", "immutable event"] },
  { id: "rk0RHxQCD8Q", label: "CloudTrail Log File Integrity Validation", keywords: ["integrity validation", "log file integrity", "integrity of the log", "not been modified", "have not been modified", "modified or deleted", "tampered", "tampering", "digest", "digest file", "digest files", "sha-256"] },
  { id: "mSMlxUJERdg", label: "AWS Audit Manager in 5 Minutes", keywords: ["audit manager", "collecting evidence", "collect evidence", "evidence collection", "audit evidence", "assessment report", "audit-ready", "continuously audit", "audit preparation", "prepare for audits", "collecting screenshots"] },
  { id: "RH3uQ1A6WGs", label: "GuardDuty vs Detective: What Are the Differences?", keywords: ["how guardduty works", "guardduty works", "telemetry", "dns logs", "analyzes vpc flow", "out of the box", "enable guardduty", "enabling guardduty", "enables amazon guardduty", "enable amazon guardduty"] },
  { id: "tT8LXTztKjE", label: "AWS Config and Conformance Packs (AWS)", keywords: ["conformance pack", "conformance packs", "aggregator", "config aggregator", "across all accounts and regions", "compliance status of resources", "noncompliant", "non-compliant", "remediation", "auto-remediation", "automatic remediation"] },
  { id: "uJsIA3wwPj0", label: "Lambda Code Signing with AWS Signer", keywords: ["aws signer", "code signing", "signed by", "digitally signed", "signing profile", "signing configuration"] },
  { id: "iODPCcQEPto", label: "AWS Shared Responsibility Model (Digital Cloud Training)", keywords: ["managed service", "fully managed", "managed node", "self-managed", "patching the operating system", "guest operating system", "operating system patches", "os patching", "patch the os", "worker nodes", "infrastructure services", "container services", "abstracted services", "who patches", "patching of the underlying"] },
  { id: "ESPBBEK-cvo", label: "The AWS Shared Responsibility Model in 4 Minutes", keywords: ["shared controls", "inherited controls", "customer specific controls", "customer-specific", "patch management", "configuration management", "awareness and training", "physical disks", "end of life", "decommission", "decommissioned", "media disposal", "destroyed", "badge access", "physical data centers"] },

  // Compute and serverless
  { id: "4HNE1IscKUg", label: "Amazon Machine Images (AMI) Explained", keywords: ["ami", "amis", "amazon machine image", "amazon machine images", "golden image", "custom ami", "custom image", "marketplace ami", "appliance ami", "ami is regional", "preconfigured"] },
  { id: "h07XKYLmzYs", label: "AWS Lambda Cold and Warm Start Explained", keywords: ["cold start", "cold starts", "provisioned concurrency", "warm", "initialization", "first request to each", "latency targets", "snapstart"] },
  { id: "C02cylYvMkw", label: "What Are Lambda Layers?", keywords: ["lambda layer", "lambda layers", "shared libraries", "shared dependencies", "bundle the same", "deployment package", "common code"] },
  { id: "iR1eb6AJ-zk", label: "AWS Lambda Function URLs Explained", keywords: ["function url", "function urls", "over https", "https endpoint", "invoke it over https", "dedicated https endpoint", "without api gateway"] },
  { id: "84Ga-Z-A8SU", label: "Lambda and EventBridge: Scheduled Tasks (Cron Jobs)", keywords: ["cron", "run on a schedule", "runs on a schedule", "scheduled lambda", "schedule a lambda", "schedule the function", "rate expression", "cron expression", "run automatically every", "every day at", "nightly", "eventbridge scheduler", "at a specific time", "on a schedule"] },
  { id: "GSBR4G4pVAE", label: "AWS Lambda with S3 Event Notifications Explained", keywords: ["thumbnail", "thumbnails", "resize", "image-processing", "image processing", "uploads an image", "upload an image", "every time a user uploads", "when an object is created", "object is uploaded", "new object"] },
  { id: "MVxHQbmA2Dg", label: "What Are S3 Event Notifications", keywords: ["event notification", "event notifications", "s3 notification", "notifies", "notify", "when a file lands", "when objects are"] },
  { id: "f2HG8_0eE80", label: "SQS Dead Letter Queues Explained", keywords: ["dead-letter", "dead letter", "dlq", "maxreceivecount", "poison", "failed messages", "problem messages", "repeatedly fail", "fails to process", "retry", "retries", "visibility timeout"] },

  // Storage
  { id: "kgrCecl2cjM", label: "S3 Pre-Signed URLs Explained", keywords: ["presigned", "pre-signed", "presigned url", "pre-signed url", "time-limited", "time limited", "temporary access to an object", "temporary url", "temporary link", "download link", "without making the bucket public", "private objects", "private object"] },
  { id: "-b0gTxpTyik", label: "S3 Transfer Acceleration Explained", keywords: ["transfer acceleration", "accelerate uploads", "accelerated upload", "around the world who upload", "around the world upload", "upload multi-gigabyte", "long-distance", "long distance", "edge network to upload"] },
  { id: "hslYYmjy_as", label: "Why S3 Uploads Fail Without Multipart Upload", keywords: ["multipart", "multi-part", "single connection", "large file upload", "large files", "4 tb", "parallel upload", "in parts", "parts in parallel"] },
  { id: "I039A_NkTDo", label: "What Is S3 Batch Operations?", keywords: ["batch operations", "s3 batch", "million existing objects", "existing objects", "bulk", "in bulk", "hundreds of millions of objects"] },
  { id: "N_eNklFKQMQ", label: "What Is S3 Object Lock", keywords: ["object lock", "worm", "write once", "write-once", "legal hold", "retention period", "immutable", "cannot be deleted or overwritten", "compliance mode", "governance mode"] },
  { id: "9vhEqjR2zsc", label: "Amazon S3: Data Durability and Global Resiliency (AWS)", keywords: ["99.999999999", "eleven nines", "11 nines", "durability", "durable", "designed for", "99.99% availability"] },
  { id: "7vfrDYIHlaI", label: "S3 Encryption: Client-Side, In-Transit and Server-Side Keys", keywords: ["sse-s3", "sse-kms", "sse-c", "server-side encryption", "client-side encryption", "client side encryption", "encrypted before they leave", "encrypted before", "default encryption", "automatically encrypted at rest", "encrypt objects", "encrypted at rest in"] },

  // Networking and load balancing
  { id: "VFwLffElIgc", label: "Which Type of Elastic Load Balancer Should I Use?", keywords: ["path-based", "path based", "host-based", "host based", "content-based", "layer 7 routing", "/api/", "target group", "target groups", "listener", "listeners", "ultra-low latency", "ultra low latency", "millions of requests per second", "static ip address", "static ip", "tcp traffic", "udp", "layer 4 load", "alb vs nlb", "alb or nlb", "alb and a network"] },
  { id: "ABOwqvA52_k", label: "AWS Gateway Load Balancer Deep Dive", keywords: ["gateway load balancer", "gwlb", "third-party firewall", "third party firewall", "virtual appliance", "virtual appliances", "firewall appliances", "intrusion detection appliance", "inspect all traffic", "packet inspection", "full packet", "geneve", "inline inspection", "security appliance", "security appliances"] },
  { id: "kAdnshoSYwc", label: "ALB Sticky Sessions Explained for Beginners", keywords: ["sticky session", "sticky sessions", "stickiness", "session affinity", "stateful web", "same target", "same instance", "session state", "user's session"] },
  { id: "3fUBKhMfvlE", label: "What Is AWS PrivateLink", keywords: ["privatelink", "endpoint service", "endpoint services", "expose the api privately", "call the api privately", "dozens of customers", "customers to call", "saas provider", "own vpc", "service provider vpc", "consumer vpc", "without vpc peering", "without peering"] },
  { id: "vT9PVdNY8sw", label: "Route 53: DNS, Routing, Health Checks and Failover", keywords: ["failover routing", "failover", "health check fails", "unhealthy", "route 53 health", "dns failover", "weighted", "latency-based", "latency routing", "geolocation", "geoproximity", "routing policy", "routing policies", "multivalue"] },

  // Databases
  { id: "r_o4RTl1zXo", label: "Lambda + DynamoDB Streams: How They Work Together", keywords: ["dynamodb stream", "dynamodb streams", "item is inserted", "inserted or", "whenever an item", "change data capture", "changes to items", "table changes", "stream of changes"] },
  { id: "HdtHyqNl-As", label: "What Is Amazon Aurora Global Database", keywords: ["aurora global", "global database", "cross-region read", "secondary region", "under a second", "less than one second", "replication lag", "sub-second", "promote the secondary", "another region that stays"] },
  { id: "d_g0RmfvPnY", label: "Amazon RDS Proxy Overview", keywords: ["rds proxy", "connection pooling", "connection pool", "too many connections", "database connections", "connections from lambda", "exhaust", "exhausts"] },

  // Billing and organizations
  { id: "UVyxW-l-eEU", label: "How Consolidated Billing Shares Reserved Instance Discounts", keywords: ["reserved instance sharing", "ri sharing", "discount sharing", "shared across accounts", "promotional credits", "credits", "aws credits", "reserved instance discount", "savings plans discount", "benefit of the reserved", "apply to other accounts", "other accounts in the organization"] },

  // Added: every video below is under 10 minutes; narrower topics so the largest clusters split further
  // Organizations, multi-account and governance
  { id: "2jG4wkvrx3E", label: "AWS Organizations Explained in 3 Minutes", keywords: ["single aws account", "separate accounts", "separate aws accounts", "multiple aws accounts", "multi-account strategy", "blast radius", "account per", "each business unit", "one account per", "isolate workloads into"] },
  { id: "xbGs-t0y_QY", label: "How Do I Access Member Accounts Created Using AWS Organizations? (AWS)", keywords: ["organizationaccountaccessrole", "root user password", "root user passwords", "root credentials for each", "access member accounts", "log in to member", "sign in to member", "created by organizations", "accounts created through"] },
  { id: "uBD-wxsc0PE", label: "Delegating Administration of AWS Services (Cybr)", keywords: ["delegated administrator", "delegated admin", "delegate administration", "dedicated security account", "security tooling account", "security account", "administer the service from", "register a member account", "designate a member account", "central security team"] },
  { id: "4rUU3cPgI1s", label: "AWS Resource Access Manager (RAM) Explained", keywords: ["resource access manager", "aws ram", "share resources", "share a subnet", "share subnets", "shared vpc", "share the vpc", "share transit gateway", "sharing resources across accounts", "share it with other accounts"] },
  { id: "0MuZtFbBDUM", label: "What is AWS License Manager?", keywords: ["license manager", "software licenses", "commercial software licenses", "bring your own license", "byol", "license rules", "licensing", "license usage", "license compliance", "fixed number of"] },
  { id: "k9Q_31KqXcQ", label: "AWS Cost Categories (AWS)", keywords: ["cost categories", "cost category", "group costs", "group your costs", "map costs to", "tag policies", "tag policy", "inconsistent", "inconsistently", "standardize tags", "standardized tags", "enforce tag"] },
  { id: "ykiVl1F5bd8", label: "Share Your AMI With Other AWS Accounts", keywords: ["ami public", "public ami", "share an ami", "share the ami", "block public access for amis", "make an ami public", "make an amazon machine image public", "amis public", "publicly shared ami", "image public"] },
  { id: "MX-iunIYoEE", label: "How to Create a CloudTrail Organization Trail", keywords: ["organization trail", "org trail", "single cloudtrail", "single aws cloudtrail", "all member accounts", "every account in the organization", "api activity across accounts", "all accounts in the organization", "trail for all accounts", "central logging account", "log archive account"] },

  // Identity, policies and credentials
  { id: "GUou0EGif-o", label: "IAM Permissions Boundaries: Limit Maximum Permissions", keywords: ["maximum permissions a role", "developers create their own iam roles", "create their own iam roles", "create iam roles for their applications", "no role a developer", "cap the permissions", "upper limit on permissions", "never exceed", "cannot exceed", "let developers create"] },
  { id: "83K8imcWnrc", label: "Identity vs Resource Policies (Cloud Bart)", keywords: ["identity-based polic", "resource-based polic", "identity-based and resource-based", "trust policy", "trust policies", "two kinds of policies", "permissions policy and a trust", "who can assume", "attached directly to an aws resource", "attached to a resource"] },
  { id: "h7Z2l_9Sq8Y", label: "AWS IAM: PassRole or AssumeRole", keywords: ["passrole", "pass role", "iam:passrole", "sts:assumerole", "assumerole", "pass a role", "passing a role", "session policy", "session policies", "scoped-down", "scope down", "narrower than the role"] },
  { id: "iWJKlf411WY", label: "Service-Linked Roles and PassRole in AWS", keywords: ["service-linked role", "service linked role", "service-linked roles", "awsservicerolefor", "predefined by the service", "linked to a service", "created automatically by", "role that nobody", "owned by the service"] },
  { id: "Y2xAwDC_QIg", label: "Introduction to Amazon Verified Permissions (AWS)", keywords: ["verified permissions", "cedar", "fine-grained authorization", "fine-grained, policy-based authorization", "authorization inside the application", "authorization inside their application", "application-level permissions", "who can do what within the application", "document-sharing", "document-management"] },
  { id: "BBu5WCNR_eI", label: "Attribute-Based Access Control at AWS (Cloud Bart)", keywords: ["abac", "attribute-based", "attribute based", "tag-based access", "principal tag", "principaltag", "resourcetag", "tags on the role", "matching tags", "hundreds of projects", "single policy for all", "instead of writing a separate iam policy", "separate iam policy for each"] },
  { id: "QZKpufELZCA", label: "AWS IAM vs IAM Identity Center (Digital Cloud Training)", keywords: ["iam vs identity center", "still uses iam users", "instead of iam users", "rather than iam identity center", "long-term credentials", "long term credentials", "long-lived", "long-term access key", "long-term access keys", "long-term iam", "workforce users", "human users"] },
  { id: "Shg3uD80IUo", label: "IAM Access Key Rotation Best Practices", keywords: ["rotate access keys", "access key rotation", "rotate the access key", "rotate its access", "rotate the key", "two active access keys", "second access key", "create a second", "keys created three years", "created three years ago", "old access keys", "unused access keys", "last used"] },
  { id: "mhbBxYFUkkA", label: "What Is an IAM Role for EC2 Instances?", keywords: ["instance profile", "instance profiles", "role to the ec2 instance", "role attached to the instance", "without embedding", "embedding credentials", "embedding access keys", "hard-coded credentials", "hardcoded credentials", "hard-code", "storing credentials on the instance", "credentials on the instance", "iam role for ec2", "attach an iam role to the instance"] },
  { id: "JNNXjGvtN6M", label: "AWS IAM and CI/CD Security: Roles, OIDC and Secrets", keywords: ["oidc", "openid connect", "github actions", "pipeline to assume", "web identity", "assumerolewithwebidentity", "identity federation for workloads", "workflow assumes", "deploys to aws from github", "stored in github"] },
  { id: "69smn613j2k", label: "IAM Roles Anywhere (Cybr)", keywords: ["roles anywhere", "servers in its own data center", "on-premises servers that must call", "x.509", "workloads outside aws", "outside of aws to obtain", "on-premises workloads to assume", "temporary credentials for on-premises"] },
  { id: "uAhIrTek7pg", label: "How Do I Run Security Assessments or Penetration Tests on AWS? (AWS)", keywords: ["penetration test", "penetration tests", "penetration testing", "pen test", "pentest", "port scanning", "vulnerability scanning against", "without prior approval", "prior authorization", "permitted services", "simulated events", "dos simulation"] },

  // Global infrastructure, sovereignty and regional resources
  { id: "2Fxfq_8i928", label: "Data Sovereignty in the AWS Cloud", keywords: ["will not move", "not move or replicate", "move or replicate", "without your consent", "customer content", "who owns", "owns the data", "aws employees", "data stays", "stays in the region", "does not replicate", "chosen region", "region you select", "region they choose", "unless you choose", "except as necessary"] },
  { id: "BMn2xlx7SOw", label: "Introduction to AWS GovCloud (US) (AWS)", keywords: ["govcloud", "itar", "fedramp high", "us government", "federal", "defense contractor", "us persons", "government agency", "public sector", "dod", "export-controlled", "controlled unclassified"] },
  { id: "Z1fijHBkWy8", label: "What Digital Sovereignty Really Means (AWS)", keywords: ["digital sovereignty", "european sovereign cloud", "sovereign cloud", "eu data", "european union", "european customers", "german company", "eu residents", "eu regulation"] },
  { id: "F1Il__dMMQM", label: "Copy an AMI Between Regions", keywords: ["amis are regional", "regional resource", "regional resources", "not visible in", "cannot find the ami", "does not appear in", "later tries to launch", "tries to launch it in", "use it in another region", "in a different region", "copy it to the target region"] },
  { id: "VlNScZcsIjA", label: "AWS Global Infrastructure: Regions and AZs (CloudWolf)", keywords: ["new region", "region opening", "upcoming region", "announced a new region", "opt-in region", "enable the region", "opt in", "region is disabled", "regional service", "regional services", "enable it in every region", "in every region", "each region", "per region", "region-specific", "region specific", "is regional", "regions where its workloads", "only in the region"] },
  { id: "lkl6lkSMukE", label: "AWS Global Cloud Infrastructure: Data Centers, Regions and AZs", keywords: ["az id", "az ids", "zone id", "mapped independently", "independently mapped", "different physical", "same name", "physical location", "one or more discrete data centers", "discrete data centers", "redundant power", "physically separate", "physically separated", "meaningful distance", "miles apart", "same availability zone name"] },

  // Availability zones, placement and capacity
  { id: "_MROZtLtCcA", label: "Introduction to Amazon RDS Multi-AZ Deployments (AWS)", keywords: ["primary database instance", "primary instance or its", "minimal downtime if the primary", "automatic failover", "synchronous standby", "standby replica", "standby in another", "standby in a different", "fails over", "promotes the standby", "automatically fail over"] },
  { id: "n5bDDofU6JE", label: "EC2 Placement Groups: Cluster, Spread, Partition", keywords: ["placement group", "placement groups", "cluster placement", "spread placement", "partition placement", "tightly coupled", "tightly-coupled", "low-latency network", "low network latency", "high-bandwidth", "node-to-node", "hpc", "high performance computing", "high-performance computing", "same rack", "separate racks", "computational fluid", "exchanges large volumes"] },
  { id: "wczSf-hg3qU", label: "EC2 Capacity Reservations (CloudWolf)", keywords: ["capacity reservation", "capacity reservations", "on-demand capacity reservation", "reserve capacity", "guarantee capacity", "guaranteed capacity", "insufficient capacity", "insufficientinstancecapacity", "capacity is available", "disaster recovery exercise", "certain it can launch", "be certain", "must be certain", "launch 200 ec2", "capacity will be available"] },
  { id: "LKhwz-1O7zY", label: "What the Nines Really Mean: 99.9% Uptime Explained", keywords: ["99.9%", "99.99%", "99.999%", "nines", "downtime per year", "downtime per month", "availability target", "availability targets", "minutes of downtime", "hours of downtime", "roughly how much", "availability promise", "promises customers"] },
  { id: "miEHdzqlRsY", label: "High Availability vs Fault Tolerance (Cloud Academy)", keywords: ["n+1", "one more than", "extra instance", "keep handling peak", "still handle peak", "handle peak traffic if", "loses an availability zone", "loss of one availability zone", "tolerate the loss", "tolerate losing", "survive the loss of", "two very large", "many smaller instances", "smaller instances instead"] },
  { id: "hoECEWGFJMk", label: "What is Auto Scaling and Elasticity (360Learning)", keywords: ["not limited to adding and removing", "beyond ec2", "elasticity on aws", "sticky session", "sticky sessions", "session in the memory", "session state", "stateless web tier", "stateless application", "externalize session", "store session", "session store"] },
  { id: "B4dzXFC5THM", label: "EC2 Auto Scaling Predictive Scaling (A Cloud Guru)", keywords: ["predictive scaling", "scheduled scaling", "scheduled action", "scheduled actions", "predictable traffic every", "every weekday at", "spikes at 09:00", "09:00", "daily pattern", "repeats every week", "forecast traffic", "machine learning to forecast", "ahead of the spike", "before the spike", "in advance of"] },

  // Shared responsibility, compliance and physical security
  { id: "vQsqF2gOYqM", label: "AWS Shared Responsibility Model: Who Secures What", keywords: ["physical data centers", "physical security", "badge access", "physical access", "facilities", "physical disks", "decommission", "decommissioned", "end of life", "media destruction", "destroyed", "destroys", "degauss", "nist 800-88", "storage devices", "physical hardware"] },
  { id: "bFYDrHYDns4", label: "Working in an AWS Data Center (AWS)", keywords: ["data center security", "physical layer", "environmental layer", "perimeter layer", "infrastructure layer", "security guards", "biometric", "guarded facilities", "24/7 guarded", "cannot afford", "video surveillance", "fire suppression", "power and cooling"] },
  { id: "iT517huuZik", label: "What is the Shared Responsibility Model and How It Impacts Security", keywords: ["shared responsibility model for sustainability", "sustainability of the cloud", "sustainability in the cloud", "carbon footprint", "customer carbon footprint tool", "carbon footprint tool", "renewable energy", "water usage", "efficiency of the workload", "reduce the carbon", "sustainability officer", "environmental responsibility"] },
  { id: "ebPOgsO5c9E", label: "Simplify Cloud Compliance with AWS (AWS)", keywords: ["pci dss level 1", "pci dss", "pci-dss", "compliance of the underlying", "does not make your application", "does not automatically make", "automatically compliant", "inherit", "inherited", "compliance programs", "certified as", "compliance is shared", "fedramp", "still responsible for", "concludes that any"] },

  // Migration and modernization
  { id: "2rlN3LO6rfE", label: "What is AWS App2Container?", keywords: ["app2container", "app 2 container", "containerize", "containerizes", "containerizing", "java and .net applications", ".net applications", "java web application", "package it as a container", "packages the application into a container", "into containers without", "existing applications into containers"] },
  { id: "hA4cTZosVOg", label: "VMware Cloud on AWS Overview", keywords: ["vmware cloud on aws", "vmware", "vsphere", "vcenter", "elastic vmware service", "vmware workloads", "without refactoring", "same vmware tools", "vmware environment", "hundreds of virtual machines on vmware", "lease is ending", "lease expires"] },
  { id: "70cGmQk_c2I", label: "The 7 Rs of Cloud Migration Explained", keywords: ["minor optimizations", "minor optimization", "without changing the core", "core architecture", "lift, tinker", "tinker and shift", "replatforming", "refactoring", "re-architect", "rearchitect", "re-architecting", "monolith", "monolithic", "saas alternative", "subscribe to a saas", "no longer used", "not migrate", "keep on-premises", "not ready to migrate", "revisit later", "one more than the classic", "seven strategies", "seventh strategy"] },
  { id: "e3z1Pa4C0uk", label: "Mastering AWS Migration Readiness (ClearScale)", keywords: ["migration readiness", "readiness assessment", "mra", "cloud readiness", "readiness", "portfolio assessment", "assess phase", "unsure whether each should be", "which strategy for each", "assign one of the 7 r"] },
  { id: "9Mfj_gqn_VY", label: "Get Migration Discovery Data into AWS Migration Hub (AWS)", keywords: ["application discovery service", "discovery service", "discovery agent", "agentless collector", "discovery data", "server dependencies", "dependency mapping", "dependencies between servers", "share databases and call each other", "call each other", "wave planning", "discovery data shows", "migration discovery"] },
  { id: "lDKwELDAHQM", label: "Introducing AWS Migration Hub Orchestrator (AWS)", keywords: ["migration hub orchestrator", "single place to track", "track the status of", "many teams and tools", "across many teams", "status of all migrations", "central view of migration", "migration dashboard"] },

  // Serverless and event-driven
  { id: "i6ls3qinMM4", label: "AWS Lambda Environment Variables: 8 Things to Know", keywords: ["environment variable", "environment variables", "api token", "third-party api token", "store the token", "plaintext in the function", "store secrets", "secure string", "securestring", "ssm parameter", "secret in plaintext", "instead of environment variables"] },
  { id: "R1wRuPhvu90", label: "AWS Lambda Concurrency: Reserved vs Provisioned", keywords: ["reserved concurrency", "concurrent executions", "concurrency", "too many invocations", "limit the number of concurrent", "each open a connection", "hundreds of concurrent"] },
  { id: "yj-BRhfr9z8", label: "SQS Standard vs FIFO Queues (LearnCantrill)", keywords: ["fifo queue", "fifo queues", "standard queue", "standard queues", "exactly-once", "exactly once", "at-least-once", "at least once", "message ordering", "in the order", "order of messages", "duplicate messages", "deduplication", "strict ordering", "processed in order"] },
  { id: "beV1AYyhgYA", label: "Connecting a Lambda Function to a VPC (Digital Cloud Training)", keywords: ["lambda function must query", "lambda in a vpc", "lambda to a vpc", "function to the vpc", "attach the function to", "private subnet with no public", "no public endpoint", "not publicly accessible", "rds in a private subnet", "database that sits in a private subnet", "vpc configuration for the function", "connect the lambda function to the vpc"] },
  { id: "xKFA6PJgp0o", label: "Amazon Aurora Serverless (AWS)", keywords: ["aurora serverless", "serverless v2", "sporadic", "hours of no activity", "hours with no activity", "idle for hours", "scales to zero", "pause when idle", "automatically start", "unpredictable database", "capacity units", "acu", "acus", "database-per-tenant", "separate database for each of its"] },
  { id: "ynY7vQtcQUw", label: "What is AWS IoT Greengrass? (AWS)", keywords: ["iot greengrass", "greengrass", "intermittent connectivity", "intermittent internet", "run lambda at the edge", "local compute", "edge devices", "iot core", "aws iot", "sensors on factory", "factory floors", "cameras and sensors", "mqtt", "device shadow", "iot devices", "connected devices"] },
  { id: "57XS0jAn2UE", label: "AWS EventBridge: 5 Things You Must Know", keywords: ["from its own microservices", "own applications, aws services", "saas partners", "partner event source", "partner event sources", "events from third-party saas", "single event bus", "central event bus", "route events to", "filter events", "event pattern", "event patterns", "schema registry", "archive and replay", "replay events"] },

  // Block storage
  { id: "O5rm3AKjTo8", label: "Types of EBS Volumes (CloudWolf)", keywords: ["gp3", "gp2", "io2", "io1", "st1", "sc1", "provisioned iops", "throughput optimized", "throughput-optimized", "cold hdd", "general purpose ssd", "volume type", "volume types", "large files sequentially", "sequential", "sub-millisecond", "50,000 iops", "millions of small", "provisioned size", "billed for the provisioned", "pay for the full", "amount provisioned", "regardless of how much", "only written 100"] },
  { id: "NvTSnUM9ASY", label: "What is an EBS Snapshot? (DevOps Adda)", keywords: ["ebs snapshot", "ebs snapshots", "point-in-time", "point in time", "incremental", "incremental backups", "snapshot to another region", "copy the snapshot", "copy a snapshot", "move a volume", "move the volume", "move a 2 tb", "another availability zone", "different availability zone", "data lifecycle manager", "dlm", "automate snapshot", "backup strategy for amazon ebs", "same availability zone as the instance", "must be in the same availability zone", "cannot attach", "attach an existing", "shared publicly", "public snapshot", "snapshot public", "block public access for snapshots", "block public sharing", "publicly shared"] },
  { id: "pMrWl12yp1c", label: "EBS Snapshot Archive Explained (CloudWolf)", keywords: ["snapshot archive", "archive tier", "rarely restored", "snapshots that are rarely", "archived snapshot", "archive storage tier"] },
  { id: "cTwWCIZRgEQ", label: "Encrypt All EBS Volumes With a Single Setting", keywords: ["encryption by default", "encrypt by default", "default encryption", "every new ebs volume", "every new amazon ebs volume", "all new volumes", "account-level setting", "region-level setting", "automatically encrypted", "created in a region must be encrypted", "must be encrypted at creation", "enable ebs encryption by default"] },
  { id: "iI-cAtKgPXs", label: "Multi-Attach for EBS Provisioned IOPS Volumes (A Cloud Guru)", keywords: ["multi-attach", "multi attach", "attach the same volume", "same ebs volume to multiple", "multiple instances simultaneously", "both instances to read and write", "read and write to the same", "shared block", "clustered application", "cluster-aware", "clustered database", "several amazon ec2 instances in the same availability zone", "two amazon ec2 instances in the same availability zone"] },

  // NoSQL and purpose-built databases
  { id: "EC_GEessfJI", label: "Global Tables in DynamoDB: 6 Things to Know", keywords: ["global table", "global tables", "multi-region replication", "multi-region, multi-active", "multi-active", "active-active", "users in north america, europe", "replicated across regions", "replicate the table", "low-latency reads and writes in each region", "in multiple regions with local"] },
  { id: "qZhcgNdK1bs", label: "Amazon DynamoDB DAX: 5 Things to Know", keywords: ["dynamodb accelerator", "in-memory cache for dynamodb", "microsecond", "microseconds", "read millions of times", "same items", "same top-100", "hot items", "hot partition", "read-heavy", "read heavy", "cache for dynamodb", "same seat", "same rows", "millions of times per second", "leaderboard stored in amazon dynamodb"] },
  { id: "J4FNdwgqxPg", label: "DynamoDB TTL: Automatically Delete Old Data (CloudWolf)", keywords: ["time to live", "ttl", "expire automatically", "automatically delete", "automatically deleted", "disappear automatically", "expired items", "session records", "sessions should", "after 24 hours", "after a fixed period", "remove old items"] },
  { id: "CQPpE5I4QeY", label: "DynamoDB Throughput: On-Demand vs Provisioned (CloudWolf)", keywords: ["on-demand capacity", "on-demand mode", "provisioned capacity", "provisioned mode", "read capacity units", "write capacity units", "rcu", "wcu", "unpredictable traffic", "completely unpredictable", "pay per request", "pay-per-request", "traffic is unpredictable", "auto scaling for dynamodb", "capacity mode", "some days there is almost", "may be zero"] },
  { id: "IsmhOkimHyI", label: "Introduction to Amazon Timestream (AWS)", keywords: ["time series", "time-series", "smart meter", "smart meters", "iot sensor data", "readings every", "readings from millions", "telemetry", "metrics over time", "timestamped", "time-stamped", "measurements over time"] },
  { id: "PYdLIvBHe2E", label: "Overview of Amazon Keyspaces (AWS)", keywords: ["apache cassandra", "cql", "cassandra query language", "cassandra-compatible", "cassandra cluster", "cassandra workloads", "self-managed apache cassandra"] },
  { id: "RKLPTQgcmUE", label: "Introduction to Amazon DocumentDB (AWS)", keywords: ["mongodb-compatible", "mongodb compatible", "document store", "json documents", "content management system", "self-managed mongodb", "mongodb database", "mongodb workloads", "mongodb drivers"] },
  { id: "HftOfMERxO8", label: "AWS Purpose-Built Database Strategy (AWS)", keywords: ["purpose-built database", "purpose-built databases", "purpose built", "right database for the job", "right tool for the right job", "one database for everything", "single database for all", "different database engines", "correctly describe purpose-built", "choose a database", "choosing a database", "cannot agree on whether", "relational database, a data warehouse"] },
  { id: "Nax2zbYakf4", label: "RDS Backups: Automated Backups and Manual Snapshots (CodeLucky)", keywords: ["automated backup", "automated backups", "manual snapshot", "manual snapshots", "backup retention", "retention period of", "point-in-time recovery", "point in time recovery", "backup window", "restore to any second", "restore to a point", "backup and recovery for an amazon rds", "backups are deleted when", "retained after deletion", "500 gb of allocated storage"] },
  { id: "yzyXY1bvXCY", label: "RDS Read Replicas: Scale Read Operations (CodeLucky)", keywords: ["read-heavy", "read heavy", "offload reads", "offload reporting", "reporting queries", "scale reads", "scale read", "read traffic", "read scaling", "reporting workload", "analytics queries slow down", "reporting workloads away from", "cross-region read replica", "promote the read replica", "promoted to a standalone"] },
  { id: "JZnd74HAmq0", label: "Amazon RDS Performance Insights (AWS)", keywords: ["performance insights", "database load", "slow queries", "slow query", "which sql", "which queries", "top sql", "wait events", "becomes slow every afternoon", "cannot see which queries", "database performance", "tune the database", "query performance"] },

  // Cloud concepts and economics
  { id: "e8F2ls3n_Wo", label: "Scalability vs Elasticity in 99 Seconds", keywords: ["scalability", "scalable", "scale up or down", "scale up and down", "scale resources", "acquire resources", "release resources", "match demand", "matches demand", "as demand changes", "only what you need", "grow and shrink", "acquire and release"] },
  { id: "5T_LL0-3VqY", label: "The Six Advantages of AWS Cloud Computing", keywords: ["six advantages", "6 advantages", "benefit from massive economies", "massive economies of scale", "stop guessing capacity", "guessing capacity", "guess capacity", "increase speed and agility", "speed and agility", "stop spending money running and maintaining", "running and maintaining data centers", "trade fixed expense", "trade capital expense", "fixed expense for variable", "upfront expense for variable", "capital expenses for variable"] },
  { id: "wxTznCzs2ts", label: "Economies of Scale in Cloud Computing", keywords: ["lower pay-as-you-go prices", "hundreds of thousands of customers", "aggregated usage", "lower variable cost", "achieve a lower variable cost", "usage from hundreds of thousands", "buys in bulk", "bulk purchasing", "purchasing power"] },
  { id: "2pMhRe9iVxI", label: "What is Cloud Computing? Benefits Explained", keywords: ["definition of cloud computing", "on-demand delivery", "on demand delivery", "it resources over the internet", "over the internet", "pay-as-you-go pricing", "compute power, database", "compute, database, storage", "via the internet", "delivered over the internet", "definition that aws uses"] },
  { id: "mNo-zmFu5Zw", label: "AWS SES Explained for Beginners", keywords: ["simple email service", "send email", "sending email", "send emails", "transactional email", "transactional emails", "marketing email", "marketing emails", "bulk email", "newsletter", "order confirmations", "password reset messages", "email sending", "outbound email", "email delivery"] },
  { id: "xwikGprUIY0", label: "Schedule EC2 Instances With Instance Scheduler", keywords: ["instance scheduler", "outside business hours", "outside of business hours", "business hours", "nights and weekends", "evenings and weekends", "stop instances", "stop the instances", "shut down", "turned off when not", "not in use", "left running", "running 24/7", "24/7", "dev and test", "development and test", "development and test environments", "nearly as high as production", "test environments to aws"] },

  // Cloud Adoption Framework and Well-Architected practice
  { id: "VC6fje9JC-s", label: "AWS Cloud Adoption Framework (Hey Computer)", keywords: ["envision", "launch phase", "scale phase", "transformation phases", "technology transformation", "process transformation", "organization transformation", "organizational transformation", "product transformation", "capability gaps", "capability gap", "transformation opportunities", "transformation initiatives", "pilot workloads", "pilots", "delivered several pilot", "reduce business risk", "improve esg", "grow revenue", "increase operational efficiency", "business outcomes", "lack cloud skills", "cloud skills", "cross-functional team", "cloud center of excellence", "ccoe", "caf and the well-architected", "difference between the aws caf", "cloud adoption framework and the well-architected", "organizational readiness"] },
  { id: "Ak5k-DPBW48", label: "AWS Well-Architected Tool: 5 Things You Must Know", keywords: ["well-architected tool", "well architected tool", "wa tool", "structured set of questions", "answer a set of questions", "answer questions", "answer a structured", "review a workload", "review workloads", "review a production workload", "self-service", "improvement plan", "high risk issues", "high-risk issues", "hris", "milestone", "milestones"] },
  { id: "i1Q3JVxEcEQ", label: "AWS Well-Architected Lenses Explained (CloudWolf)", keywords: ["lens", "lenses", "serverless lens", "serverless applications lens", "machine learning lens", "saas lens", "industry-specific", "workload-specific", "tailored to that specific", "tailored guidance", "specific technology domain", "guidance that is tailored", "specific to serverless"] },
  { id: "esH7nyNJ0hc", label: "Well-Architected Framework: Design Principles and 6 Pillars", keywords: ["general design principles", "design principles", "stop guessing your capacity", "test systems at production scale", "production scale", "full-scale copy", "automate to make architectural experimentation", "architectural experimentation", "allow for evolutionary architectures", "evolutionary architecture", "evolutionary architectures", "drive architectures using data", "drive architecture using data", "improve through game days", "game day", "game days", "trade-off", "tradeoff", "trade-offs", "tradeoffs", "based on intuition", "intuition", "design a system once", "design once", "treat late changes"] },
  { id: "RFFK9nO3QPs", label: "Well-Architected Review (AWS Cost Optimisation Series)", keywords: ["well-architected review", "well architected review", "periodic review", "regularly review", "review two years ago", "two years ago and has not", "continuous improvement", "reviewed once", "one-time review", "reviews should be", "review regularly", "iterative", "single aws well-architected review", "has not repeated", "not revisited"] },

  // Observability
  { id: "JJIANYptzTw", label: "Amazon CloudWatch Agent: 6 Things You Need To Know", keywords: ["cloudwatch agent", "unified agent", "memory utilization", "memory usage", "disk usage", "disk space", "memory metrics", "memory and disk", "not available by default", "not collected by default", "operating system metrics", "os-level metrics", "custom metrics from the instance", "install an agent", "install the agent", "also needs memory"] },
  { id: "y74TTzNWuoM", label: "CloudWatch Synthetics: 6 Things You Must Know", keywords: ["synthetics", "canary", "canaries", "synthetic monitoring", "checkout page", "before customers report", "before customers complain", "even when there is no traffic", "no real users", "no traffic", "simulate a user", "simulated user", "scripted", "heartbeat", "broken links", "endpoint availability", "test the endpoint", "at 3 a.m", "when customers complain", "learns that its web application is down", "all of them look healthy"] },
  { id: "mAdBKHDTAiI", label: "CloudWatch Logs Insights: Search, Filter, Parse", keywords: ["metric filter", "metric filters", "filter pattern", "count the number of", "occurrences", "paymenttimeout", "count of errors", "count errors", "log lines such as", "query the logs", "query logs", "search log", "search the logs", "alarm when the number of", "error log lines", "number of times"] },
  { id: "YG7KlK-puco", label: "AWS X-Ray SDK Explained (CloudWolf)", keywords: ["service map", "end-to-end", "end to end", "which component", "where the latency", "latency across services", "microservices latency", "bottleneck in a request", "servicelens", "application signals", "built from an api gateway front end", "several aws lambda functions, an amazon", "trace a request", "trace requests", "follow a request", "segments", "subsegments"] },
  { id: "XJ-Xd9braDw", label: "CloudWatch Anomaly Detection (A Cloud Guru)", keywords: ["naturally rises", "seasonal", "seasonality", "expected pattern", "expected range", "expected band", "machine learning to establish", "deviates", "deviation", "unusual", "daily pattern", "weekly pattern", "higher on weekends", "rises every evening", "static threshold", "fixed threshold"] },
  { id: "c6GKSqweBKQ", label: "Configure AWS Billing Alarms Using CloudWatch (Jon Good)", keywords: ["estimated charges", "estimatedcharges", "month-to-date", "month to date", "billing metric", "billing metrics", "receive billing alerts", "us-east-1 for billing", "charges exceed", "exceeds a dollar", "estimated bill", "simple amazon cloudwatch alarm that sends an email", "sends an email when", "estimated charges exceed"] },
  { id: "wLpDM0IlYmo", label: "Monitoring AWS Cloud Using CloudWatch", keywords: ["detailed monitoring", "basic monitoring", "every 5 minutes", "5-minute", "five minutes", "5 minutes", "1-minute", "one-minute", "every minute", "1 minute intervals", "one minute granularity", "high-resolution", "high resolution", "more frequent metrics", "only every 5"] },

  // Networking and delivery
  { id: "xqjjnsGSTmE", label: "Security Groups (Stateful) and Network ACLs (Stateless)", keywords: ["rule 100", "rule 200", "rule number", "rule numbers", "lowest number", "evaluated in order", "numbered rules", "custom network acl", "default network acl", "denies all", "deny all inbound", "explicit deny", "deny rule", "deny rules", "cannot deny", "block a single ip", "block all traffic from a specific", "specific malicious ip", "single known-malicious", "malicious ip address"] },
  { id: "9O-HMekY8cs", label: "VPC Security: Security Groups vs Network ACLs (Cloud Explainers)", keywords: ["return traffic", "response traffic", "outbound rule for the response", "allow the response", "no outbound rule", "automatically allowed", "has no outbound rules", "default security group", "without specifying a security group", "default security group allows", "preventive", "detective control", "detective controls", "preventive control", "preventive controls"] },
  { id: "icuh75LGyJ8", label: "NACL vs Security Group in AWS: Stateless vs Stateful", keywords: ["vpc flow logs", "flow logs", "flow log", "capture metadata about ip traffic", "ip traffic", "accepted or rejected", "accept or reject", "source, destination, port", "network reachability", "reachable from the internet", "reachability", "network access analyzer", "ports they", "unintended network access"] },
  { id: "bDp5znRHHfM", label: "How To Restrict S3 Bucket Access To CloudFront (Gokce DB)", keywords: ["origin access control", "origin access identity", "oac", "oai", "only through cloudfront", "bypass cloudfront", "bypassing cloudfront", "directly from the s3 bucket", "restrict access to the bucket", "access the bucket directly", "bucket url directly", "bucket only from cloudfront", "protect the origin"] },
  { id: "YmZPqPEBUkY", label: "CloudFront Origins: S3 and Custom Origins (CodeLucky)", keywords: ["cache ttl", "default cache ttl", "time to live for", "stale content", "invalidate", "invalidation", "invalidations", "cache invalidation", "updated images", "old version of", "still see the old", "cached copy", "cache behavior", "cache behaviours", "cloudfront functions", "lambda@edge", "tiny piece of javascript", "at the edge", "signed url", "signed urls", "signed cookie", "signed cookies", "hotlink", "hot-linking", "other websites embedding", "referer"] },
  { id: "_zpR-WRFGC4", label: "Route 53 Resolver Endpoints: Hybrid DNS (Network Ninja)", keywords: ["route 53 resolver", "resolver endpoint", "resolver endpoints", "inbound endpoint", "outbound endpoint", "hybrid dns", "resolve private dns names", "on-premises must resolve", "servers on-premises must resolve", "servers in the data center must resolve", "resolve names of resources in the vpc", "resolve the private", "private hosted zone", "private hosted zones", "internal microservices on ec2", "discover each other by name", "internal dns"] },
  { id: "6VlNu0Kr9tQ", label: "AWS Route 53 Resolver DNS Firewall", keywords: ["dns firewall", "route 53 resolver dns firewall", "dns queries to", "dns exfiltration", "exfiltrated data by making dns", "malicious domains", "block dns", "dns query logging", "resolver query logs", "dns-based"] },
  { id: "_mHLkFeTuFo", label: "AWS PrivateLink (AWS)", keywords: ["privatelink", "private link", "endpoint service", "expose a service to other vpcs", "expose the service privately", "saas vendor to read objects", "vendor's vpc", "without vpc peering", "without exposing it to the internet", "privately expose", "interface endpoint to a service in another"] },

  // Compute purchasing, tenancy and licensing
  { id: "-RYsEvQpoSM", label: "Dedicated Host vs Dedicated Instances (Cloud Champ)", keywords: ["dedicated host", "dedicated hosts", "per physical socket", "per socket", "per core", "per-socket", "per-core", "physical server", "physical servers", "not shared with other customers", "physical isolation", "physically isolated", "host affinity", "bring your own windows", "byol windows", "software assurance", "license mobility", "perpetual", "sql server licenses", "physical cores", "licensed per physical"] },
  { id: "gvucWiD9jMA", label: "Savings Plans vs Reserved Instances (VK Seth)", keywords: ["convertible", "convertible reserved", "standard reserved", "standard reserved instances", "change the instance family", "switch instance families", "switch to a different instance", "expects to switch", "may need to change", "flexibility to change", "exchange", "exchanged", "sell reserved", "reserved instance marketplace", "ri marketplace", "cancelled after", "no longer needed reserved", "unused reserved", "ri utilization", "utilization report", "coverage report", "ri coverage", "what percentage of"] },
  { id: "O1CkTel3nMs", label: "AWS Savings Plans vs Reserved Instances (PTP)", keywords: ["all upfront", "partial upfront", "no upfront", "paid $36,000 upfront", "upfront in january", "upfront payment", "payment option", "payment options", "amortized", "amortization", "unblended", "blended cost", "net amortized", "how the upfront", "spread the upfront"] },
  { id: "aRlY3VBX3Lc", label: "Amazon EC2 Spot Instances (AWS)", keywords: ["spot instance", "spot instances", "spot fleet", "spot price", "interrupted", "interruption", "interruptions", "two-minute warning", "2-minute", "fault-tolerant workload", "flexible start", "can be interrupted", "tolerate interruption", "up to 90%", "90% discount", "unused ec2 capacity", "spare capacity", "five-day model training", "16 gpu-based"] },
  { id: "vmAV2y5YQng", label: "EC2 Image Builder Overview", keywords: ["image builder", "ec2 image builder", "build and test images", "golden ami pipeline", "automate ami creation", "automate the creation of amis", "patched ami", "hardened ami", "image pipeline", "customized linux kernel", "kernel module", "specific operating system version"] },

  // Storage services and data movement
  { id: "wfr1VVsAT2U", label: "AWS S3 Object Versioning (CloudWolf)", keywords: ["versioning enabled", "enable versioning", "previous versions", "previous version", "overwritten object", "overwrites", "overwrite", "recover an overwritten", "restore a previous", "delete marker", "delete markers", "noncurrent", "non-current", "every version", "keep every version", "mfa delete"] },
  { id: "l8haF7PboH0", label: "AWS S3 Tutorial: How Replication Works (CloudWolf)", keywords: ["same-region replication", "same region replication", "srr", "crr", "replicate objects to", "replicate new objects", "replication rule", "replication rules", "copy of every object in another region", "second region for compliance", "replicated to a bucket in", "replication time control", "replicate existing objects", "batch replication"] },
  { id: "Am2nq8msn3M", label: "What is AWS S3 Object Lock? (InfosecTrain)", keywords: ["cannot be deleted for", "cannot be modified for", "prevent deletion for", "deleted or altered for", "retain for seven years", "seven-year retention", "regulatory retention", "tamper-proof", "tamperproof", "tamper proof", "financial records must", "audit logs cannot be"] },
  { id: "It-a5iOE8-E", label: "AWS SNS Explained: Alerts, Notifications and Pub/Sub", keywords: ["sms", "text message", "text messages", "push notification", "push notifications", "mobile push", "fan out", "fan-out", "fanout", "publish/subscribe", "pub/sub", "pub-sub", "topic subscribers", "subscribe to the topic", "email subscription", "notify an operations team", "send an alert to", "multiple subscribers", "several subscribers"] },
  { id: "Pv-vfdS9LOA", label: "Detect Stack Drift in AWS CloudFormation (Gokce DB)", keywords: ["drift", "drift detection", "detect drift", "drifted", "someone changed", "changed manually", "changed outside of", "modified outside", "differs from the template", "change set", "change sets", "preview the changes", "before applying an updated", "what will change", "suspects someone changed"] },
  { id: "aen4qHCsR4w", label: "CloudFormation StackSets (A Cloud Guru)", keywords: ["stackset", "stacksets", "stack set", "stack sets", "deploy the same cloudformation", "same template to multiple accounts", "across multiple accounts and regions", "60 aws accounts", "every account in", "all accounts and regions", "baseline resources in every", "standard set of baseline"] },
  { id: "5z7oAZSNRQ4", label: "AWS Health Dashboard: Service Health and Account Health", keywords: ["health dashboard", "personal health dashboard", "service health dashboard", "aws health", "scheduled maintenance", "planned maintenance", "affecting your account", "affecting your resources", "service event", "service events", "aws outage", "is aws having an issue", "status of aws services", "health api", "health events"] },
];

/** Domain-level fallback used when no keyword matches. */
const domainFallback: Record<Domain, string> = {
  "cloud-concepts": "a9__D53WsUs",
  "security-and-compliance": "9Pk2J_5qnlk",
  "cloud-technology-and-services": "BtJAsvJOlhM",
  "billing-pricing-and-support": "-t148tYgnJU",
};

export function videoUrlFor(id: string): string {
  return `https://www.youtube.com/watch?v=${id}`;
}

/** Text a keyword must match against: the question, its explanation, and the correct options. */
function searchableText(question: Question): string {
  const correctOptions = question.options
    .filter((o) => question.correctOptionIds.includes(o.id))
    .map((o) => o.text);
  return [question.text, question.explanation, ...correctOptions].join(" \n ").toLowerCase();
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Scores a keyword against the haystack. Whole-word matches only, so "ec2" does not match
 * "ec2-classic"'s neighbour text incorrectly and "scp" does not match "scope".
 * Each hit is worth the keyword's length so multi-word phrases dominate single words.
 */
function keywordScore(keyword: string, haystack: string): number {
  const pattern = new RegExp(`(^|[^a-z0-9])${escapeRegExp(keyword)}(?=$|[^a-z0-9])`, "g");
  const hits = haystack.match(pattern)?.length ?? 0;
  return hits * keyword.length;
}

/**
 * Picks the best curated video for a question. An explicit `videoUrl` on the question wins;
 * otherwise the catalog entry with the highest keyword score is used, falling back to a
 * domain-level video so every question has a link.
 */
export function resolveVideo(question: Question): { url: string; label: string } {
  if (question.videoUrl) {
    return { url: question.videoUrl, label: question.videoLabel ?? "YouTube" };
  }

  const haystack = searchableText(question);
  let best: VideoEntry | undefined;
  let bestScore = 0;

  for (const entry of videoCatalog) {
    let score = 0;
    for (const keyword of entry.keywords) {
      score += keywordScore(keyword.toLowerCase(), haystack);
    }
    if (score > bestScore) {
      bestScore = score;
      best = entry;
    }
  }

  const chosen = best ?? videoCatalog.find((v) => v.id === domainFallback[question.domain])!;
  return { url: videoUrlFor(chosen.id), label: chosen.label };
}
